### ISSUE TITLE
Erro na instalação do Pacote

### ISSUE THREAD

**Issue by leonardodecuritiba** [eduardokum/laravel-boleto#101]
Amigo,
Tive um problema no composer no momento de instalação do pacote.
Você já viu isso acontecer?

Dá uma olhada no log.
![screenshot_1](https://cloud.githubusercontent.com/assets/13199964/22668799/3b74ef28-eca9-11e6-9244-38909dcbb73d.png)

**Comment by edigomes** [comment]
![image](https://cloud.githubusercontent.com/assets/9788003/22668870/1969f99e-eca1-11e6-9568-4c332dca750c.png)

Instale a ext-intl do php!!

 @eduardokum coloca isso bem grande no readme!

**Comment by eduardokum** [comment]
Vou colocar! Vlw!
