### ISSUE TITLE
Problema na renderização (looping infinito)

### ISSUE THREAD

**Issue by leonardodecuritiba** [eduardokum/laravel-boleto#102]
Eduardo, estava tentando criar aqui e não vai de todo o jeito.
O problema é que não retorna nem erro.
O código que usei é o mesmo do exemplo:

        $beneficiario = new \Eduardokum\LaravelBoleto\Pessoa(
            [
                'nome'      => 'ACME',
                'endereco'  => 'Rua um, 123',
                'cep'       => '99999-999',
                'uf'        => 'UF',
                'cidade'    => 'CIDADE',
                'documento' => '99.999.999/9999-99',
            ]
        );
        $pagador = new \Eduardokum\LaravelBoleto\Pessoa(
            [
                'nome'      => 'Cliente',
                'endereco'  => 'Rua um, 123',
                'bairro'    => 'Bairro',
                'cep'       => '99999-999',
                'uf'        => 'UF',
                'cidade'    => 'CIDADE',
                'documento' => '999.999.999-99',
            ]
        );
        $boleto = new \Eduardokum\LaravelBoleto\Boleto\Banco\Santander(
            [
                'logo'                   => asset('uploads/instuticional/logo_atlas.png'),
                'dataVencimento'         => new \Carbon\Carbon(),
                'valor'                  => 100,
                'multa'                  => false,
                'juros'                  => false,
                'numero'                 => 1,
                'numeroDocumento'        => 1,
                'pagador'                => $pagador,
                'beneficiario'           => $beneficiario,
                'carteira'               => 101,
                'agencia'                => 1111,
                'conta'                  => 99999999,
                'descricaoDemonstrativo' => ['demonstrativo 1', 'demonstrativo 2', 'demonstrativo 3'],
                'instrucoes'             => ['instrucao 1', 'instrucao 2', 'instrucao 3'],
                'aceite'                 => 'S',
                'especieDoc'             => 'DM',
            ]
        );
        $boleto->renderHTML();

**Comment by eduardokum** [comment]
O método renderHTML retorna uma string tenta dar echo nela e veja se funciona

**Comment by leonardodecuritiba** [comment]
Nada ainda.
Vou postar o erro e as dependências instaladas:
![screenshot_2](https://cloud.githubusercontent.com/assets/13199964/22687847/e4470156-ed10-11e6-8757-e48c77e1f898.png)

    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laravelcollective/html": "5.2.*",
        "zizaco/entrust": "5.2.x-dev",
        "maatwebsite/excel": "~2.1.0",
        "laravelcollective/bus": "^5.2",
        "sintegra-php/sp": "dev-develop",
        "barryvdh/laravel-ide-helper": "v2.2.1",
        "barryvdh/laravel-dompdf": "^0.7.0",
        "eduardokum/laravel-boleto": "^0.5.0"
    },

**Comment by eduardokum** [comment]
não sei te dizer, teria que debugar pra ver onde esta esse loop. Acredito que na classe o unico loop que tem nesse método é no método que gera o o código de barras getImagemCodigoDeBarras

**Comment by leonardodecuritiba** [comment]
Cara, muito estranho, esse é o retorno da variável boleto:
![screenshot_3](https://cloud.githubusercontent.com/assets/13199964/22691168/4668bf50-ed20-11e6-9144-8700d7e5c663.png)
Que vem de:
`$boletoArray = [
            'logo'                   => asset('uploads/instuticional/logo_atlas.png'),
            'dataVencimento'         => new \Carbon\Carbon(),
            'valor'                  => 100,
            'multa'                  => false,
            'juros'                  => false,
            'numero'                 => 1,
            'numeroDocumento'        => 1,
            'pagador'                => $pagador,
            'beneficiario'           => $beneficiario,
            'carteira'               => 101,
            'agencia'                => 1111,
            'conta'                  => 99999999,
            'descricaoDemonstrativo' => ['demonstrativo 1', 'demonstrativo 2', 'demonstrativo 3'],
            'instrucoes'             => ['instrucao 1', 'instrucao 2', 'instrucao 3'],
            'aceite'                 => 'S',
            'especieDoc'             => 'DM',
        ];
        **$boleto = new \Eduardokum\LaravelBoleto\Boleto\Banco\Santander($boletoArray);**`

É um array mesmo?

**Comment by eduardokum** [comment]
O Boleto
![image](https://cloud.githubusercontent.com/assets/2566340/22691370/526aac22-ed21-11e6-81d8-aa7b094da8b0.png)

O Controller
![image](https://cloud.githubusercontent.com/assets/2566340/22691383/629857a2-ed21-11e6-8e72-3951b8556a64.png)

O dd()
![image](https://cloud.githubusercontent.com/assets/2566340/22691399/75985f1e-ed21-11e6-9d5b-0932080678bb.png)

**Comment by leonardodecuritiba** [comment]
O problema parece estar na função:

    public function renderHTML($print = false)
    {
        **$html = new Html($this->toArray());**
        return $html->gerarBoleto($print);
    }
Ele gera looping infinito na conversão.

**Comment by leonardodecuritiba** [comment]
Agora lá vai eu debugar linha por linha da AbstractBoleto::toArray()

**Comment by leonardodecuritiba** [comment]
Maravilha, achei o problema e consegui fazer funcionar, estava na função toArray, mais especificamente:
                'logo_base64'                 => $this->getLogoBase64(),

Vou fazer mais alguns testes pra avaliar, mas obviamente o caminho da imagem deve ser absoluto, o que eu não estava fazendo. Mas parece que sem a definição da valor de "logo", ou deixando como vazio ou NULL também entra em looping. Vou testar melhor e te retorno.
Uma dúvida, que medida você toma para encaminhar o pdf por email?

**Comment by eduardokum** [comment]
Eu disponibilizo um link que o usuário ve a situação do boleto e pode imprimir html pdf ou so copiar a linha digitável

**Comment by leonardodecuritiba** [comment]
Blz, cara. Muito bom o seu pacote! Você está contribuindo legal com a comunidade, Show de bola!
A função renderHTML() funcionou tranquilo:
![screenshot_5](https://cloud.githubusercontent.com/assets/13199964/22692418/0e9440b2-ed26-11e6-9af4-0425d0f56300.png)


mas a renderização com o PDF não rolou. Tem alguma outra forma:
return $boleto->renderPDF(true); // imostra a janela de impressão
![screenshot_6](https://cloud.githubusercontent.com/assets/13199964/22692444/45921fa8-ed26-11e6-9f7f-4f06731a3301.png)

**Comment by eduardokum** [comment]
Então, ele retorna a string por padrao so passar os headers de pdf ou mudar para:

```php
$pdf = new Eduardokum\LaravelBoleto\Boleto\Render\Pdf();
$pdf->addBoleto($boleto);
$pdf->gerarBoleto();
```

que ele faz o output standard do FPDF que ja coloca os headers na resposta

**Comment by leonardodecuritiba** [comment]
Blz Eduardo,
Isso só me gerou uma confusão por causa do doc, talvez eu tenha entendido errado, mas outros podem ter o mesmo problema:
![screenshot_7](https://cloud.githubusercontent.com/assets/13199964/22692933/551d0e36-ed28-11e6-965b-323f7b11fc0c.png)

Mas blz, já consegui gerar em HTML e PDF, a única questão em aberto foi que não consegui gerar o boleto com **logo** = NULL ou vazio.
Mas valeu cara! sucesso!

**Comment by eduardokum** [comment]
Beleza cara, vou tentar melhorar a documentação.
