### ISSUE TITLE
[Sugestão] Adicionar uma condicional na remessa do santander caso não haja dias para juros

### ISSUE THREAD

**Issue by israaraujo** [eduardokum/laravel-boleto#108]
Fiz uma remessa e havia deixado zerado o "juros_apos" ai não passou na homologação do banco, como no meu caso não haverá juros, fiz essa adaptação.

[https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Remessa/Cnab400/Banco/Santander.php#L163](url)

`$this->add(102, 107, $boleto->getJurosApos() > 0 ? $boleto->getDataVencimento()->copy()->addDays($boleto->getJurosApos())->format('dmy') : '000000');`

**Comment by eduardokum** [comment]
Obrigado @israaraujo. Vou implementar isso.

**Comment by eduardokum** [comment]
Adicinei porém quando maior que zero e sim igual a === false porque ainda pode por 0 e usar a data do vencimento como valor para cobrar o juros somente após vencido. 10130985a604cc394d14a79b92c362fafd6e705d
