### ISSUE TITLE
[Duvida/Sugestão] Output da Remessa

### ISSUE THREAD

**Issue by dbemfica** [eduardokum/laravel-boleto#109]
Bom dia, eu procurei na biblioteca e não encontrei, quando fui gerar o arquivo de remessa eu usei para sua saída o método 'gerar()' funcionou perfeitamente mais gostaria de saber se tem algum método para já sair com o header para forçar o download o o arquivo já sair no formato TXT?

Se o método não existir eu poderia fazer um pull com ele oque vocês acham?

**Comment by eduardokum** [comment]
Bom dia,
Hoje tem o método gerar, e o método save, se você puder fazer o download seria útil sim, so manda o PR pro branch develop por favor.
