### ISSUE TITLE
Campos requeridos pelo banco, aparentam estar ausentes

### ISSUE THREAD

**Issue by ricardobarantini** [eduardokum/laravel-boleto#11]
Os campos `agencia` e `conta` não estão vazios mas o erro continua. Forcei a criação do arquivo alterando a função `isValid()` e o arquivo realmente não captura essas informações, porém quando dou `dd()` na função `$remessa->addBoleto()` ele exibe essas informações normais.

**Comment by eduardokum** [comment]
Você precisa configurar essas informações no objeto remessa para criar o header da remessa

**Comment by ricardobarantini** [comment]
Eu fiz isso, mas continua com esse problema.

**Comment by ricardobarantini** [comment]
Eu instanciei o objeto $remessa erto porém o header retorna vazio. Não testei de outros bancos mas esse que estou usando é do Santander.

```php
"header" => []
```

**Comment by eduardokum** [comment]
```php
$remessaArray = [
    'agencia' => 9999,
    'conta' => 99999,
    'codigoCliente' => 99999,
    'beneficiario' => $beneficiario,
];

$remessa = new \Eduardokum\LaravelBoleto\Cnab\Remessa\Banco\Santander($remessaArray);

$remessa->addBoleto($boleto); // Objeto de boleto gerado, BoletoContract

echo $remessa->gerar();
```

Esta seguindo esse padrão?

**Comment by ricardobarantini** [comment]
Sim, isso mesmo.

**Comment by eduardokum** [comment]
Não sei cara, posta como você está fazendo

**Comment by ricardobarantini** [comment]
A função que gera o arquivo é a `gerarRemessas()`.

https://gist.github.com/ricardobarantini/4a8241329fb98fd97442a72b0dbb3ec9

**Comment by eduardokum** [comment]
Voce conseguiu identificar se esse erro da na remessa ou no boleto?? pois a
msg é a mesma para os 2, pro boleto é obrigatório no santander carteira,
agencia e conta, já na remessa é obrigatório agencia, conta e código do
cedente. aparentemente pelo código que voce mandou parece estar ok, ja
tentou debugar?

EDUARDO GUSMÃO
Analista de Sistemas
E-mail: eduardo@intrasis.com.br
Telefone: 11 2208 2423 | 41 8479 6288 (Oi)
Endereço: Av. Engenheiro Caetano Álvares, 3536 | São Paulo
Site: www.intrasis.com.br

2016-06-21 16:07 GMT-03:00 Ricardo Barantini <notifications@github.com>:

**Comment by ricardobarantini** [comment]
Já, não consigo encontrar o problema em nenhum lugar. Todos os campos obrigatórios estão sendo preenchidos corretamente.

**Comment by ricardobarantini** [comment]
Isso está certo?

```php
/**
 * Define as carteiras disponíveis para este banco
 * @var array
 */
protected $carteiras = ['101', '201'];
```

```php
/**
 * Define os nomes das carteiras para exibição no boleto
 * @var array
 */
 protected $carteirasNomes = ['101' => 'Cobrança Simples ECR', '102' => 'Cobrança Simples CSR'];
```

**Comment by marcosformagini** [comment]
Para gerar a remessa, você tem que informar uma das carteiras suportadas. Uso desta maneira no meu projeto e funciona perfeitamente.

```javascript

$remessaArray = [
    'agencia' => $agencia,
    'agenciaDv' => $agenciaDv,
    'conta' => $conta,
    'carteira' => ($registrada==true?'102':'101'),
    'codigoCliente' => $codCliente,
    'beneficiario' => $beneficiario,
];

$remessa = new \Eduardokum\LaravelBoleto\Cnab\Remessa\Banco\Santander($remessaArray);
$remessa->addBoleto($boleto);
echo $remessa->gerar();

```
Espero ter ajudado.
