### ISSUE TITLE
Criar Carnê

### ISSUE THREAD

**Issue by girlanlira** [eduardokum/laravel-boleto#111]
Boa tarde, tem alguma possibilidade de criar carnê?

**Comment by dieisonbeck** [comment]
Estou precisando também.

Em 15 de fevereiro de 2017 16:41, girlanlira <notifications@github.com>
escreveu:

**Comment by eduardokum** [comment]
Eu sei que tem o layout em HTML feito, não tem em PDF e não sei como funciona, as informações necessárias no boleto e remessa, teria que dar uma estudada pra ver se atende. Nunca trabalhei com carnê.

Posta no [grupo de discussão](https://groups.google.com/d/forum/laravel-boleto), de repente alguém usa.

**Comment by dieisonbeck** [comment]
Olá girlanlira, conseguiu gerar o carnê?
