### ISSUE TITLE
Header BB

### ISSUE THREAD

**Issue by jammersonf** [eduardokum/laravel-boleto#12]
Gerei a remessa e encaminhei para validação no banco do Brasil e me retornaram o seguinte:

> Posições 077 a 094: Preencher com '001BANCODOBRASIL'

Eu vi que na remessa gerada, ficou  '00             ', mas os valores estão corretos na função que gera o header:
`$this->add(77, 79, $this->getCodigoBanco());
 $this->add(79, 94, Util::formatCnab('X', 'BANCODOBRASIL', 15));`

Não entendi o pq de ter cortado o 1 do código e não ter ficadoo nome do banco.

Segue em anexo a remessa gerada. [14061601.txt](https://github.com/eduardokum/laravel-boleto/files/326030/14061601.txt)

**Comment by jammersonf** [comment]
Consegui corrigir. Vou ver se precisa de mais alguma alteração, daí tento corrigir e mandar um PR

**Comment by eduardokum** [comment]
Que bom que conseguiu, quando mandar o PR eu dou merge
