### ISSUE TITLE
Homologação Bradesco

### ISSUE THREAD

**Issue by edolfuchs** [eduardokum/laravel-boleto#121]
Estou tentando homologar o layout do boleto no bradesco, mas ocorre um erro.

Estou homologando pelo sistema OBB Plus do bradesco. Estou seguindo os seguintes passos:

1 - Selecionar o tipo da importação

![image](https://cloud.githubusercontent.com/assets/12100777/23552585/70b1fd42-fffb-11e6-96e1-bb1ba41b7f86.png)

2 - Selecionar o boleto em pdf

![image](https://cloud.githubusercontent.com/assets/12100777/23552590/777a4fee-fffb-11e6-8912-79c87af7eb9c.png)

3 - O resultado retorna um erro

![image](https://cloud.githubusercontent.com/assets/12100777/23552595/7dbb0128-fffb-11e6-9f4d-e11bb342f803.png)

Alguem ja tentou homologar por esse sistema ou já se deparou com esse problema?

**Comment by eduardokum** [comment]
Você esta enviando o boleto em pdf pra validação da remessa?

**Comment by edolfuchs** [comment]
Isso, estou enviando em pdf.

**Comment by edigomes** [comment]
???
Amigo isso é pra validar o cnab 400 não o pdf do boleto

Em 3 de mar de 2017 10:30, "edolfuchs" <notifications@github.com> escreveu:

**Comment by edolfuchs** [comment]
Entendi. Desculpe minha ignorância, mas como posso homologar o layout do boleto?

**Comment by eduardokum** [comment]
Normalmente é enviando pro gerente ou em algum link especifico para boleto no site do banco. Mais acredito eu que seja sempre por email para conferencia manual de alguém...

**Comment by edolfuchs** [comment]
Certo. Vou ver com o gerente do banco qual é o procedimento.

Outra dúvida: esse cnab 400 seria para validar o arquivo de remessa?

**Comment by edolfuchs** [comment]
Eu testei importando um arquivo de remessa e deu um erro na linha **140 a 142 Banco Encarregado da Cobrança** disse que o campo era inválido. Ai alterei o método _addBoleto_ da classe _Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bradesco_ _linha 184_ para _$this->add(140,_ 142, '000'); e funcionou corretamente.

**Comment by eduardokum** [comment]
blza hoje esta '', envia PR pra develop que eu faço o merge.
