### ISSUE TITLE
Header da remessa do Sicoob com um caracter a menos

### ISSUE THREAD

**Issue by devguar** [eduardokum/laravel-boleto#123]
Boa tarde,
No arquivo de remessa da SICOOB (Bancoob) no header a informação do tipo (cobrança) deve ir com Ç (cedilha). Na versão que dei pull eu tinha feito um workaround pra isso funcionar sem dar problema com o strlen do PHP.

O que acontece:
Se mandar assim na geração da remessa
`$this->add(12, 26, '      COBRANÇA');`

Ele vai inserir um caracter a menos pois o STRLEN do php considera o Ç como 2 caractéres... então na primeira linha vai ficar com 399 caracteres pois todos os caracteres a seguir vão estar uma casa atrás.

Na versão que eu dei pull eu dei override no método Gerar pra dar replace do COBRANCA (sem cedilha) pro COBRANÇA (com cedilha):
`$this->add(12, 26, '      COBRANCA');`

`    public function gerar()
    {
        //Feito isso porque o Header do Sicoob exige o campo Identificação por Extenso do Tipo de Serviço: "COBRANÇA" (com cedilha).
        //Assim dava problema na validação pois o strlen retorna 2 caracteres neste caso, então vai acabar estrapolando os 400 caracteres e dando exceção, quando não é totalmente verdade.
        //Optei por não mudar a validação da classe abstrata pois este é o unico banco até o momento com essa particularidade
        $remessa = parent::gerar();
        $remessa = str_replace_first('COBRANCA','COBRANÇA',$remessa);
        return $remessa;
    }`

Concordo que não seja a melhor solução. Mas desta maneira funciona e foi homologado.

**Comment by eduardokum** [comment]
Fiz uma alteração que resolveu o problema,
o problema era a função str_split que não lida muito bem com multibyte string, alterei para preg_slipt e agora o header esta com 400 posições em vez de 399 como antes.

02a1826eb83892424a5f1f9ae3158d8f153bd250
