### ISSUE TITLE
Problema homologação remessa bradesco

### ISSUE THREAD

**Issue by edolfuchs** [eduardokum/laravel-boleto#133]
Eu enviei uma remessa para o banco validar e retornaram com alguns erros.

**Retorno do banco (problemas em vermelho):**

![erro boleto](https://cloud.githubusercontent.com/assets/12100777/24064167/adcf5156-0b41-11e7-9a69-147823b2dced.png)

**Como foi gerado a remessa:**

$boleto = new \Eduardokum\LaravelBoleto\Boleto\Banco\Bradesco([
            'logo' => 'c://...',
            'dataVencimento' => new \Carbon\Carbon('2017-03-23'),
            'valor' => 0.42,
            'multa' => 0.00, // porcento
            'juros' => 0, // porcento ao mes
            'juros_apos' =>  0, // juros e multa após
            'diasProtesto' => false, // protestar após, se for necessário
            'numero' => '23',
            'numeroDocumento' => '23',
            'pagador' => $pagador, // Objeto PessoaContract
            'beneficiario' => $beneficiario, // Objeto PessoaContract
            'agencia' => '6026', // BB, Bradesco, CEF, HSBC, Itáu
            'agenciaDv' => '7',
            'conta' => '0000097', // BB, Bradesco, CEF, HSBC, Itáu, Santander
            'contaDv' => '3', // Bradesco, HSBC, Itáu
            'carteira' => '09', // BB, Bradesco, CEF, HSBC, Itáu, Santander
            'codigoCliente' => '7818222', // Bradesco, CEF, Santander
            'descricaoDemonstrativo' => [], // máximo de 5
            'instrucoes' =>  [], // máximo de 5
            'aceite' => 'N',
            'especieDoc' => 'DM',
        ]);
$remessaArray = [
	   'idremessa' => '1706563',
           'agencia' => '6026',
           'agenciaDv' => '7',
           'conta' => '00000XX',
           'contaDv' => '3', 
           'carteira' => '09',
           'codigoCliente' => '7818222', 
           'beneficiario' => $beneficiario,
	];

$remessa = new \Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bradesco($remessaArray);
$remessa->addBoleto($boleto);

**Comentários:**

A Linha 02 - Posição 025 à 025 mesmo adicionar um zero a esquerda (ex **0**6026) na remessa parece desconsiderar esse zero.

A Linha 2- Posição 82 não consegui identificar o problema.

A Linha 2 - Posição 82 e Linha - 2 - Posição 174 à 192, não adicionei nenhum desconto.

Alguem consegue dar um auxilio?

**Comment by edolfuchs** [comment]
Obs.: O parte _'data_desconto' => new \Carbon\Carbon()_ no boleto, eu adicionei depois, para testar....na remessa que enviei não informei esse campo

**Comment by eduardokum** [comment]
Você pode mandar o txt pra eu ver como esta? se você so adicionar 'agencia' => '06026', ja não funciona?

**Comment by edolfuchs** [comment]
Forçando setar a agencia não deu certo. Mas eu consegui resolver boa parte do problema.

- Na posição **021 a 037 - Idenfificicação  da Empresa Beneficiária no Banco** o banco informou que estava errado.  

Exemplo:

Carteira: 9
Agencia: 6026
Conta: 97-3

Correto: 00090602600000973
Errado: 0090602600000973

Para resolver alterei o arquivo: 

_Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bradesco_
![remessa-erro-conta](https://cloud.githubusercontent.com/assets/12100777/24174814/7e689fde-0e71-11e7-822a-688db4c4f603.png)


- Na posição 174 à 192 (descontos) o banco exige que coloque algum valor maior que zero caso a data de desconto seja informada. Pelo que eu vi no código, não é possível deixar a data de desconto zerada. Então eu alterei o arquivo:

_Eduardokum\LaravelBoleto\Boleto\AbstractBoleto_
![boleto-erro-data](https://cloud.githubusercontent.com/assets/12100777/24174947/631edecc-0e72-11e7-9c0c-f0315a173d15.png)
_Nesse método deixei o parâmetro aceitar receber null._

A alteração acima afeta outro arquivo:



 _Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bradesco_
![boleto-erro-remessa](https://cloud.githubusercontent.com/assets/12100777/24175087/10b79560-0e73-11e7-969b-293528da6763.png)

_Adicionei um if na linha 203_

Essa alteração permite adicionar ou não um desconto: _$boleto->setDataDesconto(null)_ ou _$boleto->setDataDesconto(new \Carbon\Carbon());_

Não sei se é a melhor forma de resolver isso.

**Comment by eduardokum** [comment]
Ele seta essa data no contruct se você não passar nada, ta certo que pode sobescrever depois, mais não acho o ideial, talvez, verificar se possui desconto colocar a data se não colocar 0000000, pode ser uma ideia.

Quanto ao código do beneficiário qual foi a alteração? Me parece igual ao do projeto.
https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Remessa/Cnab400/Banco/Bradesco.php#L149

**Comment by edolfuchs** [comment]
Entendi, acho melhor sua sugestão. Quanto ao beneficiário, mandei o print errado segue a alteração:

![beneficiario](https://cloud.githubusercontent.com/assets/12100777/24201450/d20960f6-0eee-11e7-8521-4b5ca92a87aa.png)

Basicamente alterei a linha **$beneficiario_id =  Util::formatCnab('9', $this->getCarteiraNumero(), 4)** .

**Comment by eduardokum** [comment]
so alterar a linha 
de $this->add(21, 37, Util::formatCnab('X', $beneficiario_id, 17));
para $this->add(21, 37, Util::formatCnab('9', $beneficiario_id, 17));

que ele ja coloca quantos 0 for necessário antes até completar 17

**Comment by edolfuchs** [comment]
Funcionou. 

Voce consegue subir essas alterações no master?

**Comment by eduardokum** [comment]
Eu mandei no dev,  estou esperando so pra terminar de fechar a versão com o novo banco BNB e ja faço o merge.

**Comment by edolfuchs** [comment]
Valeu.

A parte da remessa é isso. O banco também validou o boleto em pdf e tem alguns ajustes. Vou abrir um novo issue, ok?

**Comment by eduardokum** [comment]
Blza
