### ISSUE TITLE
Homologação Boleto Bradesco

### ISSUE THREAD

**Issue by edolfuchs** [eduardokum/laravel-boleto#137]
Encaminhei um boleto (pdf) para validação no banco e retornaram solicitando alguns ajustes, como mostra na imagem:

![boleto-homologacao](https://cloud.githubusercontent.com/assets/12100777/24210514/23f9a178-0f08-11e7-81f2-9b46c0b888e3.png)

A parte do "local de pagamento" eu vi que é possível alterar, já nos outros items eu alterei direto no código.

Existe outra forma de ajustar esses items?

**Comment by eduardokum** [comment]
Ja removi essa quantidade e valor, na versão html ja estava sem, removi na pdf agora.

o local de pagamento voce pode setar manualmente `setLocalPagamento` ou no array `['localPagamento' => 'Pagav...']`

**Comment by edolfuchs** [comment]
Legal.

E quanto ao endereço da empresa no campo beneficiário? Tem alguma ideia de como adicionar?

**Comment by eduardokum** [comment]
`['nome'      => 'ACME Rua endereco, 123',]`

**Comment by edolfuchs** [comment]
Eu tentei adicionar o endereço no nome, mas excede o limite de tamanho do campo:

![erro-beneficiario](https://cloud.githubusercontent.com/assets/12100777/24255671/e3f23b5e-0fc4-11e7-947a-0fcf0fbee4da.png)

Não deveria quebrar a linha automaticamente?

**Comment by eduardokum** [comment]
É fixo o tamnho do boleto não pode quebrar a linha, você tem que limitar alguma coisa ai pra caber...

**Comment by edolfuchs** [comment]
Blz. Valeu
