### ISSUE TITLE
CAIXA - Cartilha de Arrecadação

### ISSUE THREAD

**Issue by marcosformagini** [eduardokum/laravel-boleto#141]
Boa tarde.

Alguém sabe ou já fez o código para geração de uma Cartilha de Arrecadação?
Essa é a documentação: [https://cmsportal.febraban.org.br/Arquivos/documentos/PDF/Layout%20-%20C%C3%B3digo%20de%20Barras%20-%20Vers%C3%A3o%205%20-%2001_08_2016.pdf](https://cmsportal.febraban.org.br/Arquivos/documentos/PDF/Layout%20-%20C%C3%B3digo%20de%20Barras%20-%20Vers%C3%A3o%205%20-%2001_08_2016.pdf)

**Comment by eduardokum** [comment]
Olá bom dia, infelizmente não, veja se algume já fez la no grupo https://groups.google.com/d/forum/laravel-boleto.

Abraço
