### ISSUE TITLE
Como informar edição do boleto e cancelamento na remessa 

### ISSUE THREAD

**Issue by rafwell** [eduardokum/laravel-boleto#144]
Como posso informar que um boleto foi editado ou que foi cancelado na geração da remessa?

**Comment by rafwell** [comment]
Pelo que li no código, a informação da alteração do vencimento e status baixa está condicionada ao objeto do boleto. Mas, pela sua experiência, não há necessidade de implementar as outras ocorrências?

Trecho do Cnab400\Banco\Bradesco, linha 174
```
$this->add(109, 110, self::OCORRENCIA_REMESSA); // REGISTRO
        if ($boleto->getStatus() == $boleto::STATUS_BAIXA) {
            $this->add(109, 110, self::OCORRENCIA_PEDIDO_BAIXA); // BAIXA
        }
        if ($boleto->getStatus() == $boleto::STATUS_ALTERACAO) {
            $this->add(109, 110, self::OCORRENCIA_ALT_VENCIMENTO); // ALTERAR VENCIMENTO
        }
```

**Comment by brunoneve** [comment]
@rafwell 

em seu projeto você possui uma base de dados e nela tabela com os boletos, digamos que em sua tabela boletos você tem coluna status_boleto.

Digamos que as seguintes numerações correspondem as ações:
1 = Registrar; // PADRÃO
2 = Alteração;
3 = Baixar/Cancelar;

Então no momento que você vai criar uma remessa, você vai verificar o campo status_boleto, mais ou menos assim:

` 
        if ($blt->status_boleto == 2){
                $boleto->alterarBoleto();  #determinar novo status do boleto para remessa
        } 

        if ($blt->status_boleto == 3){
                $boleto->baixarBoleto();  #determinar novo status do boleto para remessa
        } 

        $remessa->addBoleto($boleto); #Adiciona boleto na remessa 

`
Basicamente é assim.

**Comment by eduardokum** [comment]
Olá.

Pelas necessidades que vi até hoje não. Existe muitas opções, e cada banco possui as suas. Essas são basicamente as que possui em todos os bancos.

**Comment by rafwell** [comment]
@brunoneve Obrigado! A lógica eu já sabia como aplicar, a dúvida era quanto as outros tipos de remessa.

@eduardokum Blz cara, já me deixa mais tranquilo. Obrigado e parabéns pelo trabalho.
