### ISSUE TITLE
[Dúvida] Usar em um projeto não Laravel

### ISSUE THREAD

**Issue by ednonunes** [eduardokum/laravel-boleto#147]
Olá, consigo utilizar este pacote em um projeto não Laravel (nenhum framework pra ser mais exato)?
Se sim, preciso ajustar algo?

Obrigado

**Comment by edigomes** [comment]
Creio q dá sim cara ele vai baixar as dependências do Illuminate.

**Comment by marcosformagini** [comment]
Eu uso em Phalcon PHP! Algumas coisas tiveram que ser modificadas, mas funciona muito bem!

**Comment by eduardokum** [comment]
Em teoria funciona rsrs como o @marcosformagini disse que funciona no dele então funciona! abraço
