### ISSUE TITLE
Validação Remessa Itaú CNAB 400

### ISSUE THREAD

**Issue by brnmonteiro** [eduardokum/laravel-boleto#148]
Quando o arquivo de remessa é validado no gerenciador do itau apresenta os seguintes erros:

[valida_CN0205BBREM.pdf](https://github.com/eduardokum/laravel-boleto/files/971447/valida_CN0205BBREM.pdf)

Porém a transmissão é efetuada sem problema. Por que será que está dando isto?

**Comment by brnmonteiro** [comment]
Pelo manual 2016 itau o campo bairro é da posição 315 a 326.
Vou ver se consigo fazer um PR

[layout_cobranca_400bytes_cnab_itau versão 2016.pdf](https://github.com/eduardokum/laravel-boleto/files/971472/layout_cobranca_400bytes_cnab_itau.versao.2016.pdf)

**Comment by brnmonteiro** [comment]
Na verdade isso já esta implementado, perdão.

**Comment by richardgdias** [comment]
@brnpimentel pode me informar por onde você faz o teste de validação? estou começando a fazer a remessa agora e preciso desse validador
