### ISSUE TITLE
Layout Caixa

### ISSUE THREAD

**Issue by lucassmacedo** [eduardokum/laravel-boleto#15]
Olá, gostaria de saber qual é o padrão de Layout que está sendo usado para o padrão Caixa?
Remessa está como 240?
E o Retorno 240 ou 400?
Tive alguns problemas ao ler o retorno e enviar a remessa no sistema da caixa.

**Comment by eduardokum** [comment]
Tanto retorno quando remessa é 400 posições para todos os bancos, eles não informam o erro??

**Comment by lucassmacedo** [comment]
O erro era examante esse, dizendo que não era 400 posições, grato irei alterar aqui.

**Comment by eduardokum** [comment]
Então, todos são 400 posicoes, pode ser que esteja com erro em algum
parametro que nao esta sendo tratado e ele esta passando 399 posicoes ou
pode ser a quebra de linha se voce salvar no bloco de notas por exemplo ele
perde o CR e LN, são exemplos dos problemas que pego normalmente.

EDUARDO GUSMÃO
Analista de Sistemas
E-mail: eduardo@intrasis.com.br
Telefone: 11 2208 2423 | 41 8479 6288 (Oi)
Endereço: Av. Engenheiro Caetano Álvares, 3536 | São Paulo
Site: www.intrasis.com.br

Em 27 de junho de 2016 14:22, Lucas Macedo <notifications@github.com>
escreveu:
