### ISSUE TITLE
Dígito verificador da agência remessa BB

### ISSUE THREAD

**Issue by devguar** [eduardokum/laravel-boleto#152]
Boa noite!
Estou com problemas em um cliente que utiliza Banco do Brasil onde o digito verificador da conta e agência é X.

Tentei mandar a remessa com o verificador da agência calculado pelo módulo 11 e não foi aceito:
```
        $this->add(27, 30, Util::formatCnab('9', $this->getAgencia(), 4));
        $this->add(31, 31, Util::modulo11($this->getAgencia()));
        $this->add(32, 39, Util::formatCnab('9', $this->getConta(), 8));
        $this->add(40, 40, Util::formatCnab('9', $this->getContaDv(), 1));
```
O retorno no processo de homologação no banco foi:

> ****************************** Header do Arquivo *******************************
> Posições 031 a 031: Preencher com o DV correto da agência: 'X'
> Posições 040 a 040: Preencher com o DV correto da conta corrente: 'X'
>  
> ******************************  Detalhe tipo 7  ********************************
> Posições 022 a 022: Preencher com o DV correto da agência: 'X'
> Posições 031 a 031: Preencher com o DV correto da conta corrente: 'X'

Confirmei com o gerente do banco se é pra enviar a string X. De fato é isso mesmo.

Pensei em alterar a classe da remessa BB CNAB400 para mandar o dígito verificador da agência mas aí será necessário alterar o AbstractRemessa.php e provavelmente perderá compatibilidade.

Alguma sugestão?

**Comment by eduardokum** [comment]
Você tem algum manual com o calculo do DV da agencia e conta do BB?

**Comment by eduardokum** [comment]
O digito da conta corrente voce ainda pode passar so alterar
de
```php
$this->add(31, 31, Util::formatCnab('9', $this->getContaDv(), 1));
```
para
```php
$this->add(31, 31, Util::formatCnab('X', $this->getContaDv(), 1));
```

Ja fiz a alteração ja vou subir, eu acredito que o calculo do DV da agencia seria X se o digito for 10, se for isso seria mudar
de
```php
$this->add(22, 22, Util::modulo11($this->getAgencia()));
```
para
```php
$this->add(22, 22, Util::modulo11($this->getAgencia(), 2, 9, 0, 'X'));
```

Mais precisaria ter certeza que o X seria nessa ocasião...

**Comment by eduardokum** [comment]
Ja vi aqui é isso mesmo

![image](https://cloud.githubusercontent.com/assets/2566340/26072632/91493b54-3982-11e7-88e0-cad55a27f2c7.png)


vou mandar um push, depois veja se deu certo

**Comment by devguar** [comment]
Perfeito @eduardokum!
É exatamente isso. Testado e validado.
Obrigado!

**Comment by mastertag** [comment]
esse bug ainda está aqui.
