### ISSUE TITLE
Envio de remessa

### ISSUE THREAD

**Issue by aneraojunior** [eduardokum/laravel-boleto#158]
Olá. Como sou novo nesse mundo dos boletos, estou na dúvida sobre como enviar um arquivo de remessa ao banco, no caso, o Sicoob.

Eu consegui imprimir o arquivo de remessa na view mas, e agora? Como envio isso ao banco? Em que formato?

Eu dei uma procurada no Google mas não consegui achar nada concreto e o cara do banco não tem a menor ideia do que eu esteja falando.

**Comment by rafwell** [comment]
Você deve criar o arquivo da remessa e importar dentro do sistema do banco, pelo internet banking ou similar

**Comment by aneraojunior** [comment]
Entendi. As remessas geradas para o banco sicoob estão no formato 400, né?
