### ISSUE TITLE
cnab240 x cnab400

### ISSUE THREAD

**Issue by aneraojunior** [eduardokum/laravel-boleto#159]
Pessoal, hoje em conversa com o banco Sicoob, me informaram que o cnab 400 vai ser descontinuado e, por isso, já não estão mais aceitando remessas nesse formato.

Pelo que eu vi do laravel-boleto ele gere remessas para o Sicoob apenas em cnab400. É isso mesmo?
Pergunto porque se não for possível gerar em 240 vai um pouco além do meu conhecimento para fazer essa alteração no momento.

**Comment by eduardokum** [comment]
Na verdade tem alguns bancos que ja tem o 240 mais precisa pegar o manual em implementar a versão de 240 para os bancos que não tem o suporte ainda

**Comment by aneraojunior** [comment]
Obrigado por responder, eduardokum.
O banco em questão (Sicoob) está aceitando apenas o 240 agora.
A questão é: O laravel-boleto não emite em 240, né? Se for o caso preciso dar uma esforçada aqui para entender como fazer a remessa em 240.

**Comment by eduardokum** [comment]
O Sicoob le retorno de 240 (ainda não validado 100%) mais ainda não gera, o projeto hj so gera do santander, precisaria pegar o manual de 240 e implementar o do sicoob

**Comment by aneraojunior** [comment]
Beleza. Quando eu conseguir vou fazer um pull request
