### ISSUE TITLE
Problema ao instalar o pacote

### ISSUE THREAD

**Issue by ederlopes** [eduardokum/laravel-boleto#16]
Bom dia, 

Estou com problemas com a minha aplicação já é o segundo pacote que eu instalo. Após a instalação a aplicação começa a gerar o seguinte erro "Call to undefined method Illuminate\Database\Query\Builder" como se tive-se dando conflito com uma das minhas classes...Gostaria de saber se alguém tem alguma sugestão do que possa ser....segue o erro completo

BadMethodCallException in Builder.php line 2161: Call to undefined method Illuminate\Database\Query\Builder::buscarPrecoProduto()

lembrando que este erro não acontece antes da instalação do pacote....

**Comment by eduardokum** [comment]
Não faço a menor ideia, não utilizo nada de query no projeto

EDUARDO GUSMÃO
Analista de Sistemas
E-mail: eduardo@intrasis.com.br
Telefone: 11 2208 2423 | 41 8479 6288 (Oi)
Endereço: Av. Engenheiro Caetano Álvares, 3536 | São Paulo
Site: www.intrasis.com.br

Em 1 de julho de 2016 10:27, Eder Campos <notifications@github.com>
escreveu:

**Comment by ederlopes** [comment]
@eduardokum o meu convenio com o banco é de 8 digitos como faço para implementar a regra na geração do nosso número ele tem que ser composto por quantos digitos?

**Comment by eduardokum** [comment]
[Convênio de 7 posições](https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Remessa/Banco/Bb.php#L224) não tem suporte para outros convênios, teria que ver nos manuais e implementar.
