### ISSUE TITLE
Erro ao processar aquivo de retorno

### ISSUE THREAD

**Issue by marcus-campos** [eduardokum/laravel-boleto#163]
Boa tarde,

Estou com problemas para processar o retorno do Bancoob. 

O que já tentei:
=> Converter de UTF-8 para ISO-8859-1
=> Converter de US-ASCII para ISO-8859-1

Alguém poderia me ajudar?

Segue a mensagem de erro

`(1/1) ErrorException array_splice() expects parameter 1 to be array, null given
--
in Util.php (line 787)
at HandleExceptions->handleError(2, 'array_splice() expects parameter 1 to be array, null given', '/var/www/html/Web/gerador-boletos/vendor/marcuscampos/laravel-boleto/src/Util.php', 787, array('i' => 0, 'f' => 3, 'array' => null, 't' => 3, 'toSplice' => null))
at array_splice(null, 0, 3)in Util.php (line 787)
at Util::remove(0, 3, null)in AbstractRetorno.php (line 222)
at AbstractRetorno->rem(1, 3, null)in Bancoob.php (line 251)
at Bancoob->processarHeaderLote(array('7', '5', '6', '0', '0', '0', '1', '1', 'T', '0', '1', ' ', ' ', '0', '4', '3', ' ', '2', '0', '1', '9', '2', '2', '4', '0', '6', '6', '0', '0', '0', '1', '9', '3', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '4', '3', '7', '0', '0', '0', '0', '0', '0', '9', '0', '4', '3', '7', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '2', '6', '7', '5', '6', '0', 'C', 'L', 'U', 'B', 'E', ' ', 'D', 'E', ' ', 'B', 'E', 'N', 'E', 'F', 'I', 'C', 'I', 'O', 'S', ',', ' ', 'P', 'R', 'O', 'D', 'U', 'T', 'O', 'S', ',', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '0', '0', '0', '0', '0', '0', '0', '0', '1', '6', '1', '2', '2', '0', '1', '6', '0', '0', '0', '0', '0', '0', '0', '0', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '))in AbstractRetorno.php (line 127)`

**Comment by eduardokum** [comment]
Opa desculpa a demora, você pode me enviar esse arquivo para eu poder fazer uns testes aqui?

**Comment by marcus-campos** [comment]
@eduardokum Sem problemas meu caro, segue o link para o arquivo de retorno: https://drive.google.com/a/devyzi.com/file/d/0B7aXWwGpZJx7QmFJZm1fUUU1djA/view?usp=sharing

**Comment by marcus-campos** [comment]
Olá Eduardo,

Consegui resolver meu problema, tratando o retorno da function remove em Util. 

O que acontecia é que em certos momentos (quase sempre na ultima linha dos retornos do Bancoob) a linha vinha em branco e o retorno ficava como nulo.

Fiz um pull request, por favor analise e se de fato for contribuir ao projeto, aceite-o.

**Comment by eduardokum** [comment]
respondi lá,
