### ISSUE TITLE
Remover dados do rodapé

### ISSUE THREAD

**Issue by diegomengarda** [eduardokum/laravel-boleto#164]
É possível remover as informações do rodapé quando é gerado vários boletos ?
Ex.: Boleto 1/10

Obrigado.

**Comment by eduardokum** [comment]
Opa desculpe a demora, acredito que se adicionar um a um o rodapé some.

Vou arrumar isso amanha pra não sobrepor o código de barras.

**Comment by guicouto** [comment]
Precisei dessa funcionalidade hoje. Fiz como Eduardo comentou, adicionei um a um. Funcionou perfeitamente.

**Comment by eduardokum** [comment]
Bom dia, coloquei uma flag no addBoletos

```php
public function addBoletos(array $boletos, $withGroup = true)
```

que se setar em false ele não gera essas páginas.
