### ISSUE TITLE
Dados de Beneficiário

### ISSUE THREAD

**Issue by frredy** [eduardokum/laravel-boleto#168]
Olá pessoal,

Gostaria de entender melhor o programa de geração de boletos...

1. O que devo colocar na variável:

       'conta' => ,  Código da operação "870"? ou
                            Código da conta que já utilizo para emitir os boletos pelo CobCaixa? ou os dois
                            Código da conta corrente onde são creditados os boletos?

      'codigoCliente' => ,   Código da operação "870"? ou
                                          Código da conta que já utilizo para emitir os boletos pelo CobCaixa? ou
                                          Código da conta corrente onde são creditados os boletos?
                                          Ou código do cliente para quem o boleto foi emitido(código aleatório)?

2. Considerando que os números "5" são dígitos verificadores, porque os números 1, 4 e 7 nunca mudam(o que representam)?

00000.00005   05000.100045    00000.00005#    5    70000000000000

**Comment by eduardokum** [comment]
A Conta é a conta bancária do emissor do boleto e o código do cliente é um numero que o gerente passa, tem banco que chama de código de beneficiário, código de cliente, código de transmissão, código de cedente.

o 1 é uma constante da caixa
o 4 é é outra constante 
o 7 é parte do fator de vencimento, parta da data de vencimento.
