### ISSUE TITLE
Validação Remessa CEF

### ISSUE THREAD

**Issue by frredy** [eduardokum/laravel-boleto#173]
Boa tarde!
Consegui homologar o layout dos boletos, mas estou tendo problema para homologar o arquivo de remessa. A caixa está disponibilizando um programa de validador de arquivo de remessa, só pesquisar no google "validador arquivo remessa caixa" e clicar no primeiro link. 

O programa não está aprovando por ausência das linhas 2, 3 e 6.

As linhas 1,4 e 5 ele valida normalmente sem erros

Alguém sabe porque no meu arquivo de remessa está faltando 3 linhas?

**Comment by eduardokum** [comment]
Olá, não tem a ver com a carteira que você esta usando que talvez exija essas linhas?

**Comment by frredy** [comment]
Acabei de conversar com o gerente da Caixa, ele disse que o padrão 3 linhas será o novo padrão da caixa, mas por enquanto o padrão é de 6 linhas e o validador serve para todo brasil independente da carteira, basta escolher 240 ou 400 (no meu caso escolhi 400).
O padrão 3 linhas engloba todas as informações do padrão de 6 linhas. No de 6 apenas muda a disposição das informações.

Ele me passou um arquivo de remessa que é validado:
1)01REMESSA01COBRANCA       1604077583          Escola de Infantil Fa104C ECON FEDERAL 240217                                                                                                                                                                                                                                                                                                 2)00002000001
3)1020329881100010916040473832000090300406400000000200000114000000002000001                                 4)0101000200000109031700000000010001040000003N240217020000000000000000903170000000000300000000000000000000000000000100033235178813THIAGO MASCARENHAS FIGUEIRA DA SILVA    R. PEDRINA OLIVEIRA DA CUNHA, 530       JARDIM TERRA13185558HORTOLANDIA    SP0102570000000020                      00901000002
5)9                                                                                                                                                                                                                                                                                                                                                                                                         6)000003

**Comment by frredy** [comment]
Parece que o padrão 3 linhas dobra as informações

**Comment by frredy** [comment]
Fiz um teste manual aqui...
Joguei as duas remessas no sublime e comparei uma com a outra
A remessa do laravel-boleto tinha duas linhas em branco depois do header, e antes do encerramento
retirei as linhas em branco colei em um novo txt e submeti no validador da caixa e aprovou
Então para correção basta ver porque ele está adicionando essas linhas

**Comment by frredy** [comment]
Consegui corrigir o problema...
No arquivo: laravel-boleto/src/Cnab/Remessa/Cnab400/Banco/Caixa.php
Na linha 61 e 68
De:
protected $fimLinha = "\r\n";
protected $fimArquivo = "\r\n";

Para: 
protected $fimLinha = "\n";
protected $fimArquivo = "\n";

Gerei, submeti no validador de remessa da caixa e apareceu "Aprovado".

Fica ai galera pra quem precisar.

Abraços

**Comment by eduardokum** [comment]
Opa, Obrigado, vou olhar se tem novo manual da caixa pois no antigo era \r\n, no novo devem ter alterado.
