### ISSUE TITLE
Boleto Registrado Santander

### ISSUE THREAD

**Issue by eullercdr** [eduardokum/laravel-boleto#174]
Prezados, é possivel gerar boletos registrados para o banco Santander utilizando esta biblioteca?

Desde já agradeço!

**Comment by eduardokum** [comment]
Sim é sim.

**Comment by eullercdr** [comment]
Apenas por remessa ou online. Pois online as chamadas são totalmente diferentes e exigem um certificado digital.

**Comment by eduardokum** [comment]
Apenas remessa, geração do arquivo e importação no bankline
