### ISSUE TITLE
Remessa Santander problema valor carteira

### ISSUE THREAD

**Issue by kcirtapsi** [eduardokum/laravel-boleto#178]
Olá,

Estou tentando montar uma remessa registrada para banco santander utilizando o modelo:
https://github.com/eduardokum/laravel-boleto/blob/master/exemplos/santander_remessa.php

O banco me informou que devo utilizar o valor 5 para carteira, porém ao utilizar este valor recebo um erro exception:

Carteira não disponível!

Podem me ajudar?

Obrigado desde já.

**Comment by eduardokum** [comment]
Pode usar a carteira 101, na remessa e boleto as carteiras disponiveis sao 101 com registro e 102 sem registro, usando a 5 a classe converteria para 101, não sei pq da exception, depois vou fazer uns testes, mais pode usar a 101 que da certo.

Abraço
