### ISSUE TITLE
Bancoob CNAB 400

### ISSUE THREAD

**Issue by marcus-campos** [eduardokum/laravel-boleto#181]
Olá,

Eu estive conversando com o pessoal do Sicoob (Bancoob) e eles me informaram que o CNAB 400 não será mais aceito. Alguém já tentou implementar o 240? Como devo caminhar para implementar e contribuir com o projeto?

![captura de tela de 2017-08-10 11-49-42](https://user-images.githubusercontent.com/5151894/29176654-d67785da-7dc2-11e7-86c8-f899e01164bf.png)

**Comment by guicouto** [comment]
Olá Marcus,
Boa noite. Entrei em contato como meu gerente do Sicoob para ver essa questão do CNAB400. O mesmo informou que ainda não existe essa data definida para descontinuação do CNAB400, porém me recomendou que seja implementado o CNAB240 o quanto antes. 

Caso você tenha interesse podemos trocar uma ideia para inplementarmos essa modalidade juntos. 

Um abraço.

**Comment by eduardokum** [comment]
Aparentemente os bancos vão padronizar no 240, ja tem 240 feito, precisa so usar como molde pra fazer dos outros bancos, ultimamente estou bem enrolado de tempo, mais ja estou pretendendo fazer isso a algum tempo...

**Comment by marcus-campos** [comment]
Olá @guicouto e @guicouto,

Me adicione no meu email e vamos começar a implementar para o Bancoob.

campos.v.marcus@gmail.com

**Comment by eduardokum** [comment]
Vocês tem o manual novo? aparentemente os bancos tem uma versão nova de jul/2017... se tiver faz um PR que tem banco que não estou achando em lugar nenhum
