### ISSUE TITLE
Sacador/Avalista - Bancoob

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#183]
Boa tarde,
ao adicionar no boleto o sacador/avalista, utilizando o método setSacadorAvalista($ObjetoPessoaContract), ou seja adicionando diretamente no array do boleto, no atributo sacadorAvalista=>$ObjetoPessoaContract, a biblioteca aceita e processa normalmente. Porém no momento de fazer o render do HTML ou do PDF, os dados que são exibidos no sacador/avalista são os dados do pagador.

Este bug aconteceu comigo, durante o processo de geração dos boletos do Banco Bancoob.

**Comment by eduardokum** [comment]
Vou dar uma conferida nisso amanhã. Realmente nunca usei essa opção de sacador avalista...

**Comment by eduardokum** [comment]
Achei onde estava o problema, ja subi. Abraço
