### ISSUE TITLE
Retorno - Bancoob

### ISSUE THREAD

**Issue by rafaelggads** [eduardokum/laravel-boleto#185]
Boa noite, 
ao realizar processamento do arquivo retorno tenho a seguinte error "Arquivo nomedoarquivo.RET não é um arquivo de retorno". Analisei o motivo pois já tinha realizado o processamento de outros arquivos, então olhando os commit encontrei a alteração na classe "Ultil.php" no método "isCnab400" onde passou a utilizar o "mb_strlen" e então realizei um debug identifiquei que com essa alteração ela retorna 398 caracteres e não passa na validação, abri o notepad e com a documentação do sicoob tenho todos os dados informado e com 400 posições. realizei teste na versão anterior e consigo realizar o processamento. Nos outros bancos não tenho problema, porem no siccob tenho e acredito ser por causa que a codificação do arquivo não vem utf-8 e sim ANSI. Segue o arquivo de retorno para teste.
[CEDcnab4000000205141201705220750590246.RET.zip](https://github.com/eduardokum/laravel-boleto/files/1226544/CEDcnab4000000205141201705220750590246.RET.zip)

**Comment by rafaelggads** [comment]
Resolvi da seguinte forma.

    /**
     * Validação para o tipo de cnab 240
     *
     * @param  $content
     * @return bool
     */
    public static function isCnab240($content)
    {
        $content = is_array($content) ? $content[0] : $content;
        return mb_strlen(rtrim(utf8_decode($content), "\r\n")) == 240 ? true : false;
    }

    /**
     * Validação para o tipo de cnab 400
     *
     * @param  $content
     * @return bool
     */
    public static function isCnab400($content)
    {
        $content = is_array($content) ? $content[0] : $content;
        return mb_strlen(rtrim(utf8_decode($content), "\r\n")) == 400 ? true : false;
    }

Na validação para o tipo de cnab 400 e cnab 240, estou passando o conteúdo para UTF-8,  ja que o conteúdo que vem nos arquivos de retorno SICOOB está em ANSI, pois para o obter o número de caracteres usando "mb_strlen" a sequencia dos caracteres devem ser UTF8.

**Comment by eduardokum** [comment]
Na verdade no seu PR voce esta usando o decode o decode é pra mudar de UTF-8 para o ISO qualquer coisa, acho que vou colocar como dep a lib "neitanod/forceutf8": "^2.0" para forçar pro utf8 do jeito correto e não dar esse problema. Do jeito que você colocou no PR depende do banco se ja estiver em utf8 ou se não tiver pode dar resultados diferentes...

**Comment by rafaelggads** [comment]
Verdade acabei me confundindo na tentativa de resolver, beleza então aguardando a alteração dessa forma que falou. obrigado

**Comment by rafaelggads** [comment]
Tem a previsão de quando vai fazer merge com a master ?

**Comment by eduardokum** [comment]
amanha vou fazer uma avaliação de se vai quebrar alguma coisa, so depois disso posso fazer o merge e criar tag

**Comment by eduardokum** [comment]
Fiz o merge la
