### ISSUE TITLE
Bancoob CNAB 240

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#193]
**Pessoal, boa tarde.**
Estou iniciando o desenvolvimento do **CNAB 240** do Bancoob.
Deixando esse issue aberto, pois caso alguém já tenha começado favor comunicar aqui.

Fiz um fork, disponível em: [https://github.com/guicouto/laravel-boleto](https://github.com/guicouto/laravel-boleto)
Caso alguém queira contribuir / acompanhar.

**Desde já agradeço pela atenção.**

**Comment by eduardokum** [comment]
Olá, boa tarde, estou começando a desenvolver os 240 agora, ja fiz o do itau, do bradesco e estou desenvolvendo agora o da caixa, so consegui validar 100% do itau pois é a minha conta de cobrança, dos outros bancos preciso utilizar contas de clientes porém todos os meus clientes utilizam 400 posições... depois que eu fizer a remessa de 240 vou começar os retornos... mais não tenho um prazo ainda

**Comment by guicouto** [comment]
Tranquilo. Já consegui o suporte do Bancoob, e já estou iniciando o desenvolvimento. O pessoal lá ficou a disposição para homologar a remessa também. Dentro de alguns dias eu faço o pull request para análise e já informo se tudo foi validado corretamente pelo Bancoob.

**Comment by eduardokum** [comment]
Você pode me mandar os manuais pra eu atualizar no repositorio? se tiver os de 240 e 400 eu atualizo aqui. vlw

**Comment by guicouto** [comment]
Posso sim.
Segue o mesmo.

**OBS:** Segundo o Bancoob, a última versão é essa de Fev 2017.

[Layouts_para_troca_de_informacões_Fev_2017.xls.zip](https://github.com/eduardokum/laravel-boleto/files/1246727/Layouts_para_troca_de_informacoes_Fev_2017.xls.zip)

**Comment by eduardokum** [comment]
É mais atual que o que tem aqui ja, o daqui é de 2015, ja vou subir vlw

**Comment by guicouto** [comment]
Finalizado a implementação do CNAB 240. Fiz todos os testes com base em uma remessa real, e tudo está certo. Hoje na parte da manhã já faço a validação no banco.

Sabem me dizer se o retorno do **Bancoob CNAB240** já está funcionando certinho?

**Comment by eduardokum** [comment]
Não sei cara, não foi eu que fiz ela, precisa testar, quando mandar o PR manda pra develop blza?

**Comment by guicouto** [comment]
PR Efetuado no develop.
[#194 - Pull Request](https://github.com/eduardokum/laravel-boleto/pull/194)
