### ISSUE TITLE
Layout Boletos

### ISSUE THREAD

**Issue by rafaelggads** [eduardokum/laravel-boleto#195]
Ao gerar PDF de vários  boletos a quantidade de Boletos está saindo por baixo do código de barra. 
Estou gerando da seguinte forma:
$pdf = new \Eduardokum\LaravelBoleto\Boleto\Render\Pdf();
$pdf->addBoletos($boletos);
return response($pdf->gerarBoleto(), 200, [
    'Content-Type' => 'application/pdf',
    'Content-Disposition' => 'inline; Boleto',
]);

Na versão anterior da biblioteca não tive esse problema, alguma coisa foi alterada em relação a isso?

**Comment by eduardokum** [comment]
Existe duas opções, ou você usa o método addBoleto e adiciona um a um os boletos ou passa a false na opções withGroup do addBoletos.

https://github.com/eduardokum/laravel-boleto/blob/develop/src/Boleto/Render/Pdf.php#L391
