### ISSUE TITLE
Remessa Banco do Brasil para Homologação

### ISSUE THREAD

**Issue by flavio-evocorp** [eduardokum/laravel-boleto#197]
Olá tem algum método que indique na hora da geração da remessa se a mesma é para **produção** ou é para **homologação**? Procurei e não encontrei. 
No momento estou alterando manualmente a string antes de gerar o arquivo.

**Comment by eduardokum** [comment]
Hoje so existe a opção no banrisul acredito, a maioria dos bancos não faz diferença nenhuma, precisaria fazer um levantamento de quais bancos faz essa diferenciação para adicionar esse suporte a eles.

**Comment by flavio-evocorp** [comment]
Banco do Brasil também diferencia, segundo a documentação dever vir **TESTE** NO LUGAR DE **REMESSA**
 
![bb-rem](https://user-images.githubusercontent.com/24256804/30027437-6066934c-9157-11e7-88c6-f28a010422cf.png)
