### ISSUE TITLE
Problema com homologação bb apenas convênio 7 Digitos

### ISSUE THREAD

**Issue by flavio-evocorp** [eduardokum/laravel-boleto#198]
Pequeno problema ao gerar nosso número para impressão no boleto, quando convênio é de 7 digitos

Nosso número está sendo impresso no boleto da seguinte forma:
9999999000000000-1
O banco acusou erro e informou que o correto seria o seguinte:
99999990000000001 => Sem Digito Verificador

Procurei no código e vi que uma pequena alteração resolve o problema:
no arquivo **src/Boleto/Banco/Bb.php**
no metodo getNossoNumeroBoleto()
alertar a condição  de **<= 17** para **< 17**

Agradeço a atenção, vlw!

**Comment by eduardokum** [comment]
Opa, o manual que eu tenho a apresentação no boleto esta com esse - ai separando o digito. 

![image](https://user-images.githubusercontent.com/2566340/30431219-4433a388-9934-11e7-8093-e649b8a8ca36.png)

Pelo que você esta dizendo o único problema é o traço pois o numero de baixo tem o dv só não tem o traço separando... 

Se você tiver um manual mais novo que tenha essa correção pode enviar aqui?

**Comment by flavio-evocorp** [comment]
Olá amigo, 
Desculpe acredito que não conseguir expressar de forma clara o problema.

Para convênio de 7 digitos do Banco do Brasil é Opcional na impressão do boleto.
Vou exemplificar o problema:

Nosso Numero Sem o DV **99999990000000001**

Na impressão do boleto eu tanto posso imprimir **99999990000000001** Sem o DV
Como tambem posso imprimir **99999990000000001-X** Com o DV

O problema e que quando o boleto é gerado para impressão ele não calcula o DV e coloca o último número como sendo o DV dessa forma  **9999999000000000-1** onde o 1 não é o DV mas sim o último digito da sequencia.

Quanto ao manual de geração do boleto, estou usando o mesmo que está anexado nos manuais deste projeto.

Agradeço a atenção vlw.

**Comment by eduardokum** [comment]
Na verdade não é isso que ocorre...

Aqui ele gera o nosso numero com 17 posicoes
https://github.com/eduardokum/laravel-boleto/blob/develop/src/Boleto/Banco/Bb.php#L118

e aqui ele cria o nosso numero do boleto
https://github.com/eduardokum/laravel-boleto/blob/develop/src/Boleto/Banco/Bb.php#L132

que são as 17 posicoes, calcula o dv e coloca ele no final com o -

**Comment by flavio-evocorp** [comment]
Correto mas veja que quando ele cria o nosso número do boleto
https://github.com/eduardokum/laravel-boleto/blob/develop/src/Boleto/Banco/Bb.php#L132

ele chama o metodo CalculoDV::bbNossoNumero

Mas o metodo CalculoDV::bbNossoNumero retorna null para convenio >= 17
https://github.com/eduardokum/laravel-boleto/blob/develop/src/CalculoDV.php#L22

**Comment by eduardokum** [comment]
Tem razão, você ja fez a alteração? se fez manda PR na develop por favor.

**Comment by eduardokum** [comment]
Vlw.
