### ISSUE TITLE
Geração boleto com código do cliente

### ISSUE THREAD

**Issue by kcirtapsi** [eduardokum/laravel-boleto#207]
Olá srs.

Gerei um boleto e TXT de remessa registrada e ao enviar para o banco santander avaliar recebi a resposta de uma inconsistência.

No na área do PDF **Agência / Código beneficiário** hoje está sendo exibido os dígitos da Agência -/ Nrº conta do cliente Ex: 1234- / 123214546-1

Mas o contato do Santander nos informou que no lugar de Nº da conta do cliente, deve ser exibido o código do cliente.

E no código digitável também está com a mesma situação, hoje faz referência à conta do cliente, e precisa ter como referência o código do cliente.

Ao montar o array de boleto fiz de forma correta, uso o índice **conta** com o número da conta e o índice **codigoCliente** com o código do cliente.

Podem me ajudar?

**Comment by eduardokum** [comment]
Utilize o branch develop que esta mudança ja foi feita, logo logo solto um release no master.
