### ISSUE TITLE
Geração boleto com código do cliente

### ISSUE THREAD

**Issue by kcirtapsi** [eduardokum/laravel-boleto#208]
Olá srs.

Gerei um boleto e TXT de remessa registrada e ao enviar para o banco santander avaliar recebi a resposta de uma inconsistência.

No na área do PDF Agência / Código beneficiário hoje está sendo exibido os dígitos da Agência -/ Nrº conta do cliente Ex: 1234- / 123214546-1

Mas o contato do Santander nos informou que no lugar de Nº da conta do cliente, deve ser exibido o código do cliente.

E no código digitável também está com a mesma situação, hoje faz referência à conta do cliente, e precisa ter como referência o código do cliente.

Ao montar o array de boleto fiz de forma correta, uso o índice conta com o número da conta e o índice codigoCliente com o código do cliente.

Podem me ajudar?

PS: 
**Utilizei o branch develop como indicado pelo Eduardo, porém agora a situação está diferente:**
**Agora no campo do PDF agencia /  código do cliente é exibido o numero da agência - / , onde deveria ter o código do cliente está vazio. Na linha digitável continua como antes**

Podem me ajudar? agradeço desde já.

**Comment by eduardokum** [comment]
Deve ser algum erro nas informações que você esta passando pela classe, agencia conta codigo do cliente, o santander acabou de ser homologado, esta sendo enviados sem problemas para o banco

**Comment by kcirtapsi** [comment]
Então,  eu criei 2 diretórios no ftp, um com o branch develop e o outro com o branch master, eu passo o mesmo array para os 2 branchs, e um ele retorna o numero da conta no lugar do cliente, e pro branch develop o numero do cliente está vazio.

Não sei se ajuda muito

**Comment by eduardokum** [comment]
O que esta correto é o do branch develop, é o que acabou de ser homologado

**Comment by eduardokum** [comment]
veja essa issue https://github.com/eduardokum/laravel-boleto/issues/180

**Comment by kcirtapsi** [comment]
Obrigado @eduardokum 
Sobre a área do PDF consegui ajustar o meu script, agora está aparecendo de forma correta, porém a linha digitável persiste mencionando a conta do cliente, vou colocar abaixo a imagem e código utilizado.

![erro_boleto](https://user-images.githubusercontent.com/25175360/30860563-e886e6b2-a29d-11e7-9f9c-67477ccab14e.jpg)

`
$beneficiario = new \Eduardokum\LaravelBoleto\Pessoa(
		[
			'nome'      => 'EMP BENEFICIADA',
			'endereco'  => 'ENDERECO BENEFICIADA',
			'cep'       => '77777777',
			'uf'        => 'SP',
			'cidade'    => 'Cidade BEN',
			'documento' => '88888888888888'
		]
	);
	
	$pagador = new \Eduardokum\LaravelBoleto\Pessoa(
		[
			'nome'      => 'NOME PAGADOR LTDA',
			'endereco'  => 'AVENIDA ANTNIO',
			'bairro'    => 'VILA PAGADOR',
			'cep'       => '55555555',
			'uf'        => 'SP',
			'cidade'    => 'CIDADE PAGADOR',
			'documento' => '66666666666666'
		]
	);
	
	
	$boletos_arr[] = [
		'logo'                   => '',
		'dataVencimento'         => new \Carbon\Carbon('2017-09-25'),
		'valor'                  => 200.00,
		'multa'                  => 2.00,
		'juros'                  => 3.00,
		'juros_apos'             => '2017-09-25',
		'diasProtesto' 			 => '',
		'codigoCliente'          => 4444444, 
		'range'                  => '',
		'convenio'               => '',
		'variacaoCarteira'       => '',
		'numero'                 => 1,
		'numeroDocumento'        => 1,
		'pagador'                => $pagador,
		'beneficiario'           => $beneficiario,
		'diasBaixaAutomatica'    => 15,
		'carteira'               => 101,
		'agencia'                => 1111,
		'agenciaDv'              => '',
		'conta'                  => 22222222,
		'contaDv'                => 3,
		'descricaoDemonstrativo' => array(),
		'instrucoes'             => array(),
		'aceite'                 => 'S',
		'especieDoc'             => 'DS',
		'ios'                    => ''
	];
	
	$boleto_obj = new Eduardokum\LaravelBoleto\Boleto\Banco\Santander($boletos_arr[0]);
	
	$pdf = new Eduardokum\LaravelBoleto\Boleto\Render\Pdf();
	$pdf->addBoleto($boleto_obj);
	$pdf_inline = $pdf->gerarBoleto($pdf::OUTPUT_STRING);
`

Suspeita o que pode ser?

**Comment by kcirtapsi** [comment]
Vi aqui @eduardokum, e ao gerar a linha digitável ele continua utilizando a conta do cliente, mesmo na branch develop.

No arquivo:
https://github.com/eduardokum/laravel-boleto/blob/develop/src/Boleto/Banco/Santander.php

Na função getCampoLivre() ela retorna:
`return $this->campoLivre = '9' . Util::numberFormatGeral($this->getConta(), 7)
            . Util::numberFormatGeral($this->getNossoNumero(), 13)
            . Util::numberFormatGeral($this->getIos(), 1)
            . Util::numberFormatGeral($this->getCarteira(), 3);`

Mas precisa retornar:
`return $this->campoLivre = '9' . Util::numberFormatGeral($this->getCodigoCliente(), 7)
            . Util::numberFormatGeral($this->getNossoNumero(), 13)
            . Util::numberFormatGeral($this->getIos(), 1)
            . Util::numberFormatGeral($this->getCarteira(), 3);`
E isso afetará a linha digitavel e código de barras pelo que vi.

Fiz essa alteração segundo o manual oferecido pelo santander de janeiro v31 pagina 12 e 13.

é isso mesmo?

**Comment by eduardokum** [comment]
Acredito que seja, fiz a atualização, atualiza seu develop ai e veja se resolve o problema

**Comment by kcirtapsi** [comment]
Não sei se fiz errado, eu criei um arquivo composer.json como segue abaixo:

**Comment by eduardokum** [comment]
Fiz uns commits no develop, veja se resolveu seu problema por favor

**Comment by kcirtapsi** [comment]
Sobre o boleto está ok @eduardokum muito obrigado

**Comment by eduardokum** [comment]
Disponha.

Qualquer problema pode perguntar.

**Comment by efelipeyahoooo** [comment]
qual campo devo utilizar para que o valor da multa já apareça calculado para o caixa?
exite um campo:
valormulta => $cvalormulta

obrigado e parabéns pelo proejeto.
