### ISSUE TITLE
Carteira Boleto Santader

### ISSUE THREAD

**Issue by diegomengarda** [eduardokum/laravel-boleto#209]
Boa noite,

estou precisando adicionar mais tipo de carteira no boleto e me deparei com essa parte do código.
![image](https://user-images.githubusercontent.com/8545323/30892802-febc260e-a310-11e7-92ce-a0ec477fb4ec.png)

Preciso adicionar a carteira 105 que será RCR (Cobrança Simples com Registro)
Qual seria o valor ideal para adicionar no switch case?

PS.: Já adicionei nas outras partes da classe o registro 105.
![image](https://user-images.githubusercontent.com/8545323/30892845-3a2de0d8-a311-11e7-80f8-f7da133f3dc3.png)
![image](https://user-images.githubusercontent.com/8545323/30892851-420e7c04-a311-11e7-955b-5915f4bbccb4.png)

Obrigado.

**Comment by eduardokum** [comment]
Bom dia, teria que ver no manual da remessa qual é o valor relativo a ela, se é com registro tem que ter lá

**Comment by eduardokum** [comment]
Essa carteira 105 não estou achando em nenhum manual, nem do e boleto nem no de Remessa

As única carteira disponível é a 101, nem a 102 e a 201 estão mais.

![captura de tela 2017-09-30 as 10 23 40](https://user-images.githubusercontent.com/2566340/31046131-b4146dda-a5c9-11e7-9577-171173654b03.png)
![captura de tela 2017-09-30 as 10 24 44](https://user-images.githubusercontent.com/2566340/31046130-b414604c-a5c9-11e7-89c2-c50afdc13ddb.png)

**Comment by diegomengarda** [comment]
Esse código foi uma confusão que o atendente do santander fez, na verdade a cobrança é 5 (Rápida com Registro).
Valeu pela ajuda.
