### ISSUE TITLE
LAYOUT BOLETO BANCO DO BRASIL

### ISSUE THREAD

**Issue by marcosformagini** [eduardokum/laravel-boleto#21]
Bom dia.
Recentemente recebemos um pedido de adaptação do layout para o boleto do Banco do Brasil. A mudança é no **Modelo de recibo do pagador** e está no ANEXO III deste manual -> [http://www.bb.com.br/docs/pub/emp/empl/dwn/Doc5175Bloqueto.pdf](http://www.bb.com.br/docs/pub/emp/empl/dwn/Doc5175Bloqueto.pdf).

Gostaria de saber se há alguma previsão para fazer tal alteração, ou se ela não se faz necessária?

Desde já, obrigado!

**Comment by eduardokum** [comment]
Não estava sabendo dessa mudança, precisaria corrigir isso somente para o BB. Se você já fez essa alteração envie um PR que eu dou merge.
