### ISSUE TITLE
Código de Ocorrência Remessa Caixa

### ISSUE THREAD

**Issue by jsalmeida1101** [eduardokum/laravel-boleto#211]
Boa tarde! Estou desenvolvendo a geração de remessa de arquivos da caixa, mas as opções de status gerados pela ferramenta são somente 3:  01, 02 e 05 mas eu preciso de todas as 12 opções. 
Gostaria de saber se há uma possível solução para meu problema.

Obrigado.

**Comment by eduardokum** [comment]
Bom dia, hoje a classe não oferece essa opção.
