### ISSUE TITLE
Erro no cadastro do nossonumero no santander

### ISSUE THREAD

**Issue by jocajunior77** [eduardokum/laravel-boleto#213]
Caro Eduardo,
na classe Eduardokum\LaravelBoleto\Boleto\Banco\Santander o metodo gerarNossoNumero 
deveria ser modificado de 

protected function gerarNossoNumero()  {
        $numero_boleto = $this->getNumero();
        return Util::numberFormatGeral($numero_boleto, 12)
            . CalculoDV::santanderNossoNumero($numero_boleto);
 }

para 

protected function gerarNossoNumero()  {
        $numero_boleto = $this->getNumero();
        return Util::numberFormatGeral($numero_boleto, 7)
            . CalculoDV::santanderNossoNumero($numero_boleto);
}

pois ao gerar com 12 numeros + o dv o nossonumero fica com 13 caracteres
e na classe Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Santander no metodo addBoleto na linha 

$this->add(63, 70, Util::numberFormatGeral($boleto->getNossoNumero(), 8));

ele pega os 8 caracteres de 13 fazendo com que o nosso numero fique errado.

Exemplo::
boleto = 321331
o gerarNossoNumero deixara o nossonumero 0000003213315
e no add ele ficara 00000032 fazendo que o numero do boleto registrado seja errado

[]s
Joca

**Comment by jocajunior77** [comment]
ou alterar a linha 

$this->add(63, 70, Util::numberFormatGeral($boleto->getNossoNumero(), 8));
para 
$this->add(63, 70, Util::numberFormatGeral((int)$boleto->getNossoNumero(), 8));

[]s
Joca

**Comment by jocajunior77** [comment]
vendo o issue  #160 , acredito que a segunda opcao eh mais adequada.

alterar a linha
$this->add(63, 70, Util::numberFormatGeral($boleto->getNossoNumero(), 8));
para
$this->add(63, 70, Util::numberFormatGeral((int)$boleto->getNossoNumero(), 8));

[]s
Joca

**Comment by eduardokum** [comment]
No develop isso ja esta corrigdo, so não foi para o master ainda
