### ISSUE TITLE
Bradesco - Digito do "nosso numero"  inválido.

### ISSUE THREAD

**Issue by rafaelggads** [eduardokum/laravel-boleto#214]
Boa noite,
Assistência do Banco Bradesco me informou que o digito do nosso numero não é valido. Bom achei muito estranho porque já utilizo bastante tempo e nunca tive esse problema. Porem recentemente atualizei a biblioteca e depois de carregar uma remessa o gerente informou o meu cliente. Então realizei o calculo conforme a documentação enviado pelo banco é realmente não é valido. 
Ex: 
nosso numero: 1094179
nosso numero com digito gerado: 00001094179-8
nosso numero com digito correto segundo o calculo: 00001094179-5

Analisado a função  na classe "CalculoDV.php"
public static function bradescoNossoNumero($carteira, $nossoNumero) {
        return Util::modulo11($carteira . $nossoNumero, 2, 7, 0, 'P');
}
   Verifiquei que o valor do nosso numero enviado para o calculo é "091094179" porem o correto é "0900001094179" segundo é informado na documentação.Para o cálculo do digito, o nosso numero contém 11 dígitos mais o numero da carteira.

Para resolver isso acredito que na classe "Bradesco.php" a função "gerarNossoNumero" deve ser alterado para:

   protected function gerarNossoNumero()
    {
        $nosso_numero = Util::numberFormatGeral($this->getNumero(), 11);
        return $nosso_numero
            . CalculoDV::bradescoNossoNumero($this->getCarteira(), $nosso_numero);
    }

pois atualmente se encontra assim :

 protected function gerarNossoNumero() {
        return Util::numberFormatGeral($this->getNumero(), 11)
            . CalculoDV::bradescoNossoNumero($this->getCarteira(), $this->getNumero());
}

Com a mudança o calculo voltou a ficar certo, houve alguma alteração nisso ou algo que afetou na geração do digito ?

**Comment by eduardokum** [comment]
Entendi, e alterando isso o digito ficou correto?

Ocorreu isso pois fiz uma refatoração, a classe de calculo ficou separada... vou arrumar isso, so antes me confirma se ficou certo o digito com a mudança

**Comment by rafaelggads** [comment]
Sim ficou certo o digito!

**Comment by eduardokum** [comment]
blza, ja mandei no develop https://github.com/eduardokum/laravel-boleto/commit/c1cf1d9bf34e55588165f0e64221d457d7525db5

Depois vou criar uma tag pra mandar pro master
