### ISSUE TITLE
Remessa Bancoob CNAB 240 - Fix Juros ao Mês

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#216]
O valor de juros ao mês está sendo calculado utilizar o valor ao dia ($boleto->getMoraDia()), porém ao processar esse valor no Bancoob, o banco está convertendo em porcentagem, ficando dessa forma incorreto o cálculo de juros.

Irei alterar para que seja informado na remessa o valor percentual ao mês. Dessa forma basta utilizar a função $boleto->getJuros(), que irá preencher com a taxa de juros mensal no campo 127-141 da remessa.

**Comment by guicouto** [comment]
Enviado PR.

**Comment by eduardokum** [comment]
Blza fiz o merge ja. Vlw
