### ISSUE TITLE
BANRISUL - Erro no NC do Nosso Número

### ISSUE THREAD

**Issue by marcosformagini** [eduardokum/laravel-boleto#219]
Para o número Nosso Número **270** o NC deveria ser **06**, mas está saindo **05**. Ao que tudo indica o problema está no cálculo do módulo 11 (_no arredondamento do resto do cálculo_ ). Já fiz algumas modificações, porém não obtive o resultado esperado. Desde já agradeço.

**Comment by eduardokum** [comment]
Bom dia,
Onde você viu que o DV deveria ser 06? conferi os cálculos pelo manual e me parece tudo correto

**Comment by marcosformagini** [comment]
Isso foi me repassado pelo suporte do banco! Eles informaram que deveria ser 06 e o que está saindo é 05. Fiz o cálculo manual e deu 06. Consegui isso arredondando pra cima o resto do módulo 11.

**Comment by eduardokum** [comment]
Então a melhor forma é você debugar a geração do DV e ir comparando com o calculo que você fez manual ver onde o código esta se perdendo...

**Comment by marcosformagini** [comment]
Faltava fazer algumas verificações no Duplo Digito! Agr está OK!
