### ISSUE TITLE
Boleto com desconto

### ISSUE THREAD

**Issue by josericardomcastro** [eduardokum/laravel-boleto#22]
Olá como faço pra inserir desconto nos boletos?

Nos boletos registrados, o valor do desconto é gerado no arquivo de remessa?

**Comment by eduardokum** [comment]
no boleto você usa desconto_abatimento para destacar do lado >>>  e adicionar na instrucoes a  linha do desconto, descreva la como funciona seu desconto. A remessa vai buscar esse campo desconto_abatimento, ai para ver se a data de até quando ou a partir de quando esse desconto vai valer, precisa olhar no manual do banco especifico

**Comment by fhferreira** [comment]
@eduardokum primeiramente parabéns pelo pacote, excepcional.

Informando no array de atributos: 
```
'descontosAbatimentos' => 10.00
```

Só conseguir imprimir isso no boleto  com essas alterações:

https://github.com/eduardokum/laravel-boleto/blob/master/src/Boleto/Render/Pdf.php#L157
```
$this->Cell(30, $this->cell, $this->_(''), 'LR');
```
change to:
```
 $this->Cell(30, $this->cell, $this->_(Util::nReal($this->boleto[$i]->getDescontosAbatimentos())), 'LR', 0, 'R');

```

https://github.com/eduardokum/laravel-boleto/blob/master/src/Boleto/Render/Pdf.php#L277
```
$this->Cell(120, $this->cell, $this->_(''), 'LR');
```
change to:
```
$this->Cell(50, $this->cell, $this->_(Util::nReal($this->boleto[$i]->getDescontosAbatimentos())), 'R', 1, 'R');
```

**Comment by eduardokum** [comment]
Esses campos no boleto tem que vir em branco mesmo, isso é para o caixa preencher, o desconto só vai na remessa e nas intruções.

e esse método *getDescontosAbatimentos* não existe mais usar agora o *setDesconto* e *setDataDesconto*

**Comment by fhferreira** [comment]
@eduardokum obrigado pela explicação. Entendi, colocarei somente na remessa e nas mensagens de instruções.
