### ISSUE TITLE
Validação dos campos obrigatórios deve verificar pelo tipo também

### ISSUE THREAD

**Issue by juelisjr** [eduardokum/laravel-boleto#223]
No método `isValid()` do `AbstractBoleto` deve ser usado o operador de comparação por tipagem também. Me ocorreu um caso onde o `getContaDv()` me retorna 0 e o sistema acaba invalidando dizendo que o campo está em branco.

**Comment by eduardokum** [comment]
Estranho a validação é "" 

```php
if (call_user_func([$this, 'get' . ucwords($campo)]) == '') {
    $messages .= "Campo $campo está em branco";
    return false;
}
```

**Comment by juelisjr** [comment]
Exatamente! `0 == ''` é verdadeiro. No caso ele estava retornando um inteiro.

**Comment by eduardokum** [comment]
Tem razão, já fiz a alteração

e2ec23af0333ac5f41ddf9b9ab242d9c5103f549

Obrigado

**Comment by juelisjr** [comment]
Nóis
