### ISSUE TITLE
CÁLCULO MÓDULO 11

### ISSUE THREAD

**Issue by marcosformagini** [eduardokum/laravel-boleto#232]
Bom dia!

Tenho uma dúvida. No módulo 11 o RESTO deveria ser subtraído por 11 para se obter o resultado. Não consigo identificar no projeto aonde está sendo feito isso.

```php
   public static function modulo11($n, $factor = 2, $base = 9, $x10 = 0, $resto10 = 0)
    {
        $sum = 0;
        for ($i = mb_strlen($n); $i > 0; $i--) {
            $sum += mb_substr($n, $i - 1, 1)*$factor;
            if ($factor == $base) {
                $factor = 1;
            }
            $factor++;
        }
        if ($x10 == 0) {
            $sum *= 10;
            $digito = $sum%11;
            if ($digito == 10) {
                $digito = $resto10;
            }
            return $digito;
        }
        return $sum%11;
    }
```

**Comment by eduardokum** [comment]
Não esta sendo feiro isso ai, ai ele retorna somente o resto da divisão por 11, a subtração quando necessária é feita na própria classe que necessita.

**Comment by marcosformagini** [comment]
Entendi. É que temos um problema no Banrisul e só agr que fui olhar o código q vi isso. rs
Vlew cara!

**Comment by eduardokum** [comment]
Manda aquele PR seu no branch develop, ou então arruma isso no banrisul, manda o PR normal mesmo que eu tento puxar ele pro develop.

Abraço
