### ISSUE TITLE
Homologação banco Sicredi

### ISSUE THREAD

**Issue by fabritha** [eduardokum/laravel-boleto#233]
Bom dia, para fazer alterações de fonte de código de barras, como posso proceder? Estou fazendo a homologação do boleto Sicredi e isso foi solicitado pelos mesmos. Preciso fazer isso de uma maneira que não gere problemas para as pessoas que já utilizam a biblioteca, portanto estou na dúvida de como proceder neste caso. Foi solicitada também a alteração da logo, mas esse já encontrei o arquivo que deve ser substituído e em breve farei o pull request.

Att. Thays.

**Comment by eduardokum** [comment]
Olá, não sei bem se existe isso, trocar a font, são barras criadas com Rect pelo pdf mudar fonte não mudaria em nada as barras...

Qual foi a solicitação exata que te fizeram?

**Comment by fabritha** [comment]
Bom dia, foram enviadas as seguintes solicitações de ajustes:

![email_sicredi](https://user-images.githubusercontent.com/8298846/32950985-72a4973a-cb8f-11e7-94c6-d3932f26b0bb.jpg)

![emailsicredi2](https://user-images.githubusercontent.com/8298846/32951086-ce096218-cb8f-11e7-993a-dffda3116d4a.jpg)
O email acima foi resolvido apenas alterando o valor da variável de "localPagamento" na classe Sicredi.

Att. Thays.

**Comment by eduardokum** [comment]
Hoje ja esta assim, seu repositório deve estar desatualizado. quanto ao codigo de barras, esse é o modelo mesmo Interleaved 2of5

**Comment by fabritha** [comment]
Okay, vou atualizar meu repositório e irei desconsiderar a observação dele em relação a fonte.

Obrigada.

**Comment by eduardokum** [comment]
Se der algum problema pra validar em pdf tenta enviar a versão em html, as vezes passa, nunca vi ngm com problema no codigo de barras.

Qualquer coisa comente aqui nessa issue, mais vou fechar ela

Abraço
