### ISSUE TITLE
Pacotes não instalam via composer

### ISSUE THREAD

**Issue by gwathsule** [eduardokum/laravel-boleto#235]
![image](https://user-images.githubusercontent.com/8078156/33071486-d10e8b3a-cea2-11e7-9d49-681f2cb027f0.png)

Olá amigo, desculpe se está passando algo despercebido, estou tentando usar o pacote em um projeto laravel...
O composer atualiza meu arquivo composer.json mas suas classes não se encontram na pasta vendor...

**Comment by eduardokum** [comment]
Tem que ver se seu composer não esta com algum problema, tenta reinstalar ele, pois quem baixa o pacote é o composer, não tem nada que de pra fazer no pacote para controlar algo na instalação
