### ISSUE TITLE
Problema ao apresentar o código de barras na versão 0.7.1

### ISSUE THREAD

**Issue by strazburger** [eduardokum/laravel-boleto#239]
Olá,
Atualizando a versão do componente eduardokum/laravel-boleto 0.7, para a versão 0.7.1, na geração do código de barras do boleto em PDF, está ficando inultilizado perante ao banco Banrisul, não está sendo considerado boleto válido. Foi percebido que está utlizando a biblioteca "setasign/fpdf" e a anterior utilizava a "itbz/fpdf".

Ao gerar o PDF e fazer a leitura do código de barras, consta o seguinte:
0.7.1 = 0041937369000055150321094000045500124512140210
0.7.0 = 04192109430000455001824512140112973690000551503

Os dados acima apresentados, são resultados da geração do mesmo boleto, apenas gerado em versões diferentes do componente eduardokum/laravel-boleto.

Obs: 
1) a apresentação da linha digitável e do código de barras é a mesma nas duas versões, o problema ocorre apenas quando renderiza em PDF, na apresentação do código de barras.
2) Note que o valor do boleto, mudou de posição na versão 0.7.1. Na versão 0.7 ele é apresentado no últimos caracteres. Já na 0.7.1 ele fica representado a partir da posição 10.
3) os dados constantes 041, está representado como 041 na versão 0.7 e 0041 na versão 0.7.1

![img_20171124_163743927](https://user-images.githubusercontent.com/3814090/33221578-ad0d556c-d137-11e7-8ce9-0168a9bdb7a8.jpg)

**Comment by eduardokum** [comment]
Estou fazendo uns testes o teste que eu gerei aqui ele não colocou 0041 e sim 041, estou usando o develop, você consegue testar com ele?
ou me mandar os dados que você esta usando pra gerar o boleto, e qual seria a linha digital e o codigo de barras que deveria gerar?

Obrigado

**Comment by strazburger** [comment]
O que foi feito: em outubro, baixamos o pacote via composer. Fizemos vários testes, enviamos ao Banrisul para homologar e tudo certo.

Quando rodamos o composer novamente, agora em novembro, ele atualizou e dois dias após descobrimos o problema, ao chegar relatos que os códigos não estavam sendo lidos corretamente.

Voltamos a versão antiga e resolveu.

Alguns dados:
$dadosPagador = array("nome" => "Aluno",
                      "endereco" => "Endereço",
                      "bairro" => "Bairro",
                      "cep" => "CEP",
                      "uf" => "RS",
                      "cidade" => "Cidade",
                      "documento" => "documento");
//
$dadosBoleto = array( "dataVencimento" => new \Carbon\Carbon($registro["datavencimento"]),
                      "valor" => "207",
                      "numero" => 0117682803,
                      "numeroDocumento" => "0123456",
                      "pagador" => $dadosPagador);

**Comment by eduardokum** [comment]
Boa tarde, fiz alguns testes mais não consegui identificar o problema.

Pode ser que seja talvez o tamanho da conta, faltando algum zero, ou algo que esteja passando despercebido mais me parece que está iguais os 2 boletos

[banrisul_0_7_1.pdf](https://github.com/eduardokum/laravel-boleto/files/1511324/banrisul_0_7_1.pdf)
[banrisul_0_7.pdf](https://github.com/eduardokum/laravel-boleto/files/1511325/banrisul_0_7.pdf)
