### ISSUE TITLE
Sacador/Avalista

### ISSUE THREAD

**Issue by didosilva** [eduardokum/laravel-boleto#24]
Não consigo definir o sacador/avalista no Boleto. Gerou o boleto em PDF mas não apareceu as informações do sacador/avalista. Tentei assim:

$sacadorAvalista = new \Eduardokum\LaravelBoleto\Boleto\Pessoa([
    'nome' => 'Cliente Sacador',
    'endereco' => 'Rua um, 123',
    'bairro' => 'Bairro',
    'cep' => '99999-999',
    'uf' => 'UF',
    'cidade' => 'CIDADE',
    'documento' => '999.999.999-99',
]);

$boleto = new Eduardokum\LaravelBoleto\Boleto\Banco\Bradesco([
    'logo' => realpath(__DIR__ . '/images/') . DIRECTORY_SEPARATOR . '237.png',
    'dataVencimento' => new \Carbon\Carbon(),
    'valor' => 100,
    'multa' => false,
    'juros' => false,
    'numero' => 1,
    'numeroDocumento' => 1,
    'pagador' => $pagador,
    'beneficiario' => $beneficiario,
    'sacadorAvalista' => $sacadorAvalista,
    'carteira' => '09',
    'agencia' => 1111,
    'conta' => 9999999,
    'descricaoDemonstrativo' => ['demonstrativo 1', 'demonstrativo 2', 'demonstrativo 3'],
    'instrucoes' =>  ['instrucao 1', 'instrucao 2', 'instrucao 3'],
    'aceite' => 'S',
    'especieDoc' => 'DM',
]);

**Comment by eduardokum** [comment]
Sacador avalista é somente uma string não um objeto Pessoa

**Comment by eduardokum** [comment]
Adicionei o Sacador avalista nos boletos

3baf5541914a6f73cd17e0ca14cc0deb2e1af86b
