### ISSUE TITLE
Layout CNAB 240 Febraban

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#241]
Pessoal,
eu estava conversando com o gerente do meu banco (Sicoob), e ele me disse que, o Sicoob vai deixar de utilizar o layout "próprio" do CNAB 240 e vai se adequar exatamente com as normas da Febraban.

Alguém sabe se mais algum banco vai acontecer isso? Mais alguém consegue confirmar essa informação em outra agência Sicoob?

Caso essa informação seja realmente válida, podemos criar um layout de remessa padrão, que não se normaliza com nenhum banco, mas sim com a Febraban. Dessa forma, se mais algum banco se aderir a essa modalidade (o que eu acho que seria o ideal, pois bastaria desenvolver uma única classe rsrs...),   já temos essa classe pronta para ser utilizada.

Abraços,
Guilherme Couto

**Comment by eduardokum** [comment]
Boa noite, eu fiz as quase todas as remessas em 240 pq a classe não tinha e só alguns bancos que tem diferenças do layout padrão do febraban mais não são muitas, se acontecer a mudança mesmo acredito que não seja difícil a alteração, pq quando muda do padrão é bem pouco nos bancos que mudam

Em 28 de nov de 2017 20:20 -0200, Guilherme da Costa Couto <notifications@github.com> escreveu:

**Comment by eduardokum** [comment]
O problema de fazer uma só é que mesmo seguindo o padrão não é padrão rsrs por exemplo da posição 10 a 30 é ag e conta, mais tem banco que usa da 10 a 20 zeros e da 20 a 30 código do cedente, mais ou menos isso saca ? Não é bem um padrão, mais valor vencimento varias outras informações ficam no mesmo lugar em todas, mais cada banco tem uma forma de identificar o cliente

Em 28 de nov de 2017 20:20 -0200, Guilherme da Costa Couto <notifications@github.com> escreveu:

**Comment by guicouto** [comment]
Boa noite, então, eu até dei uma olhada mesmo e realmente as classes ficaram muito parecidas. Cheguei a comparar também algumas documentações e de fato as informações, modificam muito pouco. Vou tentar confirmar essa informação. Se puder deixar essa issue aberta por mais um pequeno período de tempo, pois alguém pode ser identificar na mesma situação.

**Comment by guicouto** [comment]
Até porque hoje me aconteceu algo estranho, que eu ainda não tive tempo de depurar. No caso do Bancoob, eles possuem dois sistema que conseguem fazer a importação da remessa. Em um deles (o mais antigo), a remessa no formato CNAB 240 que já está implementada aqui, importa perfeitamente, sem nenhum ressalva. Pelo contrário, no novo sistema, ele me acusa erros no HEADER e TRAILER do arquivo.

**Comment by eduardokum** [comment]
é então o problema é achar manuais atualizados, tem banco que é dificil de achar, então se tiver manual mais atualizado do que os que estão na pasta manuais, por favor mande eles por PR

**Comment by guicouto** [comment]
Bom, deixei essa issue aberta por vários dias, acho que ninguém passou pelo mesmo problema. Irei fechá-la. Desde já agradeço a atenção.
