### ISSUE TITLE
Retornos

### ISSUE THREAD

**Issue by brunoneve** [eduardokum/laravel-boleto#242]
Arquivos retornos com caracteres especiais estão falhando nas validações do arquivo.

Classe Util.php

```
    public static function isHeaderRetorno($header)
    {
        if (!self::isCnab240($header) && !self::isCnab400($header)) {
            return false;
        }
        if (self::isCnab400($header) && mb_substr($header, 0, 9) != '02RETORNO') {
            return false;
        }
        if (self::isCnab240($header) && mb_substr($header, 142, 1) != '2') {
            return false;
        }
        return true;
    }
```

Basta add  em mb_substr(Encoding::toUTF8($header), 142, 1)

Se quiser mando PR.

**Comment by eduardokum** [comment]
Em teoria o mb_substr ja deveria tratar o utf8.

Isso `mb_substr($header, 142, 1)` retorna o que esta em qual posição?

**Comment by brunoneve** [comment]
No meu caso não retorna nada.

**Comment by eduardokum** [comment]
Acredito que ja resolvi esse caso, estou convertendo tudo pra utf-8 agora, veja se resolveu pra você.

Abraço
