### ISSUE TITLE
Sicoob

### ISSUE THREAD

**Issue by brunoneve** [eduardokum/laravel-boleto#243]
Bom dia,

Arquivo de Remessa

Estou implementando sistema com sicoob e notei algumas divergências com o layout que o banco passou.

Espécia de Título: mesmo colocando do tipo DM a biblioteca está gerando com código 01 que de acordo o layout do banco 01 = CH Cheque.

Também quando informamos o numeroDocumento que é de controle nosso, ele está criando igual ao nossoNumero e ignorando o que passamos na tag numeroDocumento ao criar o objeto.

Por enquanto foram essas, estou verificando e caso haja mais inconsistências aviso aqui

**Comment by eduardokum** [comment]
Você pode mandar PR desses manuais? Tem banco que não disponibiliza somente pra correntista. Aí já faço as atualizações . Obrigado

**Comment by girlanlira** [comment]
Boa Tarde Eduardo, eu tenho esse manual veja se lhe ajuda : 
[FORMULARIO & LAYOUT - BANCOOB REGISTRADO.zip](https://github.com/eduardokum/laravel-boleto/files/1584351/FORMULARIO.LAYOUT.-.BANCOOB.REGISTRADO.zip)

**Comment by eduardokum** [comment]
o problema é que no 400 posiçoes 01 é DM e em 240 é CH


## 240
![image](https://user-images.githubusercontent.com/2566340/34578576-9f8f1100-f16c-11e7-9b11-85896c1b0db9.png)

## 400
![image](https://user-images.githubusercontent.com/2566340/34578588-a9846dea-f16c-11e7-9780-188d44e214a8.png)


vou ter que fazer uma tabela de conversão do 400 pro 240 que o boleto é baseado no 240.

**Comment by eduardokum** [comment]
Agora a espécia vai ser convertida da remessa de 400 posições para o código respectivo nas 240 posições

1eda1a8eee06f5c7e0b30fcc55ca6ae415611958

**Comment by karlasantos** [comment]
@eduardokum as espécies do documento mapeadas nesse boleto não são do CNAB400? É nesse atributo que eles são mapeados?
`    protected $especiesCodigo = [
        'DM' => '01',
        'NP' => '02',
        'DS' => '12',
    ];`
Na remessa de CNAB240 está ficando 01 no segmento P, posso estar fazendo algo errado na geração?
