### ISSUE TITLE
Cnab240 gerando com 241 Posições

### ISSUE THREAD

**Issue by carlao14** [eduardokum/laravel-boleto#245]
Aoba, estou usando a biblioteca e ao gerar a remessa dos Bancos Sicoob e BB o arquivo veio com 241 posições. Possui em espaço em branco ao final, sabe me explicar o porque ?
Desde já muito obrigado !

**Comment by juelisjr** [comment]
Tive um problema parecido na geração da remessa do Banco do Brasil. No meu caso havia alguns caracteres com encode errado no banco e, na hora de gerar o arquivo, a aplicação acabava não conseguindo contar esse caracteres (fazendo com que gerasse uma posição a mais).

**Comment by eduardokum** [comment]
Acredito que pode ser isso mesmo carácteres esses unicodes às vezes conta como 2 você está usando qual versão do projeto?

**Comment by eduardokum** [comment]
O problema persiste?

**Comment by carlao14** [comment]
Desculpa a demora pra responder, o problema era no charset, estava sendo gerado em utf8. Trocando pra ANSI resolveu o problema . Muito obrigado
