### ISSUE TITLE
Validação Remessas Bradesco

### ISSUE THREAD

**Issue by projetosvillevox** [eduardokum/laravel-boleto#246]
Olá, boa tarde!

Primeiramente parabéns pelo projeto. O uso da lib é bem simples e direto, estamos implementando a mesma em um sistema nosso para gestão de locações.

Após tentar enviar uma remessa (CNAB 400) para o Bradesco, recebemos a informação de que algumas posições estavam incorretas no arquivo.

Verificamos e encontramos a seguinte situação: 

No header da remessa, logo na posição 27 em diante, fica o código da empresa (acessório escritural)
No detalhamento dos boletos, na posição 21 em diante ficam os dados da carteira, agência, dígito, etc.

Observando a classe que gera o arquivo (\Remessa\Cnab400\Banco\Bradesco) notamos que em ambas as posições, é chamada a função "getCodigoCliente()". Porém, como as informações são diferentes, como devemos proceder?

Tentamos usar a função "setCodigoCliente" e inserir o acessório escritural, o que corrige o header, mas deixa o detalhamento dos boletos incorreto. Se não usarmos esta função, o header fica incorreto e o detalhamento fica correto.

Obs.: A chamada da função fica na linha 142 e 173 da classe de remessa do bradesco.

Grato pela excelente lib e disponibilidade nos updates!

**Comment by eduardokum** [comment]
Opa obrigado, amanhã vou dar uma olhada o que seria esse acessório escritural? Não é o código do cliente padrão gerado pela classe? Seria um número diferente? É que nunca comum caso desse, não me lembro de ter visto isso já no manual, se puder me informar isso já ajuda a identificar o problema

Em 11 de dez de 2017 16:00 -0200, Projetos villevox <notifications@github.com> escreveu:

**Comment by juelisjr** [comment]
Boa tarde.

Uma outra questão sobre as remessas do Bradesco é que, na classe de Boleto são listadas as seguintes carterias: `$carteiras = ['09', '06', '21', '22', '25', '26'];`, porém, ao fazer a geração do arquivo de remessa, as carteiras disponíveis são: `$carteiras = ['09', '28'];`.

Meu cliente está tentando trabalhar com a 26 e, ao gerar a remessa, dá erro dizendo que a carteira não está disponível.

**Comment by eduardokum** [comment]
O código do cedente agora so vai ser gerando caso não seja informado na instancia da classe, acredito que isso resolva o caso quando o código for diferente do padrão
