### ISSUE TITLE
Bradesco - cód. de carteira errado ao gerar remessa

### ISSUE THREAD

**Issue by juelisjr** [eduardokum/laravel-boleto#249]
Ao gerar arquivo de remessa do Bradesco, uma das carteiras disponíveis está com o código errado. Está como 28 mas deve ser 26 (assim como na listagem de carteiras disponíveis na classe de boleto do Bradesco).

**Comment by eduardokum** [comment]
Entendi, amanhã dou uma olhada nisso. Vlw
