### ISSUE TITLE
Dígito verificador boleto Banrisul divergente do manual

### ISSUE THREAD

**Issue by devguar** [eduardokum/laravel-boleto#250]
Boa noite!
Estou implementando o boleto do Banrisul em um cliente e os dígitos verificadores não estão sendo aceitos em algumas situações bem específicas. Explico:

O "nosso número" do Banrisul é composto por 2 verificadores:
1. Nosso número (8 posições)
2. Aplica o modulo 10 e concatena no nosso numero
3. Aplica o módulo 11 nos 9 caracteres anteriores

Esse processo está sendo feito na src/CalculoDV.php no método banrisulDuploDigito.

Após calcular o módulo 10 tem um teste se o resto é igual a 9, se for, vai substituir por 0:
```
    public static function banrisulDuploDigito($campo)
    {
         $dv1 = Util::modulo10($campo);
            if ($dv1==9) {
                $dv1 = 0;
            }
...
```

Os boletos em que o calculo gerou resto 9 não foram homologados pelo banco. Olhando o manual aqui:
http://www.banrisul.com.br/BOB/data/CobrancaEletronicaBanrisul_layout_pdr_Febraban400_vrs12082013_ed02.pdf?cache=5 página 32 tem a seguinte instrução:

> Primeiro DV = 10 - RESTO.
> --quando o somatório for menor que 10, o resto da divisão por 10 será o próprio somatório.
> --quando o resto for 0, o primeiro DV é igual a 0.
> 

Então acredito que o teste deveria ser **maior** que 9:
```
    public static function banrisulDuploDigito($campo)
    {
         $dv1 = Util::modulo10($campo);
            if ($dv1>9) {
                $dv1 = 0;
            }
...
```

Como é algo bastante sensível gostaria da opinião de outros users antes de mandar PR com a alteração.
Valeeu!

**Comment by devguar** [comment]
Na real homologando aqui a função correta ficou dessa forma:
`    public static function banrisulDuploDigito($campo)
    {
		$dv1 = Util::modulo10($campo);
		$dv2 = Util::modulo11($campo . $dv1, 2, 7, 1, 10);
		
		if ($dv2 == 1){
			if ($dv1 == 9){
				$dv1 = 0;
			}else{
				$dv1++;
			}
			
			$dv2 = Util::modulo11($campo . $dv1, 2, 7, 0, 10);				
		}else{
			$dv2 = (11 - $dv2);
		}
			
		return $dv1 . $dv2;
    }`

Em anexo o documento que me foi disponibilizado pelo próprio banco.

[CÁLCULO NC Nosso Número.docx](https://github.com/eduardokum/laravel-boleto/files/1583109/CALCULO.NC.Nosso.Numero.docx)

**Comment by eduardokum** [comment]
Esta funcioando assim? manda PR em develop por favor com essa mudança então que eu gero uma nova versão.

Grato

**Comment by devguar** [comment]
Funcionando sim, homologado no banco. Já enviei a PR.
Obrigado
