### ISSUE TITLE
Nosso Número Proprio

### ISSUE THREAD

**Issue by jjalvesneto** [eduardokum/laravel-boleto#251]
Olá como fazer em uma situação que já tenho o nosso número gerado devido uma migração de sistemas ? estive dando uma olhada nesse caso (  https://github.com/eduardokum/laravel-boleto/pull/60 ), mas não achei nada ainda na master.

**Comment by eduardokum** [comment]
Boa tarde,

A classe que gera o nosso numero, baseado no numero, mais depende de cada banco. cada um pode usar informação diferente, mais se for as mesmas informações o NN que a classe gerar tem que ser o mesmo que você tem
