### ISSUE TITLE
Boleto Sicredi - Código de barras e Linha digitável

### ISSUE THREAD

**Issue by wafgomes** [eduardokum/laravel-boleto#252]
Alguém pode confirmar a homologação do boleto no banco Sicredi utilizando os arquivos do último repositório?

Estou com erro no código de barras e linha digitável.

Apesar de constar no manual que o código de barras utiliza o número do posto na posição 35 – 36, no boleto gerado pelo site da Sicredi a posição 35 inicia com o código do beneficiário, **sem o número do posto**.

**Comment by eduardokum** [comment]
Não sei amigo, não tenho com testar, o sicredi disponibiliza uma testador de linha digital na área logada se não me engano. Veja se consegue testar por la

**Comment by eduardokum** [comment]
Fiz alguns testes agora, e estão validando normal em 400 e 240 posições.
