### ISSUE TITLE
Erro arquivo de remessa Bradesco

### ISSUE THREAD

**Issue by edolfuchs** [eduardokum/laravel-boleto#254]
Bom dia.

Encontrei um possível erro no arquivo de remessa. O número da agencia/conta/carteira está em branco no arquivo.

Percebi que o método abaixo pode estar errado:

Posição 21 a 37
```
public function getCodigoCliente()
    {
        if (empty($this->codigoCliente)) {
            $this->codigoCliente = Util::formatCnab('9', $this->getCarteiraNumero(), 4) .
            Util::formatCnab('9', $this->getAgencia(), 5) .
            Util::formatCnab('9', $this->getConta(), 7) .
            Util::formatCnab('9', $this->getContaDv() ?: CalculoDV::bradescoContaCorrente($this->getConta()), 1);
        }
        return $this->codigoCliente;
    }

Classe : Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bradesco
```

Pelo que entendi se o codigoCliente estiver vazio ele preenche os dados da conta e se estiver preenchido não mostra os dados da conta?

**Comment by eduardokum** [comment]
Isso porém ele pega essas informações da instancia da remessa e não do boleto.

**Comment by eduardokum** [comment]
Porque o código do cedente é padrão, é a junção dessas variaveis so em alguns casos que são diferente, caso a sua seja diferente só informar na instancia da remessa, se não a classe gera automaticamente
