### ISSUE TITLE
Problema ao testar exemplos

### ISSUE THREAD

**Issue by duard** [eduardokum/laravel-boleto#255]
Olá,
quando tento rodar um dos exemplos fornecidos no projeto acaba acontecendo este problema 

`Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\boletos\vendor\eduardokum\laravel-boleto\exemplos\autoload.php on line 2`

Quando aumento o tempo de execução, o problema é com a memória
`Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in C:\xampp\htdocs\boletos\vendor\eduardokum\laravel-boleto\exemplos\autoload.php on line 8
`
Alguém save como devo proceder para corrigir isto ?

Obrigado.

**Comment by duard** [comment]
Consegui rodar, o problema era na linha que pega o autoload.php

**Comment by eduardokum** [comment]
Blza. Vlw.
