### ISSUE TITLE
Update composer

### ISSUE THREAD

**Issue by fabritha** [eduardokum/laravel-boleto#257]
Boa tarde, hoje estava testando as informações de retorno de remessa e as mesmas não estavam indo para arquivo, portanto decidi fazer um composer update e não consegui mais ter acesso as informações referentes à biblioteca, houve algum problema com última versão ?

Att. Thays

**Comment by eduardokum** [comment]
Boa tarde, 

Eu tinha apagado umas tags. Não sei se isso afetou alguma coisa no packagist.org.

Subi uma tag nota 0.7.2.

Faça um update no dev-master ou ~0.7 e veja se resolve

**Comment by fabritha** [comment]
![image](https://user-images.githubusercontent.com/8298846/35009782-d35e8ab8-fae7-11e7-957f-35c9f13f12ea.png)

Ainda não obtive exito, tentei com a dev-master e a ~0.7 

:(

**Comment by rafwell** [comment]
Prezados, o packagist esteve fora do ar hoje pela manhã, por volta das 11 horas. Diversos pacotes que uso apresentaram problemas ao rodar um composer update. Após algum tempo eu consegui rodar normalmente. Tente apagar a pasta vendor e rodar um update para recriar.

**Comment by eduardokum** [comment]
faz o seguinte, da um `composer remove eduardokum:laravel-boleto` e depois você paga a pasta `eduardokum/laravel-boleto` dentro da sua pasta vendor e so depois da uma `composer require eduardokum/laravel-boleto`

**Comment by fabritha** [comment]
Funcionou!! Obrigada, só preciso ver agora pois o banco Bradesco solicitou o tipo de carteira 4, irei enviar um pull request com a solicitação ok?

Att. Thays.

**Comment by eduardokum** [comment]
Blza, manda o manual junto, caso não tenha a especificação dessa carteira no manual que hoje esta la na pasta de manuais.

Obrigado
