### ISSUE TITLE
Problema no Render e PageGroups.

### ISSUE THREAD

**Issue by t0ledoj** [eduardokum/laravel-boleto#260]
Bom dia,

Achei esse projeto a algum tempo e achei bem legal a iniciativa, e ontem resolvi testar no sistema que estou fazendo.

Porém tive problemas na renderização de PDF.

Para garantir que o problema não era no meu projeto criei um repositório novo do Laravel 
i.e. '$laravel new foobar', e baixei o projeto pela linha de comando conforme a documentação.

E tive os mesmos erros, que são:

`$boleto->renderPDF();` 
Ao utilizar o método abaixo para renderizar o PDF individual, é disparado o seguinte erro.
Obs.: O mesmo erro ocorre ao tentar renderizar múltiplos, instanciando a classe Pdf, e o método, addBoleto().
![image](https://user-images.githubusercontent.com/9754430/35149106-0d709348-fcfc-11e7-896a-cefd797ce944.png)

---
Ao utilizar o método addBoletos(), segue o código abaixo:
```
$pdf = new Pdf();
$pdf->addBoletos(array($boleto, $boleto, $boleto));
$path = __DIR__.'\arquivos\\'.time();
$pdf->gerarBoleto($pdf::OUTPUT_SAVE, $path);
```
ocorre outro erro relacionado ao $this->PageGroups
![image](https://user-images.githubusercontent.com/9754430/35152885-59929bae-fd0b-11e7-824a-20368da111a1.png)

Infelizmente não tive tempo suficiente para verificar onde isto influência. 
Mas, aparentemente o PageGroups está com valor null.
Comentando as linhas 19,20,21, 
e na linha 82 alterar o if
 `if ($this->NewPageGroup)` 
para: 
`if (!$this->NewPageGroup)` 
tudo parece funcionar normalmente.
_caminho do arquivo: vendor/eduardokum/laravel-boleto/src/Boleto/Render/AbstractPdf.php_

Obs.: A renderização no formato HTML funciona normalmente, com as alterações ou sem. 

Infos do ambiente:
- Windows 10 x64
- XAMPP com PHP 7.2.0
- Laravel 5.5

**Comment by eduardokum** [comment]
deve ser por conta do php 7.2, vou dar uma olhada nisso.

**Comment by eduardokum** [comment]
Desculpe a demora, mais acredito que esteja ok ja

4d5fabfb59ef65d9e419263f173d9f5a8d2b63d4

Obrigado
