### ISSUE TITLE
Erro ao valida arquivo remessa BB modelo 240

### ISSUE THREAD

**Issue by mflm30** [eduardokum/laravel-boleto#261]
Boa noite,

Não estou conseguindo validar o arquivo remessa do BB, ele retorna um erro no segmento P. O campo do erro é o Identificação do Título no Banco(começa na coluna 38 até 57), posições estão incorretas o convênio que testei foi o de 7 dígitos. A solução que encontrei foi no próprio doc do BB 240 "todos os 'nosso número' devem ser alinhados à esquerda com brancos à direita.".

Fiz uma pequena alteração para corrigir esse error, troquei essa linha https://github.com/eduardokum/laravel-boleto/blob/b8cda0fd068b4ec1768a697169d3e978a5d59260/src/Cnab/Remessa/Cnab240/Banco/Bb.php#L187

por 

$this->add(38, 57, str_pad($this->nossoNumero($boleto), 20, " "));

Não sei se é um erro de fato, mas com isso agora eu consigo validar os arquivos remessas BB. 

Links:
https://gmtedi.bb.com.br/validaleiaute/#/validadorleiaute -> validador remessa
http://www.bb.com.br/docs/pub/emp/empl/dwn/CbrVer04BB.pdf -> doc especifica da remessa 240

Obrigado pela atenção e pelo projeto!

**Comment by mflm30** [comment]
Antes esse campo na posição 38 até a 57 do boleto (segP) era "000621223900001111111", pela documentação do Bb não poderia ter esses 0's a direita, Depois ficou "62122391000027970       ", pode completa o campo com 0's ou espaços em brancos a esquerda eu deixei os espaços em brancos. Depois que fiz essa alteração passou na validação.

**Comment by eduardokum** [comment]
Fiz a mudança, acredito que agora funcione, ele vai deixar o 0 pad pra esquerda

032d8eb7803a2fff734a13e7c1d77995274fcccc

**Comment by celsobtu** [comment]
@eduardokum o erro relatado pelo @mflm30 ainda continua, usando a  solução dada por ele funcionou.
obrigado pelo projeto incrível !
