### ISSUE TITLE
Erro com NumberFormatter

### ISSUE THREAD

**Issue by luxu** [eduardokum/laravel-boleto#262]
Está dando erro 
`Class 'NumberFormatter' not found`
num achei solução idéias?

**Comment by enricodvn** [comment]
Qual a sua versão do PHP? 
PHP no ubuntu é meio chato, se estiver nesta distro, tenta dar um ``` sudo apt-get install php7.0-intl ``` , ou ```sudo apt-get install php5-intl``` se estiver usando PHP5
Se estiver no windows tem que habilitar o intl nas extensões do .ini

**Comment by luxu** [comment]
É windows 10 e já está habilitado...

**Comment by eduardokum** [comment]
Tem que ver no php.info se ela aparece, as vezes esta hablitado no cli mais nao no fpm ou apache...

**Comment by luxu** [comment]
Na verdade dá erro no carregamento da DLL qdo habilita no php.ini

**Comment by eduardokum** [comment]
Então, deve ser algum conflito de versão as vezes dll de versão errado do php, tenta instalar ela com pecl

**Comment by luxu** [comment]
Há hospedagem corrigiu pra mim e ficou ok
