### ISSUE TITLE
Remessa Bradesco Cnab400 divergente da documentação do Banco

### ISSUE THREAD

**Issue by wesleysaraujo** [eduardokum/laravel-boleto#263]
Boa tarde @eduardokum, antes de mais nada gostaria de parabenizar pela inciativa e pelo empenho em manter a Biblioteca atualizada e progredindo.

Fui fazer uma homologação de boletos e remessa ontem junto ao Bradesco, e tive problema com com o arquivo remessa, as linhas referente à transação foram invalidade, até falei com o gerente da conta do meu cliente, o acompanhando passo a passo observando os detalhes da documentação pude constatar os erros nas posições que o setor técnico apontou:

**_Linha 2, colunas 022 a 024, Registro tipo 1, carteira inválida.
Linha 2, colunas 025 a 029, Registro tipo 1, Agência do beneficiário zerada.
Linha 2, colunas 037 a 037, dígito da conta-corrente inválido.
Linha 2, colunas 063 a 065, Registro tipo 1, informar zeros ou brancos. Sem dados para débito automático.
Linha 2, colunas 082 a 082, Registro tipo 1, Dígito do nosso número inválido.
Linha 2, colunas 221 a 234, Registro tipo 1, CNPJ do pagador inválido._**

Referente a essas observações realmente pude observar que da posição 022 a 037 a biblioteca preenche com zeros e o código do beneficiário e não Carteira, Agência e Conta Corrente. Já da linha 063 a 065 só é preenchido com o código do banco quando o beneficiário possui débito automático, quando não ele deve ser preenchido com 0. E na linha 082 o calculo do digito do nosso número foi inválido, segundo o gerente, isso pode ter ocorrido porquê o calculo do Dígito leva em consideração o número da carteira. Em fim, não sei se essa divergência é resultado da atualização do manual, que na Lib tá 10, e essa última versão disponibilizada para o banco é a 11, de qualquer forma estou sinalizando aqui e caso eu consiga fazer esse ajuste te mando um PR.

**Comment by eduardokum** [comment]
Bom dia, Você esta colocando os dados do cliente somente no boleto ou esta colocando na instancia da remessa também?? porque se você não colocar na remessa ele vai zerado mesmo....

**Comment by wesleysaraujo** [comment]
Estou colocando sim, mas ele está setando o código do beneficiário no trailer, enquanto deveria estar setando as infos de carteira, agência de conta. Vi que no método getCodigoCliente vc verifica se o codigoCliente for vazio ele seta as infos corretas que são necessárias, o problema de eu deixar o codigoCliente vazio na remessa, é que ele usa esse mesmo método tanto no método header quanto no addBoleto.

![image](https://user-images.githubusercontent.com/1865543/35626849-23ee21d6-067e-11e8-9b79-a82d31a9e563.png)

![image](https://user-images.githubusercontent.com/1865543/35627045-d45b3c16-067e-11e8-9980-407b52048c25.png)

**Comment by wesleysaraujo** [comment]
Eu fiz um fork e refatorei as linhas do método addBoleto conforme orientação do setor técnico do Bradesco, enviei os arquivos para análise novamente e estou aguardando:

![image](https://user-images.githubusercontent.com/1865543/35627327-b78c59b6-067f-11e8-8ba1-4b00a50fddc0.png)

**Comment by wesleysaraujo** [comment]
Como falei no comentário anterior, após a refatoração do método, o banco reanalisou os arquivos e deram OK. Posso mandar um PR?

![image](https://user-images.githubusercontent.com/1865543/35645689-ccb8bf9e-06b3-11e8-9614-f3fe42fb81fc.png)

**Comment by eduardokum** [comment]
Fiz o merge la. 

Obrigado.

Abraço

**Comment by wesleysaraujo** [comment]
Valeu :+1: .
