### ISSUE TITLE
Remessa CAIXA CNAB 240

### ISSUE THREAD

**Issue by leosantoscunha** [eduardokum/laravel-boleto#266]
Estou com um erro na hora de gerar remessa CEF, eu passo a carteira RG e sempre dá erro 'Carteira indisponível', verifiquei que a classe Abstract Boleto esta trocando a carteira para SR o que da esse erro. 
Se alguém puder me ajudar.

**Comment by wesleysaraujo** [comment]
Meu arquivo remessa da Caixa também foi invalidado, a formação das linhas estão incorretas de acordo com o Verificador de Arquivo Remessa que eles disponibilizam no site deles. Ainda não consegui refatorar e fazer um PR, porém ainda não tinha percebido esse erro de trocar RG por SR.

**Comment by leosantoscunha** [comment]
A carteira passa por esse método: 

class AbstractRemessa
`    public function setCarteira($carteira)
    {
//aqui o $carteira = 'SR' 
        if (! in_array($carteira, $this->getCarteiras())) {
            throw new \Exception("Carteira não disponível!");
        }
        $this->carteira = $carteira;

        return $this;
    }`
Porem também passa pelo mesmo método no Abstract boleto é nele que a carteira aparece como 'SR',
não faço ideia do porque.

**Comment by leosantoscunha** [comment]
```
 /**
     * Define o código da carteira (Com ou sem registro)
     *
     * @param  string $carteira
     *
     * @return AbstractBoleto
     * @throws \Exception
     */
    public function setCarteira($carteira)
    {
        var_dump($carteira);
        die();
        if (!in_array($carteira, $this->getCarteiras())) {
            throw new \Exception("Carteira não disponível!");
        }
        $this->carteira = $carteira;

        return $this;
    }
```

Aqui a carteira muda para 'SR', isso na mesma remessa.

**Comment by eduardokum** [comment]
Você esta usando a ultima versão do pacote?

Antes acho que ele mudava carteiras pq na remessa usava numero e no coleto letra algo tipo assim... mais isso nao acontece mais...
