### ISSUE TITLE
Impressão em branco na tela quando HTML

### ISSUE THREAD

**Issue by StevensonFraga** [eduardokum/laravel-boleto#271]
Olá, aguem me ajuda por favor.
Estou com problemas quando tento executar a pagina não vem erro e também não sai nada .
No caso do PDF funciona bem somente HTML que não

$html = new Eduardokum\LaravelBoleto\Boleto\Render\Html();
$html->addBoleto($boleto);
$html->showPrint();
//$html->hideInstrucoes();
$html->gerarBoleto();
//$html->gerarCarne();

At
Stevenson Fraga

**Comment by eduardokum** [comment]
voce precisa dar um echo.

**Comment by StevensonFraga** [comment]
Desculpe, mais não entendi, seria 
echo $html; 

Quando carrego recebo erro
[12-Feb-2018 16:47:15 America/Sao_Paulo] PHP Recoverable fatal error:  Object of class Eduardokum\LaravelBoleto\Boleto\Render\Html could not be converted to string in D:\Sites\Local\laravel-boleto-master\exemplos\cef_boleto_HTML.php on line 148

**Comment by andersonhsilva** [comment]
Olá pessoal eu também estou com o mesmo problema, alguém aqui tem a solução?
