### ISSUE TITLE
Retorno do Bradesco

### ISSUE THREAD

**Issue by msouzarunner** [eduardokum/laravel-boleto#272]
Bom dia, estou usando o retorno do Bradesco e o numero da carteira está vindo nulo. Estou usando o layout de 400 posições.

**Comment by eduardokum** [comment]
Atualmente não esta puxando a carteira mesmo nos retornos, precisaria fazer a alteração na classe pra puxar, vou olhar isso. Obrigado

**Comment by msouzarunner** [comment]
Bom dia !!!
   
   Ainda não está fazendo falta pois estou usando uma carteira, mas logo vou usar outra. Agradeço o retorno.

**Comment by eduardokum** [comment]
Ja mandei a alteração.

c00fb31dd248626a4f41ba575064f69e9a108e6c

Obrigado
