### ISSUE TITLE
Linha em branco no fim do arquivo-remessa

### ISSUE THREAD

**Issue by luxu** [eduardokum/laravel-boleto#273]
Está ficando uma linha em branco no fim do meu arquivo-remessa alguem sabe como resolver?

**Comment by eduardokum** [comment]
Bom dia, tem banco que exige isso, não esta passando na validação?

**Comment by luxu** [comment]
Resolvi isso...mas agora falam q num tem 400 posições no header mas dos 3 boletos q mandei 1 não deu esse erro, ou seja, como pode 3 coisas idênticas 2 dá erro e outro não?...aproveitando dos erros q corrigi esses 3 abaixo num sei onde buscar:

> - Número seqüencial do registro
> - Quantidade de documentos no arquivo
> - Valor total dos títulos

e esse outro num sei o q fzr:

> Registro inválido na linha 3. O registro está fora de ordem.

**Comment by luxu** [comment]
mas se vem no retorno pq pedem na remessa?

**Comment by eduardokum** [comment]
Essas informações vai na remessa de 240 posições a classe calcula isso sozinho, mais como você esta usando a remessa de 400 posições, essas informações não são utilizadas

**Comment by luxu** [comment]
Será Eduardo pq além de falarem q está errado eles mandam o q deve ser colocado lá...essa linha 

> Encoding::toUTF8($stringRemessa);

é só pra quem usa laravel? Pois estou fazendo no ZF1 e dá erro falando q não existe...

**Comment by eduardokum** [comment]
Não esse encoding é  ```"neitanod/forceutf8": "^2.0",```, não sei que erro pode ser esse não, a menos que tenha um registro detalhe e nao tenha um registro header antes ou tenha um trailer e depois um detalhe, a classe não geraria isso, mais se voce concatenar arquivos pode dar um erro assim acredito.
