### ISSUE TITLE
Problema no render HTML

### ISSUE THREAD

**Issue by karlasantos** [eduardokum/laravel-boleto#274]
Olá, estou tendo problema ao renderizar o boleto em HTML, retorna uma exeção do Compiler.php informando que o cache path é inválido. É algum problema na minha instalação das dependências dos pacotes ou pode ser no código?

**Comment by eduardokum** [comment]
Você não usa o laravel? pq se usa deve ser algum problema na instalação ou configuração se não usa ele cria uma instancia do blade e vai criar o cache path dentro de /vendor/eduardokum/laravel-boleto/src/Boleto/Render/view/cache/

pode ser que não tenha permissão pra criar ou algo do tipo

**Comment by karlasantos** [comment]
Não uso o Laravel, uso o Zend. Isso resolveu o problema, obrigada e parabéns pelo excelente trabalho!
