### ISSUE TITLE
Erro ao gerar Boleto em HTML

### ISSUE THREAD

**Issue by didosilva** [eduardokum/laravel-boleto#28]
Quando tento gerar um boleto em HTML utilizando $boleto->renderHTML(), me retorna:

Fatal error: Call to undefined function Eduardokum\LaravelBoleto\Boleto\Render\view() in /home/storage/b/f6/fe/camelao1/public_html/sistema/vendor/eduardokum/laravel-boleto/src/Boleto/Render/Html.php on line 120

**Comment by eduardokum** [comment]
É algum problema na sua instalação do laravel, a função view() é uma helper do laravel
