### ISSUE TITLE
Código linha digitável está diferente do código gerado no código de barras

### ISSUE THREAD

**Issue by moisesabreu** [eduardokum/laravel-boleto#283]
Olá amigos, estou tentando utilizar o pacote de vocês mas percebi este detalhe ao ler o código de barras durante homologação do meu boleto no Itaú, debugando o código percebi que ele está se perdendo em algum momento. Seguem exemplos de códigos:

código errado gerado pelo código de barras:
34191745400000087001090000360186077219852000

Código correto gerado na linha digitável:
34191090080036018607672198520008174540000008700

Se puderem me dar uma dica de como resolver agradeço!

**Comment by eduardokum** [comment]
Isso mesmo, o codigo de barras é isso mesmo, a linha digitavel é o IPTE, que tem os digitos verificadores e misturado. esta correto.
