### ISSUE TITLE
Não gera boleto com o método renderHTML();

### ISSUE THREAD

**Issue by moisesabreu** [eduardokum/laravel-boleto#284]
Prezados, tentei realizar um teste com o $boleto->renderHTML(); porém a view está vindo em branco. Poderiam me indicar o que pode estar errado? 

Utilizei as referências de vocês descritas na documentação do projeto.

Obrigado!

**Comment by moisesabreu** [comment]
Prezados, consegui gerar assim: return response($boleto->renderHTML());

De qualquer forma agradeço!

**Comment by eduardokum** [comment]
Isso, essa função retorna o html, teria que transformar em rsponse no caso no laravel mesmo.

**Comment by moisesabreu** [comment]
Olá @eduardokum, Já começamos a utilizar o pacote em alguns testes e está se comportando bem. Obrigado!
