### ISSUE TITLE
Dúvida sobre alteração de boleto

### ISSUE THREAD

**Issue by LeandroSe** [eduardokum/laravel-boleto#285]
Olá, 

Estou implementando um sistema ainda não fiz uso desta biblioteca mas pretendo logo fazer uso, atualmente tenho uma herdado do sistema antigo, queria saber alteração de valor de boleto como proceder?
No Banco Itau tem a Alteração de vencimento que é a implementado desta biblioteca, mas a alteração de valor nesta ocorrencia se editar altera o valor do boleto?

Desculpa sei q não é uma dúvida do sistema em si.. Obrigado por qualquer coisa.

**Comment by eduardokum** [comment]
Olá boa tarde, os bancos acho que todos não oferece opção de alterar valores 

![image](https://user-images.githubusercontent.com/2566340/37115085-f074bb6e-2228-11e8-86be-a43b833ec244.png)

**Comment by LeandroSe** [comment]
Então eu vi essa opção, e no internet bank tem como mudar o valor... ai gerou a duvida!
Vou ver para testar isso, qualquer coisa informa.. Mas obrigado

**Comment by eduardokum** [comment]
Ok. Qualquer coisa comente aqui então

**Comment by efelipeyahoooo** [comment]
ao inserir minha data de vencimento ocorre o erro:
Fatal error: Uncaught TypeError: Argument 1 passed to Eduardokum\LaravelBoleto\Boleto\AbstractBoleto::setDataVencimento() must be an instance of Carbon\Carbon, string given, called in /home/datafaci/public_html/site/vendor/eduardokum/laravel-boleto/src/Util.php on line 914 and defined in /home/datafaci/public_html/site/vendor/eduardokum/laravel-boleto/src/Boleto/AbstractBoleto.php:530 Stack trace: #0 /home/datafaci/public_html/site/vendor/eduardokum/laravel-boleto/src/Util.php(914): Eduardokum\LaravelBoleto\Boleto\AbstractBoleto->setDataVencimento('2018-12-20') #1 /home/datafaci/public_html/site/vendor/eduardokum/laravel-boleto/src/Boleto/AbstractBoleto.php(298): Eduardokum\LaravelBoleto\Util::fillClass(Object(Eduardokum\LaravelBoleto\Boleto\Banco\Bb), Array) #2 /home/datafaci/public_html/site/vendor/eduardokum/laravel-boleto/src/Boleto/Banco/Bb.php(13): Eduardokum\LaravelBoleto\Boleto\AbstractBoleto->__ in /home/datafaci/public_html/site/vendor/eduardokum/laravel-boleto/src/Boleto/AbstractBoleto.php on line 530
....
'logo'                   => realpath(__DIR__) . DIRECTORY_SEPARATOR . '001.png',
        'dataVencimento'         => '2018-12-20', //new \Carbon\Carbon(),
...

como devo proceder para corrigir este erro?

obrigado.
