### ISSUE TITLE
Instruções estoura o tamanho.

### ISSUE THREAD

**Issue by jeidison** [eduardokum/laravel-boleto#288]
Quando uma instrução é adicionada com o texto muito grande, a mesma estoura e quebra o layout do PDF.

Solução é alterar o método private function listaLinhas($lista, $pulaLinha);

De:
private function listaLinhas($lista, $pulaLinha)
    {
        foreach ($lista as $d) {
            $pulaLinha -= 2;
            $this->Cell(0, $this->cell - 0.2, $this->_(preg_replace('/(%)/', '%$1', $d)), 0, 1);
        }

        return $pulaLinha;
    }

Para: 

private function listaLinhas($lista, $pulaLinha)
    {
        foreach ($lista as $d) {
            $pulaLinha -= 2;
            $this->MultiCell(0, $this->cell - 0.2, $this->_(preg_replace('/(%)/', '%$1', $d)), 0, 1);
        }

        return $pulaLinha;
    }

**Comment by eduardokum** [comment]
Respondi o PR
