### ISSUE TITLE
Protesto de boleto é ativado na Remessa mesmo com diasProtesto no boleto em 0 dias

### ISSUE THREAD

**Issue by didosilva** [eduardokum/laravel-boleto#29]
Ao homologar o boleto com meu banco, fui informado que a remessa apresentava a numeração '06' nos campos 157-158 e nos campos 159-160 o número de dias estava em 0. Como eu não protesto boleto, fui corrigir e vi que no boleto eu já tinha colocado a opção 'diasProtesto' em 0.

Para resumir, a remessa está setando em '06' mesmo colocando diasProtesto no boleto em 0. O certo seria setar os campos 157-158 em '00', pois o número de dias foi setado em 0.

no arquivo Cnab/Remessa/Banco/Bradesco.php verifiquei estas linhas:

```
$this->add(157, 158, '00');
$this->add(159, 160, '00');

if($boleto->getDiasProtesto() !== false)
{
   $this->add(157, 158, '06');
   $this->add(159, 160, Util::formatCnab('N', $boleto->getDiasProtesto(), 2));
}
```

Fiz um teste alterando `!== false` por `!= false` e funcionou. Isto corrigiria o problema?

**Comment by eduardokum** [comment]
Fiz algumas alterações em relação a esse protesto ac32a567de37a38a12656434242e7431a4ff3651

Obrigado
