### ISSUE TITLE
Dúvida dados do boleto - Arquivo Remessa

### ISSUE THREAD

**Issue by BrunoLagoa** [eduardokum/laravel-boleto#291]
Olá, 
estou criando o arquivo remessa do banco itaú modelo **Cnab 400**;
Quando envio o arquivo de remessa, após o processamento, no primeiro item de instrução, vem o texto:
**Instrução: Aplicar juros no valor de R$ 0,45 após o vencimento**

[imagem do arquivo] url: https://prnt.sc/iqbn5r

Esse juros não seria no item do boleto:
```
'multa' => 0, 
'juros' => 0,
'juros_apos' => 0, 
```
Qual deles e usado para gerar esse valor? gostaria que não tivesse juros. eu já tentei false, 0.00 e 0. mas esse valor ainda persiste na instrução.

Como posso regrar o arquivo e boleto sem aplicar o juros e se aplicar teria que ser 0.

**Comment by eduardokum** [comment]
Bom dia, acredito que isso deve ser alguma configuração global da cobrança direto no internet banking, que vem por padrão quando não se manda instrução nenhuma. se o juros for 0 ou false ele vai deixar o campo de mora/juros em branco.

**Comment by BrunoLagoa** [comment]
Bom dia... hoje conseguir um retorno do banco, me disseram que isso e uma configuração do banco, mesmo mandando zero, vai existir esse calculo.

Fica um alerta para alguém mais passar por isso. 

Muito obrigado pela ajuda!
