### ISSUE TITLE
Item beneficiário da ficha de compensação do Boleto do Banco Bradesco

### ISSUE THREAD

**Issue by murilolopes** [eduardokum/laravel-boleto#294]
Estou em processo de homologação do boleto com o pessoal do Bradesco e um dos tópico que eles não validaram é que na ficha de compensação, no item beneficiário só conta a razão social e o CNPJ.

O retorno foi o seguinte: 
**- Campo Beneficiário deve ser preenchido com Razão Social, CNPJ/CPF e o Endereço.**

Alguém com a mão na massa que possa subir essa solicitação?

**Comment by eduardokum** [comment]
Onde no boleto isso? versão em pdf ou html?

**Comment by murilolopes** [comment]
Nos dois.
Segue o email.

![captura de tela 2018-03-13 as 150631](https://user-images.githubusercontent.com/5649574/37361228-2f70a768-26d1-11e8-80a6-1457af8fc8c9.png)

**Comment by eduardokum** [comment]
tem erros ai que você que tem que arrumar no quando gerar os boletos, numeros sempre 1 aceite S, o local de pagamento é so trocar em $boleto->setLocalPagamento(). ja o endereço nunca vi pedirem, pede um manual atualizado para ver como deve ser feito.

**Comment by murilolopes** [comment]
@eduardokum Na página 31 você consegue verificar isso.

Segue o arquivo.
[4008-524-0121-layout-cobranca-versao-portugues - bradesco.pdf](https://github.com/eduardokum/laravel-boleto/files/1815832/4008-524-0121-layout-cobranca-versao-portugues.-.bradesco.pdf)

**Comment by eduardokum** [comment]
Vou dar uma olhada, vlw

**Comment by fabritha** [comment]
enviei a informação do item beneficiário do banco Bradesco pelo front, concatenando nome,documento e endereço e passando documento nulo, então item beneficiário ficou como no manual, caso seja uma emergência fica sugestão. xD

**Comment by murilolopes** [comment]
@fabritha é emergência sim e vlw pela ótima sugestão

**Comment by eduardokum** [comment]
Acredito que o gerente esta muito criterioso, pois na documentação apesar de la em cima estar "Nome do beneficiário/CPF/CNPJ/Endereço" na instrução de preenchimento nem menciona que deve ser preenchido o endereço.
![captura de tela de 2018-03-27 11-32-29](https://user-images.githubusercontent.com/2566340/37974755-0b44976c-31b4-11e8-986d-66ddbd4d8a03.png)
