### ISSUE TITLE
Retorno Sicredi CNAB 400

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#295]
Pessoal, 
boa tarde,

encontrei um problema no retorno do SICREDI no CNAB400.
Veja, esse é o array do registro, após o processamento pela biblioteca:

![Array do Retorno](https://user-images.githubusercontent.com/8810377/37359966-ba52ae7a-26cd-11e8-9816-2ff63bfd11dc.png)

Veja que o atributo numeroDocumento possui o seguinte código 318J98540. Porém no arquivo de retorno o número veio com um 0 (zero) na frente. Então o número correto é o 0318J98540, segue abaixo a imagem: 
![Registro no Arquivo de Retorno](https://user-images.githubusercontent.com/8810377/37360085-0156615e-26ce-11e8-8dc4-2611e7c5e304.png)

O que preciso fazer para corrigir esse problema?

**Comment by eduardokum** [comment]
o numero que voce enviou tem o 0 antes? quando voce envia ele não preenche com 0 antes do nosso numero... se no retorno esta vindo com 0 é o banco que esta preenchendo então você pode fazer um ltrim($numero, 0) que vai remover esse 0 ai, pois não tem o que fazer o banco que esta retornando esse 0 ai

**Comment by guicouto** [comment]
Na verdade o número enviado para o banco tem 0. Mas eu entendi o raciocínio. Na verdade então, quando um campo é preenchido com zeros a esquerda, para a instituição bancária, é uma representação de ausência de informação, certo?! Vou fazer o ltrim para remover essa informação no meu processamento de retorno. Muito obrigado.

**Comment by eduardokum** [comment]
Opa, qualquer coisa comenta ai.
