### ISSUE TITLE
Caractere especial invalida arquivo de remessa.

### ISSUE THREAD

**Issue by alunoadauto** [eduardokum/laravel-boleto#298]
Tive um problema com endereços que possuíam o caractere de ordem (º). 
A linha ficava com 241 caracteres inviabilizando o arquivo.
Corrigi colocando uma str_replace pra filtrar a entrada de dados, porém é uma coisa que a função UTIL poderia resolver.

Abraço, parabéns pelo excelente trabalho.

**Comment by eduardokum** [comment]
é o comportamento padrão da classe é deixar esses caracteres, existe uma função no util pra tratar isso chamada Util::normalizeChars(), porém ela não é chamada, não sei se todos os bancos dão problema em acentuação ou em que momento da o problema, inclusive uso com acentuação e o arquivo codificado em utf-8 e o banco aceita normal.

Não sei se a classe deveria alterar as informações pra normalizar os acentos para enviar pro banco, ou se isso deve ser responsabilidade da aplicação.

Por exemplo se o cliente tiver um contrato com o banco que ele envia o boleto mais o banco também envia, chegaria o nome sem a acentuação, e talvez isso não deveria ser o ideal.
