### ISSUE TITLE
Remessa Bradesco duplicação de mesma variável

### ISSUE THREAD

**Issue by fabritha** [eduardokum/laravel-boleto#299]
Bom dia, percebi que da versão 0.72 acima na remessa do Bradesco o código do cliente vem sendo duplicado no header e no corpo da remessa (com isso o arquivo de remessa se tornaria inválido).
[Header] ->Na coluna 027 a 046 tamanho de campo 20: Será fornecido pelo Bradesco,
quando do Cadastramento;
[Corpo] -> Na coluna 021 a 037 tamanho de campo 17: Zero, Carteira, Agência e Conta -
Corrente.

Versão nova:
![0 72](https://user-images.githubusercontent.com/8298846/37837162-46ca50ac-2e93-11e8-825f-652f91785c74.jpg)

Versão antiga (sem duplicação):
![0 71](https://user-images.githubusercontent.com/8298846/37837144-3d275bc6-2e93-11e8-830c-222badaae787.jpg)

Att. Thays

**Comment by eduardokum** [comment]
no branch develop isso ja esta corrigido, vou terminar de arrumar umas issues e fecho uma versão nova.


Veja aqui.
https://github.com/eduardokum/laravel-boleto/blob/develop/src/Cnab/Remessa/Cnab400/Banco/Bradesco.php

**Comment by fabritha** [comment]
Obrigada Eduardo!! Estarei no aguardo da nova versão =D!!!

**Comment by eduardokum** [comment]
criei a tag https://github.com/eduardokum/laravel-boleto/tree/0.7.5

**Comment by fabritha** [comment]
obrigada Eduardo! =D tenha um bom dia!
