### ISSUE TITLE
Erro ao gerar Remessa Bradesco

### ISSUE THREAD

**Issue by tarcisioruas** [eduardokum/laravel-boleto#3]
Eduardo,

Antes de mais nada, parabéns pelo seu trabalho.

Verifiquei que, ao gerar a remessa para Bradesco, há uma verificação se o dv da conta está preenchido. 

> Cnab/Remessa/Banco/Bradesco.php

`if(empty($this->getCodigoCliente()) || empty($this->getContaDv()) || !parent::isValid())
 {
            return false;
 }`

Porém, quando o digito da conta é '0', o  $this->getContaDv() está retornando true, gerando assim um erro indevido.

Além disso, as carteiras chumbadas no arquivo do Bradesco estão como 21 e 22. Sendo que a carteira que estou usando para o Bradesco é 09. Houve alguma mudança na numeração dessas carteiras?

Agradeço pela atenção e mais uma vez parabéns.

**Comment by eduardokum** [comment]
Opa obrigado, você tem razão essa verificação está errada do DV, está com a última versão?  Creio que seja só a 09 porque liguei no sac deles lá e eles me informaram que só trabalhavam com essa, se está com 21 22  e erro me fala onde está para verificar, valeu 

Enviado do Meu celular

    _____________________________

**Comment by tarcisioruas** [comment]
Obrigado por responder Eduardo.

Sobre a versão, estou usando a ultima versão, baixei ainda essa semana.
Sobre as carteiras, vou verificar com o banco.

Agradeço pela atenção.

Em 9 de abril de 2016 14:51, Eduardo Gusmão <notifications@github.com>
escreveu:

**Comment by eduardokum** [comment]
Se você está usando o 09 está certo, você viu no arquivo que está 21 e 22? Antes achei que eram essas porém estava errado, se está isso está errado

Enviado do Meu celular




On Sat, Apr 9, 2016 at 11:33 AM -0700, "tarcisioruas" <notifications@github.com> wrote:










Obrigado por responder Eduardo.



Sobre a versão, estou usando a ultima versão, baixei ainda essa semana.

Sobre as carteiras, vou verificar com o banco.



Agradeço pela atenção.



Em 9 de abril de 2016 14:51, Eduardo Gusmão <notifications@github.com>

escreveu:

**Comment by tarcisioruas** [comment]
Isso, confirmando...no arquivo está 21 e 22. Mas a que estou usando é a 09.

Em 9 de abril de 2016 15:40, Eduardo Gusmão <notifications@github.com>
escreveu:

> Se você está usando o 09 está certo, você viu no arquivo que está 21 e 22?
> Antes achei que eram essas porém estava errado, se está isso está errado
>
> Enviado do Meu celular
>
>
>
>
>
> On Sat, Apr 9, 2016 at 11:33 AM -0700, "tarcisioruas" <

**Comment by eduardokum** [comment]
Então acho que está errado no arquivo, vou ver isso 

Enviado do Meu celular




On Sat, Apr 9, 2016 at 2:28 PM -0700, "tarcisioruas" <notifications@github.com> wrote:










Isso, confirmando...no arquivo está 21 e 22. Mas a que estou usando é a 09.



Em 9 de abril de 2016 15:40, Eduardo Gusmão <notifications@github.com>

escreveu:



> Se você está usando o 09 está certo, você viu no arquivo que está 21 e 22?

> Antes achei que eram essas porém estava errado, se está isso está errado

>

> Enviado do Meu celular

>

>

>

>

>

> On Sat, Apr 9, 2016 at 11:33 AM -0700, "tarcisioruas" <
