### ISSUE TITLE
Boleto Sicredi

### ISSUE THREAD

**Issue by leomoty** [eduardokum/laravel-boleto#30]
Alguma chance de existir a inclusão? Ou alguma idéia de como poderia implementá-lo usando seu sistema?

**Comment by tofarias** [comment]
Acredito que de pra orientar-se pelo [boletophp.com.br](http://boletophp.com.br/#bancos) e adaptar a implementação para este projeto.

**Comment by mprandot** [comment]
Estou trabalhando nisso!

**Comment by eduardokum** [comment]
Acabei de enviar esse banco, estava trabalhando nele...

So não testei completamente a parte de retorno  pois não tenho o arquivo... 

commit 0187a275be81531cf1beb864eca63235c52c1305

**Comment by mprandot** [comment]
Perdi algumas horas desenvolvendo esse layout! hahaha :hankey: 
Obrigado, vou baixar aqui e testar

Logo mais vou implementar do Banrisul.
