### ISSUE TITLE
Como adicionar alteração do valor do título?

### ISSUE THREAD

**Issue by edolfuchs** [eduardokum/laravel-boleto#300]
Eu envio remessas de alteração de título e funciona bem, mas percebi que quando altero o valor do título o mesmo não é lido pelo banco. 

Pelo que vi no código realmente ele envia somente instrução de alteração do vencimento do título:
// Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bradesco;

$this->add(109, 110, self::OCORRENCIA_REMESSA); // REGISTRO
if ($boleto->getStatus() == $boleto::STATUS_BAIXA) {
   $this->add(109, 110, self::OCORRENCIA_PEDIDO_BAIXA); // BAIXA
}
if ($boleto->getStatus() == $boleto::STATUS_ALTERACAO) {
   $this->add(109, 110, self::OCORRENCIA_ALT_VENCIMENTO); // ALTERAR VENCIMENTO
   $this->add(109, 110, self::OCORRENCIA_ALT_OUTROS_DADOS); // < Precisaria incluir essa linha
}

Eu adicionei manualmente a linha de self::OCORRENCIA_ALT_OUTROS_DADOS. Minha pergunta é: tem outra forma de resolver isso?

**Comment by eduardokum** [comment]
Boa tarde, 

Com essa alteração ele altera o valor?

Pelo que li no manual achei que essa função de alterar valor não tinha via remessa, pois tinha banco que dava a ocorrencia de alterar valor mais foi retirado em versões mais recentes... 

OCORRENCIA_ALT_OUTROS_DADOS altera o valor? qual o banco que você utiliza? 

Se essa ocorrencia realmente alterar o valor, teria que ver se todos os bancos aceitam a alteração dessa forma e fazer uma função igual tem de alteração de vencimento e baixa por exemplo.

**Comment by edolfuchs** [comment]
Atualmente estou usando o banco bradesco.

Vou fazer alguns testes pra ver como alterar o valor do vencimento.

**Comment by edolfuchs** [comment]
Fiz alguns testes e segundo o Bradesco, não é possível alterar o valor de um título já registrado. Como são títulos registrados o mesmo pode ser atualizado no site de cada banco.
