### ISSUE TITLE
Arquivo Retorno Bradesco - Entradas Rejeitadas 

### ISSUE THREAD

**Issue by BrunoLagoa** [eduardokum/laravel-boleto#301]
No arquivo retorno, conseguimos pegar o erro do arquivo retorno?

**TABELA 1 - Entradas Rejeitadas (código da ocorrência = 03 na Posição 109 a 110)**

aqui ele mostra o motivo que o boleto foi rejeitado.

**Comment by eduardokum** [comment]
Sim amigo, rejeição 03 acredito que em todos o bancos ja pode ser acessado via $detalhe->getError(); so uns 2 bancos que não tinha o descritivo mais ja acabei de subir pra eles.

**Comment by BrunoLagoa** [comment]
Então... estou achando estranho, pq a mensagem não bate com o valor que está na documentação;
vou pegar um caso:

ele está me dizendo assim: 
**Entrada rejeitada (nota 20 - tabela 1) | Consulte seu Internet Banking**

Mas quando eu entro do arquivo retorno, eu tenho o valor de **14**
quando vou em **TABELA 1 - Entradas Rejeitadas (código da ocorrência = 03 na Posição 109 a 110)** e pesquiso o valor 14, tenho a seguinte informação: 
**14 NOSSO NÚMERO NOSSO NÚMERO JÁ REGISTRADO NO CADASTRO DO BANCO OU FORA DA FAIXA**

**Comment by BrunoLagoa** [comment]
A mensagem informativa fica aqui:
**ERROS / MENSAGEM INFORMATIVA 
REGISTROS REJEITADOS OU ALEGAÇÃO DO PAGADOR OU REGISTRO DE MENSAGEM INFORMATIVA
POSIÇÃO: 378 385  - X(08) NOTA 20**

**Comment by eduardokum** [comment]
Qual banco?

**Comment by BrunoLagoa** [comment]
Bradesco.

**Comment by BrunoLagoa** [comment]
[layout_cobranca_400bytes_cnab_itau.pdf](https://github.com/eduardokum/laravel-boleto/files/1853313/layout_cobranca_400bytes_cnab_itau.pdf)

**Ele fica na Página 26**

**Comment by BrunoLagoa** [comment]
essas informações deveria vim pelo **$detalhe->getError();** ?

**Comment by eduardokum** [comment]
> layout_cobranca_400bytes_cnab_itau.pdf
> 
> Ele fica na Página 26

Mais voce esta olhando no manual do itau o retorno do bradesco?

>  essas informações deveria vim pelo $detalhe->getError(); ?

Isso mesmo

**Comment by BrunoLagoa** [comment]
desculpa... escrevi errado, estava olhando um outro sistema e falei brasdesco... 
e itau. rs

teria que implementar essas informações para atualizar? pq não vem a informação correta;
`$detalhe->getError();`  e busca o código que tem na posição **378 385**

**Comment by BrunoLagoa** [comment]
vou mandar o arquivo de exemplo, apartir da linha 173 tem os dados... 
[CN09038A.zip](https://github.com/eduardokum/laravel-boleto/files/1853858/CN09038A.zip)

**Comment by eduardokum** [comment]
o itau estava sem mostrar os erros mesmo. Coloquei ja, subi em develop.Veja se esta ok ai.

**Comment by BrunoLagoa** [comment]
Olá, 
agora funcionou perfeitamente... 

https://prnt.sc/ixai9p

**Comment by BrunoLagoa** [comment]
Olá, eu refiz algumas mensagens, caso queira atualizar, segue abaixo:
por exemplo: quando o erro é **08** ele mostra assim **Não informado ou deslocado**, ai ficamos sem entender ainda do que se trata, ai mudei para **Nome do Pagador - Não informado ou deslocado**, deixei o problema mais clara.

```
private $rejeicoes = [
        '03' => 'Ag. Cobradora - Cep sem atendimento de protesto no momento',
        '04' => 'Sigla do estado inválida',
        '05' => 'Data Vencimento - Prazo da operação menor que prazo mínimo ou maior que o máximo',
        '07' => 'Valor do título maior que 10.000.000,00',
        '08' => 'Nome do Pagador - Não informado ou deslocado',
        '09' => 'Agência/Conta - Agência encerrada',
        '10' => 'Logradouro - Não informado ou deslocado',
        '11' => 'Cep não numérico ou cep inválido',
        '12' => 'Sacador/Avalista - Nome não informado ou deslocado (bancos correspondentes)',
        '13' => 'Estado/Cep - Cep incompatível com a sigla do estado',
        '14' => 'Nosso número já registrado no cadastro do banco ou fora da faixa',
        '15' => 'Nosso número em duplicidade no mesmo movimento',
        '18' => 'Data de entrada inválida para operar com esta carteira',
        '19' => 'Ocorrência inválida',
        '21' => 'Ag. Cobradora - Carteira não aceita depositária correspondente estado da agência diferente do estado do pagador ag. cobradora não consta no cadastro ou encerrando',
        '22' => 'Carteira - Não permitida (necessário cadastrar faixa livre)',
        '26' => 'Agência/Conta não liberada para operar com cobrança',
        '27' => 'Cnpj do beneficiário inapto devolução de título em garantia',
        '29' => 'Código empresa - Categoria da conta inválida',
        '30' => 'Entradas bloqueadas, conta suspensa em cobrança',
        '31' => 'Agência/Conta - Conta não tem permissão para protestar (contate seu gerente)',
        '35' => 'Iof maior que 5%',
        '36' => 'Quantidade de moeda incompatível com valor do título',
        '37' => 'Cnpj/Cpf do pagador não numérico ou igual a zeros',
        '42' => 'Nosso número fora de faixa',
        '52' => 'Ag. cobradora empresa não aceita banco correspondente',
        '53' => 'Ag. cobradora empresa não aceita banco correspondente - cobrança mensagem',
        '54' => 'Data de vencimento banco correspondente - título com vencimento inferior a 15 dias',
        '55' => 'Cep não pertence à depositária informada',
        '56' => 'Data Vencimento superior a 180 dias da data de entrada',
        '57' => 'Cep só depositária bco do brasil com vencimento inferior a 8 dias',
        '60' => 'Valor do abatimento inválido',
        '61' => 'Juros de mora maior que o permitido',
        '62' => 'Valor do desconto maior que valor do título',
        '63' => 'Valor da importância por dia de desconto (idd) não permitido',
        '64' => 'Data de emissão do título inválida',
        '65' => 'Taxa financiamento inválida (vendor)',
        '66' => 'Data de vencimento invalida/fora de prazo de operação (mínimo ou máximo)',
        '67' => 'Valor do título/quantidade de moeda inválido',
        '68' => 'Carteira inválida ou não cadastrada no intercâmbio da cobrança',
        '69' => 'Carteira inválida para títulos com rateio de crédito',
        '70' => 'Agência/Conta beneficiário não cadastrado para fazer rateio de crédito',
        '78' => 'Agência/Conta duplicidade de agência/conta beneficiária do rateio de crédito',
        '80' => 'Agência/Conta quantidade de contas beneficiárias do rateio maior do que o permitido (máximo de 30 contas por título)',
        '81' => 'Agência/Conta para rateio de crédito inválida / não pertence ao itaú',
        '82' => 'Desconto/Abatimento não permitido para títulos com rateio de crédito',
        '83' => 'Valor do título menor que a soma dos valores estipulados para rateio',
        '84' => 'Agência/Conta beneficiária do rateio é a centralizadora de crédito do beneficiário',
        '85' => 'Agência/Conta do beneficiário é contratual / rateio de crédito não permitido',
        '86' => 'Código do tipo de valor inválido / não previsto para títulos com rateio de crédito',
        '87' => 'Agência/Conta registro tipo 4 sem informação de agências/contas beneficiárias do rateio',
        '90' => 'Número da linha cobrança mensagem - número da linha da mensagem inválido ou quantidade de linhas excedidas',
        '97' => 'Sem mensagem (só de campos fixos), porém com registro do tipo 7 ou 8',
        '98' => 'Registro mensagem sem flash cadastrado ou flash informado diferente do cadastrado',
        '99' => 'Conta de cobrança com flash cadastrado e sem registro de mensagem correspondente',
    ];
```

**Comment by sergiomiguell** [comment]
nao estou conseguindo usar a rotina de retorno do itau poderia me ajudar.. estou usando atravez da pasta vendor o codigo e este:
function gerar_retorno_boleto($fin_id_filial,$fin_banco,$fin_agencia,$fin_conta,$fin_arq_retorno)
{
	ini_set('display_errors', 'on'); 
	error_reporting(E_ALL);	

    $pasta_cert  = $_SERVER['DOCUMENT_ROOT'];
	$pasta_raiz  = $_SESSION['scriptcase']['SC_app_dir'];

	require_once $pasta_cert .'/sgn_lib/boleto_php/vendor/autoload.php';	
	
	$arquivo = $pasta_cert.'/sgn_lib/boleto_pdf/'.$fin_arq_retorno;	
	
	echo 'Arquivo..:'.$arquivo;
	
	$cnab_ret = new Eduardokum\LaravelBoleto\Cnab\Retorno\Factory();
	
	$cnab_ret->make($arquivo);
	
	//echo 'retorno..:'.$retorno;
	
	$cnab_ret->processar();
//
	echo $cnab_ret->getBancoNome();
	dd($cnab_ret->getDetalhes());
