### ISSUE TITLE
Código de banco na remessa do Bradesco

### ISSUE THREAD

**Issue by murilolopes** [eduardokum/laravel-boleto#303]
@eduardokum No processo de homologação da remessa fui alertado para o seguinte erro:

**Linha 2, colunas 063 a 065, Registro tipo 1, informar zeros ou brancos. Sem dados para débito automático.**

No arquivo de layout do bradesco, na página 17, tem a seguinte instrução:

**063 a 065 - Códigos do Banco para Débito - “237”
Deverão ser informados 237, _caso o cliente Beneficiário tenha optado pelo débito automático_ em Conta do Pagador.
Para Títulos em que não deve ser aplicado o débito automático, este campo deverá ser preenchido com Zeros.**

O que acontece é que esta sendo setado o "237" por padrão e não há alguma condição para o caso do cliente que não tiver adquirido o serviço de débito automático, meu caso.

**Comment by eduardokum** [comment]
Olá, acredito que você deve estar usando alguma versão desatualizada.

A classe esta gerando 000 na posição 63-65

https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Remessa/Cnab400/Banco/Bradesco.php#L180
