### ISSUE TITLE
Este pacote registra o boleto diretamente no sistema do Sicoob?

### ISSUE THREAD

**Issue by lucasdelalibera** [eduardokum/laravel-boleto#304]
Bom dia!

Desculpe o desconhecimento, este pacote realiza a geração de um boleto e o registro do boleto diretamente no sistema do banco Sicoob?

Ele utiliza algum webservice fornecido pelo banco Sicoob para o registrar o boleto ou é preciso enviar a remessa manualmente?

Sabe se o Sicoob possui algum webservice para geração e registro de boletos?

Obrigado.

**Comment by brunoneve** [comment]
@lucasdelalibera 

a lib faz geração de boletos, remessa e trata retornos. Não tem nenhuma comunicações via webservices com nenhum banco.

Sobre o sicoob, até onde sei, eles não liberaram nenhum webservices para fazer esse tipo de integração.

**Comment by tortato** [comment]
@lucasdelalibera 
Para um meio mais automatizado de comunicação com o banco vc precisa contratar um servido de VAN, que realiza isso forma automática. Eu uso o serviço do pessoal da Nexxera, mas não é uma coisa simples de implementar, pq da uma dorzinha de cabeça!
