### ISSUE TITLE
Class 'NumberFormatter' not found

### ISSUE THREAD

**Issue by marcosbarbosa031** [eduardokum/laravel-boleto#305]
Olá, eu estou tentando rodar o exemplo de geração de boleto, porém retorna o seguinte erro:

Fatal error: Uncaught Error: Class 'NumberFormatter' not found in C:\xampp\htdocs\laravel-boleto\vendor\eduardokum\laravel-boleto\src\Util.php:338 Stack trace: #0 C:\xampp\htdocs\laravel-boleto\vendor\eduardokum\laravel-boleto\src\Boleto\AbstractBoleto.php(999): Eduardokum\LaravelBoleto\Util::nFloat(100, 2, false) #1 C:\xampp\htdocs\laravel-boleto\vendor\eduardokum\laravel-boleto\src\Util.php(914): Eduardokum\LaravelBoleto\Boleto\AbstractBoleto->setValor(100) #2 C:\xampp\htdocs\laravel-boleto\vendor\eduardokum\laravel-boleto\src\Boleto\AbstractBoleto.php(292): Eduardokum\LaravelBoleto\Util::fillClass(Object(Eduardokum\LaravelBoleto\Boleto\Banco\Caixa), Array) #3 C:\xampp\htdocs\laravel-boleto\vendor\eduardokum\laravel-boleto\src\Boleto\Banco\Caixa.php(13): Eduardokum\LaravelBoleto\Boleto\AbstractBoleto->__construct(Array) #4 C:\xampp\htdocs\laravel-boleto\vendor\eduardokum\laravel-boleto\exemplos\cef_boleto.php(44): Eduardokum\LaravelBoleto\Boleto\Banco\Caixa->__construct(Array) #5 {main} thrown in C:\xampp\htdocs\laravel-boleto\vendor\eduardokum\laravel-boleto\src\Util.php on line 338

Estou rodando o teste localmente através do XAMPP com a versão 7.2.3 do PHP.
Alguma ideia do porquê deste erro? Agradeço desde já;

**Comment by marcosformagini** [comment]
Tenta o seguinte:
Abre o **php.ini** e acha essa linha
```
;extension=php_intl.dll
```
e descomenta ela tirando o ;
```
extension=php_intl.dll
```
Depois reinicia o Apache.

**Comment by venezianluis** [comment]
Estou tendo o mesmo problema, e mesmo após descomentar a linha `extension=php_intl.dll
` não foi resolvido. Alguém pode me ajudar com outra configuração? Agradeço.

**Comment by matheuscurvelo** [comment]
tambem estou coom esta dificuldade
