### ISSUE TITLE
Linha 2 das instruções cortada no arquivo remessa Sicredi

### ISSUE THREAD

**Issue by jsjunior** [eduardokum/laravel-boleto#306]
Boa noite.

Estou tendo problemas com a 2a. linha da instrução no arquivo remessa do Sicredi conforme imagem anexo. Ao invés das 80 posições previstas no layout, estão sendo inseridas no arquivo apenas 20

![captura de tela 2018-04-16 as 23 20 15](https://user-images.githubusercontent.com/1750415/38845167-dbf3edb8-41cc-11e8-8c89-9076674bbefa.png)

**Comment by eduardokum** [comment]
Voce diz nos 400 posições na linha das instruções?

**Comment by jsjunior** [comment]
Isso.

**Comment by eduardokum** [comment]
Não esta indo nenhum caracter inválido? [Aqui](https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Remessa/Cnab400/Banco/Sicredi.php#L184) que ele faz a inserção desses 80 caracteres, não vejo problema, consegue dar um DD nesse trecho e ver o que essas funcoes formatCnab estão retornando?

**Comment by jsjunior** [comment]
Acredito que o erro esteja na linha 186:
` $this->add(122, 261, Util::formatCnab('X', $boleto->getInstrucoes()[2], 80));`
                       
A posição inicial não deveria ser 182? A instrução 2 parece que está sendo sobrescrita.

**Comment by eduardokum** [comment]
Tem razão, ja vou mandar uma atualização
Obrigado

**Comment by jsjunior** [comment]
Não cara, eu é que agradeço. Não fosse esse pacote teria de reimplementar os boletos o que é um saco diga-se de passagem. Muito obrigado mesmo.
