### ISSUE TITLE
Dúvida arquivo remessa 

### ISSUE THREAD

**Issue by BrunoLagoa** [eduardokum/laravel-boleto#307]
Olá, existe alguma função que possa ler o arquivo remessa da mesma forma que o retorno?

**Comment by eduardokum** [comment]
Bom dia, não existe a Util::criarRetornoFake() que uso pra criar modelos de retorno baseado na remessa, mais não é bem a leitura, so muda algumas informações para montar um arquivo "fake de retorno"
