### ISSUE TITLE
Dúvida Boleto Bradesco

### ISSUE THREAD

**Issue by BrunoLagoa** [eduardokum/laravel-boleto#308]
Olá, se eu tiver a linha digitável mas outros dados do cliente, eu consigo gerar gerar o boleto bradesco com a mesma linha digital? Estava precisando gerar o mesmo boleto já registrado.

**Comment by eduardokum** [comment]
Se voce colocar as mesmas informações no boleto em teoria deveria ser o mesmo boleto..
Se vce tiver a linha digitavel voce consegue extrair as variaves com `Util::IPTE2Variveis('')` e a partir dai voce gera um novo boleto

**Comment by BrunoLagoa** [comment]
obrigado
