### ISSUE TITLE
Detalhes no Boleto BRADESCO

### ISSUE THREAD

**Issue by duard** [eduardokum/laravel-boleto#309]
Olá mais uma vez,
caras, tenho achado o BRADESCO uma inháca danada, tanto remessa quanto boleto. Já fiz tudo com o SICOOB e foi bem mais tranquilo. Enfim, enviei alguns boletos meus gerados com o projeto para o pessoal do BRADESCO validar, e depois de dias e dias de espera, eles me responderam. Tenho duas dúvidas com relação `a resposta deles e o projeto : 

1 - como colocarei a informação do endereço sendo que não há mais espaço ali
2 - como modificar esta msg de pago preferencialmente ?

- Os Campos Beneficiário e Pagador devem ser preenchidos com Razão Social CNPJ/CPF e o Endereço.
- Campo Local de Pagamento, mencionar: “Pagável preferencialmente na Rede Bradesco ou Bradesco Expresso”.

![unnamed_042718_101408_am](https://user-images.githubusercontent.com/36894/39364260-c28c886e-4a03-11e8-9118-6fbeefc197d1.jpg)

**Comment by eduardokum** [comment]
Bom dia, esse bradesco nem sabe o que diz... veja essa issue #294 no manaul diz que não precisa

**Comment by eduardokum** [comment]
Se não estiver resolvido comente aqui de novo, Vlw.
