### ISSUE TITLE
Banco inter

### ISSUE THREAD

**Issue by juizmill** [eduardokum/laravel-boleto#310]
Teria alguma proposta para o banco inter?

**Comment by eduardokum** [comment]
Bom dia, infelizmente não, mais se você tiver o manual mande o PR.

**Comment by tiagofranco86** [comment]
Ola pessoal, cheguei a iniciar a implementação com esse banco, cheguei a gerar a integração da remessa, retorno e da emissao do boleto, porém impaquei na geração da ficha de compensação. 

Atualmente estou sem tempo, se tiver alguem que possa me ajudar nessa parte da ficha agradeceria. Fiz um fork do projeto **https://github.com/tiagofranco86/laravel-boleto**, assim q finalizado essa parte da ficha poderemos enviar aqui para a api do Eduardo.

**Comment by eduardokum** [comment]
Olá já está disponível remessa retorno boleto e api do Inter em beta!

Pode ajudar a testar


Obrigado
Em 5 de fev. de 2022 02:40 -0300, tiagofranco86 ***@***.***> escreveu:

**Comment by tiagofranco86** [comment]
Salve Eduardo, blza!

**Comment by devthiagolino** [comment]
Oi @eduardokum aparentemente o banco inter só permite arquivos CNAB 240. No que puder ver você homologou o layout para o CNAB 400.

Veja abaixo um trecho da documentação:

O arquivo remessa deverá ter a seguinte formatação de nome para upload com sucesso no Internet Banking PJ - CI240_001_NNNNNN.REM:

CI - CNAB Inter
240 Tipo de arquivo CNAB 
001 - Versão do layout

**Comment by eduardokum** [comment]
Se ver na pasta manual tem o manual de 400 posições, utilizo ele em produção e funciona, a menos que mudou algo para remover suporte a 400 posições, se não está funcionando sim
