### ISSUE TITLE
Erro submissão Remessa Sicredi CNAB240

### ISSUE THREAD

**Issue by karlasantos** [eduardokum/laravel-boleto#311]
Olá, estou tendo problemas ao submeter o arquivo de remessa Sicredi com CNAB240, recebo o seguinte erro:
```
Dados inválidos.
991:Erro Fatal na Rotina de Upload: ORA-06502: PL/SQL: numeric or value error: chara.
```
Alguma ideia do que possa ser? Pode ser um erro na geração do arquivo? Testei o CNAB400 e está funcionando corretamente.

**Comment by eduardokum** [comment]
Vixi o banco que te retorna isso?

**Comment by karlasantos** [comment]
@guicouto também reparei que o erro era uma exceção do DB, o que indica que pode ser um erro no conteúdo do arquivo ou um erro do Sicredi ao tratar as remessas desse layout. Vou tentar entrar em contato com o Banco amanhã e retorno aqui.

**Comment by karlasantos** [comment]
O erro não teve relação com a geração da remessa, a Sicredi não aceita envio de CNABs diferentes para uma mesma conta, deve ser realizado um pedido de alteração de CNAB na instituição. Da mesma forma que pedidos de alterações e baixas de um boleto enviado por um arquivo de CNAB400 não podem ser realizados por um CNAB240, a instituição armazena no boleto cadastrado o CNAB enviado no cadastro. Obrigada pela atenção.
