### ISSUE TITLE
Boleto Banco Safra S.A

### ISSUE THREAD

**Issue by wandersonmax** [eduardokum/laravel-boleto#312]
Boa Tarde,

gostaria de contribuir para o projeto com o boleto do banco safra.

Fiz um fork do projeto e implementei o boleto, como faço para enviar para avaliação e inclusão no projeto?

**Comment by edigomes** [comment]
[https://www.youtube.com/watch?v=E8MPe6tCMo8](url)

**Comment by eduardokum** [comment]
Isso mesmo. So mandar um PR que eu aceito aqui, so mante pro branch develop.

**Comment by eduardokum** [comment]
Precisa de ajuda com o PR? qualquer coisa pode comentar aqui de novo. vlw

**Comment by wandersonmax** [comment]
Estou no processo de validação com o Safra, assim que conseguir finalizar envio. Obrigado!
