### ISSUE TITLE
Dúvida: Reimpressão ou Segunda Via

### ISSUE THREAD

**Issue by globsecure** [eduardokum/laravel-boleto#313]
Para reimpressão ou segunda via do boleto (sem atualizar nenhum dado, juros ou multa.) É possível recriar o boleto?
---
PS: Não gostaria de manter arquivos PDF no servidor / Ideia é manter gerar sempre em HTML.

**Comment by eduardokum** [comment]
Opa, sempre que voce gerar os boletos com os mesmos parametros será uma copia igual, mesmo pra boletos vencidos.

**Comment by globsecure** [comment]
@eduardokum - Fiz isso, realizei o backup dos parametros no banco e sempre chamo os mesmo funcionou perfeitamente. Obrigado!
