### ISSUE TITLE
Erro na Remessa 240 para Siccob

### ISSUE THREAD

**Issue by jeffie22** [eduardokum/laravel-boleto#314]
Boa tarde,  estou tendo problemas para enviar arquivo de remessa para Sicoob, já fiz para 2 clientes usando o cnab400 e funcionou blz, estou tendo problema agora por que este cliente so pode usar cnab240 o sicoob me informou que vai descontinuar o cnab400 e chamei a classe do cnab240 com os mesmo dados e não funcionou.

Header Arquivo Pos(19),Tam(14) - CPF/CNPJ não é válido.

**Comment by eduardokum** [comment]
Bom dia, 

Não necessariamente é so trocar, no 240 necessita mais informações que a 400 posições, CNPJ do beneficiario por exemplo é uma delas, não precisa na 400 e precisa na 240, voce precisa informar o cadastro completo do beneficiario http://laravel-boleto.readthedocs.io/en/latest/usage/beneficiario.html
