### ISSUE TITLE
Boleto Banrisul

### ISSUE THREAD

**Issue by cacio** [eduardokum/laravel-boleto#315]
Bom dia, estou usando a sua api para fazer a geração do boleto banrisul só me deparei com uma situação no boleto não aparece Agência/Código beneficiário e o digito verificador esta estranho, os valores no caso valor cobrado também não parece  tens como me ajudar com essas informações obrigado, segue a imagem de um boleto abaixo; 
![image](https://user-images.githubusercontent.com/4051536/39867886-73c4190c-542d-11e8-8536-33bba554cfe4.png)

**Comment by eduardokum** [comment]
Bom dia, valor cobrado é o caixa que preenche. o agencia/codigo do beneficario so vai aparacer se voce passar o campo `codigoCliente` quando instanciar o boleto

**Comment by cacio** [comment]
@eduardokum  Obrigado pela dica abraço
