### ISSUE TITLE
Erro ao pagar Boleto Bradesco no Itaú

### ISSUE THREAD

**Issue by rafwell** [eduardokum/laravel-boleto#316]
Boa tarde! Estou recebendo relatos frequentes do meu cliente que diz que os boletos estão sendo recusados como "Não encontrados no banco". Porém, o PDF parece válido, a remessa foi enviada dia 8 e não conseguem pagar.

Alguém passou por algo semelhante e pode me dar um norte?

Abraços.

**Comment by enricodvn** [comment]
Precisaria ver o conteúdo do arquivo de retorno, após o envio da remessa. Se deu entrada (código 02) tem que ver com o gerente se a carteira está validada. Pode ser que o ambiente esteja em desenvolvimento, etc... Se o boleto estivesse errado, o sistema do banco rejeita.

**Comment by eduardokum** [comment]
Se não estiver resolvido comente aqui de novo, Vlw.

**Comment by rafwell** [comment]
Obrigado pelas respostas. No meu caso o arquivo de remessa estava sendo recusado. Enviava normal, porém depois de cerca de 6 horas é que o Bradesco processa o arquivo. Ele ficava com status "Indícios de Rejeição". Segundo o suporte, era o número de sequencia que estava menor que o necessário. 
Alterei. Abraços.
