### ISSUE TITLE
[SUGESTÕES] Variáveis para Particularidades

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#317]
**Boa tarde pessoal,**
recentemente notei que algumas classes, possuem dados _"estáticos"_, que poderiam se tornar variáveis a fim de facilitar para o desenvolvedor padronizar o seu código.

**Vejam alguns exemplos:**

- Na classe Bancoob do CNAB 240, o juros está estático para ser utilizado com um percentual mensal. ([Linha 133](https://github.com/eduardokum/laravel-boleto/blob/f4064befef8f4c0ad2fe7580790d726c26a76566/src/Cnab/Remessa/Cnab240/Banco/Bancoob.php#L133))
- Na classe do Bb do CNAB240, o juros está estático para ser utilizado com o valor ao dia. ([Linha 203](https://github.com/eduardokum/laravel-boleto/blob/f4064befef8f4c0ad2fe7580790d726c26a76566/src/Cnab/Remessa/Cnab240/Banco/Bb.php#L203))

Esse mesmo cenário acontece para outras situações, por exemplo, o **desconto promocional até uma data pré-estabelecida**, pode ser concedido em porcentagem, ou em valor fixo. Algumas classes podem estar de uma forma diferente de outras.

Pode ser que já exista essa padronização nas classes e eu não sabia. Caso exista, por favor me instruam como utilizar.

Abraços.

**Comment by eduardokum** [comment]
Bom dia, seria interessante, mais teria que ver caso a caso isso, pois tem banco que nao oferece essa possibilidade, tem banco que é so % e tem outro que é so R$. Pra ter certeza mesmo teria que conferir a classe e olhar no manual. Preciso de um tempo pra fazer uma documentação que especifique essas coisas direito.
