### ISSUE TITLE
[BUG FIX] CPF/CNPJ do Sacado Incorreto no CNAB 240 do Banco do Brasil

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#318]
Boa noite,
encontrei um problema na geração da remessa no CNAB 240 do Banco do Brasil.

## Problema:
Na geração da remessa no formato CNAB 240 do Branco do Brasil, o campo da Identificação do Sacado (Posiões de 19-33) deve ser preenchido com o CPF/CNPJ do sacado (pagador), conforme o layout as instruções do[ CNAB 240 da Febraban](http://www.bb.com.br/docs/pub/emp/empl/dwn/003Cobranca.pdf).

Porém, na biblioteca está sempre utilizado o CPF/CNPJ do emitente, conforme especificado na linha [L247](https://github.com/eduardokum/laravel-boleto/blob/f4064befef8f4c0ad2fe7580790d726c26a76566/src/Cnab/Remessa/Cnab240/Banco/Bb.php#L247)

## Correção:

Alterar o conteúdo da linha 246 para:
`$this->add(18, 18, strlen(Util::onlyNumbers($boleto->getPagador()->getDocumento())) == 14 ? 2 : 1);`

Alterar o conteúdo da linha 247 para:
`$this->add(19, 33, Util::formatCnab('9', Util::onlyNumbers($boleto->getPagador()->getDocumento()), 15));
`

Provavelmente com isso o problema será corrigido.

**Comment by eduardokum** [comment]
Tem razão, ja fiz a mudança aqui jaja eu subo obrigado.
