### ISSUE TITLE
Digito verificador do nosso número Bradesco

### ISSUE THREAD

**Issue by victormangia** [eduardokum/laravel-boleto#319]
Pessoal, quando eu envio o CNAB, não coloco no campo nosso número o Digito Verificador do nosso número incluso, o correto seria colocar?

Como eu posso fazer para pegar esse valor dentro da função para gerar o remessa?

**Comment by eduardokum** [comment]
Bom dia, não a classe calcula o dv sozinho, não precisa pegar so adicionar o boleto que a remessa vai pegar o valor com DV ja.
