### ISSUE TITLE
Carteira no boleto ITAU

### ISSUE THREAD

**Issue by codzero** [eduardokum/laravel-boleto#32]
Olá, o campo carteira no boleto Itaú não esta sendo exibido no boleto individual usando renderHTML().

Parabéns pelo laravel-boleto

**Comment by eduardokum** [comment]
É proposital, o boleto do itau não usa esse campo

<img width="589" alt="itau" src="https://cloud.githubusercontent.com/assets/2566340/20113038/d85d99f4-a5d5-11e6-9167-a65aecc12618.png">

**Comment by eduardokum** [comment]
Valeu obrigado.

**Comment by codzero** [comment]
Opa perfeito Eduardo, falha minha.
