### ISSUE TITLE
GetTotais Method not found </3

### ISSUE THREAD

**Issue by cvieiraeduardo** [eduardokum/laravel-boleto#321]
Boa Noite @eduardokum,
Primeiramente, sou muito grato pela iniciativa do seu projeto, 
estou implementando ele em um ERP SaaS , e realmente superando as expectativas, 

Bom, esta issue, é para criação de um método na classe AbstractRetorno ([Cnab/Retorno/AbstractRetorno.php](https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Retorno/AbstractRetorno.php)),
o Método é o **GetTotais()** que retorna as informações de "**protected $totais = [];**", para pegar o retorno dos totais, as informações são bem interessantes, porem não tem este método na classe, seria possível a implementação?

Até fiz uma modificação e funcionou, porem será interessante atualizar aqui também, pois uso em produção esta lib aqui do github.

Grato .,

Att,
Carlos E. Vieira
carlos@hisoft.com.br
+55 41 9 84277103

**Comment by eduardokum** [comment]
Opa bom dia, consegue mandar o PR? manda em develop que eu junto com outras modificações e crio um release. vlw

**Comment by eduardokum** [comment]
Implementei aqui ja, tinha outros codigos pra mandar ai ja coloquei, vlw.
