### ISSUE TITLE
Dúvida Validador de arquivo de remessas CEF

### ISSUE THREAD

**Issue by ySales** [eduardokum/laravel-boleto#322]
Tentei validar o arquivo de remessa gerado utilizando o validador disponibilizado no site da caixa, porém algumas informações foram rejeitadas,, a citar no header do arquivo em que foi passado 101 e o validador esperava 050. Conferi o layout da Caixa e as posições de 164 a 166 de fato esperam 101.

Isso se trata de um desencontro de versões do layout e do validador? Posso presumir que o layout disponibilizado esta sempre a frente do validador?

**Comment by eduardokum** [comment]
Bom dia amigo, esse valor 101 é hardcoded... ou esse validador esta desatualizado ou o manual. Acredito que seja o validador pois o manual é de julho/2017

![image](https://user-images.githubusercontent.com/2566340/40173782-51433f76-59a9-11e8-8be2-386b493facc3.png)

**Comment by ySales** [comment]
De fato, em contato com a caixa, me informaram para considerar sempre com maior prioridade o manual.
