### ISSUE TITLE
Remessa Itaú - ERRO contaDv=0

### ISSUE THREAD

**Issue by wallysonn** [eduardokum/laravel-boleto#323]
Notei que a linha:
$this->add(29, 29, $this->getContaDv() ?: CalculoDV::itauContaCorrente($this->getAgencia(), $this->getContaDv())); 
não reconhece o dígito zero. No meu caso, se eu informar a conta 25832-0, ele monta com um dígito errado, fica 258323 (Dígito 3). Não sei se é a solução correta, mas no meu caso, eu tornei obrigatório o preenchimento do campo DV da conta, então deixei a linha assim:
$this->add(29, 29, $this->getContaDv());

**Comment by eduardokum** [comment]
Ola bom dia, tem razão ele esta usando o metodo errado pra criar o dv, o certo seria usar o metodo ` CalculoDV::itauContaCorrente($this->getAgencia(), $this->getConta())` em vez de ` CalculoDV::itauContaCorrente($this->getAgencia(), $this->getContaDv())` vou subir o codigo jaja obrigado
