### ISSUE TITLE
Sicred CNAB400 Remessa Número do Documento do Sacador/Avalista Sendo Convertido para Zeros

### ISSUE THREAD

**Issue by jsjunior** [eduardokum/laravel-boleto#327]
Boa tarde.

Em uma segunda homologação no Sicredi para outro cliente, foi apontado um falso positivo de erro na posição 354 do detalhe porque o número do documento do Sacador/Avalista estava preenchido e o nome não.

Na verdade, não havia dados do Sacador e a formatCnab recebe uma máscara tipo 9L e completa o comprimento do documento com zeros ao invés de espaços como requerido, ocasionando o falso positivo no nome.

Como solução para seguir na homologação, modifiquei a linha 174 do arquivo Cnab/Remessa/Cnab400/Banco/Sicredi.php para:
`$this->add(340, 353, $boleto->getSacadorAvalista() ? Util::formatCnab('9L', $boleto->getSacadorAvalista()->getDocumento(), 14) : Util::formatCnab('X', '', 14));
`

Fica como sugestão de melhoria esta modificação ou haja uma forma melhor (alterando a Util, talvez). Obrigado.

**Comment by eduardokum** [comment]
Ola boa noite, vou fazer esse update. Obrigado.

**Comment by eduardokum** [comment]
Subi ja . Obrigado

https://github.com/eduardokum/laravel-boleto/releases/tag/0.7.8
