### ISSUE TITLE
Arquivo remessa CEF está gerando 2 ou 3 espaços a mais na posição 192

### ISSUE THREAD

**Issue by agkairos** [eduardokum/laravel-boleto#328]
Olá, veja a imagem http://prntscr.com/jksb5d
Antes de REMESSA-PRODUCAO, tem 2 ou 3 espaços que não consegui remover e com isso o banco está rejeitando o arquivo.

**Comment by edigomes** [comment]
Aí teria que postar como vc está gerando e seu arquivo.

Em Seg, 21 de mai de 2018 15:12, Weslley N.Dutra <notifications@github.com>
escreveu:

**Comment by agkairos** [comment]
Opa! faço conforme a documentacao:

> $remessa = new \Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab240\Banco\Caixa([
                                'agencia'       => 3659,
                                'idRemessa'     => $request->cliente,
                                'conta'         => 10053,
                                'carteira'      => 'RG',
                                'codigoCliente' => 878840,
                                'beneficiario'  => $beneficiario,
                            ]);

            $dir = storage_path().'/app/public/remessa/';
            $remessa->addBoletos($geraBoleto);
            $file = $remessa->save($dir . 'cef.txt');
            return response()->download($file, "cef.txt");

>

**Comment by agkairos** [comment]
Caro amigos, descobrir o que era o correto é
`$this->add(192, 211, Util::formatCnab('X', 'REMESSA-PRODUCAO', 20)); ou $this->add(192, 211, Util::formatCnab('X', 'REMESSA-TESTE', 20));`

Se for somente `$this->add(192, 211, 'REMESSA-PRODUCAO';` cria os espaços extras.

**Comment by eduardokum** [comment]
Qual versão do pacote você esta usando?

Qual a versão do Cnab que você esta usando?

**Comment by agkairos** [comment]
é a versao 0.7.8 e cnab240.
Detalhe, no metodo segmentoP(), tem a posicao $this->add(38, 39, '00'); mas o banco recusou, pois o correto, segundo a documentacao é $this->add(38, 40, '000');

**Comment by eduardokum** [comment]
Qual documentação você esta vendo??

a que eu tenho de julho/2017 esta assim 

![image](https://user-images.githubusercontent.com/2566340/41234584-fbaf87b8-6d62-11e8-9d65-1f087f7ff72b.png)

**Comment by agkairos** [comment]
Eduardo a documentação que o cara do banco me passou é de 2015. Mano, vou conferir com ele isso.
![image](https://user-images.githubusercontent.com/11198681/41237153-3e738260-6d69-11e8-9ca7-0f1b5a2f41a2.png)

**Comment by eduardokum** [comment]
A que esta baseado o projeto é na ultima depois das mudanças da febraban.  veja isso mais acredito que o banco deva estar confundo algo ai.
