### ISSUE TITLE
Suporte 5.1

### ISSUE THREAD

**Issue by irineujunior** [eduardokum/laravel-boleto#33]
Existe a possibilidade de manter o suporte no 5.1?
Estamos finalizando nosso financeiro e a tag `illuminate/support": "~5.2.0|~5.3.0` acabou por frear nosso dev =)

**Comment by eduardokum** [comment]
O próximo commit vou adicionar o suporte

**Comment by eduardokum** [comment]
adicionei o suporte em 0187a275be81531cf1beb864eca63235c52c1305
