### ISSUE TITLE
Homologação CEF

### ISSUE THREAD

**Issue by ySales** [eduardokum/laravel-boleto#331]
Estou em processo de homologação dos boletos CEF. Tive algumas observações de retorno no primeiro lote de boletos que enviei.

1 - Não consta o campo JUROS: A célula na classe PDF traz apenas Mora / Multa. O layout de especificação de boletos da caixa de 2014(na pasta de projeto parece que o de 2013 foi utilizado) traz esse campo na ficha de compensação. 

2 - SAC Caixa não informado: Informar os dados de contato da Caixa tanto na ficha de compensação como no recibo do pagador.
![saccaixa](https://user-images.githubusercontent.com/16749697/40661777-01dd2c4a-632b-11e8-9cd1-47208210a50e.png)

A classe PDF é usada para renderizar boletos de todos os bancos, como ter uma especificidade dessa como a solicitada?

**Comment by ySales** [comment]
O ponto 2 parece ser possível de resolver como mencionado em #95. Irei verificar, acabei postando sem consultar as issues fechadas.

**Comment by eduardokum** [comment]
Bom dia,

Você tem a especificação do boleto atualizada, a que tenho realmente é 2013, se tiver a nova eu vejo como faço para alterar somente na caixa.

**Comment by ySales** [comment]
Olá Eduardo. 

Segue o arquivo de 2014.
[sigcb_cod_barras.pdf](https://github.com/eduardokum/laravel-boleto/files/2094453/sigcb_cod_barras.pdf).

Na primeira vez  que submeti eles pediram para informar o campo de juros (Mora/Multa => Mora/Multa/Juros) . Fiz essa alteração na classe de PDF. Também questionaram as questões de SAC como eu mencionei.

Agora pediram para que campo Valor do documento (que fica do lado do campo Quantidade) seja alterado apenas para Valor, pois já existe Valor do Documento na sequência(puseram isso como uma observação).

A classe PDF é a mesma para para todos os boletos, alterei porque emito apenas para caixa. Fiquei em duvida de como resolver esse empasse!

**Comment by eduardokum** [comment]
O que falta é somente um "/juros" e o campo valor documento seja somente valor?

Exemplo do arquivo
![image](https://user-images.githubusercontent.com/2566340/41417912-054aeb96-6fc5-11e8-96d4-ffaa94835217.png)

Gerado pela classe
![image](https://user-images.githubusercontent.com/2566340/41417970-2479b100-6fc5-11e8-8703-ecc8fe9aafcc.png)

**Comment by ySales** [comment]
Sim, foi a observação que me retornaram(mas pediram para colocar somente valor e não xValor como no layout) . Enviei uma remessa nova para o banco e aguardo resposta.

**Comment by eduardokum** [comment]
Fiz a alteraçao jaja eu mando em develop.

Obrigado

**Comment by ySales** [comment]
O layout do boleto foi homologado pela Caixa.

**Comment by ySales** [comment]
O layout do boleto foi homologado!
