### ISSUE TITLE
[DUVIDA] - Retorno Bancário - Ocorrencia 11 (Em Ser)

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#333]
Pessoal,
Boa tarde,

Alguns boletos estão retornando com a ocorrencia 11 (em ser). Alguém já passou por essa mesma situação? 

Obs: Estou utilizando o banco Sicoob.

Desde já agradeço.

**Comment by marcosgerene** [comment]
@guicouto tive o mesmo retorno em alguns poucos boletos de um cliente novo.

Sabe me dizer o motivo?
