### ISSUE TITLE
Remessa BRADESCO CNAB400 Protesto e Correio

### ISSUE THREAD

**Issue by duard** [eduardokum/laravel-boleto#335]
Existem propriedades ao gerar a remessa para informar que : 

A conta terá qtdDias para ser protestada após o vencimento
A conta terá o Boleto confeccionado pelo banco ?

Um cliente meu me pediu tais features.

```
093 a 093 Condição para Emissão da Papeleta de
Cobrança 001
1 = Banco emite e Processa o
registro. 2 = Cliente emite e o Banco
somente processa o registro – Vide
obs. Pág. 19
```

**Comment by duard** [comment]
Cara, pelo que observei no código do projeto, está fixado para sempre ser emitido pelo Cliente

`$this->add(93, 93, '2'); // 1 = Banco emite e Processa o registro. 2 = Cliente emite e o Banco somente processa o registro`

Estou tentando criar esta propriedade aqui para gerar minha remessa com esta opção.

**Comment by eduardokum** [comment]
Olá, isso mesmo o projeto foi feito nessa intensão, pra gerar o boleto e a remessa tudo pelo projeto. Para o banco gerar acredito que precise passar mais informações na remessa, com dizeres que devem ser escrito no descritivo, coisa que não tem pronto no projeto.

**Comment by duard** [comment]
Pois é, no caso do meu cliente existem boletos que serão emitidos por ele e outros pelo banco (o banco envia pelo correio), ou seja, está propriedade seria necessária

**Comment by eduardokum** [comment]
Pra gerar isso você teria que estender a classe e sobrescrever o método de addBoleto mudar essa posição 93 e seguir o manual la que acho que é detalhe do tipo 2 que passa essas mensagens o banco gerar o boleto.
