### ISSUE TITLE
[Dúvida] - Nosso Número no arquivo de remessa

### ISSUE THREAD

**Issue by renanaazevedo** [eduardokum/laravel-boleto#336]
Olá,

O arquivo de remessa de 400 posições dos bancos Itau e Santander é gerado com substring do nosso número do boleto (no caso do itau o ultimo caractere é omitido e no caso do santander são os 5 primeiros).

Qual a razão disso, foi por causa do layout?

Ao usar o gerador de retorno do Util.php para gerar um arquivo de retorno para simular, percebi que por conta da remessa o retorno gerado tem o nosso número do mesmo jeito.

Isso dificulta a identificação do boleto pelo nosso número quando ele vier no arquivo de retorno.

O layout desses bancos (itau e santander) é assim mesmo ou foi apenas um erro de implementação.

Att.

**Comment by eduardokum** [comment]
No caso do itau ele remove o DV que tem que ir sem e no caso do Santander o boleto aceita ate 12 posiccoes porem na remessa so aceita 8 não sei o pq disso
