### ISSUE TITLE
Remessa do BB incorreto

### ISSUE THREAD

**Issue by diorges** [eduardokum/laravel-boleto#339]
No segmento P da coluna 38-57, o convenio e o nosso numero fica alinhado a direita, na validação de leiaute do BB passa, mas no retorno diz que está errado.

Verificando o manual, percebi que nesses campos independente do tamanho de posições do convenio, o convenio deve vir nos primeiros campos (alinhado a esquerda).

Aqui uso convenio de 7 posições, ou seja, as 7 primeiras casas tem que ser o meu convenio.

No arquivo src/Cnab/Remessa/Cnab240/Banco/Bb.php temos a linha:
``` 
$this->add(38, 57, Util::formatCnab('9', $this->nossoNumero($boleto), 17));
```

Ele preenche 17 posições das 20, mas alinha tudo para a direita, e fica 3 espaços nas primeiras casas e se eu mudar o 17 pra 20, preenche com 0 as 3 primeiras casas.

No momento para resolver o meu caso mas não é o correto, eu mudei de 38-57 para 38-54 e adicionei 3 campos em branco nas posições 55, 56 e 57. 
```
$this->add(38, 54, Util::formatCnab('9', $this->nossoNumero($boleto), 17));
$this->add(55, 55, '');
$this->add(56, 56, '');
$this->add(57, 57, '');
```

Tive um retorno OK do banco a partir da aqui e a remessa pode ser registrada.

**Comment by eduardokum** [comment]
Bom dia, tem razao olhei no manual e nao é número é alfa, não precisa fazer isso so mudar o '9' para 'X'.

Vou mandar um update.
