### ISSUE TITLE
Homologação

### ISSUE THREAD

**Issue by thiagof** [eduardokum/laravel-boleto#34]
Oi Eduardo, está fazendo um bom trabalho aqui!

Poderia falar algo sobre a homologação, já conseguiu passar com este codebase?

**Comment by eduardokum** [comment]
Olá, obrigado, o processo de homologação depende de cada banco mais normalmente é enviar 10 remessas e 10 boletos pra ele se validarem, alguns pedem mudanças em instrução ou algo assim mais homologam, BB e caixa foram os últimos que homologuei, os outros bancos já tinha homilogado com outra biblioteca aí só alterei pra essa e tudo continuou funcionando normalmente...

**Comment by eduardokum** [comment]
Na verdade não são 10 remessas, é uma remessa com os 10 boletos
