### ISSUE TITLE
[BUG] Dígito da Agência no Boleto da CEF

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#340]
Durante uma homologação do boleto da CEF, recebi o seguinte retorno do banco:

**O código do cedente deverá estar no formato AAAA/XXXXXX-DV**

Percebi que a biblioteca gera no seguinte formato AAAA-DV/XXXXXX-DV
Olhando a especificação do boleto em [Link da Específicação](https://github.com/eduardokum/laravel-boleto/blob/master/manuais/CEF/Especificacao_Boleto_Jul_2013.pdf) na página 13, realmente reporta que o formato que deve ser utilizado é o AAAA/XXXXXX-DV.

Para resolver o problema, implementei o método getAgenciaCodigoBeneficiario na classe Boleto/Banco/Caixa.php da seguinte forma:

```
/**
     * Retorna o campo Agência/Beneficiário do b  oleto
     *
     * @return string
     */
    public function getAgenciaCodigoBeneficiario()
    {
        $agencia = $this->getAgencia();
        $conta = $this->getContaDv() !== null ? $this->getConta() . '-' . $this->getContaDv() : $this->getConta();

        return $agencia . ' / ' . $conta;
    }
```

Sendo assim, basta acrescentarem esse método em um PR que irá resolver o problema.

**Comment by eduardokum** [comment]
So você não passar o DV que ele não vai colocar no boleto. a Caixa não usa esse DV.

**Comment by alexsmonte** [comment]
@guicouto tive esse problema tbm, irei fazer sua implementação.
