### ISSUE TITLE
Instrução de multa / juros

### ISSUE THREAD

**Issue by renanBritz** [eduardokum/laravel-boleto#341]
Boa noite!

Estou um pouco confuso com relação a instrução de multa / juros. Gerei um boleto com multa porém a única instrução presente neste é "Pagar até a data de vencimento". Procurei no código e consultei algumas issues antigas mas não ficou claro se isso está implementado ou não.

Devo adicionar a instrução manualmente? Ou será se fiz algo errado / É um bug?

Obrigado.

**Comment by renanBritz** [comment]
Olá @brunoneve 

Acabei me expressando mal, desculpe.

Eu queria saber se o laravel-boletos adicionava automaticamente a instrução de juros / multa.

Fica aí a sugestão.

Obrigado!

**Comment by brunoneve** [comment]
Ah ok,
mas não faz automático, você seta multa e juros na criação do boleto, mas pra colocar os valores de juros e multa nas instruções você precisa fazer isso .
