### ISSUE TITLE
Ajuda esse erro 

### ISSUE THREAD

**Issue by DavidGina306** [eduardokum/laravel-boleto#342]
"Class 'App\Http\Controllers\Eduardokum\LaravelBoleto\Boleto\Render\Pdf' not found"

**Comment by eduardokum** [comment]
Voce tem que usar ```\Eduardokum\LaravelBoleto\Boleto\Render\Pdf``` em vez de ```Eduardokum\LaravelBoleto\Boleto\Render\Pdf```
