### ISSUE TITLE
Erro Espécie Doc CNAB240 Sicoob

### ISSUE THREAD

**Issue by karlasantos** [eduardokum/laravel-boleto#345]
Bom dia,
no segmento P no arquivo de remessa do CNAB240  a espécie do documento está indo com os valores do CNAB400. Notei que na issue #243 isso está marcado como corrigido e vendo as modificações e o código as trocas dos valores de espécie do documento 240 estão sendo feitas na classe do 400. Eu alterei incluindo o mapemaneto na classe do 240, incluí a espécie DMI e o arquivo foi aceito pela Sicoob.

**Comment by eduardokum** [comment]
Bom dia, ja fiz o merge #347 obrigado
