### ISSUE TITLE
Retorno Cnab240 Santander não está chegando na função incrementDetalhe

### ISSUE THREAD

**Issue by tperrelli** [eduardokum/laravel-boleto#35]
Olá, no Retorno Santander Cnab240, ao invés de identificar T, está vindo A,B ou Z.

Estou passando um arquivo de retorno com vários clientes, que por sua vez deveriam ter seus detalhes atribuídos na collection que está na função incrementDetalhe().

Na classe AbstractRetorno.php
. Função processar
. Linha 270 "$this->getSegmentType($linha) == 'T'"

Estou com um arquivo de retorno fornecido diretamente pelo Santander. Esse Arquivo vem com vários registros. Na função mencionada da linha 270 apenas vem o tipo de segmento ABZABZABZABZABZ (Considerando que cada letra se refere a cada linha de registro do arquivo de retorno).

Sendo assim, a execução nunca chega na função incrementDetalhe().

Valeu!

**Comment by eduardokum** [comment]
Essa classe somente trata o retorno de cobrança, sendo segmento T e U não sei quais segmentos são esses que você diz ser A, B ou Z.

Verifique no manual "Layout de Arquivo - Padrão 240 – Cobrança" do banco santander. 

Abraço
