### ISSUE TITLE
Preciso enviar código 06 remessa cnab 240 bancoob colunas 16-17

### ISSUE THREAD

**Issue by fabritha** [eduardokum/laravel-boleto#351]
Olá, deixei um pull request com as alterações para enviar código 06 na remessa nos segmentos P, Q e R do boleto Sicoob, em caso de apenas alteração de data de vencimento ao invés de enviar código 31 enviar o 06.

Att. Thays

**Comment by edigomes** [comment]
Olá Thays, enquanto o pull request não é aceito você pode usar seu fork como repositório no composer, vide: https://getcomposer.org/doc/05-repositories.md#vcs

**Comment by fabritha** [comment]
Agradeço pela sugestão Edi =)

**Comment by ySales** [comment]
O composer recomenda que você use vcs https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository.

Utilizei vcs do projeto.

**Comment by eduardokum** [comment]
Respondi la no PR.
