### ISSUE TITLE
Qual tamanho ideal para logo do boleto? 

### ISSUE THREAD

**Issue by MatthausNawan** [eduardokum/laravel-boleto#352]
Qual tamanho da logo ideal para o boleto? todas os arquivos que eu uso fica muito pequeno, tem como ajustar isso na mão?

![image](https://user-images.githubusercontent.com/10215771/41927223-f7321980-7947-11e8-8752-d924e6ce9724.png)

**Comment by eduardokum** [comment]
Boa tarde, ele valida pela altura, se você mandar uma imagem grande ele vai deixar a altura no max de 2,8cm e vai fazer o width proporcional, ele usa a função Image do fpdf.
