### ISSUE TITLE
Gravar nosso numero no banco

### ISSUE THREAD

**Issue by agkairos** [eduardokum/laravel-boleto#353]
Olá!
Gostaria de gravar o nosso numero no banco, ao fazer:
`$html = new \Eduardokum\LaravelBoleto\Boleto\Render\Html();
                $html->addBoletos($geraBoleto);`

Tentei um foreach `foreach ($geraBoleto as $boleto)` porém não conseguir acessar o paramentro nossoNumero para depois salvar no meu banco de dados.

Obrigado.

**Comment by eduardokum** [comment]
Voce tem que usar 

$geraBoleto->getNossoNumero()
