### ISSUE TITLE
Erro validação de Layout - Banco do Brasil

### ISSUE THREAD

**Issue by ilson-nobrega** [eduardokum/laravel-boleto#355]
![protesto](https://user-images.githubusercontent.com/7192737/42062058-b565ebfa-7b02-11e8-921d-4f8ef052c162.jpeg)

Eu seto false para o número de dias de protesto, e ele fica 00 no arquivo de remessa. Ok, até aí tudo bem.
O problema é ao validar no Banco do Brasil, o mesmo diz que o número de dias precisa ser especificado.
Lendo algumas issues vi que foi falado sobre baixa automática. Só consigo anular o protesto se determinar uma data para baixa automática?

Apenas uma dúvida mesmo.

Obrigado.

**Comment by eduardokum** [comment]
Opa, 240 ou 400?

**Comment by ilson-nobrega** [comment]
400. Só que tem uma curiosidade. Mesmo com o erro no validador, mandei pro banco o arquivo de remessa. O boleto foi pago, caiu na conta normalmente kkkk
Agora to com medo de estar protestando automaticamente.

**Comment by eduardokum** [comment]
No site do banco você consegue ver quais instruções ele acatou. mesmo pq só aceita valores específicos

![image](https://user-images.githubusercontent.com/2566340/42632815-d75afe64-85b4-11e8-9cc5-4e7a63f1cc2b.png)

**Comment by eduardokum** [comment]
Acredito que isso seja so um warning e nao um erro
