### ISSUE TITLE
DÚVIDA - Erro ao validar remessa CNAB240 CEF

### ISSUE THREAD

**Issue by olimarferraz** [eduardokum/laravel-boleto#356]
Alguém sabe me dizer se o validador de remessa CNAB240 da CAIXA se mantém atualizado em relação ao que eles exigem. Validando uma remessa eu me deparei com alguns erros e discrepâncias em relação a documentação e ao relatório do validador, porém 1 campo apresenta erro mesmo se comparado aos dois guias:

**Header de Lote**

**Validador:** Uso Exclusivo CAIXA | Posição 40 - 53 | Esperado 0000000000000 | Encontrado ""
**Documentação:** 11.1 | Uso Exclusivo CAIXA | 40 | 53 | 9(014) | Preencher com zeros.

PS: Vou enviar o arquivo para homologação na semana que vem e retorno com o feedback, mas se até lá alguém puder contribuir agradeço.

**Comment by eduardokum** [comment]
Vou alterar, Obrigado.
