### ISSUE TITLE
Erro Caractere "º" no arquivo de remessa

### ISSUE THREAD

**Issue by wallysonn** [eduardokum/laravel-boleto#358]
Em um arquivo remessa do banco itaú, em um endereço continha "**...08 APT 201, Nº 201...**", sendo que esse caractere ficou errado na remessa.
Segue link no dropbox para visualização: [https://www.dropbox.com/s/dwpp152cr76fr89/print%20erro.png?dl=0](https://www.dropbox.com/s/dwpp152cr76fr89/print%20erro.png?dl=0)

**Comment by wallysonn** [comment]
**nº201** -> correção, está digitado assim, sem espaço!

**Comment by wallysonn** [comment]
Vou deixar aberto para o administrador do projeto avaliar ou postar uma solução adequada, mas resolvi o problema removendo esses caracteres dentro da função **normalizeChars**, inluindo **'º' => '', 'ª' => ''**

**Comment by eduardokum** [comment]
Blza, vou atualizar no repositorio obrigado.
