### ISSUE TITLE
Homologação CNAB 240 Santander

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#359]
Durante a homologação do CNAB 240 do Santander foram encontrados diversas divergências no código implementando. Sendo assim, fiz todas as alterações e consegui homologar junto ao Santander.

Irei fazer um PR com as alterações e os novos manuais (Abrail / 2018).

**Comment by guicouto** [comment]
Adicionado #360

**Comment by eduardokum** [comment]
Fiz o merge ja obrigado.
