### ISSUE TITLE
Homologação

### ISSUE THREAD

**Issue by mprandot** [eduardokum/laravel-boleto#36]
Todos os boletos implementados já passaram por homologação junto aos bancos?

**Comment by eduardokum** [comment]
Sim, alguns a mais tempo que outros, sendo assim pode ter mudado alguma documentação e ainda poder ocorrer erros na homologação.

**Comment by mprandot** [comment]
@eduardokum, estou baixando o pacote mas o banco sicredi não está sendo baixado, tu não precisa atualizar alguma coisa no packagist talvez?

**Comment by eduardokum** [comment]
Utilize o dev-master, ainda não validei 100% o retorno, so validei pelos testes que eu mesmo gero o retorno fake, estou aguardando um retorno real para validar 100% e liberar o release novo
