### ISSUE TITLE
Erro retorno CNAB240 Bancoob e remessa CNAB240 BB

### ISSUE THREAD

**Issue by karlasantos** [eduardokum/laravel-boleto#361]
- O processamento do retorno do CNAB240 do Bancoob esta retornando o número da parcela, a modalidade e o tipo do formulário juntamente com o nosso número.
- O código do desconto da remessa do CNAB240 do BB está indo como 1 mesmo se não houver desconto e ocorreu erro na validação:
![screenshot from 2018-07-12 09-00-37](https://user-images.githubusercontent.com/15219598/42632457-9d864442-85b3-11e8-9972-88d22f87f94a.png)

Segue o PR corrigindo esses campos #357

**Comment by eduardokum** [comment]
Fiz o merge ja, obirgado.
