### ISSUE TITLE
Erro protesto e total de registros do lote da remessa com CNAB240 do BB

### ISSUE THREAD

**Issue by karlasantos** [eduardokum/laravel-boleto#363]
- Quando não houver protesto no boleto deve ser informado o valor 3 para o código do protesto.
- E o número de registro do lote não pode ser igual ao número de registros do arquivo.
![screenshot from 2018-07-12 10-19-49](https://user-images.githubusercontent.com/15219598/42635790-618ae682-85bd-11e8-89cc-d43e8fbdfd82.png)

**Comment by eduardokum** [comment]
#merged
