### ISSUE TITLE
Necessário mandar código 06 nas colunas 16-17 remessa bancoob (alteração data venc)

### ISSUE THREAD

**Issue by fabritha** [eduardokum/laravel-boleto#366]
Olá, havia enviado um pull request com melhorias para poder enviar o código 06 (alteração de data de vencimento para o banco sicoob) porem foi rejeitado, todos os outros bancos também possui o código 06, então gostaria de saber o impacto dessa mudança para não ser aceito.

Att. Thays

**Comment by eduardokum** [comment]
Respondi na PR

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
