### ISSUE TITLE
SICOOB/BANCOOB CNAB 400 Dígito NOSSO NUMERO Inválido 

### ISSUE THREAD

**Issue by duard** [eduardokum/laravel-boleto#367]
Pessoal, minha cliente foi enviar uma remessa hoje para o SICOOB, no envio tudo ocorreu corretamente, porém quando foi puxar o retorno, encontrou relatório de inconsistências dizendo que o problema é o dígito do nosso número ... este dígito é gerado pelo projeto, correto ?

![digito errado](https://user-images.githubusercontent.com/36894/42902950-a9b58078-8aa6-11e8-9677-78a6e1ffe722.PNG)

Obrigado.

**Comment by diorgesl** [comment]
Nosso número, geralmente é o código interno do seu sistema, que pode ser o ID do boleto por exemplo.

**Comment by duard** [comment]
@diorgesl  sim jovem, porém tem um dígito que é gerado pelo laravel-boleto e que está dando inválido na validação do banco SICOOB/BANCOOB

**Comment by eduardokum** [comment]
240 ou 400? Você esta passando todas as informações para o boleto? numero, agencia, convenio? ele usa todas essas infos para gerar o NN se alguma delas estiver errada ou em branco vai gerar codigo errado

**Comment by duard** [comment]
@eduardokum acredito que tenha passado todos os dados. Com o mesmo código, eu estava gerando no Bradesco e até agora está ok. 

`

  $beneficiario = new \Eduardokum\LaravelBoleto\Pessoa(
      [
          'nome'        =>    $result->header->beneficiario,
          'documento'   =>    $result->contas[0]->cnpj_beneficiario,
          'agencia'     =>    $resut->header->agencia,
      ]
  );

  $remessa = new \Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bancoob(
      [
          'agencia'       =>    $result->header->agencia,
          'conta'         =>    $result->contas[0]->conta_corrente,
          'carteira'      =>    $result->header->carteira_banco,
          'convenio'      =>    $result->header->codigo_beneficiario.$result->header->codigo_beneficiario_dv,
          'idRemessa'     =>    $result->header->numero_sequencial_arquivo,
          'beneficiario'  =>    $beneficiario
      ]
  );

  for ($i = 0; $i < count($result->contas); $i++) {
    $conta = $result->contas[$i];

    $pagador = new \Eduardokum\LaravelBoleto\Pessoa(
        [
            'nome'      => $conta->nome_pagador,
            'endereco'  => $conta->endereco_pagador,
            'bairro'    => $conta->bairro_pagador,
            'cep'       => $conta->cep_pagador,
            'uf'        => $conta->uf_pagador,
            'cidade'    => $conta->cidade_pagador,
            'documento' => $conta->cnpj_pagador,
        ]
    );
    $boleto = new Eduardokum\LaravelBoleto\Boleto\Banco\Bancoob(
        [
            'dataVencimento'         => new \Carbon\Carbon($conta->data_vencimento),
            'valor'                  => $conta->valor_titulo,
            'multa'                  => $conta->taxa_multa,
            'juros'                  => $conta->taxa_juros,
            'numero'                 => $conta->nosso_numero,
            'numeroDocumento'        => $conta->numero_empresa,
            'pagador'                => $pagador,
            'beneficiario'           => $beneficiario,
            'carteira'               => $conta->carteira_modalidade,
            'agencia'                => $conta->agencia,
            'conta'                  => $conta->conta_corrente.$conta->conta_corrente_dv,
            'convenio'               => $conta->convenio
        ]
    );

    $remessa->addBoleto($boleto);
  }

`

**Comment by eduardokum** [comment]
esse 
'agencia'       =>    $result->header->agencia,
tem o mesmo valor de
'agencia'                => $conta->agencia,


e 

'convenio'      =>    $result->header->codigo_beneficiario.$result->header->codigo_beneficiario_dv,
tem o mesmo valor de
'convenio'               => $conta->convenio


??

**Comment by duard** [comment]
```
 "header": {
    "numero_sequencial_arquivo": "45",
    "codigo_beneficiario_dv": "0",
    "tipo_servico": "01",
    "identificacao_banco": "756BANCOOBCED",
    "numero_convenio": "",
    "tipo_operacao": "1",
    "tipo_servico_desc": "COBRANCA",
    "data_gravacao": "2018-07-19",
    "carteira_banco": "1",
    "cnpj": "null",
    "agencia_dv": "0",
    "beneficiario": "Goiabadas Azedinhas",
    "agencia": "3178",
    "codigo_beneficiario": "11667",
    "tipo_operacao_desc": "REMESSA",
    "sequencial_remessa": "01",
    "identificacao_registro": "0"
  }

```
esta mesma agencia vai para o detalhe, e sobre o convenio
Número do Convênio de Cobrança do Beneficiário: "000000" segundo o manual do banco

`1028888888000012231780000035507000000                         0000183486620100       0000000000000000    2010134866     10081800000000954007563178002019071800000033000200002000000000000000000090000000000000000000000000091989792000160GOIABADA E CIA LTDA                     RUA GOIABADA TRISTE , 10              CENTRO      38800000SAO GOIABADA    RJ                                        00 000003`

**Comment by eduardokum** [comment]
Esse convênio você tem que passar o mesmo que passa na remessa pro boleto, pq usa convênio número do boleto e agência pra calcular o DV do NN, veja se você está passando tudo isso certo
Em 19 de jul de 2018 16:03 -0300, Carlos Eduardo <notifications@github.com> escreveu:

**Comment by duard** [comment]
@eduardokum  , não entendi o que você disse.

1 - eu estou gerando REMESSA
2 - esta conta aqui na empresa, não possui número convênio.

**Comment by duard** [comment]
Eduardo, tem um contato (skype, twitter, gmail, etc) para eu poder te mostrar os dados ? 
Estranho demais isto.

**Comment by eduardokum** [comment]
Então é esse o problema, você está passando um código de convênio no objeto do boleto enquanto na remessa você está passando 000000 se não tem convênio você tem que passar o 000000 no objeto do boleto pois ele usa isso para gerar o nosso número. Pode mandar email nesse que tem no meu perfil do GitHub se precisar 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by duard** [comment]
Bom, se entendi bem, o que você está dizendo é para eu passar ZEROS fixos no campo convenio do objeto "boleto", certo ? 

```
          $boleto = new Eduardokum\LaravelBoleto\Boleto\Banco\Bancoob(
              [
                'dataVencimento'         => new \Carbon\Carbon($conta->data_vencimento),
                'valor'                  => $conta->valor_titulo,
                'multa'                  => $conta->taxa_multa,
                'juros'                  => $conta->taxa_juros,
                'numero'                 => $conta->nosso_numero,
                'numeroDocumento'        => $conta->numero_empresa,
                'pagador'                => $pagador,
                'beneficiario'           => $beneficiario,
                'carteira'               => $conta->carteira_modalidade,
                'agencia'                => $result->header->agencia,
                'conta'                  => $conta->conta_corrente.$conta->conta_corrente_dv,
                'convenio'               => '000000'
              ]
          );
```
Vou gerar aqui e enviar para o banco validar.

**Comment by eduardokum** [comment]
Isso, voce disse que a conta do cliente nao tem convenio, se nao tem convenio, voce tem que passar zerado tanto na remessa quanto no boleto, pois como disse antes o bancoob utiliza esse campo pra gerar o DV do NN.

**Comment by duard** [comment]
@eduardokum , eu e a moça aqui geramos e até agora, pelo menos, não veio o maldito relatório de inconsistências 👍

**Comment by eduardokum** [comment]
Blza.
