### ISSUE TITLE
[DUVIDA] Alterar valor nominal do título Santander CNAB 400

### ISSUE THREAD

**Issue by tortato** [eduardokum/laravel-boleto#369]
Conversando com a equipe de suporte do banco Santander me repassaram que passando a instrução 47 na posição 109 e 110 é possível modificar o valor nominal de um título (documentação nova) e passando a instrução 98 eu posso cancelar o protesto antes de iniciar o ciclo do protesto. Tem alguma maneira de realizar essas instruções? Eu dei uma olhada na remessa e o unico parametro de alteração é apenas data de vencimento.

**Comment by eduardokum** [comment]
Opa, blza, ainda não tem, pretendo fazer uma opção no boleto para comandar instruções custom, diferente de baixar e alterar. tem alguma outra ideia?

**Comment by tortato** [comment]
Bom, teria q mudar desde da interface do boleto até a remessa, seria mta mão de obra, o que eu fiz foi apenas setar novos status e verificá-los na geração da remessa 400 (Solução clips, cola e barbante), mas funciona... O ruim é que o pacote ficaria meio zoado com esse tipo de solução.

Boleto/Banco/Santander.php
![image](https://user-images.githubusercontent.com/2292334/42948790-a62178cc-8b46-11e8-8910-ab4696a38732.png)

Cnab/Remessa/Cnab400/Banco/Santander.php
![image](https://user-images.githubusercontent.com/2292334/42948926-f0d2c498-8b46-11e8-886c-9b733e41a18e.png)
![image](https://user-images.githubusercontent.com/2292334/42948851-c626aafc-8b46-11e8-8aa9-81f9478e7f5e.png)

**Comment by tortato** [comment]
Pensando agora, o ideal é passar um parametro no método alterar para saber qual tipo de alteração vai ser feita. Acho q essa seria uma solução mais plausível, o problema é q eu não tenho conhecimento dos outros bancos se tem mais tipos de alterações suportados.

**Comment by eduardokum** [comment]
é isso mesmo, esses status podem ser outros código em outros bancos

**Comment by tortato** [comment]
Por fim, eu vou trabalhar em uma solução paleativa para o Santander e dar um pull request, se vc achar q vale a pena ou q tem considerações, me avise, enquanto eu estudo os demais bancos para fazer uma solução completa.

**Comment by eduardokum** [comment]
Mandei uma atualização para que de pra enviar um comando especifico.  03f9429348f530104d2c08005c3129e0b8f887f4
