### ISSUE TITLE
Parse error: syntax error, unexpected '?'  ja tiveram esse erro ?

### ISSUE THREAD

**Issue by alexsmonte** [eduardokum/laravel-boleto#371]
Vocês já tiram esse erro? 

Rodei no servidor de produção e deu isso

Parse error: syntax error, unexpected '?' in /home/aboaracatuba/www/boleto/vendor/illuminate/support/Str.php on line 681

![captura de tela de 2018-07-19 13-05-35](https://user-images.githubusercontent.com/1400348/42958746-7b15e89e-8b54-11e8-8f7f-1048eb82f891.png)

**Comment by eduardokum** [comment]
Esse erro é na classe do de suporte do proprio laravel, provavelmente, referente a versão do seu php. Tente no 7.0 que esse erro provavelmente sumirá
