### ISSUE TITLE
BB CNAB 240 convênio de 7 dígitos - Erro Validação

### ISSUE THREAD

**Issue by Fertusco** [eduardokum/laravel-boleto#372]
Bom dia.

Estou com alguns problemas na validação do CNAB 240 para o BB com convênio de 7 dígitos (carteira 17 variação 19).

- O nosso número está sendo gerado com número excessivo de caracteres, acima dos 17 permitidos. 
- Apresentando erros com a parte de desconto, porém o desconto está setado como zero.

Segue abaixo a preview com o erros de validação. Poderiam me ajudar?

![captura de tela 2018-07-21 as 12 37 49](https://user-images.githubusercontent.com/9468100/43037519-4f87d156-8ce4-11e8-9ca0-2d6bf240415c.png)

**Comment by eduardokum** [comment]
Bom dia, fiz testes aqui no meu local e aparentemente esta colocando os espaços no fim e nao no inicio do NN.

Qual versão você esta usando?

tente atualizar seu pacote.

**Comment by Fertusco** [comment]
@eduardokum boa tarde.

Reparei que a dev-develop está sobrescrevendo as funções da dev-master que estavam causando os problemas reportados. Atualizei para a develop e os problemas foram resolvidos.

Vi também que o CNAB está sendo gerado sem a linha R, com as informações de multa.

Vou fazer a implementação desta linha, caso ache pertinente, posto depois.

Obrigado pela ajuda!
