### ISSUE TITLE
Dúvida para gerar o arquivo de remessa!

### ISSUE THREAD

**Issue by ebertbueno** [eduardokum/laravel-boleto#374]
Boa noite.

Estou usando sua biblioteca de boletos do laravel, e estou com uma dúvida.
Qual a ordem para incluir os boletos no arquivo de remessa para ser gerado? Eu sou meio leigo nessa parte, e não entendi isso muito bem, poderia me dar uma ajuda? Vlw

**Comment by eduardokum** [comment]
Olá,

Você cria o objeto da remessa 
https://laravel-boleto.readthedocs.io/en/latest/usage/remessa/itau.html

e depois adiciona os boletos
https://laravel-boleto.readthedocs.io/en/latest/usage/remessa/index.html?highlight=addBoleto
