### ISSUE TITLE
Processo para gerar boleto registrado BB

### ISSUE THREAD

**Issue by jn18** [eduardokum/laravel-boleto#378]
Olá, estou querendo criar um sistema que gere boletos do banco do brasil, mas nunca trabalhei com boletos e estou meio perdido, alguém poderia me ajudar com o passo a passo para gerar o boleto registrado do BB?

**Comment by MagnumCortez** [comment]
Olá Man! Tudo blz, eu estou gerando boleto da Caixa Economica Federal, tive que mudar algumas coisas no layout do boleto e na remessa para aprovação da mesma. Os que estão aqui estão um pouco desatualizados. Mas enfim qual a dificuldade em si, vc olhou os exemplos?

**Comment by jn18** [comment]
Estava com dificuldade porque não sabia o que precisava fazer, mas entre o telegram e lá me explicaram que eu tenho que ir no banco,  que depois eu tenho que enviar a remessa para o sistema do banco, obter o retorno e validar o retorno.

De qualquer forma, obrigado pela atenção!
