### ISSUE TITLE
Problema no Documento do Pagador - Remessa cef

### ISSUE THREAD

**Issue by georgecpacheco** [eduardokum/laravel-boleto#380]
Estou tendo problema com a remessa da Caixa, no lugar do CNPJ do pagador, ta indo o CNPJ do beneficiario, verifiquei no manual de Junho e realmente esta errado no código. Já sugeri um PullRequest.
E também esta dando erro na quantidade de registro no lote, esse eu não consegui achar onde esta o erro. Se alguem puder me ajudar, agradeço.
Abraço!

**Comment by eduardokum** [comment]
Blza, manda aquele PR em develop la, que ja aceito.
