### ISSUE TITLE
Carteira 18 do BB

### ISSUE THREAD

**Issue by alexsmonte** [eduardokum/laravel-boleto#382]
Estava tentando gerar uma remessa para a carteira 18 do BB, na documentacao diz que tem carteira 18, mas na remessa 

Gerar remessa dentro do arquivo Bb.php tnato 240 como 400
protected $carteiras = ['11', '12', '17', '31', '51'];

![captura de tela de 2018-08-09 15-22-47](https://user-images.githubusercontent.com/1400348/43920942-56e77c40-9be8-11e8-96d9-ed58ce5485bf.png)

erro

> Fatal error: Uncaught exception 'Exception' with message 'Carteira não disponível!' in /home/aboaracatuba/www/CLINSOFT/vendor/eduardokum/laravel-boleto/src/Cnab/Remessa/AbstractRemessa.php:331 Stack trace: #0 /home/aboaracatuba/www/CLINSOFT/vendor/eduardokum/laravel-boleto/src/Util.php(914): Eduardokum\LaravelBoleto\Cnab\Remessa\AbstractRemessa->setCarteira('18') #1 /home/aboaracatuba/www/CLINSOFT/vendor/eduardokum/laravel-boleto/src/Cnab/Remessa/AbstractRemessa.php(140): Eduardokum\LaravelBoleto\Util::fillClass(Object(Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bb), Array) #2 /home/aboaracatuba/www/CLINSOFT/vendor/eduardokum/laravel-boleto/src/Cnab/Remessa/Cnab400/Banco/Bb.php(74): Eduardokum\LaravelBoleto\Cnab\Remessa\AbstractRemessa->__construct(Array) #3 [internal function]: Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bb->__construct(Array) #4 /home/aboaracatuba/www/CLINSOFT/include/boletos/gerar-remessa.php(43): ReflectionClass->newInstance(Array) #5 {main} thrown in /home/aboaracatuba/www/CLINSOFT/vendor/eduardokum/laravel-boleto/src/Cnab/Remessa/AbstractRemessa.php on line 331

**Comment by eduardokum** [comment]
Tem no branch develop, vou criar uma tag e vai funcionar
