### ISSUE TITLE
Erro em varias remessas em um unico arquivo (Itau cnab400)

### ISSUE THREAD

**Issue by marcosasribeiro** [eduardokum/laravel-boleto#385]
Estou tendo um problemas para gerar várias remessas do **itau cnab400** em um mesmo arquivo, eu consigo gerar normalmente um arquivo de remessa válido, porem só consigo gerar um arquivo válido se tiver apenas um registro de boleto, quando coloco pro PHP dar um looping usando o FOR pra ir pegando dados de varios clientes e adicionar no mesmo arquivo de remessa e validar o layout, o banco recusa com algumas mensagens de erro.

**Mensagens de Erro:**

![error-remessa-itau](https://user-images.githubusercontent.com/8452305/44063898-f4b0ec06-9f38-11e8-9ea2-36bf7ec3a937.png)

**Arquivo que gerei dando looping e o banco recusou**:

![arquivo-com-2-remessas](https://user-images.githubusercontent.com/8452305/44064095-c3558a3a-9f39-11e8-9219-58f17c2f1866.png)

Por que quando tento colocar mais de uma remessa no mesmo arquivo o banco recusa? Alguém poderia me dar uma ajuda com isso? Agraço quem puder me dar um help nisso, vlw.

**Comment by eduardokum** [comment]
arquivo de remessa do deve ter 1 header e um trailer no caso de 400 posições, se quiser adicionar mais de um boleto somente adicione mais de um boleto na mesma remessa. Se quiser mais de uma remessa, tem que ser em arquivos separados.
