### ISSUE TITLE
queues

### ISSUE THREAD

**Issue by GlauberF** [eduardokum/laravel-boleto#386]
Existe algum tratamento para "queues", ou seja um controle de fila a ser processado, para não sobrecarregando o serviço ?

**Comment by eduardokum** [comment]
Não, isso é so uma library não, consome nenhum serviço, so faz a geração de arquivos. Você tem que controlar isso na sua aplicação.

**Comment by GlauberF** [comment]
Perfeito @eduardokum , outra dúvida meio que fora de contexto, com o pacote hoje já consigo gerar boletos registrados etc.. ?
