### ISSUE TITLE
DV Código Beneficiário CEF Incorreto

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#393]
Estou homologando boletos na CEF, porém a homologação está parada, pois o DV do beneficiário está calculando incorreto.

**Código do Beneficiário:** 912419
**Cálculo:** (9 * 7) + (1 * 6) + (2 * 5) + (4 * 4) + (1 * 3) + (9 * 2) = 116
**Mod 11:** 116 % 11 = 6
**DV:** 11 - 6 = 5

Porém a classe está gerando o código 4 no DV.
Como faço essa correção na CEF, sem afetar os outros bancos?

**Comment by guicouto** [comment]
![captura de tela 2018-09-01 as 12 25 39](https://user-images.githubusercontent.com/8810377/44947346-3e0c2e80-ade2-11e8-8808-6dea397eb6f6.png)
Estranho, que ao executar o teste, utilizando a mesma função da classe, externamente, o resultado está correto.

**Comment by guicouto** [comment]
Correção efetuada em #394

**Comment by eduardokum** [comment]
opa, atualiza seu branch develop e manda o PR em develop, esta dando conflito.

**Comment by guicouto** [comment]
Excelente @eduardokum. Enviei um novo PR #395. Veja se não irá conflitar, por favor.

**Comment by eduardokum** [comment]
#395 merged.

Obrigado
