### ISSUE TITLE
Valor Recebido - Retorno Banco do Brasil - CNAB 240

### ISSUE THREAD

**Issue by guicouto** [eduardokum/laravel-boleto#396]
Bom dia,
o valor recebido no retorno do Banco do Brasil CNAB 240, está sendo "setado" duas vezes nas linhas 362 e 363 (conforme print anexo). Dessa forma, o sistema está pegando no valor recebido, o valor preenchido nas posições 93 até 107 (que é o valor pago pelo cliente menos a tarifa bancária).

![captura de tela 2018-09-10 as 10 57 50](https://user-images.githubusercontent.com/8810377/45302066-c1b3d280-b4e8-11e8-946d-c2ba62f00594.png)

O correto seria realmente o primeiro setValorRecebido (Linha 362).
Talvez o ideal fosse ter mais um atributo, tipo (setValorRecebidoAbatidoTarifa (só uma sugestão rsrs)).

**Comment by eduardokum** [comment]
Bom dia, ja tem um campo setValorTarifa, acho melhor fazer o valor total - valor recebido que fica so a tarifa, pois teria que ver se todos os bancos retornam esse valor igual pra so assim poder criar um campo diferente, entende?

**Comment by eduardokum** [comment]
algo assim

```
->setValorTarifa($d->getValorRecebido() - Util::nFloat($this->rem(93, 107, $detalhe)/100, 2, false))
```

**Comment by eduardokum** [comment]
#395 merged

Obrigado

**Comment by guicouto** [comment]
Certo. Vou ler a documentação de todos os bancos (CNAB240) e identificar onde fica a informação de tarifa no retorno. Assim que estiver disponível envio um PR para análise.

**Comment by eduardokum** [comment]
Olhei nos manuais todos é igual esses campos 78-92 93-107

então fiz o seguinte 0ce091d23b8b2112f98428a2fc2e8f26da98897d

**Comment by guicouto** [comment]
Ficou excelente, vou fazer um merge no meu fork e testar também.
