### ISSUE TITLE
Carteira - SICREDI - Boleto gerado 1 - Remessa 1 - Error: Disponível apenas A

### ISSUE THREAD

**Issue by globsecure** [eduardokum/laravel-boleto#399]
Senhores,

Estou fazendo alguns testes com a remessa para Sicredi, porém existe ao emitir a carteira com a opção 1 o boleto é gerado. Já quando chega a hora de gerar a remessa com a mesma carteira, temos um problema avisando que não está disponível, olhando aqui no código está limitado para 'A'.

**Comment by eduardokum** [comment]
Se voce usar o __construct para gerar a remessa ele vai definir A como padrao, a menos que voce colocar o setCarteira(1) ele vai mudar pra 1, vou arrumar o setCarteira pra nao sobrescrever tbm mais por enquanto pode usar o new Sicredi([params]) que vai ficar a carteira A
