### ISSUE TITLE
Santander Remessa CNAB 240 - Ajustes na regra de juros(mora) - Homologação

### ISSUE THREAD

**Issue by tortato** [eduardokum/laravel-boleto#400]
Enviei o arquivo de remessa para homologação no banco Santander e o analista me retornou o seguinte erro:
A cobrança de juros (mora) foi informado o código 2 que é em % neste caso deve seguir a regra da nota 18 (utilização de 5 casas decimeis)
Nota 18: CAMPOS REFERENTES A VALOR
. Quando o valor for expresso em moeda corrente, utilizar duas casas decimais: 9(013)v99;
. Quando o valor for expresso em moeda variável, utilizar cinco casas decimais: 9(010)v9(05);
. Quando o valor se referir à taxa de juros, utilizar cinco casas decimais: 9(010)v9(05);

**Comment by tortato** [comment]
Acredito que no 400 deve ter o mesmo erro.

**Comment by guicouto** [comment]
Boa tarde @tortato fiz a homologação com eles recentemente e não tive esse problema. Consegue postar para nós seu arquivo de remessa?

**Comment by tortato** [comment]
[1537472329_SVV_SANTANDER_240_101_0921_130010140_436810.txt](https://github.com/eduardokum/laravel-boleto/files/2402929/1537472329_SVV_SANTANDER_240_101_0921_130010140_436810.txt)

**Comment by eduardokum** [comment]
Tem o manual atualizado deles pra enviar?

**Comment by tortato** [comment]
O manual é o mesmo que tem aqui nos repositórios.

**Comment by eduardokum** [comment]
Fiz esse commit em develop c5859d829af9c5cdb1d02b559b7bc8dd68eb0f47 veja se resolve seu problema
