### ISSUE TITLE
Como verificar se o retorno é uma pré critica?

### ISSUE THREAD

**Issue by jovemnf** [eduardokum/laravel-boleto#401]
Quando mando a factory processar ele me retorna uma Exception caso o arquivo seja uma pré critica e não um retorno de verdade.

**Comment by eduardokum** [comment]
Bom dia, a classe só lê retorno, não lê pre critica, na verdade eu nem sei o que é pre crítica nunca houve ninguém que tivesse essa necessidade

**Comment by jovemnf** [comment]
A pré crítica é um retorno da Caixa, que é a confirmação do envio da remessa. Vem junto aos retornos.

**Comment by eduardokum** [comment]
tem algum exemplo?

**Comment by jovemnf** [comment]
Segue o arquivo
[8377GCB_MZ_BBQ2_PRECRI_A8K6L4_D180919_H111041_NT0373099567.ret.txt](https://github.com/eduardokum/laravel-boleto/files/2405593/8377GCB_MZ_BBQ2_PRECRI_A8K6L4_D180919_H111041_NT0373099567.ret.txt)

**Comment by eduardokum** [comment]
O layout é diferente mesmo, teria que chamar na factory somente retorno mesmo.
