### ISSUE TITLE
ERRO Remessa Cnab240 CAIXA

### ISSUE THREAD

**Issue by wallysonn** [eduardokum/laravel-boleto#402]
Envie uma remessa **cnab240** para homologação e o banco apontou os seguintes problemas:

- No seguimento P, a posição 221 tem que tá marcado com 1 para protesto, ou 3 para não protestar.
- A posição 224 tem que tá marcado com 1 para baixar/devolver ou 2 para não baixar/devolver.

**Como eu resolvi o problema:**
_no arquivo Cnab240/Banco/Caixa.php_
Modifiquei: 
`$this->add(221, 221, self::PROTESTO_SEM) para $this->add(221, 221, self::PROTESTO_NAO_PROTESTAR)`
```
Acrescentei após $this->add(224, 224, '2');
if ($boleto->getDiasBaixaAutomatica() > 0){
$this->add(224, 224, '1');
}
```
Veja o que diz a documentação da CAIXA sobre os erros apontados:
Código para Protesto 
Código adotado pela FEBRABAN para identificar o tipo de prazo a ser considerado para o protesto. 
‘1’ = Protestar 
‘3’ = Não Protestar 
‘9’ = Cancelamento Protesto Automático (Somente válido p/ Código Movimento Remessa = ‘31’ - Alteração de Outros Dados), vide nota C004.
Caso o CEP do Pagador não esteja vinculado a uma agência cobradora de protesto (CEP sem praça de cobrança), o título será registrado com instrução de devolução, sendo o Prazo de Devolução igual ao Prazo de Protesto, com prazo mínimo de 5 dias. 
Se Código para Protesto = ‘1’ – Protestar e Código para Baixa / Devolução = ‘1’ – Baixar / Devolver, será acatada a instrução para protesto

Código para Baixa / Devolução 
Código adotado pela FEBRABAN para identificar qual o procedimento a ser adotado com o Título. 
‘1’ = Baixar / Devolver 
‘2’ = Não Baixar / Não Devolver 
O código 2 só será aceito se Código para Protesto for = 1. 
Se Código para Baixa / Devolução = ‘1’ – Baixar / Devolver e Código para Protesto = ‘1’ – Protestar, será acatada a instrução para protesto. 
C028

**Comment by eduardokum** [comment]
Essa mudança ja foi realizada em develop, logo subirei uma nova versão.

https://github.com/eduardokum/laravel-boleto/blob/develop/src/Cnab/Remessa/Cnab240/Banco/Caixa.php#L47

https://github.com/eduardokum/laravel-boleto/blob/develop/src/Cnab/Remessa/Cnab240/Banco/Caixa.php#L175
