### ISSUE TITLE
DÚVIDA - Valor Recebido Retorno 400 vs 240

### ISSUE THREAD

**Issue by wallysonn** [eduardokum/laravel-boleto#403]
Verifiquei que na importação de um retorno **Itaú cnab 400,** o **valorRecebido** vem por padrão subtraindo a taxa, sendo que o mesmo não ocorre por exemplo, em um arquivo retorno **caixa cnab 240**.

Agradeço o retorno caso seja um bug na api ou falha minha.

--- Exemplo:
Itaú CNAB 400: Valor Recebido 60,00, taxa 1,40, então o valor recebido deveria ser 61,40 (ao menos foi o valor que o cliente pagou).

**Comment by eduardokum** [comment]
Esse valor é o que o banco informa na retorno, acontece que o layout de 400 posições esta descontinuado e eles não estão mexendo mais nele, o 240 as vezes tem mudanças, novos manuais, e informações, no 240 vem muito mais valores para ter no retorno. Isso é um característica do próprio layout
