### ISSUE TITLE
Juros e multa informados como valor em Real ao invés de porcentagem

### ISSUE THREAD

**Issue by carloshc** [eduardokum/laravel-boleto#415]
Oi, pessoal.

Na aplicação a qual estamos desenvolvendo, o usuário pode informar o percentual do juros e da multa ou valor em Real. Alguns gerentes já nos informaram que é preferível utilizar o valor em Real porque, além de facilitar o trabalho do caixa, por exemplo, evita problemas de arredondamento.

Hoje, o laravel-boleto só suporta a funcionalidade de informar o percentual do juro e da multa. 

Isso se reflete também (e principalmente) no arquivo de remessa. No caso do Itaú (CNAB400), por exemplo, é pedido o valor dos juros (e não percentual). No caso do detalhe da multa, existem as duas opções.

Daí vem a pergunta: faz sentido incluir essa opção no boleto? Mais alguém nota essa necessidade?

Obrigado.

**Comment by guicouto** [comment]
Boa tarde Carlos,
Faz sentido sim.

Na verdade uma vez até tinha aberto uma issue de sugestão de implementar variáveis para essas particularidades (https://github.com/eduardokum/laravel-boleto/issues/317).
Porém devido a falta de tempo, acabei abandonando a ideia e implementei o sistema com base na classe.

Acredito que algo mais ou menos assim, ficaria interessante:

$boleto->setTipoJuros(‘percentual’);
$boleto->setTipoDenconto(‘fixo’);

Por padrão assumiria um valor específico, caso não seja setado.

Acredito que isso facilitaria bastante para os desenvolvedores. Porém todas as classe do Cnab devem ser refatoradas, o que dá um certo trabalho.
