### ISSUE TITLE
Detalhes de Retornos com Ocorrências de Alteração

### ISSUE THREAD

**Issue by karlasantos** [eduardokum/laravel-boleto#418]
Notei que em algumas classes do retorno, no processamento do detalhe, os códigos de ocorrências de alteração de vencimento são mapeados como _OCORRENCIA_OUTROS_ e em outras são mapeados como _OCORRENCIA_ALTERACAO_. Comecei a padronizar todos eles para _OCORRENCIA_ALTERACAO_, teria algum motivo para essas diferenças ou eu posso enviar um PR padronizando?

**Comment by eduardokum** [comment]
Acredito que em documentações antigas não tinha essa opção de vencimento, alguns bancos não tinha ocorrência especifica para alterar vencimento, fui arrumando os que ia vendo na documentação quando tinha a opção, se tiver na documentação a ocorrência correta, pode mandar o PR.

Obrigado
