### ISSUE TITLE
Prazo para baixa/devolução

### ISSUE THREAD

**Issue by ricardotomim** [eduardokum/laravel-boleto#42]
Parabéns pelo projeto.

Existe alguma opção para informar o prazo (em dias) para baixa/devolução do boleto ?

**Comment by edigomes** [comment]
Também estou com duvidas e relação a outras instruções, o campo 'instrucoes' do array só imprime no boleto, mas não coloca as instruções na remessa, existe algum tipo de 'instrucoesRemessa'?

**Comment by eduardokum** [comment]
Pedido de baixa acho o padrão pelo que vi nos manuais é baixar quando você enviar o boleto com ocorrência de baixa setando o boleto para baixar ($boleto->baixarBoleto()) 

As instruções são somente algumas disponíveis, juros protesto multa, hoje o projeto não tem suporte a todas, já que tenta agregar o maior numero de bancos e nem todos possuem as mesmas instruções. 

Se você tiver alguma ideia para resolver o problema sera bem vinda...

**Comment by ricardotomim** [comment]
Bem, eu passei para homologação o arq de remessa e alguns boletos em pdf, vamos ver o que acontece, rs.

No manual da caixa tem:

> 39.3P
> Prazo p/ Baixa/ Devolução
> Número de Dias para Baixa/ Devolução
> 225 227 X(003)
> Preencher com o número desejado de dias corridos após a data de vencimento do  título não pago em que a CAIXA deverá baixá-lo da carteira e devolvê-lo; pode ser de 05 a 120 dias corridos; ATENÇÃO: Esse prazo não pode ser menor que o prazo para protesto (campo 37.3P), quando este existir
> C029

**Comment by eduardokum** [comment]
Hmm entendi olhei em uns 3 manuais não achei nada, deve ser algo especifico da caixa, deve mudar o algumas coisas na linha pois hoje nessa posição vai o documento do cliente

$this->add(221, 234, Util::formatCnab('9L', $boleto->getPagador()->getDocumento(), 14));

**Comment by ricardotomim** [comment]
Passei o arquivo de remessa e os boletos e que me retornaram foi:

![ztwqt_1wj9pn1x2375zfyaw7evw8xja34a](https://cloud.githubusercontent.com/assets/5711325/20896158/8dc5b3c0-bb03-11e6-8094-a6ea65ccd23d.jpg)


Tem como gerar remessa em 240 ?


Á O ARQUIVO DE REMESSA ENVIADO ESTA INCORRETO. O ARQUIVO ENVIADO ESTÁ NO PADRÃO CNAB 400, PORÉM DE ACORDO COM MEUS REGISTROS, O SEU CONVENIO FOI CADASTRADO NA CAIXA COMO PADRÃO CNAB 240. EU RECOMENDO A UTILIZAÇÃO DESTE PADRÃO PORQUE ELE É MAIS COMPLETO E MODERNO.
 
O CNAB 400 É MAIS ANTIGO E BOSOLETO. SÓ UTILIZE ESTE PADRÃO SE O SEU SISTEMA PRÓPRIO "REALMENTE" NÃO TIVER OUTRA OPÇÃO. NESTE CASO VOCÊ DEVE SOLICITAR A ALTERÃÇÃO DE PADRÃO EM SUA AGENCIA, COM SEU GERENTE.

**Comment by eduardokum** [comment]
Somente o que tem suporte pra 240 é o do santander e não sei se esta funcional pois não utilizo, foi alguém que contribuiu.


Voce tem que passar essas informações para o boleto como no exemplo para renderizar no boleto.

```php
'instrucoes' =>  ['instrucao 1', 'instrucao 2', 'instrucao 3'],
```

**Comment by ricardotomim** [comment]
Vou gerar novos pdfs e passar para homologação com as instruções

Quanto a cnab, vou ver com meu gerente para ativar 400.

Depois dou retorno se passou,

Grato

**Comment by edigomes** [comment]
@ricardotomim Tenta fazer a instrução de devolver da caixa que eu faço a do itaú

**Comment by eduardokum** [comment]
@ricardotomim Tem certeza que fica nesse campo que voce mandou o prazo de baixa? 

Olhando aqui no meu manual esta diferente 

![image](https://cloud.githubusercontent.com/assets/2566340/20926143/17962a0a-bba2-11e6-954d-6ae8ae369357.png)

![image](https://cloud.githubusercontent.com/assets/2566340/20926189/3d1662ea-bba2-11e6-93eb-728faf4f72aa.png)

**Comment by ricardotomim** [comment]
Bom dia

Seguem os manuais passados pelo pessoal da homologação

[CNAB_240_SIGCB.pdf](https://github.com/eduardokum/laravel-boleto/files/633914/CNAB_240_SIGCB.pdf)
[ESP_COD_BARRAS_SIGCB_COBRANCA_CAIXA.pdf](https://github.com/eduardokum/laravel-boleto/files/633915/ESP_COD_BARRAS_SIGCB_COBRANCA_CAIXA.pdf)

**Comment by eduardokum** [comment]
Esses manuais são de 240 posições a classe de remessa implementada é de 400, o manual correto é esse https://github.com/eduardokum/laravel-boleto/blob/master/manuais/CEF/remessa_retorno.pdf

**Comment by ricardotomim** [comment]
Hum, não tinha me atentado para isso, rs

**Comment by eduardokum** [comment]
Rsrs, você precisa de 240? se for precisa implementar tudo, segue o exemplo do santander ele tem remessa de 240 porem não sei se esta funcional.

**Comment by ricardotomim** [comment]
Cara, pra falar a verdade não entendo nada de boleto/remessa, só estou mexendo com isso devido essa mudança obrigando uso de carteira registrada

Mas no manual do CNAB 400, tem o campo para informar os dias de devolução.

![prazodeve](https://cloud.githubusercontent.com/assets/5711325/20926824/91b31638-bba5-11e6-9590-0a07fa97792b.PNG)

**Comment by eduardokum** [comment]
Sim tem, nas posições 392 a 393 que hoje passa os dias do protesto, pelo que entendi você definindo protesto ele baixa sozinho, caso você queira que baixa sem protesto, hoje não tem nenhuma opção dessa, teria que adicionar isso no Boleto e teria que adicionar geral, ver como funciona em todos os bancos de suporte e pensar em uma maneira de fazer.

**Comment by ricardotomim** [comment]
Mas nesse caso o que define o que se é para protestar ou devolver não é o NE024 (posições 157,158) ?

**Comment by eduardokum** [comment]
Isso

const INSTRUCAO_PROTESTAR_VENC_XX = '01';
const INSTRUCAO_DEVOLVER_VENC_XX = '02';

No 157-158 teria que ir o 02 em vez do 01, mais do jeito que classe esta hoje isso não acontece em nenhuma ocasião

**Comment by ricardotomim** [comment]
Teria que ter algo como o diasBaixa né ?

Então do jeito que esta acho que não ira passar na homologação da caixa, mesmo solictando (no meu caso) para alterar meu convenio para usar cnab400

**Comment by eduardokum** [comment]
Depende, você é obrigado a solicitar essa baixa? o titulo não pode ficar em carteira? se eles te obrigarem a passar esse 02, mais acho que nao obrigam, mesmo porque o cliente pode usar configuração global de cobrança na conta, que o cnab so sobrescreve se passar algum valor, se passar 00 ele usa a default da carteira

**Comment by ricardotomim** [comment]
Bem vou gerar novamente os boletos em pdf (colocando a instrução de  "Não receber após x dias), gerar novamente o arquivo de remessa (considerando cnab400) e vamos ver o que retornam.

Depois dou "notícias", de qualquer forma muito obrigado pela ajuda.

**Comment by ricardotomim** [comment]
Só para registrar que não passou na homologação.

Se não informar o  "prazo (em dias) para baixa/devolução do boleto", não passa (mesmo sendo cnab400).

Obs: tbem teve outras pequenas questões

**Comment by eduardokum** [comment]
Entendi, deve ser alguma particularidade da carteira desse seu cliente, amanhã vou dar uma avaliada para tentar colocar esse campo de baixa automática nos bancos, pois já vi que nem todos implementam essa funcionalidade
