### ISSUE TITLE
Sicoob Demonstrativo e Instrução CNAB

### ISSUE THREAD

**Issue by EwerCarvalho** [eduardokum/laravel-boleto#420]
Pessoal eu gerei um cnab 240 sicoob para um cliente e o mesmo ao imprimir os boletos viu que estava sem a instrução para o cliente (isso dentro do banco sicoob) a pergunta é a seguinte, por ser cnab 240, a descrição de instrução não deveria ser passada dentro do lote? para que pudesse ter essas infos ao gerar o boleto dentro do sicoob?

**Comment by EwerCarvalho** [comment]
Ninguém consegue me ajudar? eu estou só tentando gerar um cnab 240 do sicoob, o banco me informou que a descricaoDemonstrativo e instruções devem ser passadas dentro da remessa, porém não está indo as informações dentro do Cnab.

**Comment by eduardokum** [comment]
Bom dia, essas instruçoes sao passadas na remessa como comando, se quer juros precisa informar o juros no objeto do boleto, se quer protesto mesma coisa, e assim vai pra tudo que quer comandar. ja os literais escritos nao somente se for o banco que emite o boleto, mais no caso o projeto nao tem suporte pra isso, teria que implementar se for esse o caso    


http://www.eduardogusmao.com.br/laravel-boleto/class-Eduardokum.LaravelBoleto.Boleto.AbstractBoleto.html

**Comment by EwerCarvalho** [comment]
> Bom dia, essas instruçoes sao passadas na remessa como comando, se quer juros precisa informar o juros no objeto do boleto, se quer protesto mesma coisa, e assim vai pra tudo que quer comandar. ja os literais escritos nao somente se for o banco que emite o boleto, mais no caso o projeto nao tem suporte pra isso, teria que implementar se for esse o caso
> 
> http://www.eduardogusmao.com.br/laravel-boleto/class-Eduardokum.LaravelBoleto.Boleto.AbstractBoleto.html

então eu lembro que tava homologando algum banco com cnab240 e as instruções eram passadas dentro do cnab, já no sicoob isso não acontece, então eu tenho que fazer essa alteração certo?

**Comment by eduardokum** [comment]
acho que deve ser por modelo de carteira, normal so passa as instrucoes e o banco acata, mais pode ser alguma configuracao no internet banking
