### ISSUE TITLE
Duvida com quem usa remessa do BB?

### ISSUE THREAD

**Issue by diorgesl** [eduardokum/laravel-boleto#427]
Seguinte, já estou utilizando aqui as remessa do BB, até contribui com algumas modificações, mas enfim, estou me deparando com um problema, e espero que alguém possa me ajudar.

Estou com problema ao enviar remessa com alteração de vencimento e valor de boletos.

Quando mando remessa para alteração de vencimento (tentei com a ocorrência padrão do sistema que é 31 e também com 06) e o retorno rejeita as entradas, as vezes só retorna "Entrada rejeitada" e as vezes fala "Valor do Título Inválido".

Quanto a alteração de valor, tentei ocorrência 31 e 47 e também é rejeitado as entradas.

Obrigado.

**Comment by diorgesl** [comment]
Já me informei certinho, no Banco do Brasil, não se pode fazer alteração do valor, no máximo conceder abatimento, não se pode alterar o valor do titulo para mais.

Outra coisa, o segmento R, eu já tinha implementado aqui e vi que fizeram já a contribuição para o projeto, mas o segmento R deve ser incluído apenas quando for registrar, quando for alguma alteração, o segmento R não pode aparecer.

**Comment by eduardokum** [comment]
Ja foram feitas essas PR. Obrigado
