### ISSUE TITLE
Dúvida - Redirect após render

### ISSUE THREAD

**Issue by maustange** [eduardokum/laravel-boleto#428]
Estou com um problema para redirecionar para outra rota após fazer o render e gerar o boleto.
Tenho uma view simples onde informo uma ID qualquer e mando gerar o boleto. No final da rotina no controller quero retornar um redirecionamento para outra rota, porém a rotina finaliza assim que gera o PDF e não faz o redirecionamento.
É mais ou menos isso que estou fazendo:
if (request->id) {
$pdf = new Pdf();
                $pdf->addBoleto($boleto);
                $pdf->showPrint();
                $pdf->hideInstrucoes();
                $pdf->gerarBoleto($pdf::OUTPUT_DOWNLOAD, $save_path = null);
}
return redirect()->route('lista.index');

Tem como fazer esse retorno ou o render do PDF já é o retorno final?

**Comment by eduardokum** [comment]
não term como, tanto como fila attachment ou content disposition não da pra fazer esse redirect, tem que abrir em uma nova pagina caso nao queira perder a atual
