### ISSUE TITLE
CNAB240 Arquivo de remessa

### ISSUE THREAD

**Issue by josericardomcastro** [eduardokum/laravel-boleto#44]
Alguém ja usou/testou a geração de arquivo de remessa do Santander com o layout CNAB240?

Aparentemente aqui comigo ele não está gerando os Headers/Trailers de lote. Está gerando somente os Headers/Trailers de arquivo.

Vi que existe as funções de geração das informações do lote, mas em nenhum lugar do código é chamado.

**Comment by eduardokum** [comment]
Fiz algumas alterações pois ainda não testei não utilizo nenhum cnab com 240 posições (9ff1057e398e8fd67e2a81b859a55786bcd38724)
