### ISSUE TITLE
Resolver Data de Juro de Mora Inválida - SICOOB

### ISSUE THREAD

**Issue by hugohcn** [eduardokum/laravel-boleto#442]
Pessoasl, boa noite!

Ao tentar realizar a validação do CNAB 240 da Sicoob recebi o seguinte erro:

<img width="1276" alt="captura de tela 2018-12-28 as 01 51 22" src="https://user-images.githubusercontent.com/6969705/50531751-9afcc480-0af6-11e9-8143-99853f0fc444.png">

A validação que o Sicoob faz é: sempre que o código de juros for igual a zero, o campo Data Juros Mora (do caractere 119 até o caractere 126 do segmento P) deve ser informado zerado. No entanto, não é isso o que acontece no arquivo [Remessa Bancoob](https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Remessa/Cnab240/Banco/Bancoob.php#L140). 

Alguém já passou por isso? Não seria interessante colocar uma validação para preencher este campo?

```
if($boleto->getJuros() !== null && $boleto->getJuros() == 0) {
    $this->add(119, 126, '00000000');
}else {
    $this->add(119, 126, $boleto->getDataVencimento()->format('dmY'));
}
```

Atenciosamente,
[`]

**Comment by brunoneve** [comment]
Opa,

então no meu uso assim.

```
$this->add(118, 118, ($boleto->getJuros() !== null && $boleto->getJuros() > 0) ? '2' : '0');    //0 = ISENTO | 1 = R$ ao dia | 2 = % ao mês
$this->add(119, 126, $boleto->getDataVencimento()->format('dmY'));
```

**Comment by eduardokum** [comment]
Pode enviar se achou alguma solução, aparentemente funciona para algumas pessoas, o erro deve ser so pra validação de nova carteira, e não pra produção em si
