### ISSUE TITLE
Como realizar várias remessas em um único arquivo CNAB?

### ISSUE THREAD

**Issue by FXXDEV** [eduardokum/laravel-boleto#446]
Há algum exemplo para a realização desse procedimento? Estou realizando para Sicoob e Sicredi.

Não tive sucesso algum até agora, apenas com boletos individuais.

**Comment by brunoneve** [comment]
Geralmente é 1 arquivo = 1 remessa.

**Comment by FXXDEV** [comment]
@brunoneve Sim sim, a ideia é vários boletos em uma remessa. 

Consegui gerar o arquivo de remessa com vários boletos, através de um foreach da maneira que você falou, porém estou tendo problema na validação desta mesma remessa com os bancos (Sicoob e Sicredi).

**Comment by brunoneve** [comment]
O processo de validação é um pouco chata, as vezes é preciso fazer alguns ajustes nos dados da remessa, caracteres especiais, codigo de tipo de remessa, o CNAB precisa está igual ao setado nos bancos.

Mas uso o CNAB240 do Sicoob(bancoob) e não tenho nenhum erro de validação, no início tive de configuração, agencia faltando código, etc. Veja junto com sua gerente e fica mais fácil.

**Comment by lucianoreis** [comment]
O processo de gerar vários boletos e 1 retorno é legal, mas da pra **unir** vários retornos em um arquivo de retorno só para enviar para o banco?
Imagine se eu gero 100 retornos e tenho de enviar 1 a 1. O Financeiro fica loco.

**Comment by eduardokum** [comment]
não tem como, somente 1 conta/carteira/cobrança por arquivo

**Comment by sampiron** [comment]
@FXXDEV como você fez para colocar tudo dentro de 1 unico arquivo?
Pois fiz um Foreach aqui pegando os dados para corretamente, mas no final ele so salva 1 boleto dentro do arquivo.

**Comment by loja5combr** [comment]
https://laravel-boleto.readthedocs.io/en/latest/usage/remessa/index.html

`$boleto = array();`
`foreach(...){`
`     $boleto[] = new Eduardokum\LaravelBoleto\Boleto\Banco\XXXX(...);`
`}`
`$send->addBoletos($boleto);`

**Comment by FXXDEV** [comment]
@sampiron Fiz igual o o demonstrado acima pelo @loja5combr, porém ele gera com erros, não passando na validação dos bancos

**Comment by loja5combr** [comment]
No caso creio agora que vai depender dos erros retornados, geralmente é questão de adequação ao layout do banco.

**Comment by sampiron** [comment]
@loja5combr e @FXXDEV o meu deu certo, e o arquivo foi validado com sucesso pelo BB e Bradesco.
Obrigado pela Ajuda.
