### ISSUE TITLE
Faltando retorno de $this na classe Pessoa para Method Chaining

### ISSUE THREAD

**Issue by edu-lourenco** [eduardokum/laravel-boleto#448]
Olá pessoal,
Parabéns ae, acabei de conhecer o projeto e está ótimo.

Estou usando a versão 0.8 em php 7 e seguindo a documentação em:
https://laravel-boleto.readthedocs.io/en/latest/

Tentando implementar um pagador com a classe Pessoa, recebi erro de que o método "SetName" não existe.
Vi que falta retornar $this em métodos como setName ou setCidade por exemplo.

Assim o Method Chaining vai funcionar ok.
```php
$pagador = new \Eduardokum\LaravelBoleto\Pessoa;
$pagador->setDocumento('00.000.000/0000-00')
    ->setNome('Company co.')
    ->setCep('00000-000')
    ->setEndereco('Street name, 123')
    ->setBairro('district')
    ->setUf('UF');
    ->setCidade('City')

```

Obrigado

**Comment by eduardokum** [comment]
Ja arrumeei, todos os sets não estavam fluentes. Obrigado
