### ISSUE TITLE
Gerar Guia Sindical GRCSU

### ISSUE THREAD

**Issue by alexdeoliveira** [eduardokum/laravel-boleto#450]
Olá galera! Estou precisando registrar as guias sindicais GRCSU (http://www.caixa.gov.br/empresa/pagamentos-recebimentos/pagamentos/grcsu/Paginas/default.aspx).

Sabem me dizer se consigo criar essas guias e registrar na Caixa através de pacote?

Valeu!

**Comment by eduardokum** [comment]
Não, infelizmente não.
