### ISSUE TITLE
erro 503 na instalacao

### ISSUE THREAD

**Issue by criacaosites** [eduardokum/laravel-boleto#452]
Apos a instalação estou com erro 503 a tentar abrir o arquivo no debug ele diz que não consegue obter o conteúdo, na execucaodo comando json nao tive nenhuma mensagem de erro, no debug so achei isso:
[aqui](http://guarucolchoes.com.br/modules/sicoobps/laravel-boleto-master/exemplos/bancoob_boleto.php)

**Comment by criacaosites** [comment]
nao tem mais ninguem no projeto?

**Comment by rafwell** [comment]
Desculpe amigo, mas não dá pra entender nada do seu relato. O link para o log não abre.
Erro 503 pode ser que você esteja com uma versão antiga do PHP ou mesmo uma configuração errada no seu apache, difícil saber sem mais informações.

Certifique-se de que está com o php maior ou igual a 5.5, sugiro o 5.6 ou o 7 e de que há permissão de escrita e leitura na pasta storage e bootstrap/cache

**Comment by eduardokum** [comment]
Tenta explicar melhor, não da pra saber como ajudar com as informações passadas

**Comment by criacaosites** [comment]
Meu log diz:
2019/02/15 14:20:01 [error] 32282#32282: *305829 open() "/home/165597.cloudwaysapps.com/txtgbbjbbk/public_html/favicon.ico" failed (2: No such file or directory), client: 189.25.43.34, server: thirtybees-165597-730183.cloudwaysapps.com, request: "GET /favicon.ico HTTP/1.1", host: "guarucolchoes.com.br", referrer: "http://guarucolchoes.com.br/laravel-boleto-master/exemplos/bancoob_boleto.php"
2019/02/15 14:20:12 [error] 32282#32282: *305841 open() "/home/165597.cloudwaysapps.com/txtgbbjbbk/public_html/favicon.ico" failed (2: No such file or directory), client: 189.25.43.34, server: thirtybees-165597-730183.cloudwaysapps.com, request: "GET /favicon.ico HTTP/1.1", host: "guarucolchoes.com.br", referrer: "http://guarucolchoes.com.br/laravel-boleto-master/exemplos/bancoob_boleto.php"
2019/02/15 14:20:52 [error] 32282#32282: *305888 open() "/home/165597.cloudwaysapps.com/txtgbbjbbk/public_html/favicon.ico" failed (2: No such file or directory), client: 189.25.43.34, server: thirtybees-165597-730183.cloudwaysapps.com, request: "GET /favicon.ico HTTP/1.1", host: "guarucolchoes.com.br", referrer: "http://guarucolchoes.com.br/laravel-boleto-master/exemplos/bancoob_boleto.php"

**Comment by criacaosites** [comment]
??????????????

**Comment by criacaosites** [comment]
nada sobre o erro 
'PHP message: PHP Notice: autoload.php n\xc3\xa3o localizado in /home/165597.cloudwaysapps.com/txtgbbjbbk/public_html/laravel-boleto-master/exemplos/autoload.php on line 7\nPHP message: PHP Fatal error: Class 'Eduardokum\\LaravelBoleto\\Pessoa' not found in /home/165597.cloudwaysapps.com/txtgbbjbbk/public_html/laravel-boleto-master/exemplos/bancoob_boleto.php on line 3\n
