### ISSUE TITLE
Problemas com geração de remessa

### ISSUE THREAD

**Issue by LauraLD** [eduardokum/laravel-boleto#453]
Quando gero um arquivo de remessa do Bb ao final está sendo acrescentada a seguinte linha: [{"variaveis_adicionais":[]}]

Como ocultar essa linha do arquivo de remessa?

**Comment by eduardokum** [comment]
não era pra gerar isso, como voce esta fazendo para gerar o arquivo?

**Comment by LauraLD** [comment]
Estou criando os objetos do boleto e adicionando na remessa. A remessa estou fazendo da seguinte forma:

$beneficiario = new \Eduardokum\LaravelBoleto\Pessoa($beneficiary);
   
      $bb = new Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bb;
      
      $bb
        ->setAgencia($agency)
        ->setCarteira($wallet)
        ->setConta($account)
        ->setConvenio($covenant)
        ->setBeneficiario($beneficiario);

      $bb->addBoletos($billings);
      $bb->download($filename = null);
