### ISSUE TITLE
Problemas com Código de Barras e Linha Digitavel - Santander

### ISSUE THREAD

**Issue by LucasSantosDev** [eduardokum/laravel-boleto#455]
Pessoal, alguém está tendo problema com linha digitável e código de barras. Estão dando inválidos. Ai mexi no código e consegui normalizar o código de barras. Porém a linha digitável da como inválida.

Estou trabalhando com Santander registro online de boleto.

Preciso fazer isso para poder homologar o layout.

**Comment by enricodvn** [comment]
Pode dizer o erro? Eu já homologuei o Santander pra cnab 400 e tô
terminando de homologar para o 240

Em ter, 19 de fev de 2019 3:18 PM, Lucas da Silva Santos <
notifications@github.com escreveu:

**Comment by LucasSantosDev** [comment]
Então, não da erro, porém a linha digitável vem como inválida quando eu tento pagar pelo aplicativo. Já o código de barras fica correto. Layout 240

**Comment by enricodvn** [comment]
Vc ta usando a versão 0.8? Verifica o seus arquivos composer.json e principalmente composer.lock

**Comment by LucasSantosDev** [comment]
.json => "eduardokum/laravel-boleto": "^0.8.0",
.lock => "name": "eduardokum/laravel-boleto", ": "0.8",

Sim.

**Comment by LucasSantosDev** [comment]
Por exemplo...Ignora o codigo de barras ele está certo...mas segue linha digitavel..

DENTRO DO SANTANDER   => 03399.91804 05200.000007 00016.601015 7 78050000001025
DENTRO DO MEU SISTEMA => 03399.91804 05200.000007 00001.660109 7 78060000001025

**Comment by LucasSantosDev** [comment]
Pessoal consegui resolver colocando o Código de barras e linha digitavel direto o que o banco me retorna.

Não é o ideal porém deu certo! Obrigado.

**Comment by brenogalinari** [comment]
@LucasSantosDev Estou tendo o mesmo problema, como vc fez pra colocar o código de barras e a linha digitável que o banco te retorna ?

**Comment by brenogalinari** [comment]
@LucasSantosDev Já resolvi aqui, implementei uma classe que estendia a Santander e sobrescrevi os métodos. Valeu

**Comment by rafwell** [comment]
@brenogalinari compartilha ai se possível. Pode ser que seu problema seja o de outras pessoas, ou mesmo que venha a ser incorporado ao código base do projeto.

**Comment by tantoniazi** [comment]
eu estou com o mesmo problema porém no registro do bradesco, eu consigo preencher a linha digitavel, porém o código de barras sempre sai errado

**Comment by LucasSantosDev** [comment]
@brenogalinari, @rafwell tive que sobre escrever o método da linha digitavel e codigo de barras, na verdade o que fiz foi criar duas variaveis publicas chamadas linha_soap e codigo_soap, e quando instancio o Santander para gerar o layout eu passo o que o banco me retorna para essas duas variaveis e dentro do método de pegar o codigo de barras e linha digitavel eu dou um return $linha_soap; e pro outor método return $codigo_soap; Isso resolveu para mim. Se precisar de algo pode entrar em contato que te ajudo. (lucas.santos@kbrtec.com.br) Olho esse email todo dia. Abs

**Comment by IcaroRios** [comment]
@tantoniazi Como você resolveu seu problema? estou com o mesmo

**Comment by LucasSantosDev** [comment]
Eu sobrescrevi algumas infos na classe do boleto e funcionou, se precisar de alguma ajuda me fala. Eu fiz um overwrite!

________________________________
De: IcaroRios <notifications@github.com>
Enviado: quarta-feira, 8 de julho de 2020 17:29
Para: eduardokum/laravel-boleto <laravel-boleto@noreply.github.com>
Cc: Lucas da Silva Santos <lucas_ss.arts@live.com>; Mention <mention@noreply.github.com>
Assunto: Re: [eduardokum/laravel-boleto] Problemas com Código de Barras e Linha Digitavel - Santander (#455)


@tantoniazi<https://github.com/tantoniazi> Como você resolveu seu problema? estou com o mesmo

**Comment by brenogalinari** [comment]
@LucasSantosDev Eu fiz a mesma coisa aqui e funcionou também. Tive que sobrescrever.

**Comment by LucasSantosDev** [comment]
Tenta dar um fork ou cria uma PR com a modificação para quem sabe ajustar isso no pacote.

________________________________
De: Breno Galinari Barçante <notifications@github.com>
Enviado: quinta-feira, 9 de julho de 2020 11:01
Para: eduardokum/laravel-boleto <laravel-boleto@noreply.github.com>
Cc: Lucas da Silva Santos <lucas_ss.arts@live.com>; Mention <mention@noreply.github.com>
Assunto: Re: [eduardokum/laravel-boleto] Problemas com Código de Barras e Linha Digitavel - Santander (#455)


@LucasSantosDev<https://github.com/LucasSantosDev> Eu fiz a mesma coisa aqui e funcionou também. Tive que sobrescrever.

**Comment by tantoniazi** [comment]
vou verificar porque ja faz um tempo que fiz, 
se nao me engano alguma variavel que eu estava colocando estava faltando zero a esquerda

**Comment by LucasSantosDev** [comment]
ja faz um tempao que fiz tb....

________________________________
De: Tiago Guerra <notifications@github.com>
Enviado: sábado, 11 de julho de 2020 10:59
Para: eduardokum/laravel-boleto <laravel-boleto@noreply.github.com>
Cc: Lucas da Silva Santos <lucas_ss.arts@live.com>; Mention <mention@noreply.github.com>
Assunto: Re: [eduardokum/laravel-boleto] Problemas com Código de Barras e Linha Digitavel - Santander (#455)


vou verificar porque ja faz um tempo que fiz,
se nao me engano alguma variavel que eu estava colocando estava faltando zero a esquerda

**Comment by IcaroRios** [comment]
Consegui resolver. Estava enviando o nosso número errado

**Comment by LucasSantosDev** [comment]
Show man!!!!

________________________________
De: IcaroRios <notifications@github.com>
Enviado: sábado, 11 de julho de 2020 12:59
Para: eduardokum/laravel-boleto <laravel-boleto@noreply.github.com>
Cc: Lucas da Silva Santos <lucas_ss.arts@live.com>; Mention <mention@noreply.github.com>
Assunto: Re: [eduardokum/laravel-boleto] Problemas com Código de Barras e Linha Digitavel - Santander (#455)


Consegui resolver. Estava enviando o nosso número errado
