### ISSUE TITLE
Gerar boletos em novas abas

### ISSUE THREAD

**Issue by Feergod** [eduardokum/laravel-boleto#456]
Estou com o seguinte problema, estou fazendo um array com os boletos, entretanto preciso que cada um deles seja aberto em uma nova aba para downloads separados, da forma que está ele junta todos em um único PDF, como poderia ser solucionado? Grato desde já!

**Comment by luandiego7** [comment]
Bom dia pessoal!! Estou com a mesma dúvida.. gostaria de gerar um boleto em uma nova aba, é possível? Procurei se tinha que passar algum parametro, mas não vi nada.. 
Obrigado!

**Comment by eduardokum** [comment]
Teria que gerar 1 a 1, nao existe essa opcao
