### ISSUE TITLE
Atualizar boleto vencido

### ISSUE THREAD

**Issue by wafgomes** [eduardokum/laravel-boleto#457]
**Questão**
Com a nova plataforma de boletos do FEBRABAN, é possível pagar boleto vencido com o mesmo código de barra/IPTE. Ou seja, não precisa de um novo boleto.

O problema é que muitos clientes, solicitam o boleto com os valores atualizados, para isso tem que emitir pelo site do banco, mas claro, o cliente não faz isso (fato real).

Seria possível adicionar uma variável, tipo "valorAtualizado" e "vencimentoAtualizado", se essa variável estiver sendo usada, o valor do documento muda, mas não muda o código de barras/IPTE?

Hoje não alterei nada, apenas passo nas instruções do boleto, o valor total da multa calculado pelos x dias de atraso.

**Comment by brunoneve** [comment]
Sim,

você pode fazer essa funcionalidade na sua aplicação, creio que não será implementado isso na biblioteca oficial.

**Comment by wafgomes** [comment]
que posso fazer eu sei. na verdade, acho que deveria ser implementado, como apontei é um caso real, com isso consigo gerar o mesmo boleto que é gerado entrando no site do banco, acessando 2º via, preenchendo todos os campos...
enfim, fiz minhas alterações. segue:

Render\Pdf
alterado linhas com getValor() para verificar se tem getValorAtualizado(), se tiver, mostra o valor atualizado (valor+juros+multa calculado)

Boleto\AbstractBoleto
adicionado variavel $valorAtualizado, métodos getValorAtualizado() e setValorAtualizado()

o mesmo foi feito para a data de vencimento. assim, alterando só a render o código de barras sai o mesmo.

esse é o único jeito que soube fazer, não sei nada inteligentão que pudesse sobrescrever as classes. meu medo é atualizar o código e perder tudo, ai terei que refazer ;p
