### ISSUE TITLE
Remessa/Retorno automatico

### ISSUE THREAD

**Issue by criacaosites** [eduardokum/laravel-boleto#458]
**Questão**
Ola, gostaria de saber se o sicoob possui algum metodo de envio da remessa e baixa do arquivo de retorno de maneira integrada?

**Comment by brunoneve** [comment]
Trabalho com sicoob a mais de 1 ano, e até o momento pelo menos em nossa região não liberaram nenhum.

**Comment by pablovdsp** [comment]
E do Itaú, alguém tem alguma notícia?

**Comment by eduardokum** [comment]
acredito que nao, alguns bancos tem api mais é super restrito nem documentacao é aberta, acredito que levara mais algum tempo para isso .
