### ISSUE TITLE
Alteração Boleto

### ISSUE THREAD

**Issue by sampiron** [eduardokum/laravel-boleto#459]
Boa Tarde,

Quando precisar alterar algum boleto (vencimento ou Baixa), devo na geração da remessa colocar qual comando para ele entender que aquele boleto e uma alteração ?

Obrigado.

**Comment by brunoneve** [comment]
$boleto->baixarBoleto() para baixar

$boleto->alterarBoleto() para alteração de boleto

**Comment by sampiron** [comment]
@brunoneve isso na hora que imprimo o Boleto ? 
Fazendo isso automaticamente na remesa ele vai com a instrução para o banco que o boleto deve ser alterado ?

**Comment by brunoneve** [comment]
No momento que você adiciona o boleto na remessa, você chama essas funções.

**Comment by sampiron** [comment]
@brunoneve fiz isso... mas agora lendo o retorno ele me informo de entrada rejeitada como numero duplicado.
Estou colocando o comando antes de gerar a remessa.. pelo $remessa->addBoleto($boleto)

**Comment by brunoneve** [comment]
@sampiron olha esse exemplo
Primemiro você pega o boleto que quer por na remessa.


`$boleto = new Bancoob([
            'logo' => $this->pathPublic.'/img/logo.png',
            'dataVencimento' => new \Carbon\Carbon($titulo->dataVencimento),
            'DataDocumento' => new \Carbon\Carbon($titulo->dataGeracao),
            'valor' => $titulo->valor,
            'multa' => $this->multa,
            'juros' => $this->juros,
	    'abatimento' => $abatimento,
            'numero' => (integer) substr($titulo->numBoleto,3),
            'numeroDocumento' => $titulo->documento,
            'pagador' => $client,
            'beneficiario' => $cedente,
            'carteira' => $this->carteira,
            'agencia' => $this->agencia,
            'convenio' => $this->convenio,
            'conta' => $this->conta,
            'contaDv' => $this->contaDv,
            'descricaoDemonstrativo' => ['MSG 1','MSG 2'],
            'instrucoes' =>  ['Apos vencimento multa de R$ '.$multa, 'Mora diaria de R$ '.$juros],
            'aceite' => $this->aceite,
            'especieDoc' => $this->especieDoc,
        ]);`

Feito isso, digamos que você queira informar que esse boleto seja com a instrução de baixa/cancelar.

Então fazemos:

`$boleto->baixarBoleto();`

Pronto, agora esse boleto está com a instrução para baixa/cancelar, então retornamos ele para sua outra função que cria a remessa

`return $boleto;`


Agora la na sua função de criar remessa, digamos que cada boleto $boleto, você salva em um array, e depois você chama a sua função para criar a remessa. e depois la na sua remessa, você chama a função para adicionar boletos nela.

$remessa->addBoletos($titulos);
$remessa->save('local-pasta'.$nomeRemessa);

**Comment by sampiron** [comment]
@brunoneve Obrigado pela ajuda, esse e meu codigo:

` 
$boleto = new \Eduardokum\LaravelBoleto\Boleto\Banco\Bb(
[
 'logo'                   => realpath('/var/www/erp/images/unilife.png'),
 'dataVencimento'         => new \Carbon\Carbon($row['vencimento']),
'valor'                  => $row['valor_total'],
 'multa'                  => $this->modelfuncoes->getKeywords("sys_contas_banco","multa",$banco),
 'juros'                  => $this->modelfuncoes->getKeywords("sys_contas_banco","taxa_juros",$banco),
'numero'                 => $row['nr_documento'],
'numeroDocumento'        => $row['nr_documento'],
 'descricaoDemonstrativo' => ['Juros de R$ 1,89 ao dia', 'Protesto Automatico após 5 dias do Vencimento', ''],
 'instrucoes'             => ['','',''],
'aceite'                 => $this->modelfuncoes->getKeywords("sys_contas_banco","aceite",$banco),
'especieDoc'             => 'DM',
'agencia'                => $this->modelfuncoes->getKeywords("sys_contas_banco","agencia",$banco)."-".$this->modelfuncoes->getKeywords("sys_contas_banco","agencia_digito",$banco),
'conta'                  => $this->modelfuncoes->getKeywords("sys_contas_banco","conta",$banco)."-".$this->modelfuncoes->getKeywords("sys_contas_banco","conta_digito",$banco),
'pagador'                => $pagador,
'beneficiario'           => $beneficiario,
'carteira'               => $this->modelfuncoes->getKeywords("sys_contas_banco","carteira",$banco),
'convenio'               => $this->modelfuncoes->getKeywords("sys_contas_banco","codigo_convenio",$banco),
                        ]
                    );
//Verifica Alteração de Vencimeno
if($row['alterado_vencimento'] == "S"){
  $boleto->alterarBoleto();
}
//Verifica Baixa de Documento
if($row['baixar_boleto'] == "S"){
     $boleto->baixarBoleto();
 }
$remessa->addBoleto($boleto);     
`
Nessa sequencia que faço, a unica diferença que vi com o seu que p $remessa->addBoleto no meu e no seu e $re,essa->addBoletos, nesse sequencia seria para funcionar corretamente ?

**Comment by brunoneve** [comment]
Isso, você adiciona 1 boleto de cada vez na remessa, no meu eu mando vários de uma unica vez.

**Comment by williamcastro** [comment]
@brunoneve  cara, obrigado pela ajuda ai na postagem, tirou dúvidas que tinha.
Uma outra que me surgiu, no caso de realizar a alteração de um boleto (data de vencimento por exemplo), e colocar a flag alterarBoleto(), o título precisa ser reimpresso para passar as informações corretamente na leitura de barra né? Ou só alterando, o banco tem um controle pelo nosso número que atualiza os dados do boleto impresso antigo?

**Comment by brunoneve** [comment]
@williamcastro tranquilo.

Então, aqui eu faço a alteração gero a remessa, envio para o banco, até o momento esse boleto no meu sistema(banco de dados) continua com a data original do vencimento, mas tenho 1 controle em outra tabela que fica salva o novo vencimento.

Então após retorno dessa remessa que vem a confirmação se o titulo foi atualizado ou não, no caso de sim, eu atualizo a data de vencimento no meu banco de dados, e re-imprimo o boleto.

**Comment by williamcastro** [comment]
Entendi! Nesse caso acho que vou manter o fluxo atual que tenho de criar um novo título, e dar baixa no antigo.

**Comment by brunoneve** [comment]
@williamcastro tendi, existe algumas taxas nesses serviços, ai tem que ver com gerente, as vezes compensa baixar o título e gerar outro do que fazer alteração.

Abs.
