### ISSUE TITLE
Gerar Remessa Sicoob Cnab240

### ISSUE THREAD

**Issue by kessejones** [eduardokum/laravel-boleto#460]
**Questão**
Bom dia, estou tentando validar um arquivo de remessa Cnab240 no Sicoob, porém estou tendo estes erros na validação. Alguém sabe como resolver ?

`Número Remessa/Retorno 184 191 Numérico 8 00000000 Numérico Campo de preenchimento obrigatório não informado ou preenchido com
zeros`

`Número Seqüencial do Arquivo 158 163 Numérico 6 000000 Numérico Campo de preenchimento obrigatório não informado ou preenchido com
zeros`

**Comment by brunoneve** [comment]
Sicoob exige um um numero sequencial para sua remessa, então aqui fizemos uma tabela onde registramos os dois campos

sequencialRemessa = valor + 1 sempre q gerado 1 nova remessa
squencialRetorno = esse vem no arquivo de retorno.


$remessa = new \Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab240\Banco\Bancoob(
    [
        **'idRemessa'     => $seqRemessa,**
        'agencia'       => $this->agencia,
        'carteira'      => $this->carteira,
        'conta'         => $this->conta,
        'contaDv'       => $this->contaDv,
        'convenio'      => $this->convenio,
        'beneficiario'  => $cedente
    ]
);

**Comment by kessejones** [comment]
@brunoneve obrigado pela resposta. Eu não sabia que devia passar o `idRemessa` ao gerar a remessa.
Esse número eu uso para identificar de qual remessa o retorno pertence é isso ?

**Comment by brunoneve** [comment]
Tranquilo.
Então na verdade é apenas para identificação da remessa, o retorno vem com outro numero q o banco ti fornece, um numero q incrementa + 1 sempre q pegar retorno la no sistema deles.

**Comment by eduardokum** [comment]
Alguns bancos sao obrigatorio o numero seq da remessa
