### ISSUE TITLE
PHP 7.3 renderPDF

### ISSUE THREAD

**Issue by f3lpz** [eduardokum/laravel-boleto#462]
Olá,

Tive problemas ao chamar a função **renderPDF()** utilizando a versão 7.3 do Php.

Código do erro:
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?"
Arquivo: src/Util.php
linha: 708

Alterei o 'continue' para 'break' e funcionou.

Grato!

**Comment by juizmill** [comment]
Parece que já foi corrigido nesta PR https://github.com/eduardokum/laravel-boleto/pull/468

**Comment by eduardokum** [comment]
atualizado ja #464
