### ISSUE TITLE
Problema com a classe Util

### ISSUE THREAD

**Issue by juizmill** [eduardokum/laravel-boleto#464]
Ao tentar gerar o boleto e a remessa estou recebendo dois erros. 

linha 708

```
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```

Linha 547

```
A non-numeric value encountered 
```

Para resolver o problema na linha 708 simplesmente coloquei o numero 2 na frente do continue, 

```
if (self::remove(1, 1, $detalhe) != 7) {
    unset($retorno[$i]);
    continue 2;
}
```

Já na linha 547 é só converter o `$n` para inteiro, mas acho que não seria a forma correta..  

```
        $sum = 0;
        $n = (int) $n;
        for ($i = mb_strlen($n); $i > 0; $i--) {
            $sum += mb_substr($n, $i - 1, 1)*$factor;
            if ($factor == $base) {
                $factor = 1;
            }
            $factor++;
        }
```

 - Versão do PHP 7.3
 - Versão do Laravel 5.6

**Comment by juizmill** [comment]
Parece que o primeiro erro já foi corrigido na PR https://github.com/eduardokum/laravel-boleto/pull/461

**Comment by eduardokum** [comment]
Commit  f154d01758f17df5f26f19670c9c667e38cede84 em develop, logo subo pra master
