### ISSUE TITLE
Erro na validação pelo Itaú

### ISSUE THREAD

**Issue by edigomes** [eduardokum/laravel-boleto#47]
Estou recebendo o seguinte erro na validação do Itaú:
![image](https://cloud.githubusercontent.com/assets/9788003/21123499/d69c897a-c0b7-11e6-818b-63bfb32ecee7.png)

Manual:
Pag 21:
![image](https://cloud.githubusercontent.com/assets/9788003/21123704/1f4da414-c0b9-11e6-9ce0-1d6b440e22d6.png)
Pag 8:
![image](https://cloud.githubusercontent.com/assets/9788003/21123674/e23e7846-c0b8-11e6-8a3e-5117b6df6e4d.png)

Segundo o manual está tudo ok!!!
Mas fica rejeitando a remessa!!!

Segue remessa gerada:
http://pastebin.com/V0fE8sjG

Conferi todo o código e o arquivo da remessa, aparentemente está OK, usei `diasProtesto` na geração, vi que foi adicionado `diasBaixaAutomatica` não sei se teve a ver.

Alguém teve esse erro?

Att.

**Comment by eduardokum** [comment]
Nunca vi, essas ocorrências peguei desse manual que acredito ser o último, a menos que tenha um novo, amanhã vou ver... o dias de baixa é para quem quer que devolva sem protesto, ou é um ou é o outro

**Comment by edigomes** [comment]
Passei a instrução para 09 e passou:
![image](https://cloud.githubusercontent.com/assets/9788003/21163654/2af87694-c173-11e6-954b-4c0835b9f823.png)
Obs "A" dias para protesto:
![image](https://cloud.githubusercontent.com/assets/9788003/21163681/44867836-c173-11e6-820c-929da9af71f1.png)
Mas não entendi pq não passou a 34 e nem a 35, usei a carteira 109, ainda liguei pro Itaú mas depois de 1h a ligação caiu e meu gerente é um jumento...

E aí?

**Comment by eduardokum** [comment]
34 ele passa quando voce especifica dias para protesto, se voce especificar dia para baixa automatica ele vai colocar 92 que é devolver, isso sempre na 1 instrução, ja na segunda ele sempre usa 57 que é somar os juros no valor quando tiver isso seguindo o manual que tem disponivel https://github.com/eduardokum/laravel-boleto/blob/master/manuais/ITAU/remessa_retorno.pdf

a versão do seu manual é a mesma que essa?

**Comment by edigomes** [comment]
É esse mesmo manual.

Do jeito que a classe gera é colocando 35 na instrução 1 e a quantidade de dias na 392 não passa no validador, eu mudei pra 34 e nada, quando mudo pra 09 ele passa.

34 ou 35:
![image](https://cloud.githubusercontent.com/assets/9788003/21165646/58f974d8-c17f-11e6-9832-6285ed2d800b.png)

Colocando 09:
![image](https://cloud.githubusercontent.com/assets/9788003/21165662/6eda2770-c17f-11e6-95ef-7243c15f374b.png)

Remessa que passou:
http://pastebin.com/aQUnB7nR

**Comment by eduardokum** [comment]
agora que vi no manual, aparentemente deveria servir 09 34 35, não faço ideia do porque não vai, os gerentes parece que são mais perdidos que agente. Vamos mudar a classe pra 09. Parece ser a opção padrão, essas 34 35 devem ser algo especifico sei la.

**Comment by edigomes** [comment]
Vou seguindo aqui com 09 mas amanhã vou ligar de novo pra lá, vou seguir de atendente em atendente até chegar em alguém que tenha conhecimento técnico na remessa,

Ai digo no que deu ou já mando uma pull mudando pra 09, 

Até.

**Comment by eduardokum** [comment]
Deixei o padrão 09 la, quando der veja se valida.

**Comment by edigomes** [comment]
Amanhã cedo farei os testes, vlw.

**Comment by eduardokum** [comment]
Como não teve resposta acredito que esteja ok. rsrs

**Comment by edigomes** [comment]
Realmente! passou a remessa, só não obtive retorno do banco quando a os registros 34/35 acho que deve ser somente na carteira 175 (emissão pelo site do banco),

Abs.
