### ISSUE TITLE
Sobre o campo numero BB

### ISSUE THREAD

**Issue by edsonrbispo** [eduardokum/laravel-boleto#472]
**Questão**
Olá sou novo na geração de boleto, a minha duvida é sobre o atributo numero, a informação que devo preencher é fornecida pelo banco, ou ela é com base no numero do convenio.
Agradeço

**Comment by eduardokum** [comment]
é o numero do boleto no banco, o numeroDocumento é o numero dele na sua base, numero da conta da fatura, qualquer numero que voce identifique ele
