### ISSUE TITLE
Remessa Santander - addBoleto

### ISSUE THREAD

**Issue by phalkao** [eduardokum/laravel-boleto#473]
Bom dia,

Estou tentando gerar uma remessa com 5 títulos, tentei realizar usando um loop, porém é gerado um arquivo com o ultimo registro. 

Tentei criar um array antes com todos os boletos e depois usar o método passando esse array de boletos, mas também não deu certo.

Poderia ajudar, por favor?

**Comment by EwerCarvalho** [comment]
verifique a fundão addBoletos

**Comment by phalkao** [comment]
Muito obrigado pelo retorno,

Consegui ver a função e consegui fazer a alteração no meu código.


Atenciosamente



*Júlio César Santos*
*Consultor de Informática  *
julio.cesar@phalkao.com.br
*(11) 4645-2276 / **(11) 96572-8628 - Claro*




Em ter, 7 de mai de 2019 às 10:13, Ewerton Carvalho <
notifications@github.com> escreveu:
