### ISSUE TITLE
Erro na Validação do Leiaute

### ISSUE THREAD

**Issue by edsonrbispo** [eduardokum/laravel-boleto#476]
Poderia me ajudar, a verificar onde estou errando, que dado estou informando errado ou ausente.

![Capturar](https://user-images.githubusercontent.com/16540088/56139456-4d09b080-5f6f-11e9-8e6f-d08dd597e3ee.PNG)

**Comment by eduardokum** [comment]
nao entendi o erro, o digito da conta corrente esta errado?
