### ISSUE TITLE
[Dúvida ] - Código de barras

### ISSUE THREAD

**Issue by scraipt** [eduardokum/laravel-boleto#480]
É possível desenhar o código de barra separado? não encontrei nenhum método sobre, necessidade disso é colocar o código de barra em uma determinada tela do site.

**Comment by Charliiee** [comment]
Você pode usar o metodo `getImagemCodigoDeBarras($codigo_barras)` da classe `Eduardokum\LaravelBoleto\Boleto\Render\Html`. Você só precisa fornecer o código de barras do objeto do boleto.

Um exemplo do uso deste método pode ser encontrado em:

https://github.com/eduardokum/laravel-boleto/blob/master/src/Boleto/Render/Html.php#L79
