### ISSUE TITLE
Transmitir descricao, instruções e sacado junto ao arquivo de remessa bradesco

### ISSUE THREAD

**Issue by marciodiasdeveloper** [eduardokum/laravel-boleto#481]
Como transmitir estes dados junto ao arquivo de remessa? o sacado está sendo enviado mas não aparece no boleto do banco.

**Comment by eduardokum** [comment]
depende do banco da carteira, quando a impressao é pelo cliente voce que tem que gerar o boleto com as instruoes, no banco so aparece as instrucoes comandadas, agora depende da carteira e do banco voce tem que passar todos os dados em outro seguimento da remessa, informando o cliente no boleto ja adiciona o seguimento automatico
