### ISSUE TITLE
Atualizar a versão do Carbon para 2.0

### ISSUE THREAD

**Issue by jbmchd** [eduardokum/laravel-boleto#488]
Há previsão de quando será usado o Carbon 2.* no pacote? A versão 1.* está obsoleta.

![image](https://user-images.githubusercontent.com/47819400/60664439-4d13a100-9e38-11e9-9c6d-3b0a9e2d2d82.png)

**Comment by eduardokum** [comment]
Versao 2.* ja esta em develop, aguardando uma validacao no sicredi para criar uma nova versao no master

**Comment by jbmchd** [comment]
:D

**Comment by IgorDePaula** [comment]
Tambem estou esperando essa atualizacao pra usar o pacote = / estou com o mesmo problema.

**Comment by IgorDePaula** [comment]
A branch develop tambem esta com a versao 1 do carbon =/

**Comment by eduardokum** [comment]
atualizado

**Comment by IgorDePaula** [comment]
Foi atualizacao nao, nem na master, nem em homologacao.

**Comment by eduardokum** [comment]
https://github.com/eduardokum/laravel-boleto/blob/master/composer.json

**Comment by flavianohonorato** [comment]
Essa alteração resolve?, não houve algum equivoco e faltou arquivo a ser comitado?

**Comment by eduardokum** [comment]
no meu local aqui resolveu devido a versao do laravel instalada, mais acredito que instacao limpa nao esta indo o 2.0, estou tentando arrumar as versoes aqui para instalar, porque devido ao suporte do php5 nao da pra deixar 2.0 pra tudo mundo tem que deixar o 2.0 para php mais novo e 1 pro php5

Em qua, 14 de ago de 2019 às 11:56, Flaviano Honorato <notifications@github.com<mailto:notifications@github.com>> escreveu:

Essa alteração resolve?, não houve algum equivoco e faltou arquivo a ser comitado?

**Comment by IgorDePaula** [comment]
Acredito que se trocar o Carbon por helper now() ou DateTime manteria uma boa compatibilidade.
