### ISSUE TITLE
A que se refere codigoCliente na remessa Santander e Bradesco?

### ISSUE THREAD

**Issue by tperrelli** [eduardokum/laravel-boleto#49]
Bom dia. Dei uma olhada na documentação do santander e não encontrei algo relacionado ao codigo do cliente. Essa numeração seria composta de quais números?

**Comment by eduardokum** [comment]
Código do cliente é um número que o gerente fornece, com ele compõe o código de transmissão que é agencia+codigo_cliente+conta

**Comment by tperrelli** [comment]
Show! Se eu tiver alguns arquivos de remessa comigo, tem como eu fazer o processo inverso, descobrindo assim esse código do cliente? Ou realmente só é possível obtendo através do gerente do banco?

**Comment by eduardokum** [comment]
No santander no header (0) fica na posicao 27-46 o codigo de transmissão, e o codigo do cliente fica entre a agencia e conta agencia_4_digitos+codigo_cliente_8_digitos+conta_8_digitos

No Bradesco fica  no header(0) na mesma posição, mais o bradesco é o codigo inteiro 20 posições.

**Comment by tperrelli** [comment]
O que acontece:

Embora  Agência + Cod Cli + Conta resulte no total de 20 posições, no arquivo ta sendo um range no total de apenas 15 posições.

Aí fiz um teste adicionando um código de cliente qualquer só para verificar qual resultado de fato é escrito no arquivo da remessa.

Aí tá ficando dessa forma:

agencia (4) digitos + Cod cli (8) digitos + 00 + primeiro digito da conta

Explicando melhor:

Agencia: 3333
Cod cli: 1
Conta: 888888

3333 + 00000001 + 008

Tô usando Cnab 240, e realmente a linha 245 ta de acordo com a documentação

033 – 047 Código de Transmissão N 015 
$this->add(33, 47, Util::formatCnab(9, $this->getCodigoTransmissao(), 15)); // Codigo de Transmissão

Então eu compreendi que o script pega apenas os três primeiros dígitos da conta. E quanto a conta tem menos do que 8 dígitos, o script completa com dois zeros a frente, resultando como está no exemplo acima.

Todavia, na remessa real que tenho em mãos que o pessoal do financeiro me passou, range está no seguinte formato:

agência + 0000 + conta + conta div

É como se o código do cliente fosse 0.

Pergunta:
O range total deve de fato ser 20 posições?
 ou... 

15 (obtendo os três primeiros dígitos da conta ou completando com três zeros quando a conta for menor que 8 caracteres)

Valeu!

**Comment by eduardokum** [comment]
Desculpe, é que esse cnab 240 não sei se esta funcional, ele esta em testes, pois eu nunca utilizei, foi @leonardopinho que enviou o PR, não sei onde e se utiliza esse código de cliente para ele, teria que ver na documentação do banco onde fica e se realmente existe essa informação na remessa.

**Comment by tperrelli** [comment]
Entendi! Vou fazer uns testes aqui. Se funcionar mando PR.

**Comment by eduardokum** [comment]
Certo.
