### ISSUE TITLE
Erro em remessa com alteração de vencimento

### ISSUE THREAD

**Issue by glauco-torres** [eduardokum/laravel-boleto#492]
Enviei uma remessa para a CEF com alteração de vencimento  (único boleto na remessa) e a mesma foi rejeitada.
O suporte da CEF informou que o Código de Movimento Remessa (pos. 16 e 17) deve ser 06 em todos os segmentos, pelo que verifiquei só ficou 06 no segmento Q.

Acredito que o mesmo deve ocorrer nos outros bancos

**Comment by eduardokum** [comment]
não sei te dizer, não utilizo alteracao de boletos esse é o primeiro erro que relatam sobre isso, teria que fazer a alteracao e ver se passa na caixa antes de pensar em alterar outros bancos

**Comment by wehsoft** [comment]
Já utilizei a alteração de vencimento para o banco Itau, e funcionou perfeitamente!

**Comment by glauco-torres** [comment]
o Itaú que você utilizou foi 240 ou 400?
provavelmente foi o 400 pois o modelo 400 não possui a repetição desse " Código de Movimento Remessa" em várias linhas

**Comment by wehsoft** [comment]
Exato! 

Estou utilizando o 400 posições.

**Comment by tiagoguirado** [comment]
@wehsoft na alteração de data de vencimento para Itau você comanda a instrução e adiciona só os dados que consta no manual ou adiciona os dados sem se preocupar com o manual? Pois estou tendo problemas com isso. Quando eu comando a instrução pra alterar o boleto e coloco data de vencimento, o campo aparece certinho lá na posição, só que não homologa no banco pois todos os dados do boleto estão indo pra remessa, sendo que alteração devem ir somente os campos do manual.

**Comment by tiagoguirado** [comment]
Estou com quase o mesmo problema, mas pra qualquer alteração do Itau. O banco informou que ao enviar uma alteração todos os outros campos devem ser zero ou branco. Mas isso não está acontecendo. A posição está com o valor correto (06 para data ou 31 para valor ou outros campos) mas os outros campos continuam preenchidos, invalidando a remessa.

Para data de vencimento a regra é:
![image](https://user-images.githubusercontent.com/15661821/66852230-e0d62c80-ef52-11e9-96fb-2a26cc77186c.png)

Para outros campos (como o valor) a regra é:
![image](https://user-images.githubusercontent.com/15661821/66852361-2abf1280-ef53-11e9-9285-77353f39a3eb.png)
