### ISSUE TITLE
Erro ao gerar remessa Banco do Brasil agência digito X ainda permanece.

### ISSUE THREAD

**Issue by mastertag** [eduardokum/laravel-boleto#493]
Exemplo, ao gerar remessa com como agencia:  1639-X por dá erro no método modulo11 em /eduardokum/laravel-boleto/src/Util.php. Preciso manter o X pq são regras da remessa, e tambem deve aparecer X no boleto. Existem uma bug já fechado em 2017 mas ainda existe (#152 ).

**Comment by eduardokum** [comment]
voce utiliza o master ou o develop?

**Comment by mastertag** [comment]
Olá, boa tarde,

Fiz a instalação padrão da documentação.  
composer require "eduardokum/laravel-boleto"
"eduardokum/laravel-boleto": "^0.8.2",
Atualmente estou fazendo o tratamento do arquivo em um um novo arquivo e ainda estou colocando um 0 (zero) a esquerda ficando “016390” onde o ultimo zero tem que ser X (maiúsculo) como a documentação pede.

Att,
Felipe Augusto

**Comment by eduardokum** [comment]
qual o banco?

**Comment by mastertag** [comment]
Bando do brasil

**Comment by eduardokum** [comment]
a Remessa ja esta adicionando, coloquei no pdf tbm, esta somente em develop, logo subirei pra master

**Comment by mastertag** [comment]
Ok, Aguardo.
