### ISSUE TITLE
Retirar marcações do boleto

### ISSUE THREAD

**Issue by xxggabriel** [eduardokum/laravel-boleto#504]
Como faz para retirar essas marcação de quantidade de boletos, que fica no codigo de barras

**Comment by eduardokum** [comment]
provavelmente é alguma fonte maior ou espacamento maior, vou dar uma conferida

**Comment by xxggabriel** [comment]
Essa é a versão: "eduardokum/laravel-boleto": "^0.8.5",

**Comment by adrianoGaspar** [comment]
Olá, ainda não resolveram isso de aparecer a marcaçãoda qtd de boletos no código de barras?
![Captura de tela de 2019-12-03 17-00-04](https://user-images.githubusercontent.com/7820433/70085126-676fc780-15ee-11ea-8ea5-632338544ed3.png)
