### ISSUE TITLE
Teria alguma forma de fazer o envio automático de remessa?

### ISSUE THREAD

**Issue by pvictorlv** [eduardokum/laravel-boleto#506]
Gostaria de saber se tem alguma forma de eu exibir o boleto para o cliente em tempo real e o mesmo poder efetuar o pagamento, sem que seja necessário o envio manual do arquivo para o banco. no caso eu estou usando o ITAU.

**Comment by adrianoGaspar** [comment]
Olá amigo, eu estou estudando ainda este pacote. Não sei exatamente como é feito o envio ao banco. De qqr maneira o que vc pode fazer é criar um comando no artisan (https://laravel.com/docs/5.8/artisan#generating-commands), colocar a rotina de envio do arquivo ao banco neste comando do artisan,  depois criar uma crontab (https://laravel.com/docs/5.8/scheduling) que execute este comando de tempo em tempo. Acho que o caminho é este.

**Comment by williamcastro** [comment]
Mas o problema ao meu ver não está na automatização de cronjobs, mas sim na integração com os bancos. Achei bem difícil achar os manuais de webservice, e conseguir habilitar para as empresas.

**Comment by adrianoGaspar** [comment]
Olá William, eu nunca havia trabalhado com boletos bancários e agora implementando o pacote em um sistema que desenvolvi que percebi a sua dificuldade. Também tenho a mesma dúvida. Se alguém puder ajudar agradeço e sigo acompanhando.

**Comment by marcuscarvalho6** [comment]
Olá, eu consegui fazer isso com a caixa. Conversa com o banco e solicita integração van e remessa online (boletos registrados em até 15 minutos) isso para o caso da caixa. Não sei como se comportaria para outros bancos. Sobre a VAN da caixa eu consegui fazer uma adaptação e rodar um .sh que dentro do Linux para ele copiar os Arquivos .rem para o servidor da Neogrid que faz o processamento.

**Comment by meirinaldojunior** [comment]
É possível integrar com Bradesco também, segue documentação e SDK em PHP:
- Documentação Bradesco:  https://github.com/vitorccs/bradesco-api-php/files/2332693/Manual_Registro_de_Boleto_Bancario_Online_Dez17.pdf
- SDK PHP: https://packagist.org/packages/vitorccs/bradesco-api-php

**Comment by mendesalexandre** [comment]
Pessoal, segue a forma de comunicação com a api do Sicredi. Confesso que ainda estou implementando aqui, mas em breve trago mais novidades. [API SICREDI](https://drive.google.com/file/d/12dNlzHCTFBHTJ1Wplp7lVDMRPoo-y6f2/view?usp=sharing)
