### ISSUE TITLE
De que forma posso remover a imagem Sem Logo

### ISSUE THREAD

**Issue by Rarfael** [eduardokum/laravel-boleto#514]
**Questão**
De que forma consigo remover a imagem SEM LOGO que aparece quando a empresa não tem logo, caso a empresa não utilize logo nos boletos.

**Comment by renanBritz** [comment]
Então... era pra ter como dar um publish nas views, afinal isso era pra ser um pacote Laravel. Mas nem ServiceProvider tem?

Acho que tem que dar um fork :/

**Comment by Rarfael** [comment]
Por fim optei por setar uma imagem default em branco, quando a empresa não tem logo. Não foi a solução mais elegante, mas resolveu o probléma.
