### ISSUE TITLE
Registro via API do Bradesco com Código de Barras diferente

### ISSUE THREAD

**Issue by meirinaldojunior** [eduardokum/laravel-boleto#515]
**Questão**

Olá, estou realizando o registro do boleto via API do Bradesco, sendo que quando vou criar o boleto com **laravel-boleto** na 3ª posição da linha digitável do boleto gerado pela biblioteca, não bate com a linha digitável do boleto registrado retornado pela API do Bradesco, sabem informar o que pode está  acontecendo?

**Comment by meirinaldojunior** [comment]
Pessoal, encontrei o problema: era necessário informar o digito da conta em um parâmetro separado.

**Comment by IcaroRios** [comment]
Estou tendo este erro. Pode mostrar o que está enviando? pois mesmo separando o dígito da conta, não tive sucesso.

**Comment by meirinaldojunior** [comment]
E aí @IcaroRios, consegue qual bloco o código está incorreto?

**Comment by IcaroRios** [comment]
Obrigado por abrir.
A diferença é no segundo, terceiro e dígito verificador. Eu até tentei colocar direto o que eu recebia da API, más estou recebendo uma combinação de Ws e Ns no código de barras. :/

Recebido pela api:   23793.02108 90189.000004 01005.212103 4 83120000001000
Gerado pelo pacote:23793.02108 90000.000001 06005.212102 6 83120000001000

**Comment by eduardokum** [comment]
Ola, o gerado pela esta usando o nosso numero  01890000001 e o gerado pelo pacote esta usando o nosso numero 00000000006


![image](https://user-images.githubusercontent.com/2566340/86986522-46fe8180-c16a-11ea-929b-742ca51d534c.png)

![image](https://user-images.githubusercontent.com/2566340/86986532-4cf46280-c16a-11ea-9527-127bb27afd0f.png)

**Comment by IcaroRios** [comment]
O Nosso número que tenho salvo é: 1890000001.
Más gerando o boleto com os dados:
                `'logo' => public_path().'/img/logo.png',
                'dataVencimento' => \Carbon\Carbon::create($this->data_vencimento),
                'dataProcessamento' => \Carbon\Carbon::create($this->data_emissao),
                'valor' => $this->valor_original,
                'campoNossoNumero' => $this->texto_numero_titulo_cobranca,
                'numero' => $this->id,
                'numeroDocumento' => $this->id,
                'pagador' => $pagador,
                'beneficiario' => $beneficiario,
                'carteira' => env('BRADESCO_CARTEIRA'),
                'agencia' => env('BRADESCO_AGENCIA'),
                'convenio' => env('BRADESCO_CONVENIO'),
                'conta' => env('BRADESCO_CONTA'),
                'contaDv' => env('BRADESCO_CONTA_DIG'),
                'multa' => 4, // 1% do valor do boleto após o vencimento
                'juros' => 2, // 1% ao mês do valor do boleto
                'jurosApos' => 1, // quant. de dias para começar a cobrança de juros,`
O nosso numero ficou null e no boleto apareceu este : 00000000006

**Comment by eduardokum** [comment]
Fiz a geração com os mesmos dados do que vc informou na api, os numeros batem, você deve estar passando algum dado errado para o objeto. segue o pdf 
[bradesco.pdf](https://github.com/eduardokum/laravel-boleto/files/4898575/bradesco.pdf)
![image](https://user-images.githubusercontent.com/2566340/87073562-f92e5b80-c1f3-11ea-8081-7e6638a0a317.png)


```php
$boleto = new Eduardokum\LaravelBoleto\Boleto\Banco\Bradesco(
    [
    'logo' => realpath(__DIR__ . '/../logos/') . DIRECTORY_SEPARATOR . '237.png',
    'dataVencimento' => \Carbon\Carbon::createFromDate(2020, 7, 10),
    'valor' => 10,
    'multa' => false,
    'juros' => false,
    'numero' => '1890000001',
    'numeroDocumento' => 1,
    'pagador' => $pagador,
    'beneficiario' => $beneficiario,
    'carteira' => '09',
    'agencia' => 3021,
    'conta' => 52121,
    'descricaoDemonstrativo' => ['demonstrativo 1', 'demonstrativo 2', 'demonstrativo 3'],
    'instrucoes' =>  ['instrucao 1', 'instrucao 2', 'instrucao 3'],
    'aceite' => 'S',
    'especieDoc' => 'DM'
    ]
);
```

**Comment by IcaroRios** [comment]
Percebi o meu erro.
Você enviou :
`'numero' => '1890000001',`
Eu:
`'campoNossoNumero' => $this->texto_numero_titulo_cobranca,`
`'numero' => $this->id,`
Após parar de enviar o campo nosso numero e enviar o número realmente. Resolvi os problemas.

**Comment by eduardokum** [comment]
Disponha.! Fechando.
