### ISSUE TITLE
Arquivo de Remessa Bancoob - Data do Juros de Mora

### ISSUE THREAD

**Issue by jnatanael** [eduardokum/laravel-boleto#516]
**Descreva o bug**
Após gerar o arquivo de remesa, efetuei a validação do arquivo no validador do SICCOB. Nesta validação gerou o seguinte erro: Data do Juros de Mora - Data de vencimento do juros deve ser superior a data de vencimento do titulo. Este erro ocorre tanto no Segmento P, quanto no Segmento R.

**Solução encontrada**
Verificando a classe responsável por gerar o arquivo de remessa do SICCOB, verifiquei que esta data é a mesma data de vencimento do título. Minha solução foi somar a esta data +1 dia para corrigir o erro.

**Comment by adrianoGaspar** [comment]
Olá amigo, estou com o mesmo problema, encontrei o método $boleto->setJurosApos() e acredito ser os dias após vencimento para cobrança de juros, mas da multa não encontrei nada.
Poderia detalhar mais como resolveu o problema por favor?

**Comment by jnatanael** [comment]
Ola amigo, como você descreveu em sua postagem. Tive que fazer a mesma coisa!

**Comment by eduardokum** [comment]
Alteração ja feita, possivelmente isso so de problema no validador, pois utilizo dessa forma em clientes ja homologado e nao tenho problemas. Vou criar uma tag com as alteraçoes
