### ISSUE TITLE
Erro ao gerar exemplo

### ISSUE THREAD

**Issue by mprandot** [eduardokum/laravel-boleto#52]
Olá!

Estou com um problema para gerar um boleto de exemplo...
Estou pegando o exemplo do README, mas a tela fica branca e não aparece nada (usando renderHTML ou renderPDF), pode verificar por favor?

Não apresenta erro na tela, no console e no laravel.log.

**Comment by adrianoGaspar** [comment]
Tenho o mesmo problema. Como resolveu?
