### ISSUE TITLE
Boleto com dois descontos e duas datas de desconto

### ISSUE THREAD

**Issue by alexandreubaldo** [eduardokum/laravel-boleto#520]
Hoje é possível configurar um desconto e uma data de desconto através de `setDesconto` e `setDataDesconto`.

Na prática é muito comum e presente nos bancos a possibilidade de dar vários descontos, sendo que a utilização de 2 descontos é prática comum em algumas industrias. 

Para ilustrar busquei a referência em alguns dos manuais disponibilizados no projeto.

**Santander**
Página 20, nota 23 do documento: H7815 Layout Cobrança CNAB 240 posições padrão Santander Multibanco Abril
Página 8, na posição 71 e página 9 na posição 206 no documento 400_posicoes.pdf

**Caixa**
Página 30, campo 08.3R até 10.3R no documento: 240_posicoes.pdf
Página 45, campo NE057 no documento: 400_posicoes.pdf

**Comment by eduardokum** [comment]
Hoje não existe esse possibilidade, teria alguem com esse interesse desenvolver. 

Desculpe o incovenimente.
