### ISSUE TITLE
Banco e Agência no Retorno

### ISSUE THREAD

**Issue by Alecostantini** [eduardokum/laravel-boleto#521]
Prezados, bom dia.

Estou precisando extrair o número do banco e agência de cobrança onde o título foi pago.

Já identifiquei as posições no manual do banco onde constam estas informações:
Segmento T
Pos Banco: 97 99
Agencia: 100 104
Dig Agencia: 105 105

Poderiam me auxiliar como realizar está alteração adicionando estes dados no processamento do arquivo de retorno?

Obrigado pela atenção.

**Comment by eduardokum** [comment]
Tem como receuperar essas informacoes https://github.com/eduardokum/laravel-boleto/blob/master/exemplos/bradesco_retorno.php

so ver o dump que vai ver todas as informacoes que tem disponivel ou pode utilizar qualquer um desses metodos em cada iteracao do retorno https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Retorno/AbstractRetorno.php
