### ISSUE TITLE
BRADESCO

### ISSUE THREAD

**Issue by souza-17** [eduardokum/laravel-boleto#525]
estou usando o exemplos do Bradesco,
mas não estou conseguindo executar o processo de retorno poderia mostra um caso onde gere boleto registrado, e geração dos arquivos completos de remessa e retorno

**Comment by adrianoGaspar** [comment]
Olá amigo, estou trabalhando agora com o Bradesco, mas já homologuei o SICOOB.
Para gerar a remessa vc deve instanciar o objeto 
Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab240\Banco\Bradesco;
ou
Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab400\Banco\Bradesco;
conforme a CNAB desejada.
Depois utilize os métodos
            ->setBeneficiario($beneficiario)
            ->setIdremessa(id sequencial da remessa)
            ->setCarteira(carteira)
            ->setAgencia(agência)
            ->setCodigoCliente('12345678901234567890')
            ->setConta(conta bancária);

            ->addBoleto($boleto);//passe o objeto do boleto

            ->download('remessa_bradesco.rem');
O arquivo de retorno é fornecido pelo banco. Vc deve upá-lo e fazer os tratamentos.
