### ISSUE TITLE
Inserir código de barras recebido pela API do banco

### ISSUE THREAD

**Issue by rogersxd** [eduardokum/laravel-boleto#526]
É possível inserir o código de barras que recebo da API do Banco? Percebi que ele gera automaticamente.

**Comment by MatDevV** [comment]
@rogersxd conseguiu resolver? Estou com o mesmo problema

**Comment by adrianomarinho** [comment]
Também gostaria de fazer isso com o código de barras e linha digitável.

**Comment by fonini** [comment]
Pessoal, eu enfrentei o mesmo problema. Fiz um fork e implementei os métodos `getNossoNumero()` (que será usado internamente para retornar o nosso número que vamos passar, ao invés daquele gerado pelo pacote), `setCodigoBarras()` e `setLinhaDigitavel()`.

Commit: https://github.com/fonini/laravel-boleto/commit/7350ce758d3f975d8df3bb3875a04acfc82dd434

Daí é só chamar esses métodos quando for renderizar o boleto.

Ex: 

```
$boleto = new Sicredi();
$boleto->setNumero(100000)
       ->setCodigoBarras(56456456456456)
       ->setLinhaDigitavel(67567546546);
```
