### ISSUE TITLE
new Banrisul crashing Laravel

### ISSUE THREAD

**Issue by fredimaihub** [eduardokum/laravel-boleto#527]
Ao tentar criar um new Banrisul, o Laravel simplesmente fecha o php artisan serve sem mensagens de erro ou exception.

estou passando os parametros:
'logo'
'dataVencimento'
'valor'
'multa'
'juros'
'numero'
'numeroDocumento'
'pagador'
'beneficiario'
'carteira'
'agencia'
'conta'
'descricaoDemonstrativo'
'instrucoes'
'aceite'
'especieDoc'

**Comment by adrianoGaspar** [comment]
Pelo que entendi o servidor do php (server) para, imagino que seja isso. Muito estranho. Vc deve verificar os logs do server e do laravel

**Comment by fredimaihub** [comment]
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Users/fredos/Documents/syshasm/vendor/eduardokum/laravel-boleto/src/Util.php on line 707

Alterando o "break" para "continue 2" ele continua crashando

**Comment by eduardokum** [comment]
qual versao do php? somente via artisan? e com a pagina rodando em um apache ou nginx da o mesmo problema?

**Comment by fredimaihub** [comment]
acredito que seja porque estava rodando a biblioteca em uma versão mas antiga no php7.2
