### ISSUE TITLE
leitura de arquivo de retorno de banco

### ISSUE THREAD

**Issue by fredimaihub** [eduardokum/laravel-boleto#530]
a biblioteca não lê um pagamento feito após a data de vencimento do boleto no arquivo de retorno do banco Banrisul.

`10203066309001144665073144002805076                           0002289407                                   106111119    0228940002289407          10111900000000080001044135108000000000026300000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000   121119                                         15                                                  000020`

**Comment by eduardokum** [comment]
desconheço isso, preciso de mais informacoes, aqui funciona a leitura normalmente.

**Comment by fredimaihub** [comment]
acredito que seja pela versão do php e biblioteca... php5.6

**Comment by mobidrive** [comment]
Gostaria de um contato para orçamento. Preciso implantar no meu sistema.
