### ISSUE TITLE
Data de Multa e Juros após vencimento SOCOOB

### ISSUE THREAD

**Issue by adrianoGaspar** [eduardokum/laravel-boleto#533]
**Descreva o bug**
Ao tentar homologar a remessa do SICOOB, o banco me passou a seguinte situação:

1. Corrigir no detalhe do arquivo remessa, segmento P, posições 119 a 126, a data para cobrança de juros. Deverá ser informada um dia após o vencimento do título.

2. Corrigir no detalhe do arquivo remessa, segmento R posições 067 a 074, a data para cobrança de multa. Deverá ser informada um dia após o vencimento do título.

Tentei utilizar o método  $boleto->setJurosApos(1); mas não alterou nada, então verifiquei no arquivo Bancoob.php do pacote as seguintes linhas:
Linha 146
`$this->add(119, 126, ($boleto->getJuros() !== null && $boleto->getJuros() > 0) ? $boleto->getDataVencimento()->format('dmY') : '00000000');`

Linha 247
`$this->add(67, 74, $boleto->getMulta() > 0 ?  $boleto->getDataVencimento()->format('dmY') : '00000000');`

Percebam que se houver Multa ou Juro, é inserida no arquivo a data de vencimento do boleto. Segundo o banco isso está errado, eles exigem ao menos 1 dias após o vencimento para cobrança de Multa e Juros.

Como corrigi para o meu caso:
Na linha 146 substitui por:
`$this->add(119, 126, $boleto->getJurosApos() === false ? '00000000' : $boleto->getDataVencimento()->copy()->addDays($boleto->getJurosApos())->format('dmY'));`
-- Neste caso o método $boleto->setJurosApos(1); adiciona um dia além do vencimento. Aqui ficou legal pq estamos tratando o juro.

Na linha 247 substitui por
`$this->add(67, 74, $boleto->getJurosApos() === false ? '00000000' : $boleto->getDataVencimento()->copy()->addDays($boleto->getJurosApos())->format('dmY'));`
-- Neste caso o método $boleto->setJurosApos(1); adiciona um dia além do vencimento. Aqui ficou ruim pq estamos tratando a multa. O certo era ter um metodo setMultaApos().

Se puderem efetuar essa correção em um merge seria muito interessante pois eu não posso atualizar o pacote por tê-lo alterado.

**Comment by jnatanael** [comment]
Boa noite Adriano!
Tive que fazer a mesma coisa para resolver este problema!

**Comment by adrianoGaspar** [comment]
Boa noite Jnatanael, para evitar ter que alterar o pacote, eu criei um Repository no laravel onde extendi a classe Eduardokum\LaravelBoleto\Boleto\Banco\Bancoob onde criei 2 métodos:
```
    /**
     * Dias apos vencimento do boleto para aplicar a multa
     *
     * @var int
     */
    protected $multaApos = 0;

    /**
     * Seta a quantidade de dias apos o vencimento do boleto para aplicar a multa
     *
     * @param  int $multaApos
     *
     * @return AbstractBoleto
     */
    public function setMultaApos($multaApos)
    {
        $multaApos = (int)$multaApos;
        $this->multaApos = $multaApos > 0 ? $multaApos : 0;

        return $this;
    }

    /**
     * Retorna a quantidade de dias apos o vencimento do boleto para aplicar a multa
     *
     * @return int
     */
    public function getMultaApos()
    {
        return $this->multaApos ? $this->multaApos : false;
    }
``` 
Depois Criei outro Repository onde extendi a classe Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab240\Banco\Bancoob
e sobrescrevi os métodos:
```
    protected function segmentoP(BoletoContract $boleto) {
e
    protected function segmentoR(BoletoContract $boleto) {

```
Substituindo a linha 146 conforme descrito no comentário anterior e a linha 247 eu substitui por:
`        $this->add(67, 74, $boleto->getMultaApos() === false ? '00000000' : $boleto->getDataVencimento()->copy()->addDays($boleto->getMultaApos())->format('dmY'));//Linha editada do pacote para inserir numero de dias após vencimento para aplicar multa
`
O boleto eu instanciei como meu Repository que extende de Boleto e apliquei o método para incluir os dias da multa.

```
        $boleto = new BoletoBancoobRepository();
        $boleto->setMultaApos(2);//cobrar multa 2 dias após vencimento

```

**Comment by eduardokum** [comment]
Fiz um update em develop com essa alteração, usando jurosApos em vez de multaApos, ate o fim do dia coloco em uma tag
