### ISSUE TITLE
Não está gerando juros na remessa do Bradesco, mesmo setando no boleto.

### ISSUE THREAD

**Issue by adelioreis** [eduardokum/laravel-boleto#534]
**Descreva o bug**
Não está gerando juros na remessa do Bradesco, mesmo setando no boleto.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Instancie a classe Eduardokum\LaravelBoleto\Boleto\Banco\Bradesco;
2. Envie os dados: ->setJuros(0.05)->setJurosApos(0)
3. Veja o erro: não gera nada nos campos destinados a juros na remessa

**Comportamento esperado**
Deveria ser gerado informações sobre juros no arquivo de remessa cnab400;

**Desktop (por favor, complete as seguintes informações):**
 - OS: Win10
 - Versão do PHP 7.1
 - Versão do Laravel 5.7

**Comment by hkanata** [comment]
Se não me enganoo valor setado em setJuros() são enviados para o banco fazer o calculo a partir do valor que vc definir, pois o cliente pode optar em pegar a segunda via(ja vencida) no site do banco.

**Comment by adelioreis** [comment]
É justamente isso que não está acontecento, veja que coloquei "Não está gerando juros na remessa..."

**Comment by eduardokum** [comment]
Brasco so utiliza valor de multa, e valor de mora dia, nào existe onde passar o percentual juros.
