### ISSUE TITLE
Banco Safra

### ISSUE THREAD

**Issue by cacio** [eduardokum/laravel-boleto#536]
Gostaria de saber se rola fazer o do banco safra, eu comecei a implementar o banco mas estou me deparando com um erro na linha digitável eo calculo do DAC não ta fechando estou colocando na seguencia o campolivre mas não ta gerando correto se alguem me ajudar eu agradeço 

 protected function getCampoLivre()
    {
        if ($this->campoLivre) {
            return $this->campoLivre;
        }
		//echo substr($this->getCodigoCliente(),5,9)."<br/>";

		$campoLivre  = '7';
		$campoLivre .= Util::numberFormatGeral($this->getAgencia(), 4);
		$campoLivre .= substr(Util::numberFormatGeral($this->getAgencia(), 4),-1,1);		
		$campoLivre .= substr($this->getCodigoCliente(),5,9);        
        $campoLivre .= substr($this->getNossoNumero(),3,9);
        $campoLivre .= '2';
        $campoLivre .= '000';		
		//echo $campoLivre;
        return $this->campoLivre = $campoLivre;
    }

**Comment by edigomes** [comment]
Rapaz, eu fiz aqui só não mandei o pull request pq não fiz os testes ainda,
se quiser pegar do meu fork, tá funcionando...

Em qua, 11 de dez de 2019 14:21, Cacio <notifications@github.com> escreveu:

**Comment by cacio** [comment]
Aham, to tentando achar o teu fork aqui mas ta difícil, que dai eu posso compara com oque eu tenho aqui seria ótimo

**Comment by edigomes** [comment]
Só entrar no meu profile só Github e procurar o repositório.

Em qui, 12 de dez de 2019 18:24, Cacio <notifications@github.com> escreveu:

**Comment by cacio** [comment]
Obrigado , eu consegui homologar o banco estava passando um parâmetro do nosso numero errado tava indo o dv junto mas tem que ir o nosso numero sem o dv , obrigado!.

**Comment by eduardokum** [comment]
Infelizmente não tem como colocar o banco, ja tinha fui obrigado a tirar devido a solicitação da consultoria jurica do banco
