### ISSUE TITLE
Erro ao renderizar HTML

### ISSUE THREAD

**Issue by felipe-ogestor** [eduardokum/laravel-boleto#537]
Olá amigo, identifiquei aqui que ao renderizar um boleto em HTML, ele dá o seguinte erro: **syntax error, unexpected '!'** no arquivo **laravel-boleto/src/Boleto/Render/view/partials/ficha-compensacao.blade.php**.

Eu fiz um teste aqui e nesse trecho: `<td {{ !isset($mostra_cip) || !$mostra_cip ? 'colspan=2' : ''}}>` basta colocar as 2 verificações dentro de parênteses que resolve o problema. 
Ficaria tipo assim: `<td {{ (!isset($mostra_cip) || !$mostra_cip) ? 'colspan=2' : ''}}>`

Estou utilizando PHP 7.2 e Laravel 5.6.

**Comment by eduardokum** [comment]
Opa, vou subir essa alteração entao.
