### ISSUE TITLE
Erro processar retorno BB

### ISSUE THREAD

**Issue by ThorAesir** [eduardokum/laravel-boleto#54]
Olá, boa tarde.

estou tentando executar o exemplo do processamento do retorno, mas tem retornado esse erro:

> Fatal error: Call to undefined function Eduardokum\LaravelBoleto\Cnab\Retorno\Cnab400\Banco\array_get() in C:\xampp\htdocs\vendor\eduardokum\laravel-boleto\src\Cnab\Retorno\Cnab400\Banco\Bb.php on line 222

o arquivo é: exemplos/bb_retorno.php

Desde ja agradeço a atenção, obrigado.

**Comment by edigomes** [comment]
Vc está usando Laravel? esta lib necessita de algumas funções que são helpers do framework Laravel, por isso tá dizendo que a função arrau_get() não existe, mas isso não impede vc de usar a lib, pode implementar o que precisar do Laravel na sua App, só que vai dar um certo trabalho.

**Comment by eduardokum** [comment]
provavelmente voce tem que dar um composer install para instalar o illumate/support que ele instala essas funções que usa no projeto.
