### ISSUE TITLE
Migrate para salvar boletos remessa e nosso número

### ISSUE THREAD

**Issue by adrianoGaspar** [eduardokum/laravel-boleto#540]
**Questão**
Boa tarde a todos.
Estou me deparando com uma dificuldade. Como criar as tabelas para salvar boletos remessa e nosso número.
Conforme os problemas vão surgindo estou atualizando as tabelas mas gostaria de uma dica de alguém que já resolveu isso para mostrar como seria a maneira mais adequada para salvar esses dados.
Estou pensando em criar uma tabela só para controlar o nosso número.
O detalhe é que uso mais de um banco na mesma aplicação.
Agradeço qqr contribuição

**Comment by luizmagao** [comment]
Use o ID, é o que eu faço. Porém comecei por um número enorme, e por aí vai.

**Comment by Rainzart** [comment]
Na tabela de cadastro de banco deixo armazenado o último nosso número e o último número da remessa, assim tenho numerações diferentes por banco.

Todos meus boletos são vinculados a títulos, ou seja, o cliente gera o titulo (que é uma cobrança) e esse título pode ou não ter boleto. Nesse titulo tenho 2 campos, Número e Parcela e uso eles para compor o "Seu número" ou "Número do Participante".

No começo usei o ID, porém recebi algumas reclamações de numeração muito alta e uma dificuldade em saber referente à qual título aquele boleto pertencia apenas olhando o boleto impresso.

**Comment by adrianoGaspar** [comment]
Fiz o seguinte:
Meu cliente utiliza mais de um banco, neste caso eu criei uma tabela de configurações de boleto para cada banco. Criei uma tabela numero_boleto onde armazeno o último numero gerado e o id da configuração de boleto. Assim sei de qual banco o boleto está sendo gerado e também o último número gerado para os boletos deste banco. Incremento o nosso número e gero o boleto. Assim ao gerar o próximo boleto, sabendo o último número gerado sei qual seve ser o próximo.
