### ISSUE TITLE
str_random undefined na impressão de PDF

### ISSUE THREAD

**Issue by Rainzart** [eduardokum/laravel-boleto#542]
Na classe Eduardokum\LaravelBoleto\Boleto\Render\PDF, método gerarBoleto(), linha 477 é usado o helper str_random() que desde o Laravel 5.8 foi removido do core.
Eu iria fazer um PR porém existem 2 formas de resolver, uma trocando o código:
`$nameFile = str_random(32);`
por:
`$nameFile = \Illuminate\Support\Str::random(32);`

Ou adicionado ao composer o package 

`composer require laravel/helpers`

Qual ficaria melhor?

 - Versão do PHP 7.2
 - Versão do Laravel 6.10.0

**Comment by eduardokum** [comment]
Opa! ja aceitei o seu PR la em develop, logo mais subo pra master
