### ISSUE TITLE
Arquivo de remessa Sicredi

### ISSUE THREAD

**Issue by lucasimpacto** [eduardokum/laravel-boleto#543]
Estou criando um arquivo de remessa de correção que utiliza a opção 31 pra a posição 109-110 no caso, preciso especificar a opção que pretendo usar na posição 71.

**Comment by eduardokum** [comment]
para alterar os dados vc tem que usa o ->alterarBoleto(); que ele ja adiciona isso sozinho a posicao 109-110 agora a posicao 71 eu desconheco o conteudo, teria que ver no manual o que vai nela, hoje a nasse ela é preenchida com nada hardcoded, não tendo como passar nada ali.
