### ISSUE TITLE
Alteração de boleto

### ISSUE THREAD

**Issue by adrianoGaspar** [eduardokum/laravel-boleto#545]
**Questão**
Escreva sua questão aqui.
Olá a todos, já homologuei Bradesco e Bancoob, ambos com CNAB 240, porém tenho uma dúvida que gostaria de sanar  antes de sair testando nos boletos válidos.
Como altero um boleto (sem cancelar)?
Seria gerar o mesmo boleto (mantendo o número ou o nosso número??), alterando data de vencimento valor ou outros campos e depois executar os métodos 

$boleto->alterarBoleto();
$remessa->addBoleto($boleto);

E enviar a nova remessa? Se alguém puder explicar em detalhes tenho certeza que ajudará muitos.

**Comment by voope** [comment]
alguem tem uma resposta pra isso ?

**Comment by eduardokum** [comment]
isso, porem somente poucos dados da pra ser alterado via remessa, tem que ver no manual do banco qual dados é permitidos, se vc mandar o todos os dados de identificacao do boleto o mesmo e chamar um $boleto->alterarBoleto(); e enviar a remessa ele vai alterar esses dados, porem valores juros essas coisas acredito que os bancos nao liberem, tem a opcao de $boleto->alterarDataDeVencimento();
