### ISSUE TITLE
Erro ao baixar o PDF gerado

### ISSUE THREAD

**Issue by duard** [eduardokum/laravel-boleto#546]
Gero meu boleto corretamente na pasta public porém ai baixar o mesmo ele não encontra.

link gerado (fica sem o publice da erro 404 ao baixar o pdf) https://meu-dominio.com.br/arquivos/SICOOB/meu-boleto.pdf

```
$caminhoGerar = arquivos/SICOOB/meu-boleto.pdf ;
$pdf->gerarBoleto($pdf::OUTPUT_DOWNLOAD, $caminhoGerar);

```
Quando vai retornar o PDF da erro 404 pois precisa de "public" no retorno do pdf.

**Comment by adrianoGaspar** [comment]
Olá, o erro 404 indica que o arquivo não foi encontrado no caminho passado. Ele realmente está na pasta public? Vc conferiu?
Outra coisa, procure utilizas assets() ao passar o caminho no laravel.

**Comment by duard** [comment]
@adrianoGaspar quando uso o gerar boleto, passo o caminho  'arquivos/SICOOB/meu-boleto.pdf' ele gera dentro da pasta **public/arquivos/SICOOB/meu-boleto.pdf**

porém quando ele tenta baixar ele usa **arquivos/SICOOB/meu-boleto.pdf** e isto causa 404 

Este projeto funcionava até 1 mêss atrás. Apenas atualizei o composer.

**Comment by adrianoGaspar** [comment]
Que estranho. Eu trabalho armazenando o boleto na AMAZON S3 e depois puxo ele pelo link gerado, mas eu não utilizo o parâmetro Download. Eu gero o arquivo como string.
Verifiquei que existem estes parâmetros que podem ser enviado no método Gerar Boleto:
     * I: send the file inline to the browser.<br>
     * D: send to the browser and force download.<br>
     * F: save to a local<br>
     * S: return as a string. name is ignored.
Talvez vc possa tentar com outros parâmetros para testar.

**Comment by eduardokum** [comment]
Isso mesmo pra salvar em um arquivo tem que usar o OUTPUT_SAVE que a classe vai gerar o arquivo e se quiser usar o Files do laravel pra salvar no seu file system tem que usar algo do tipo

Storage::disk('local')->put('boleto.pdf', $pdf->gerarBoleto($pdf::OUTPUT_STRING));

o OUTPUT_DOWNLOAD ele da um echo no conteudo do boleto e modifica do header da pagina pra content download, ai não grava em lugar nenhum
