### ISSUE TITLE
Retorno banco Safra

### ISSUE THREAD

**Issue by dxtever** [eduardokum/laravel-boleto#547]
Boa tarde,
seria possível adicionar o código do banco safra(422) na interface Eduardokum\LaravelBoleto\Contracts\Boleto\Boleto.php

Criei uma classe para realizar a leitura do retorno do safra , porém tenho um exception que o banco é invalido devido ao código não estar nas constantes de bancos válidos.
Att,

**Comment by eduardokum** [comment]
não, infelizmente não, o banco safra atravez de acessoria juridica solicitou que tudo que vinculasse o nome desse banco fosse retirado do projeto.
