### ISSUE TITLE
CNPJ sem zeros na frente

### ISSUE THREAD

**Issue by Rainzart** [eduardokum/laravel-boleto#548]
Olá a todos.

Notei no arquivo _Cnab\Retorno\Cnab400\Header.php_, linha 276 tem um _ltrim()_ removendo zeros à frente.

`$this->codigoCliente = ltrim(trim($codigoCliente, ' '), '0');`

Tem algum motivo em especial para remover os primeiros zeros?

Particularmente armazeno em banco número de documentos como string, preservando todo o número e estou com um cliente em particular que possui um CNPJ que começa com 00.
Sendo assim no retorno recebo uma string(12) quando busco por `$retorno->getHeader()->getCodigoCliente()`.

**Comment by eduardokum** [comment]
O motivo é que tem muitas vezes mais 0 que o que vc informou, exemplo para retornoar um codigo 001234567  ele retorna 000000000001234567 ai é retirado os 0 por isso, se no caso vc usa uma quantidade de 0 fixas vc pode usar um pad comum ou retirar os 0 com um trim na hora da consulta no sql
