### ISSUE TITLE
$pagador = new \Eduardokum\LaravelBoleto\Pessoa

### ISSUE THREAD

**Issue by edsonrodsilva** [eduardokum/laravel-boleto#55]
$pagador = new \Eduardokum\LaravelBoleto\Pessoa([
    'nome' => 'Cliente',
    'endereco' => 'Rua um, 123',
    'bairro' => 'Bairro',
    'cep' => '99999-999',
    'uf' => 'UF',
    'cidade' => 'CIDADE',
    'documento' => '999.999.999-99',
]);

Quando chamamos a class Pessoa da erro Not Found.
Não deveria ter que registrar o provider?

**Comment by edigomes** [comment]
Dá uma testada pelo Tinker.

**Comment by eduardokum** [comment]
não na verdade a classe teria que ser carregada pelo seu composer autoload

**Comment by mrother** [comment]
Na verdade o namespace é diferente do que o documentado:

new \Eduardokum\LaravelBoleto\Boleto\Pessoa()

Abs

**Comment by eduardokum** [comment]
na realidade é esse mesmo

https://github.com/eduardokum/laravel-boleto/blob/master/src/Pessoa.php

Eduardokum\LaravelBoleto\Pessoa
