### ISSUE TITLE
Dá a mensagem: Campos requeridos pelo banco, aparentam estar ausentes Campo idremessa está em branco

### ISSUE THREAD

**Issue by profbaco** [eduardokum/laravel-boleto#552]
Estava usando esta lib na versão 0.7.8 com o PHP 7.1 sem nenhum problemas, mas o meu servidor de hospedagem disse que eu poderia utilizar a versão 7.3.
Estou fazendo os testes no meu cloud de teste, para o meu banco SICOOB, e a questão é que, quando eu tento gerar o arquivo na versão do PHP 7.3 o sistema acusa a seguinte mensagem:
===================
message: "Campos requeridos pelo banco, aparentam estar ausentes Campo idremessa está em branco",…}
===================
Estou passando os registros conforme abaixo:

> $remessa = new \Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab240\Banco\Bancoob([
'agencia'       => $conta->agencia,
'conta'         => $conta->conta,
'carteira'      => $conta->carteira,
'convenio'      => $conta->cedente,
'beneficiario'  => $beneficiario,
]);
$remessa->addBoletos($boleto);

E na versão do PHP 7.1 com a verdão do boleto 0.7.8 o arquivo é gerado sem problemas, nas ma versão 7.3 com a versão 0.8.8 e o erro sempre aparece.
Não posso deixar a versão do 0.7.8 no PHP 7.3 pois dá erro de valor inteiro.
Aguardo sugestões

**Comment by rafwell** [comment]
Você precisa chamar o método `$remessa->setIdremessa()` e definir manualmente o id da remessa.

**Comment by profbaco** [comment]
Resolvi adicionando o campo dentro do array de $remessa, ficando assim:

$remessa = new \Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab240\Banco\Bancoob([
'agencia' => $conta->agencia,
'conta' => $conta->conta,
'carteira' => $conta->carteira,
'convenio' => $conta->cedente,
'beneficiario' => $beneficiario,
'idremessa' => $conta->id,
]);

Com isto este ID vai ser sempre incremental, e o erro não apareceu mais

**Comment by hugohcn** [comment]
Show, isso me ajudou bastante! Executei uma migração para um cliente e o meu problema aconteceu com uma versão de PHP que não foi do 7.1 para 7.3. Foi no PHP 7.1 mesmo...

### _PHP 7.1.33-34+ (cli) (built: Feb 23 2021 15:05:35)_
