### ISSUE TITLE
"Só é possível criar um boleto com mais de 10 dígitos no nosso número quando a carteira é 21 e o convênio possuir 6 dígitos."

### ISSUE THREAD

**Issue by danilo123dez** [eduardokum/laravel-boleto#554]
Estou tentando gerar o boleto onde o "Nosso número" possui mais de 10 digitos, e a carteira é 18. porém quando é tentando gerar o boleto, dá esse erro. E na lista de carteiras disponiveis, não tem a carteira 21.

**Comment by eduardokum** [comment]
Olá bom dia, 

Qual erro?

Qual banco?

Se a carteira não tem na classe, é pq ou é uma carteira que ainda ninguém usou, nesse caso, precisa olhar a documentação e fazer as mudanças necessárias para incluir ela no projeto.
