### ISSUE TITLE
Atualização de título

### ISSUE THREAD

**Issue by hbtsmith** [eduardokum/laravel-boleto#555]
Olá PessoALL,

Uso esta ferramenta para gerar o título, eu gostaria de saber se há alguma forma de usar ela para atualizar o boleto, ou seja gerar um mesmo boleto que foi gerado anteriormente com mesmo código de barras, mas apenas realizar a atualização das informações, assim como é feito direto no site do Bradesco por exemplo:

https://www.ib2.bradesco.com.br/ibpfsegundaviaboleto/segundaViaBoletoPesquisarLinhaDigitavel.do

**Comment by rafwell** [comment]
Você pode usar a mesma ferramenta citada para atualizar os boletos que você gerar com este pacote.

Você também pode atualizar o vencimento do boleto usando este pacote, porém precisará gerar uma nova remessa pra informar ao banco que foi alterado o vencimento.
