### ISSUE TITLE
Projeto abandonado?

### ISSUE THREAD

**Issue by marcoprodata** [eduardokum/laravel-boleto#556]
**Questão**
Mestres, esse projeto foi abandonado? Vocês pretendem adicionar no boleto sicoob a opção de definir o número da parcela?

Desde já agradeço a atenção recebida.

**Comment by eduardokum** [comment]
Olá, bom dia, não esta abandonado, necessita somente de mais contribuição da comunidade.

Hoje eu não tenho essa necessidade, alguem que tenha e estiver disposto a desenvolver o projeto é aberto a contribuições.
