### ISSUE TITLE
Já estão homologados ?

### ISSUE THREAD

**Issue by PlaynowGames** [eduardokum/laravel-boleto#558]
Já estão homologados ?

**Comment by spacedog4** [comment]
Pelo que vi na documentação, está dizendo "Requer homologação"

**Comment by eduardokum** [comment]
Não tenho como saber quem utiliza qual, os que estão como "Requer homologação" são os que eu pessoalmente ainda não homologuei, porém acredito que todos devam estar, porém não tenho essa confirmação pois muitas pessoas utilizam o pacote sem feedback
