### ISSUE TITLE
Mudança nas regras SICOOB

### ISSUE THREAD

**Issue by adrianoGaspar** [eduardokum/laravel-boleto#559]
Olá a todos, recebi este comunicado do SICOOB informando mudanças nos arquivos de retorno:

ATENÇÃO ASSOCIADO SICOOB MAXICRÉDITO!!!

Informamos que a partir de 15/06/2020, haverá alteração do código da carteira de títulos no arquivo de retorno, segmento T, posição 58 (CNAB 240).

Além do código ‘1’ - COBRANÇA SIMPLES, o retorno passará a ter também os seguintes códigos: ‘2’-COBRANÇA VINCULADA / ‘3’-COBRANÇA CAUCIONADA / ‘4’- COBRANÇA DESCONTADA.

Os novos códigos já estão disponíveis no layout anexo.

Entre em contato com o desenvolvedor do seu sistema para realizar os ajustes necessários, a fim de obter a correta leitura do arquivo de retorno dos seus boletos.

Em caso de dúvidas a nossa área de suporte está disponível para atendê-los, através dos contatos (49) 3905-3925, opção 1 e 6 ou cobrancabacaria@maxicredito.coop.br.

Atenciosamente
Setor de Produtos Sicoob Maxicrédito
(49) 3905-3925 – www.maxicredito.coop.br

**Comment by eduardokum** [comment]
Aparentemente isso não precisa ser tratado no pacote, é somente o codigo da carteira, o novo valor estará disponivel no retorno como $retorno->getCarteira(), sendo 1 como antes ou agora sendo 1, 2, 3, 4, devendo você quando ler essa informação definir o que deve ser feito.
