### ISSUE TITLE
Problema na altura da logo do banco ao imprimir

### ISSUE THREAD

**Issue by mprandot** [eduardokum/laravel-boleto#56]
Ao mandar imprimir os boletos eu estou tendo um problema na logo do banco; ela está ficando um pouco mais para baixo do permitido, desconfigurando os boletos (em anexo);

Vocês estão com esse problema?
[E-SISCOM _ Sistema, Gestão _ ERP.pdf](https://github.com/eduardokum/laravel-boleto/files/684459/E-SISCOM._.Sistema.Gestao._.ERP.pdf)

**Comment by eduardokum** [comment]
Não e na realidade você tem bem mais problemas, não esta tendo quebra de páginas 2 boletos na mesma pagina e ainda vários\ outros problemas de espaçamento, acredito que deva ser algum problema na sua maquina de dev.

**Comment by mprandot** [comment]
Ótimo!
Vou verificar como posso ajustar!

Valeu @eduardokum! :D
