### ISSUE TITLE
Erro ao gerar boleto no formato HTML

### ISSUE THREAD

**Issue by Rafbannwart** [eduardokum/laravel-boleto#560]
**Questão**
Estou com problemas ao gerar o boleto em HTML, o erro que aparece é o seguinte, 

> Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable. in D:\xampp\htdocs\BOLETO_EDUARDOKUM\vendor\laravel\framework\src\Illuminate\Container\Container.php:978

a chamada que fiz foi a seguinte 

> return response($boleto->renderHTML());

desde já agradeço.

**Comment by eduardokum** [comment]
pode retornar somente return $boleto->renderHTML(); que ja contem as strings de header pronta para visualização
