### ISSUE TITLE
Erro homologação Caixa

### ISSUE THREAD

**Issue by MauricioTGomes** [eduardokum/laravel-boleto#561]
Estou tentando homologar os boletos da caixa, quando envio os 10 arquivos eles me dão o seguinte retorno:
"Erro de validação das especificações técnicas referentes ao código de barras, representação numérica e/ou fator de vencimento, conforme TERMO DE HOMOLOGAÇÃO"

Saberia me informar o que esta acontecendo ?

**Comment by cacio** [comment]
@MauricioTGomes não sei se tu conseguiu resolver eu também to passando por isso mas to olhando as novas especificação do código do cliente que não é 6 dígitos como dizem agora é 7 dígitos to alterando aqui no meu e vo manda os 10 boletos de volta pra ver se é essa situação mesma

**Comment by MauricioTGomes** [comment]
@cacio não, ainda estou tendo este problema, e não encontrei a solução, estamos trabalhando em uma solução também.

**Comment by eduardokum** [comment]
Bom dia, se tem um novo manual precisa ser refeito com as novas diretrizes, o que acontece é que quem ja tem homologado funciona normal, porém novas homologações seguem os novos critérios do novo manual, se puderem anexar o manual aqui para que possamos dar um olhada, e fazer as alterações necessárias para as nova homologações

**Comment by cacio** [comment]
[MO67119010  VERSÃO  ABRIL - 2020.pdf](https://github.com/eduardokum/laravel-boleto/files/4801240/MO67119010.VERSAO.ABRIL.-.2020.pdf)
[MO67126015.pdf](https://github.com/eduardokum/laravel-boleto/files/4801242/MO67126015.pdf)
Estou ainda com problema mandei com a correção que tinha dito em cima  mas volto como erro de 

Erro de validação das especificações técnicas referentes ao código de barras, representação numérica e/ou fator de vencimento, conforme TERMO DE HOMOLOGAÇÃO anexo.*
--

**Comment by cacio** [comment]
@eduardokum

**Comment by eduardokum** [comment]
Você utiliza 400 posições??

**Comment by MauricioTGomes** [comment]
@eduardokum sim, CNAB 400

**Comment by cacio** [comment]
inclusive a pouco eu tava debugando aqui e no getCampoLivre() na parte aonde tem  
 $campoLivre = $beneficiario. Util::modulo11($beneficiario);
eu deixei assim  $campoLivre = $beneficiario;
e gerou correto o codigo de barras , mas na hora de imprimir e eu vou bipar o codigo de barras do boleto ele não coloca os dois últimos números que faltam pra completar

**Comment by cacio** [comment]
teriam alguma dica pra me dar ?

**Comment by cacio** [comment]
ah lembrando aqui nessa parte tem que aumentar para 7 $beneficiario = Util::numberFormatGeral($this->getCodigoCliente(), 7);

**Comment by eduardokum** [comment]
então, na verdade pelo que vejo no manual so vai 6 ai mesmo 

![image](https://user-images.githubusercontent.com/2566340/85164032-1e096180-b23a-11ea-8f52-9a7dd30df3c5.png)

pelo que me parece nao mudou nada na geração do campo livre, que é o campo onde vai esses dados do boleto ai, como codigo e NN.

Pelo que vi no manual tem algumas mudanças so na remessa e retorno, essas são simples logo logo subo uma correção.

Porém no boleto, como geração de nosso numero e geração do campo livre, por esse manual que você enviou, não parece ter nenhuma mudança.

O nosso número continua 17 posições:
![image](https://user-images.githubusercontent.com/2566340/85164305-8c4e2400-b23a-11ea-9af6-46df544e96fe.png)

o campo livre é fixado em 25 posições, não pode ter mais que isso, e não tem como colocar 7 posições.

25 - 17 (NN) = 8
8 - 1 (DV campo livre) = 7
7 - 1 (DV Codigo beneficiário) 6
6 Posições do beneficiário.

Então não sei qual pode ser o problema do boleto estar com problema.

**Comment by cacio** [comment]
fico assim o  meu 
 protected function getCampoLivre()
    {
        if ($this->campoLivre) {
            return $this->campoLivre;
        }

        $nossoNumero = Util::numberFormatGeral($this->gerarNossoNumero(), 17);
		
        $beneficiario = Util::numberFormatGeral($this->getCodigoCliente(), 7);
		//echo $beneficiario;
		//. Util::modulo11($beneficiario)
        $campoLivre = $beneficiario;
        $campoLivre .= substr($nossoNumero, 2, 3);
        $campoLivre .= substr($nossoNumero, 0, 1);
        $campoLivre .= substr($nossoNumero, 5, 3);
        $campoLivre .= substr($nossoNumero, 1, 1);
        $campoLivre .= substr($nossoNumero, 8, 9);
        $campoLivre .= Util::modulo11($campoLivre);
				
        return $this->campoLivre = $campoLivre;
    }

**Comment by cacio** [comment]
porque o meu cliente tem o codigo benificiario de 8 digito sendo que no ultimo digito é o DV dele então fica 7

**Comment by MauricioTGomes** [comment]
@cacio Desta forma a caixa retorno o homologado com sucesso?

**Comment by eduardokum** [comment]
acredito que nao precisa do DV pelo que vi no manual, tenta passar somente os ultimos 6 numeros do codigo do beneficiario

**Comment by eduardokum** [comment]
No manual mostra a composição do codigo de barras, e nele o codigo do beneficiario esta com 7 posições, sendo que 1 deleas é o DV

![image](https://user-images.githubusercontent.com/2566340/85166901-590d9400-b23e-11ea-9ba9-0607fec06fb4.png)

**Comment by eduardokum** [comment]
tenta para ver se aprova

```
/**
     * Método para gerar o código da posição de 20 a 44
     *
     * @return string
     * @throws \Exception
     */
    protected function getCampoLivre()
    {
        if ($this->campoLivre) {
            return $this->campoLivre;
        }

        $nossoNumero = Util::numberFormatGeral($this->gerarNossoNumero(), 17);
        $beneficiario = Util::numberFormatGeral(substr($this->getCodigoCliente(), -6), 6);

        $campoLivre = $beneficiario . Util::modulo11($beneficiario);
        $campoLivre .= substr($nossoNumero, 2, 3);
        $campoLivre .= substr($nossoNumero, 0, 1);
        $campoLivre .= substr($nossoNumero, 5, 3);
        $campoLivre .= substr($nossoNumero, 1, 1);
        $campoLivre .= substr($nossoNumero, 8, 9);
        $campoLivre .= Util::modulo11($campoLivre);
        return $this->campoLivre = $campoLivre;
    }
```

**Comment by cacio** [comment]
@MauricioTGomes  eu mandei a pouco pro banco vamos ver se vai homologar , eu fiz no Excel os cálculos e aparentemente os código de barra deu certo gero bonito conforme os cálculos

**Comment by eduardokum** [comment]
Ok, me avise qualquer coisa.

**Comment by cacio** [comment]
@eduardokum  Assim que eu tiver retorno do banco eu aviso obrigado

**Comment by cacio** [comment]
galera bom dia, homologuei o boleto na caixa de tudo certo 
o campo livre meu fico assim , foi com esse que consegui homologar

protected function getCampoLivre()
{
if ($this->campoLivre) {
return $this->campoLivre;
}

    $nossoNumero = Util::numberFormatGeral($this->gerarNossoNumero(), 17);
	
    $beneficiario = Util::numberFormatGeral($this->getCodigoCliente(), 7);
	//echo $beneficiario;
	//. Util::modulo11($beneficiario)
    $campoLivre = $beneficiario;
    $campoLivre .= substr($nossoNumero, 2, 3);
    $campoLivre .= substr($nossoNumero, 0, 1);
    $campoLivre .= substr($nossoNumero, 5, 3);
    $campoLivre .= substr($nossoNumero, 1, 1);
    $campoLivre .= substr($nossoNumero, 8, 9);
    $campoLivre .= Util::modulo11($campoLivre);
			
    return $this->campoLivre = $campoLivre;
}

**Comment by eduardokum** [comment]
Blza, vou ter que fazer algumas alterações pra funcionar pois ainda tem codigos de 6 numeros, se colocar assim vai dar erro, então vou fazer uma checagem antes de gerar esse campo. 


Mais obrigado pela ajuda.
