### ISSUE TITLE
Ler codigo de barras

### ISSUE THREAD

**Issue by gutofurlan** [eduardokum/laravel-boleto#567]
Bom dia pessoal, essa lib permite ler o codigo de barras e interpretar o valor, data de vencimento, multa e juros de qualquer boleto ? 
Caso não de, tem alguma lib q permite?
Obrigado

**Comment by eduardokum** [comment]
Bom dia, tem uma classe de utilidades no pacote que faz isso sim, é Util::IPTE2Variveis('linha_digitavel') e ele te retorna algumas dessas variaveis, porem juros e multa não vem na linha digitavel somente no registro do banco então não tem como retornar.
