### ISSUE TITLE
Remessa/retorno via API ou txt?

### ISSUE THREAD

**Issue by eumanito** [eduardokum/laravel-boleto#571]
**Questão**
Pessoal, estou integrando boletos com os bancos pela primeira vez, tenho uma dúvida em relação à comunicação (remessa/retorno):

1. Como o banco lê os arquivos txt?
2. Existe API onde o meu sistema possa enviar requisições com um XML/Json e obter resposta imediata?

**Comment by eduardokum** [comment]
Olá, bom dia, o envio da remessa deve ser feito atravez do internet banking, bem como o retorno deve ser obtido la tbm, quanto a usar api, alguns bancos oferecem esse tipo de comunicação porem ainda não é nada padronizado até onde eu sei, cada banco possui o seu, o projeto não atende a esse proposito ainda, conforme as pessoas forem me enviando os manuais das api posso pensar em algo pra implementar na classe para automatizar isso, porém até o momento não tem nada.

**Comment by eumanito** [comment]
Obrigado @eduardokum, me esclareceu!

Infelizmente está ultrapassado esse processo. E usar algum gateway de pagamentos impede que os meus clientes façam o uso de seus convênios e vantagens negociadas diretamente com o banco.

**Comment by eduardokum** [comment]
Sim, exatamete, esse processo é ridiculo, deveria ser tudo via api e padronizado da mesma forma que o cnab é meio padronizado.

Mais se você conseguir algum manual de apis dos bancos, cria um PR que podemos pensar em fazer um wrapper pra tentar englobar todos os bancos nas classes que ja temos hoje.

**Comment by tortato** [comment]
Até onde eu sei, Bradesco, Itaú, Sicoob e Sicredi tem API para registro de boleto. O Banco do Brasil, Santander e a Caixa tem WS. Tudo depende do que vc acorda com seu gerente e quais as taxas para utilização de cada canal.

**Comment by eduardokum** [comment]
É então mais o problema que ligar no suporte pra pedir esses manuais parece que vc está falando grego, ninguém consegue ajudar, então é muito mais fácil quem tem conta e o gerente sabe da existência da api e oferece, conseguir o manual é muito mais fácil

**Comment by eumanito** [comment]
Vou ver se consigo os manuais, em breve trago novidades.

**Comment by kristiantenfen** [comment]
Documentação Itaú

[Documentação da API de Registros de Cobrança - v21.pdf](https://github.com/eduardokum/laravel-boleto/files/4960590/Documentacao.da.API.de.Registros.de.Cobranca.-.v21.pdf)

**Comment by webesistemas** [comment]
Um cliente meu disse que o SICREDI liberaria API pra ele somente se ele emitir nota fiscal do boleto .... até entao esta modo remessa/retorno
