### ISSUE TITLE
Para o Sicoob eu posso usar o  Bancoob?

### ISSUE THREAD

**Issue by ricatom** [eduardokum/laravel-boleto#572]
Olá,

Para o Sicoob eu posso usar o  Bancoob é isso mesmo?

Grato

**Comment by DevCiapixel** [comment]
Eu já usei algumas vezes e nunca tive problemas.

**Comment by eduardokum** [comment]
Sim, é o mesmo banco, alguns lugares usavam esse nome antes quando a classe foi feita entao ficou assim mesmo pra nao quebrar o codigo de quem ja usa.
