### ISSUE TITLE
Valor da tarifa não vem no detalhe

### ISSUE THREAD

**Issue by rafwell** [eduardokum/laravel-boleto#573]
**Descreva o bug**
O valor da tarifa não vem informado no detalhe, porém existe no arquivo de retorno.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Instanciar:

```
$retorno = \Eduardokum\LaravelBoleto\Cnab\Retorno\Factory::make(  'arquivo.ret' );
$retorno->processar();
$detalhes = $retorno->getDetalhes();

dd($detalhes);
```

2. Na posição 4 está o boleto que eu paguei como teste, o valor da tarifa com o banco é 2,44, e o valor_tarifa vem zerado no detalhe.  [Link para o arquivo de retorno que baixei no banco](https://pastebin.com/ei0VJGGi)

3. Veja o erro
![image](https://user-images.githubusercontent.com/2893078/87698375-c5aa7e80-c769-11ea-8f44-e15bfbb0e98a.png)

**Comportamento esperado**
O valor_tarifa deveria ser 2.44

**Desktop (por favor, complete as seguintes informações):**
 - OS: Ubuntu 16.04
 - Versão do PHP : 7.2
 - Versão do Laravel: 5.5

**Contexto adicional**
Como alternativa, eu posso considerar o boleto integralmente pago se ele vier com ocorrenciaTipo = 1? Caso o boleto seja pago com valor menor, como vem esse campo?

**Comment by rafwell** [comment]
Descobri que este commit que causou meu problema, se eu voltar ao que era funciona como esperado. Mas preciso de ajuda para entender o motivo de ter sido incluída essa linha antes de submeter um pr.

https://github.com/eduardokum/laravel-boleto/commit/2101ec29ef500521173244ce9e0e892d4fab188a#diff-d5a000c30fc538f932bd66fdc963d709

**Comment by eduardokum** [comment]
Bom dia, nao consigo achar a linha esse commit é muito grande. Pode ter sido um erro, me mostre qual é para eu te dizer.

**Comment by rafwell** [comment]
@eduardokum, https://github.com/eduardokum/laravel-boleto/pull/633/files

Acabei ficando com o meu fork em produção e esqueci deste issue. Este rodando desde então. Acabei fazendo uma outra mudança, agora no sicoob.
