### ISSUE TITLE
Ciclo de releases

### ISSUE THREAD

**Issue by claudsonm** [eduardokum/laravel-boleto#575]
Existe algum release cycle para a disponibilização das novas versões?

Gostaria de saber para me planejar melhor, já que existem algumas contribuições que gostaria de obter e que já foram aprovadas há alguns meses e ainda não foram para a master e disponibilizadas no packagist.

https://github.com/eduardokum/laravel-boleto/compare/master...develop

**Comment by eduardokum** [comment]
Bom dia, na verdade, não, se for algo bugs eu tento soltar na hora, caso contrario eu deixo acumular um pouco pra soltar comforme minha disponibilidade de tempo.
