### ISSUE TITLE
Onde obtenho os códigos de "ocorrenciaTipo" e "ocorrencia"?

### ISSUE THREAD

**Issue by eumanito** [eduardokum/laravel-boleto#578]
Pessoal, como posso obter o mapa de códigos dos campos "ocorrenciaTipo" e "ocorrencia" que são retornados no método getDetalhe() ?

No manual atualizado Cnab 240 da Febraban encontrei as opções de "motivo de movimento de retorno" e "motivo da ocorrência", seriam estes?

E se for Cnab 400, não encontrei o manual.

Todos os banco seguem esses códigos?

**Comment by eumanito** [comment]
Analisando as classes dessa lib, entendi que o campo "ocorrencia" é uma string particular de cada banco, e o campo "ocorrenciaTipo" é um agrupador para facilitar para o programador, certo?

https://github.com/eduardokum/laravel-boleto/blob/ddd301bb565d2b8aaa75058b5a5312dcd5102c65/src/Contracts/Cnab/Retorno/Detalhe.php#L7-L13

**Comment by eduardokum** [comment]
Bom dia, isso mesmo é agrupador, e o getOcorrenciaDescricao retorna essa string, se o banco não adicionou nenhum codigo des de a ultima atualizacao da classe deve retornar correto
