### ISSUE TITLE
Homologação BB - Local de Pagamento

### ISSUE THREAD

**Issue by DanieleMenegatti** [eduardokum/laravel-boleto#581]
Preciso alterar o **Local de Pagamento:** que está com a informação "Pagável em qualquer banco até a data de vencimento" para "Pagável em qualquer banco". Poderia me informar onde consigo alterar essa informação?

**Comment by adrianoGaspar** [comment]
$boleto->setLocalPagamento($configBoleto->payment_place);
                        $boleto->setDescricaoDemonstrativo(json_decode($configBoleto->demonstrative_description));
                        $boleto->setInstrucoes(json_decode($configBoleto->instructions));
