### ISSUE TITLE
Pessoal, erro fopen(\341.png): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by pedro0506** [eduardokum/laravel-boleto#587]
**Questão**
Escreva sua questão aqui.
Estou tendo o erro acima https://prnt.sc/uicm4m

O que posso estar errando?

**Comment by eduardokum** [comment]
posta o raw trace pra ter uma ideia melhor, pela imagem não tem como saber

**Comment by lucas-santana** [comment]
Mesmo erro acontecendo aqui, peguei o exemplo itau_boleto.php

#0 /var/www/html/teste_projeto/vendor/setasign/fpdf/fpdf.php(1258): FPDF->Error('Can't open imag...')
#1 /var/www/html/teste_projeto/vendor/setasign/fpdf/fpdf.php(885): FPDF->_parsepng('/341.png')
#2 /var/www/html/teste_projeto/vendor/eduardokum/laravel-boleto/src/Boleto/Render/Pdf.php(114): FPDF->Image('/341.png', 20, 66, 0, 12, 'png')
#3 /var/www/html/teste_projeto/vendor/eduardokum/laravel-boleto/src/Boleto/Render/Pdf.php(476): Eduardokum\LaravelBoleto\Boleto\Render\Pdf->logoEmpresa(0)
#4 /var/www/html/teste_projeto/itau_boleto.php(50): Eduardokum\LaravelBoleto\Boleto\Render\Pdf->gerarBoleto('F', '/var/www/html/s...')
#5 {main}

**Comment by augustojesus** [comment]
Estou com o mesmo problema. Estou tentando gerar um boleto do bradesco, mas aparece "ErrorException thrown with message "fopen(\237.png): failed to open stream: No such file or directory"

Stacktrace:
#56 ErrorException in C:\wamp64\www\orions\viniciusimoveis\vendor\setasign\fpdf\fpdf.php:1258
#55 fopen in C:\wamp64\www\orions\viniciusimoveis\vendor\setasign\fpdf\fpdf.php:1258
#54 FPDF:_parsepng in C:\wamp64\www\orions\viniciusimoveis\vendor\setasign\fpdf\fpdf.php:885
#53 FPDF:Image in C:\wamp64\www\orions\viniciusimoveis\vendor\eduardokum\laravel-boleto\src\Boleto\Render\Pdf.php:114
#52 Eduardokum\LaravelBoleto\Boleto\Render\Pdf:logoEmpresa in C:\wamp64\www\orions\viniciusimoveis\vendor\eduardokum\laravel-boleto\src\Boleto\Render\Pdf.php:476
#51 Eduardokum\LaravelBoleto\Boleto\Render\Pdf:gerarBoleto in C:\wamp64\www\orions\viniciusimoveis\app\Http\Controllers\ClienteController.php:101
#50 App\Http\Controllers\ClienteController:boleto in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#49 call_user_func_array in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#48 Illuminate\Routing\Controller:callAction in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
#47 Illuminate\Routing\ControllerDispatcher:dispatch in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
#46 Illuminate\Routing\Route:runController in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
#45 Illuminate\Routing\Route:run in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Router.php:659
#44 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#42 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:67
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
#33 Illuminate\Session\Middleware\StartSession:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:59
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#24 Illuminate\Pipeline\Pipeline:then in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Router.php:661
#23 Illuminate\Routing\Router:runRouteWithinStack in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Router.php:636
#22 Illuminate\Routing\Router:runRoute in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Router.php:602
#21 Illuminate\Routing\Router:dispatchToRoute in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Router.php:591
#20 Illuminate\Routing\Router:dispatch in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\fideloper\proxy\src\TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\wamp64\www\orions\viniciusimoveis\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in C:\wamp64\www\orions\viniciusimoveis\public\index.php:59
"

**Comment by lucas-santana** [comment]
@augustojesus tem como postar o código que originou esse erro por favor?
Tive o mesmo problema.....

**Comment by augustojesus** [comment]
@lucas-santana, o código que gerou foi o seguinte

 $beneficiario = new \Eduardokum\LaravelBoleto\Pessoa(
            [
                'nome' => 'ACME',
                'endereco' => 'Rua um, 123',
                'cep' => '99999-999',
                'uf' => 'UF',
                'cidade' => 'CIDADE',
                'documento' => '99.999.999/9999-99',
            ]
        );

        $pagador = new \Eduardokum\LaravelBoleto\Pessoa(
            [
                'nome' => 'Cliente',
                'endereco' => 'Rua um, 123',
                'bairro' => 'Bairro',
                'cep' => '99999-999',
                'uf' => 'UF',
                'cidade' => 'CIDADE',
                'documento' => '999.999.999-99',
            ]
        );

        $boleto = new \Eduardokum\LaravelBoleto\Boleto\Banco\Bradesco(
            [
                'logo' => realpath(__DIR__ . '/../logos/') . DIRECTORY_SEPARATOR . '237.png',
                'dataVencimento' => new \Carbon\Carbon(),
                'valor' => 100,
                'multa' => false,
                'juros' => false,
                'numero' => 1,
                'numeroDocumento' => 1,
                'pagador' => $pagador,
                'beneficiario' => $beneficiario,
                'carteira' => '09',
                'agencia' => 1111,
                'conta' => 9999999,
                'descricaoDemonstrativo' => ['demonstrativo 1', 'demonstrativo 2', 'demonstrativo 3'],
                'instrucoes' =>  ['instrucao 1', 'instrucao 2', 'instrucao 3'],
                'aceite' => 'S',
                'especieDoc' => 'DM'
            ]
        );

        $pdf = new \Eduardokum\LaravelBoleto\Boleto\Render\Pdf();
        $pdf->addBoleto($boleto);
        $pdf->gerarBoleto($pdf::OUTPUT_SAVE, __DIR__ . DIRECTORY_SEPARATOR . 'arquivos' . DIRECTORY_SEPARATOR . 'bradesco.pdf');

**Comment by lucas-santana** [comment]
@augustojesus exclui isso que dá certo: `'logo' => realpath(__DIR__ . '/../logos/') . DIRECTORY_SEPARATOR . '237.png',`
Aqui aconteceu o mesmo quando testei esse projeto

**Comment by augustojesus** [comment]
> @augustojesus exclui isso que dá certo: `'logo' => realpath(__DIR__ . '/../logos/') . DIRECTORY_SEPARATOR . '237.png',`
> Aqui aconteceu o mesmo quando testei esse projeto

Eu reinstalei o pacote no projeto e segui o guia de exemplo, funcionou normalmente.

**Comment by lucas-santana** [comment]
@augustojesus sem remover essa linha da logo? Pode me passar esse lindo guia de exemplo? Não consegui fazer funcionar sem tirar essa linha da logo.
