### ISSUE TITLE
Duvida sobre campos numero e numeroDocumento.

### ISSUE THREAD

**Issue by fernandolec** [eduardokum/laravel-boleto#592]
Pelo que consegui entender o campo **numero** seria um numero gerado por mim, por exemplo o id que salvei no banco, correto? Já o **numeroDocumento** eu fiquei bem na duvida, o que devo colocar?

**Comment by claudio-tosetto** [comment]
numeroDocumento deve ser um número de documento do mundo real, por ex número da nota fiscal ou número da fatura a qual o boleto se refere.

**Comment by fernandolec** [comment]
> numeroDocumento deve ser um número de documento do mundo real, por ex número da nota fiscal ou número da fatura a qual o boleto se refere.

Há algum problema em usar o mesmo número em ambos?

**Comment by claudio-tosetto** [comment]
Fica estranho, mas nada te impede de fazer isso. 

Esse número sai impresso no boleto, abaixo do nome do beneficiário e deve servir para orientar os usuários a encontrar o documento que deu origem aquele boleto. Imagine que um cliente ligue para empresa e pergunte a que se refere o boleto que ele recebeu, esse número é a única referência que terão para saber do que se trata, nesse caso seria necessário providenciar no seu sistema uma forma de consulta por id.

**Comment by fernandolec** [comment]
> Fica estranho, mas nada te impede de fazer isso.
> 
> Esse número sai impresso no boleto, abaixo do nome do beneficiário e deve servir para orientar os usuários a encontrar o documento que deu origem aquele boleto. Imagine que um cliente ligue para empresa e pergunte a que se refere o boleto que ele recebeu, esse número é a única referência que terão para saber do que se trata, nesse caso seria necessário providenciar no seu sistema uma forma de consulta por id.

Entendi, muito obrigado!
