### ISSUE TITLE
Baixa automatica

### ISSUE THREAD

**Issue by WesleiRamos** [eduardokum/laravel-boleto#593]
Como exatamente funciona o campo **diasBaixaAutomatica**? Pelo que pesquisei seria pra o banco não deixar o boleto "em aberto", de que forma essa campo é utilizado quando crio um novo boleto?

**Comment by fillipenorton** [comment]
Sim, o sentido é este mesmo. Definir por quanto tempo o boleto está apto a ser pago. E após essa quantidade de dias, o banco faz a baixa do mesmo.
