### ISSUE TITLE
Erro na Instalacão

### ISSUE THREAD

**Issue by lelommp** [eduardokum/laravel-boleto#595]
Estou tentando fazer a instalação do pacote, mas não estou conseguindo, está dando o seguinte problema:

marcelo@MacBook-Pro boletos % COMPOSER_MEMORY_LIMIT=-1 composer require "eduardokum/laravel-boleto"
Using version ^0.8.9 for eduardokum/laravel-boleto
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for eduardokum/laravel-boleto ^0.8.9 -> satisfiable by eduardokum/laravel-boleto[0.8.9].
    - Installation request for laravel/framework (locked at v8.11.2, required as ^8.0) -> satisfiable by laravel/framework[v8.11.2].
    - Can only install one of: laravel/framework[8.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.3, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.4, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.1.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.10.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.11.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.11.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.11.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.2.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.3.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.4.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.5.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.6.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.7.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.7.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.8.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.9.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.11.2].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.11.2].
    - Conclusion: install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework ^8.0 -> satisfiable by laravel/framework[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.10.0, v8.11.0, v8.11.1, v8.11.2, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].

Installation failed, reverting ./composer.json to its original content.

** Meu composer.json **
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0"
    },
    "require-dev": {
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by edgardmessias** [comment]
A versão atual ainda não é compatível com o laravel 8, você pode testar usando o ramo `develop`

```
composer require eduardokum/laravel-boleto:dev-develop
```
