### ISSUE TITLE
Capturar dados do boleto

### ISSUE THREAD

**Issue by paulodias-dev** [eduardokum/laravel-boleto#607]
Gostaria de saber como posso pegar os dados do boleto para fazer um insert no bando de dados por exemplo:

//        campoCodigoBarras
//        campoLinhaDigitavel

Como posso pegar essas informações na geração do boleto ?

**Comment by eduardokum** [comment]
Após gerado só dar get nas propriedades do boleto gerado, se quiser saber todas só dar um var_dump no objeto
