### ISSUE TITLE
Interface 'Eduardokum\LaravelBoleto\Contracts\Pessoa' not found

### ISSUE THREAD

**Issue by victorhugobarboza** [eduardokum/laravel-boleto#608]
Estou encontrado esse erro:
Interface 'Eduardokum\LaravelBoleto\Contracts\Pessoa' not found in /home/u564352237/domains/torcedoresdanacaofla.org.br/public_html/filiados_test/vendor/eduardokum/laravel-boleto/src/Pessoa.php on line 6.
Como poderia corrigi-lo? Não sei se o motivo é a name space do Pessoa.php que está assim:
namespace Eduardokum\LaravelBoleto\Pessoa;

**Comment by augustojesus** [comment]
Oi, Victor.  Tente colocar uma contra barra antes do "Eduardokum" para ele identificar que está na vendor do projeto.
ficando "\Eduardokum\LaravelBoleto\Contracts\Pessoa"

**Comment by victorhugobarboza** [comment]
Olá, na verdade está com a barra, eu que não coloquei aqui, acho que pode ser algo como 'namespace' ou 'use' no arquivo Pessoa.php que fica dentro de src. Eles estão declarados de seguinte maneira:

namespace LaravelBoleto\LaravelBoleto;
use Eduardokum\LaravelBoleto\Contracts\Pessoa as PessoaContract;
