### ISSUE TITLE
Formato dos atributos data e valor. 

### ISSUE THREAD

**Issue by tiagoandrepro** [eduardokum/laravel-boleto#609]
Estou tendo uma pequeno problema... a utilizar a função abaixo para formatar a data e valor na interface do usuário as entradas também são formatadas no HTML do boleto. Qual seria a melhor forma para contornar isso? Formatar os números no frontend ou tem alguma alternativa para isso?

```
    public function getDueDateAttribute()
     {
         return Carbon::parse($this->attributes['dueDate'])->format('d/m/Y');
     }
```

**Comment by eduardokum** [comment]
A classe retorna instância de Carbon
