### ISSUE TITLE
Bradesco Retorno

### ISSUE THREAD

**Issue by alissonlinneker** [eduardokum/laravel-boleto#61]
Fatal error: Uncaught Error: Call to undefined function Eduardokum\LaravelBoleto\Cnab\Retorno\Cnab400\Banco\array_get() in C:\xampp2\htdocs\remessaBradesco\vendor\eduardokum\laravel-boleto\src\Cnab\Retorno\Cnab400\Banco\Bradesco.php:120 Stack trace: #0 C:\xampp2\htdocs\remessaBradesco\vendor\eduardokum\laravel-boleto\src\Cnab\Retorno\Cnab400\AbstractRetorno.php(244): Eduardokum\LaravelBoleto\Cnab\Retorno\Cnab400\Banco\Bradesco->processarDetalhe(Array) #1 C:\xampp2\htdocs\remessaBradesco\vendor\eduardokum\laravel-boleto\src\Cnab\Retorno\Factory.php(106): Eduardokum\LaravelBoleto\Cnab\Retorno\Cnab400\AbstractRetorno->processar() #2 C:\xampp2\htdocs\remessaBradesco\vendor\eduardokum\laravel-boleto\exemplos\bradesco_retorno.php(3): Eduardokum\LaravelBoleto\Cnab\Retorno\Factory::make('C:\\xampp2\\htdoc...') #3 {main} thrown in C:\xampp2\htdocs\remessaBradesco\vendor\eduardokum\laravel-boleto\src\Cnab\Retorno\Cnab400\Banco\Bradesco.php on line 120

**Comment by eduardokum** [comment]
Você precisa instalar as dependências do projeto

EDUARDO GUSMÃO
Analista de Sistemas
E-mail: eduardo@intrasis.com.br
Telefone: 11 2208 2423 | 41 2626-1708 | 41 98479 6288 (Tim)
Endereço: Av. Engenheiro Caetano Álvares, 3536 | São Paulo
Site: www.intrasis.com.br

2017-01-05 10:49 GMT-02:00 Alisson Linneker <notifications@github.com>:
