### ISSUE TITLE
[PIX] - implementação

### ISSUE THREAD

**Issue by scraipt** [eduardokum/laravel-boleto#617]
Acham relevante a implementação do QrCode pix na emissão do boleto? tenho a documentação do santander, me ajudam a implementar?

**Comment by guicouto** [comment]
Envia a documentação aqui @scraipt, talvez esse não seja o repositório ideal para implementar esse código mas podem aparecer pessoas dispostas a ajudar, após ler e entender melhor a doc.

**Comment by scraipt** [comment]
@guicouto  então, eu acredito que seja aqui o repo ideal, uma vez que no rodapé do boleto aparece o QRCode, o cliente pode optar por pagar via boleto ou pix entende?

**Comment by eumanito** [comment]
@scraipt já iniciou? quero ajudar

**Comment by afonsocarlos** [comment]
Estou implementando o tratamento para pagamento via Pix do CNAB400 de Remessa e Retorno para o Itau. Talvez possamos nos ajudar, logo logo devo subir um PR
