### ISSUE TITLE
Personalizar template de impressão dos boletos

### ISSUE THREAD

**Issue by davimatos** [eduardokum/laravel-boleto#618]
Olá!

Primeiramente, parabéns por manter o projeto.

Alguém sabe dizer se é possível fazer um template de impressão do boleto personalizado? Preciso adicionar mais algumas informações no layout de impressão.

Penso que poderia fazer uma view modificada no Laravel e gerar o boleto nela.

É possível?

**Comment by tiagoandrepro** [comment]
Também quero personalizar para inserir o QR do PIX Cobrança que estou implementando.

**Comment by scraipt** [comment]
https://github.com/eduardokum/laravel-boleto/issues/617

**Comment by eumanito** [comment]
Alguém já iniciou? compartilhem a documentação e o andamento.

**Comment by laerciocrestani** [comment]
Olá pessoal. É chamado boleto híbrido... Vou dar um fork nessa repo e fazer para o Sicredi.

**Comment by scraipt** [comment]
então, eu comecei a ver, mas parei por outras demandas, mas preciso falar com o pessoal do banco, porque para implementar o qrcode, eu vou precisar de um retorno do webhook deles, que na época eles não tinham em produção ainda, hoje até tem, mas enfim, preciso levantar tudo denovo.

**Comment by eumanito** [comment]
@laerciocrestani precisa integrar com a API do Sicredi? Eu consegui o manual, eles chamam de "cobrança online". Me manda um e-mail (eumanito@gmail.com) que ajudo no desenvolvimento.

**Comment by laerciocrestani** [comment]
> @laerciocrestani precisa integrar com a API do Sicredi? Eu consegui o manual, eles chamam de "cobrança online". Me manda um e-mail (eumanito@gmail.com) que ajudo no desenvolvimento.

Claro. Podemos desenvolver juntos. Lhe chamo em breve.

**Comment by eumanito** [comment]
@tiagoandrepro já iniciou? Me manda um e-mail eumanito@gmail.com

**Comment by moisespereiram** [comment]
Olá pessoal, conseguiram implementar o QR code para pix no boleto? não estou conseguindo gerar o boleto com a imagem.

**Comment by davimatos** [comment]
> Olá pessoal, conseguiram implementar o QR code para pix no boleto? não estou conseguindo gerar o boleto com a imagem.

Eu consegui implementar modificando o classe abstrata, incluindo o qrcode como atributo e o template blade, adicionando uma tag img com o link da imagem do QR Code no src.

**Comment by bianchi** [comment]
Também tenho necessidade de customizar o template. Meu cliente quer que na impressão saiam duas fichas de compensação do mesmo boleto, uma para ficar com o pagador. Acredito que o ideal seria passar para a classe Html um parâmetro com o meu template blade.

Existe outra maneira de contornar isso?
