### ISSUE TITLE
Banco Safra S.A

### ISSUE THREAD

**Issue by andersondevkayros** [eduardokum/laravel-boleto#624]
Boa tarde senhores,

Pelo que vi a library não comporta o Banco Safra, existe previsão para ser implementado para esse banco?
Se não, como vocês realizaram homologação dele?

Desde já, obrigado

**Comment by eduardokum** [comment]
Existia a implementação, porém o setor jurídico do banco entrou em contato para a remoção e assim foi feito, não vai existir a implantação do safra no pacote infelizmente
Em 14 de jun. de 2021 11:17 -0300, andersondevkayros ***@***.***> escreveu:

**Comment by edigomes** [comment]
Verifica meu fork

Em seg., 14 de jun. de 2021 11:17, andersondevkayros <
***@***.***> escreveu:
