### ISSUE TITLE
Versão do PHP e do Laravel

### ISSUE THREAD

**Issue by douglas-88** [eduardokum/laravel-boleto#627]
Bom dia,

Sabem dizer se esse package é compatível com o PHP 8 ? Se não , até qual versão ele aceita ? 
E até qual versão do Laravel aceita tb ?

**Comment by nettopaulo** [comment]
Boa tarde!
Estou homologando com o SICREDI no PHP 8.0 e Laravel 8.19.0.
Funcionando sem problemas.

**Comment by eduardokum** [comment]
Sim, até com a 9
