### ISSUE TITLE
Número de Caracteres

### ISSUE THREAD

**Issue by AlexanderZon** [eduardokum/laravel-boleto#63]
ao escrever a remessa eu contei 400 caracteres na cadeia, mas capturando os personagens já no arquivo eu contei 394 caracteres, o problema está na linha 1, tanto o nome e endereço do pagador, que tem espaços, acho que é o problema

**Comment by AlexanderZon** [comment]
![image](https://cloud.githubusercontent.com/assets/5555468/21696775/d27963d4-d365-11e6-8c35-07507c07e619.png)

mas para mergulhar no código eu posso ver o código se eu conseguir 400 caracteres antes de gerar o arquivo
![image](https://cloud.githubusercontent.com/assets/5555468/21696864/30f7376a-d366-11e6-897e-c48ec4cd71b0.png)

**Comment by eduardokum** [comment]
Nunca vi problema assim, que banco está usando? Qual erro está dando??

**Comment by AlexanderZon** [comment]
Banco Bradesco

**Comment by AlexanderZon** [comment]
Erro na linha 1. O Tamanho do Arquivo é inválido

**Comment by eduardokum** [comment]
https://github.com/eduardokum/laravel-boleto/blob/master/exemplos/bradesco_remessa.php

Siga esse exemplo

**Comment by AlexanderZon** [comment]
com os dados de exemplo me retorna 400 caracteres, mas para preencher meus dados na mesma estrutura me retorna os mesmos 394 caracteres

**Comment by AlexanderZon** [comment]
e eu encontrei o problema, como tinha copiado os dados de um contribuinte do pdf, também me copiou uns caracteres especiais que estava geraram o problema, a solução foi re-escrever os dados de pagador.
Obrigado pela ajuda.
