### ISSUE TITLE
Problema de quebra de página e alinhamento

### ISSUE THREAD

**Issue by mprandot** [eduardokum/laravel-boleto#64]
Bom dia!

Estou com um problema (como diz o título da issue).
As páginas estão quebrando no meio dos boletos e eles não estão 100% alinhados.
Anteriormente foi dito que poderia ser minha máquina, mas testei em outras e está acontecendo a mesma coisa.

A questão do alinhamento eu até consegui arrumar, coloquei gerar o boleto em uma nova página, ai alinhou corretamente, agora a questão de quebra de página, pode ser alguma coisa com o package de impressão? 

[rbr informatica.pdf](https://github.com/eduardokum/laravel-boleto/files/693483/rbr.informatica.pdf)

**Comment by eduardokum** [comment]
Acabei de gerar um teste na minha maquina como exemplo, o erro não acontece veja.

[bb.pdf](https://github.com/eduardokum/laravel-boleto/files/693493/bb.pdf)

**Comment by mprandot** [comment]
Você tá usando o método renderHTML ou renderPDF?

**Comment by eduardokum** [comment]
Estou usando o exemplo, só adicionei mais boletos.

https://github.com/eduardokum/laravel-boleto/blob/master/exemplos/bb_boleto.php

esses métodos da classe do boleto são somente para gerar 1, a própria instancia.

Para imprimir mais de 1 tem que usar a classe Pdf como no exemplo.

**Comment by mprandot** [comment]
Acho que sei, estou gerando um boleto por vez e concatenando o HTML, pode ser isso?

**Comment by eduardokum** [comment]
Então o html não tem como controlar a quebra de página. 

no boleto voce pode usar o  renderHTML ou renderPDF quando voce quer somente 1 boleto a instancia em questão...
quando você quer agrupar mais de 1 boleto tem que ser em PDF, assim... 

$pdf = new Eduardokum\LaravelBoleto\Boleto\Render\Pdf();
$pdf->addBoleto($boleto1);
$pdf->addBoleto($boleto2);
$pdf->addBoleto($boleto3);
$pdf->addBoleto($boleto4);
$pdf->gerarBoleto();

**Comment by mprandot** [comment]
Entendi.
Vou ter que mudar minha estrutura aqui...
Eu não queria ter que armazenar o PDF toda vez (caso o usuário queira imprimir), seria interessante gerar um boleto a partir de um já existente.

Aproveitando...
Para gerar remessas, você armazena os boletos no banco de dados ou gera eles novamente quando for gerar a remessa?

**Comment by eduardokum** [comment]
Depende da sua estrutura, você pode gerar o boleto toda vez que usuário quiser visualizar, só usar o $pdf::OUTPUT_STANDARD que ele retorna o pdf e não salva em lugar nenhum

Mais eu costumo salvar o pdf e só gero outro quando o usuário faz alguma alteração já que o boleto é registrado ele não muda, somente se o usuário alterar no banco com alguma remessa de alteração

**Comment by mprandot** [comment]
'<div style="page-break-before:always"></div>' salvando minha vida :D

**Comment by eduardokum** [comment]
👍 Que bom que consegui resolver .
