### ISSUE TITLE
Alguns títulos pagos não baixaram

### ISSUE THREAD

**Issue by douglas-88** [eduardokum/laravel-boleto#641]
Boa tarde a todos,

Foi usado um arquivo de retorno para efetuarmos a baixa dos títulos, todos eles foram confirmados pelo Banco Bradesco de que foram pagos, contudo apenas alguns baixaram de fato, outros não foram.

Queria saber se é gerado algum log para tentarmos identificar o que houve para não ter baixado esses outros .
Se não é gerado nenhum log, como posso depurar então ?

Desde já agradeço a atenção e ajuda.

Obs: O layout que utilizamos é o 400 .

**Comment by eduardokum** [comment]
Você consegue ver no retorno, se não veio no retorno não tem o que fazer
