### ISSUE TITLE
Modelo de impressão

### ISSUE THREAD

**Issue by ermaito** [eduardokum/laravel-boleto#645]
Olá!

O pacote possui modelo de impressão estilo "carnê" (onde possam ser impressos vários boletos na mesma folha).

**Comment by fillipenorton** [comment]
Sim!

Ao instaciar o boleto, você pode usar a classe \Eduardokum\LaravelBoleto\Boleto\Render\Html()

E renderizar com $boleto->gerarCarne()

**Comment by ermaito** [comment]
Muito obrigado!
