### ISSUE TITLE
alterarBoleto() / baixarBoleto() 

### ISSUE THREAD

**Issue by alissonlinneker** [eduardokum/laravel-boleto#65]
> Call to undefined method Eduardokum\LaravelBoleto\Cnab\Remessa\Banco\Bradesco::alterarBoleto()

Como deve ser usada a função para alteração e baixa de boleto?

Para adicionar um boleto, uso:
$remessa->addBoleto($boleto);

Não seria o mesmo para alterar e baixar?
$remessa->alterarBoleto($boleto);
$remessa->baixarBoleto($boleto);

**Comment by eduardokum** [comment]
Não, esses métodos, são da AbstractBoleto, ou seja, tem nos objetos do boleto não da remessa.
