### ISSUE TITLE
Problemas com Boleto CEF - 7 dígitos

### ISSUE THREAD

**Issue by fillipenorton** [eduardokum/laravel-boleto#651]
Pessoal,

alguém com problemas no boleto com cedente de 7 dígitos?

A remessa é transmitida com sucesso, mas o boleto não consegue pagar!

Já olhei o manual e o mesmo cita mudanças apenas na remessa ("[...] com esclarecimentos detalhados nas Notas
Explicativas G019, G030 e C007, respectivamente.") e nada no boleto em si!

Qualquer dica será de grande valia, obrigado!

**Comment by eduardokum** [comment]
Bom dia, chegou a ver o boleto no próprio site do banco e ver se os códigos de barras batem?

**Comment by ermaito** [comment]
Bom dia, estou com problemas em boletos da CEF com 6 dígitos ao gerar arquivo de remessa da Caixa Federal CNAB 400 e com código de cliente que não se enquadra no layout 007.

Porém na linha 139 do arquivo Caixa.php está fixo o valor.
$this->add(101, 103, '007');

Utilizo para validar o arquivo o seguinte endereço:
https://validadordearquivos.caixa.gov.br/sivcb/pages/validacao/validador.xhtml
