### ISSUE TITLE
Compatibilidade com Laravel 9

### ISSUE THREAD

**Issue by angelorodem** [eduardokum/laravel-boleto#653]
Testei e não consegui instalar o pacote junto ao Laravel 9,

Alguém sabe se existe algum progresso para deixar compatível com a nova versão?

Muito obrigado!

**Comment by alexmontoanelli** [comment]
+1

**Comment by ricardosenabr** [comment]
Preciso tbm..... 👍

**Comment by eduardokum** [comment]
Ja mandei pra master segunda faço uma tag.

**Comment by ricardosenabr** [comment]
obrigado amigão.... vc é demais...  @eduardokum
