### ISSUE TITLE
Boleto não registrado (DÚVIDA)

### ISSUE THREAD

**Issue by DQ318** [eduardokum/laravel-boleto#654]
**Questão**
Fala pessoal. Bom demais?

Estou utilizando o pacote para gerar boletos e receber os pagamentos pelo ITAU. Até então, tudo bem, consigo gerar o boleto certinho, gero o arquivo de remessa, tudo ok mas, daqui pra frente, não sei mais como fazer para que o banco receba meu arquivo de remessa e gere o de retorno com o boleto válido e, se tento ler o código de barras em algum app de pagamento, recebo a mensagem que o boleto não está registrado.

Utilizo a carteira 109 e Cnab400.

Se alguém puder me orientar nos próximos passos, agradeceria muito.
Valeu!

**Comment by fillipenorton** [comment]
Opa! Você consegue transmitir o arquivo remessa no sistema do banco?

O fluxo é: 
1. gerar o boleto
2. transmitir a remessa
3. aguardar o dia seguinte para obter o retorno de entrada confirmada
4. quando boleto pago, retorno de pagamento efetuado

**Comment by DQ318** [comment]
Fala @fillipenorton , tudo bom?

Então, é daqui pra frente que estou travado. Justamente no passo 2.
Entendi o fluxo que você descreveu, entretanto, para eu testá-lo, é que preciso entender como proceder.

Pelo que entendi, devo ter obrigatóriamente uma conta PJ ativa (ou estou enganado e existe algum tipo de sandbox para testar, sei lá), correto?

O envio é feito pelo internet banking desta conta e aí é aguardar o passo 3 e seguir para o 4..

**Comment by fillipenorton** [comment]
Olá @DQ318 é isso mesmo, para você avançar nos passos 3 e 4 precisa sim ter uma conta cobrança ativa em seu banco

Para apenas validar o arquivo (saber se o mesmo tem as informações corretas) alguns bancos disponibilizam validadores, SICOOB e BB é um deles, não lembro todos. Mas alguns realmente não tem, então só transmitindo mesmo pra saber.
