### ISSUE TITLE
Bairro no pagador de boletos caixa

### ISSUE THREAD

**Issue by filipereinerts** [eduardokum/laravel-boleto#656]
Na linha 255 e 448 do arquivo PdfCaixa.php consta apenas o endereço do pagador, onde na classe Pdf.php informa o endereço + bairro. Olhando o manual da caixa eles informam apenas a palavra "Endereço" que, ao meu ver, comporta logradouro + bairro.

**Comment by filipereinerts** [comment]
Erro meu, estava desatualizado.

**Comment by eduardokum** [comment]
Vou dar uma olhada amigo, se quiser mandar pr em develop também fique a vontade
