### ISSUE TITLE
Correção arquivo Bancoob.php

### ISSUE THREAD

**Issue by JefersonCelestino** [eduardokum/laravel-boleto#662]
Estou recebendo a seguinte mensagem de erro: 
**'Unsupported operand types'**

Pois no arquivo src/Cnab/Remessa/Cnab240/Banco/Bancoob.php linha 243 possui o caractere '+':
`$this->add(67, 74, $boleto->getMulta() > 0 ?  $boleto->getDataVencimento()->copy()->addDay()->format('dmY') : '00000000');       +`

**Comment by eduardokum** [comment]
Subindo ja, ai faco uma nova tag. Obrigado
