### ISSUE TITLE
Erro: During inheritance of Countable: Uncaught ErrorException

### ISSUE THREAD

**Issue by devthiagolino** [eduardokum/laravel-boleto#663]
**Pessoal, estou tendo essa exception será que será por motivo que utilizo o PHP 8.1?**

During inheritance of Countable: Uncaught ErrorException: Return type of Eduardokum\LaravelBoleto\Cnab\Retorno\AbstractRetorno::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/utdservices/vendor/eduardokum/laravel-boleto/src/Cnab/Retorno/AbstractRetorno.php:275

**Comment by eduardokum** [comment]
Acredito que não, os testes unitarios rodam ate php 8.2 no momento do push.
