### ISSUE TITLE
Remessas Bradesco

### ISSUE THREAD

**Issue by alissonlinneker** [eduardokum/laravel-boleto#67]
Estou com um problema de "Indícios de Rejeição" nas remessas enviadas para o Bradesco.
Em contato com o suporte, foi informado que as remessas não estão sendo enviadas com o número da carteira. Porém, eu já informei o parâmetro 'carteira' => '09' na array $beneficiario, $remessa e $boleto, mas sem sucesso.

O que devo fazer?

Observações: O número da carteira precisa estar na posição 22-24 do arquivo de remessa.

**Comment by eduardokum** [comment]
Tem razão, isso seria **"Identificação da Empresa Beneficiária no Banco"** que é composto de:

21 a 21 - Zero
22 a 24 - códigos da carteira
25 a 29 - códigos da Agência Beneficiários, sem o dígito.
30 a 36 - Contas Corrente
37 a 37 - dígitos da Conta

e hoje esta assim:

```php
$beneficiario_id = '0' .
            Util::formatCnab('9', $this->getCarteiraNumero(), 3) .
            Util::formatCnab('9', $this->getAgencia(), 5) .
            Util::formatCnab('9', $this->getConta(), 7) .
            Util::formatCnab('9', $this->getContaDv(), 1);
```

tem um 0 a mais por isso esta dando esse bug.

Enviei a correção 6c0fd6f31cb21aef6a850b7ab983e9bf8dd3fb0d, acho que deve resolver.

**Comment by alissonlinneker** [comment]
O problema continua. Veja como está saindo o cabeçalho da remessa:

`01REMESSA01COBRANCA 0000000000000XXXXXXXMINHA EMPRESA`

XXXXXXX = codigoCliente

**Comment by eduardokum** [comment]
Não é no header que vai a carteira é no detalhe.

![image](https://cloud.githubusercontent.com/assets/2566340/21849259/f5fcf4b2-d7eb-11e6-9bd0-3f3ff8fc229d.png)

![image](https://cloud.githubusercontent.com/assets/2566340/21849273/fdcce5a8-d7eb-11e6-8544-872adbb3e07e.png)

O lugar onde vai a carteira é aqui:


![image](https://cloud.githubusercontent.com/assets/2566340/21849290/1653f0b2-d7ec-11e6-9137-ffbd42cca929.png)
