### ISSUE TITLE
Banrisul layout 240 - Nova versão 10.3

### ISSUE THREAD

**Issue by eduardomaito** [eduardokum/laravel-boleto#670]
Olá, realizamos homologação de boletos Banrisul, onde o layout 400 será descontinuado.

Ao enviar o arquivo de remessa, recebemos essas informações:
_**Novas determinações do BACEN serão contempladas no leiaute 240 posições.
Novas homologações serão realizadas apenas no leiaute CNAB240 versão 10.3 que é o leiaute compatível com a nova plataforma de cobrança.**_

Alguém já passou por isso?

Segue manual anexo. 
[LeiauteBanrisulFebraban_pdr240_v103_31082021.pdf](https://github.com/eduardokum/laravel-boleto/files/9104952/LeiauteBanrisulFebraban_pdr240_v103_31082021.pdf)

Desde já agradeço a atenção.

**Comment by eumanito** [comment]
@eduardomaito estou fazendo a homologação do layout 240 do Banrisul.

Só não consegui calcular o DV da Agência e Conta do registro P, posição 37.

**Comment by ermaito** [comment]
@eumanito testei com a versão do pacote 0.8.8 e deu várias divergências em uma homologação.
Estou fazendo levantamento de alterações necessárias para verificar e providenciando a atualização do pacote.
Só para me situar, você fez em qual versão que deu problema com DV?

**Comment by eumanito** [comment]
@eduardomaito 
Como vejo a versão do meu fork?
https://github.com/eumanito/laravel-boleto

Faz 2 anos que não atualizo, pois não aceitaram nenhum pull request que eu fiz, então faço a manutenção somente em meu fork.

Sobre o DV, não tem a função para calcular este, então coloquei um campo na interface para o usuário preencher.

Se precisar de ajuda é só chamar. Olha no meu fork os ajustes que fiz na remessa. 

Você tem um fork com ajustes também?

**Comment by ermaito** [comment]
@eumanito a minha versão é 0.8.8 e para você verificar pode ser no composer.json.
Fiz os ajustes aqui também em um fork, hoje recebi a confirmação de validação do Banrisul.
Mas vou atualizar a versão do pacote para verificar se isso já não consta nele.

**Comment by eumanito** [comment]
@eduardomaito compartilha comigo o seu fork também. Tenho dúvida nos dígitos verificadores.

**Comment by ermaito** [comment]
@eumanito estou em processo de atualização e testes com o pacote, mas segue anexo como ficou o arquivo Banrisul240.php.

[Banrisul240.zip](https://github.com/eduardokum/laravel-boleto/files/9756205/Banrisul240.zip)

**Comment by ermaito** [comment]
@eumanito conseguiu?

**Comment by eumanito** [comment]
Sim, agora no sistema do banco diz "aguardando análise"
