### ISSUE TITLE
Versão do PHP 7.4.29 não funciona

### ISSUE THREAD

**Issue by mauriciolanner** [eduardokum/laravel-boleto#671]
A versão 7.4.29 do php está retornando o seguinte erro: 

Package eduardokum/laravel-boleto has requirements incompatible with your PHP version, PHP extensions and Composer version:  - eduardokum/laravel-boleto 0.9.3 requires ext-intl * but it is not present

Versão do Laravel 8.83.3

**Comment by fillipenorton** [comment]
Mauricio, pelo visto falta instalar uma extensão do PHP: intl

se estiver no ubuntu ou simliar: sudo apt-get install php7.4-intl

**Comment by fillipenorton** [comment]
Lembre de fechar a issue
