### ISSUE TITLE
getDiasBaixaAutomatica - Banco do Brasil

### ISSUE THREAD

**Issue by fillipenorton** [eduardokum/laravel-boleto#672]
**Descreva o bug**
O método a seguir possui em parâmetro como default o valor 60
Causando problema para o BB, onde sempre vai entrar na mensagem de exceção

`public function getDiasBaixaAutomatica($default = 60)
    {
        return $this->diasBaixaAutomatica > 0 ? $this->diasBaixaAutomatica : $default;
    }`

Caso seja passado como parâmetro para montar o boleto diasProtesto: '0' vai sempre retornar

`throw new \Exception('Você deve usar dias de protesto ou dias de baixa, nunca os 2');`

**A solução**

`public function getDiasBaixaAutomatica($default = 0)
    {
        return $this->diasBaixaAutomatica > 0 ? $this->diasBaixaAutomatica : $default;
    }`

**Comment by joaoroyosilva** [comment]
Corrigido na versão 0.9.4
