### ISSUE TITLE
Boleto Inter CNAB 400

### ISSUE THREAD

**Issue by ViniBarizon** [eduardokum/laravel-boleto#676]
Olá! Estou trabalhando numa equipe e acabamos de implementar integração com o Banco Inter, porém surgiu uma dúvida: No campo "nosso número", o que significa e/ou como é calculado o Dígito Verificador (DV)? No Manual não encontrei nada a respeito do DV referente ao boleto.

**Comment by eduardokum** [comment]
o nosso numero do banco inter é zerado, eles enviam no retorno ou depois que envia via api o numero que eles geraram
