### ISSUE TITLE
Integração - Banco Inter

### ISSUE THREAD

**Issue by ludioao** [eduardokum/laravel-boleto#679]
**Questão**
A integração com o Banco Inter já está funcional?

**Comment by scraipt** [comment]
atualmente não existe a implementação, você tem a documentação oficial ?

**Comment by ludioao** [comment]
@scraipt sim.

mas estava olhando aqui:

https://github.com/eduardokum/laravel-boleto/commit/f7bf190b7b3cdcf1728ef3a43ecbe6fb031caa0d

**Comment by eduardokum** [comment]
Boa tarde, está funcional sim, tanto via api quanto via remessa, utilizo em produção

**Comment by XxMdePaula10xX** [comment]
Bom dia a todos! Pessoal, por gentileza, gostaria de saber se alguém já conseguiu integrar a API do Banco Inter com a Power Platform da Microsoft?
