### ISSUE TITLE
Estou com problemas na caixa na hora da emissão

### ISSUE THREAD

**Issue by fagnerdireito** [eduardokum/laravel-boleto#681]
**Questão**
Olá, hoje estou com um retorno de erro da caixa e não consigo emitir boletos, alguem está com problemas também?

a mensagem de retorno é
`(803) SISTEMA INDISPONIVEL - ERRO NO INSERT DA TABELA GCCBTB072 - FICHA`

já tentei alguns ajustes mas até agora nada.

**Comment by eduardokum** [comment]
Nunca vi esse erro, veja com o gerente da conta se pode dar mais informações.
