### ISSUE TITLE
Multa e Juros não aparecem no boleto

### ISSUE THREAD

**Issue by guigralho** [eduardokum/laravel-boleto#684]
Boa tarde,

Ao gerar um boleto com as instruções de multa e juros, esse valor não é contabilizado no boleto em nenhum dos campos e também não é acrescido ao valor total.
Verifiquei a view ficha-compensacao.blade e nela os juros ou multa não estão nem no html.
Preciso que esses valores sejam inseridos. Podem me ajudar?

Abaixo como estou inserindo os juros
```
new Eduardokum\LaravelBoleto\Boleto\Banco\Itau([
            ...
            'multa' => '2,3',
            'juros' => '1',
            'jurosApos' => 2,
            ...
]);
```

**Comment by vagnerfpaes** [comment]
Boa noite,
Acredito que essas informações estão presentes no arquivo de remessa e serão usadas após o vencimento, quando for realizar o pagamento.

Para constar no boleto impresso tu pode adicionar na descrição demonstrativo, exemplo:
`$mensagemJuros = "";
$percentualJuros = 2.3;
$mensagemJuros = str_replace('@juros', number_format($percentualJuros, 2, ',', '.'), "Apos vencimento cobrar @juros% juros ao mês\n");

$mensagemMulta = "";
$percentualMulta = 1;
if ($percentualMulta){
    $mensagemMulta = str_replace('@multa', number_format($percentualMulta, 2, ',', '.'), "Apos vencimento cobrar @multa% de multa\n");
}

new Eduardokum\LaravelBoleto\Boleto\Banco\Itau([
            ...
            'multa' => '2,3',
            'juros' => '1',
            'jurosApos' => 2,
            'descricaoDemonstrativo' => [$mensagemJuros, $mensagemMulta]
            ]);`

**Comment by guigralho** [comment]
Entendo, acontece que eu preciso dessa informação impressa no boleto porque se o cliente não vê ali acha que não está sendo passado ao banco.

**Comment by vagnerfpaes** [comment]
Tu pode adicionar essas informações nos campos instruções ou descrição demonstrativo, ex.:
`
new Eduardokum\LaravelBoleto\Boleto\Banco\Itau([
            ...
            'multa' => '2,3',
            'juros' => '1',
            'jurosApos' => 2,
            'descricaoDemonstrativo' => ['Apos vencimento cobrar 1% juros ao mês', 'Apos vencimento cobrar 1% de multa']
            ]);
`
