### ISSUE TITLE
Salvar boleto no path

### ISSUE THREAD

**Issue by steniofs** [eduardokum/laravel-boleto#687]
estou usando o  seguinte trecho código para salvar o boleto gerado em pdf: $pdf->gerarBoleto("F", public_path('arquivos/boletos/'), 'boleto');

Mas essa linha de comando está gerando o seguinte erro: 
![image](https://user-images.githubusercontent.com/43324866/213524237-4b48fb60-9e12-4ac7-adeb-746aff389a75.png)

pode me dizer o que estou fazendo de errado??

**Comment by Comozzato** [comment]
![image](https://user-images.githubusercontent.com/97927220/236313132-10f1266b-155d-43db-b227-afb5adedd6a4.png)


é possível que precise por o tipo de arquivo?
