### ISSUE TITLE
Error no Calculo data vencimento depois de 21/02/2025

### ISSUE THREAD

**Issue by MarquesSouza** [eduardokum/laravel-boleto#688]
Descreva o bug
O fator de vencimento dos boletos e composto com por um referencial numérico de 4 dígitos, situado nas quatro primeiras posições do campo "valor" do código de barra, que representa a quantidade de dias decorridos da base à data de vencimento do titulo.
Porem o bloco tem como fator limite 9999 com a data 21/02/2025 para limite.
CENEGESC - Centro Nacional de Estudos de Gestão de Caixa, da Diretoria Setorial de Serviços Bancários proposta a proposta de zerar a contagem para o fato "1000" parti da data 22.02.2025.

Para reproduzir
Passos para reproduzir o comportamento:

Emita um boleto com data de vencimento com data superior a 22/02/2025.
Encaminhe a remessa para o banco.
Comportamento esperado
O boleto e registrado no banco. Porem o boleto gerado não será possível pagar pós o código de barras estar diferente.

**Comment by danielmos-dev** [comment]
Esse bug foi resolvido?passei pelo mesmo problema
