### ISSUE TITLE
Dúvida sobre a geração do PDF

### ISSUE THREAD

**Issue by ricardobarantini** [eduardokum/laravel-boleto#7]
Ao o gerar o pdf ele é baixado ou salvo na aplicação?

**Comment by eduardokum** [comment]
Ele tem a função gerar 

public function gerarBoleto($dest = self::OUTPUT_STANDARD, $save_path = null, $print = false){

o padrão é mostrar o stream, mais voce pode usar esses:

    const OUTPUT_STANDARD   = 'I';
    const OUTPUT_DOWNLOAD   = 'D';
    const OUTPUT_SAVE       = 'F';
    const OUTPUT_STRING     = 'S';

e se usar o save voce tem que passar o path

**Comment by ricardobarantini** [comment]
Obrigado. :+1:
