### ISSUE TITLE
Santander - PIX

### ISSUE THREAD

**Issue by ViniBarizon** [eduardokum/laravel-boleto#704]
Olá, pessoal, tudo certo? Por favor, me tirem uma dúvida se possível. Já me foi esclarecido que já é possível passar o QR Code do Pix em base64 na impressão, ok. Porém, aqui utilizamos arquivos de remessa e retorno, e acredito que não seja possível enviar na remessa para registro o Pix, pois não encontrei a posição na classe do banco. É isso mesmo? Se sim, há alguma forma de personalizar e encaixar o pix no arquivo de remessa?
[H7815-Layout-Cobranca-CNAB-240-posicoes-padrao-Santander-Multibanco-Julho-2022-V4.pdf](https://github.com/eduardokum/laravel-boleto/files/11634758/H7815-Layout-Cobranca-CNAB-240-posicoes-padrao-Santander-Multibanco-Julho-2022-V4.pdf)

Posição: 159 - 193, CNAB 240, segmento Y03. 

Estou anexando a documentação que tenho, obrigado.

**Comment by eduardokum** [comment]
Ja possui uma versao em develop que envia, santander, itau e bradesco o registro do pix
