### ISSUE TITLE
FPDF error: Invalid call

### ISSUE THREAD

**Issue by cbarros** [eduardokum/laravel-boleto#705]
Está dando o seguinte erro "FPDF error: Invalid call" quando eu tento gerar o boleto em PDF, alguém consegue me ajudar nessa?

![Captura de Tela 2023-06-06 às 18 14 49](https://github.com/eduardokum/laravel-boleto/assets/5814103/abadabee-a3eb-4535-ab02-b0cdab5c7fb3)

**Comment by rcardoso1986** [comment]
@cbarros você conseguiu resolver? fui atualizar agora e estou com o mesmo erro.

**Comment by cbarros** [comment]
Retirei todos esses comandos: 

	$html->showPrint();
        $html->hideInstrucoes();
        $html->gerarBoleto();
        $html->gerarCarne();

E deixei apenas esse: 

 $pdf->gerarBoleto();

Resolveu meu problema.

Cleber Barros Pereira
***@***.***
65 98114 5840
