### ISSUE TITLE
Gerar diversos boletos em um arquivo com o addBoletos

### ISSUE THREAD

**Issue by diogoskopinski** [eduardokum/laravel-boleto#709]
**Descreva o bug**
Problema para gera 1 arquivo PDF com diversos boletos ao utilizar o addBoletos. Faço um foreach e coloco os boletos todos em um array, depois ao passar esse array no $pdf->addBoletos($arrBoletos); da o problema.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Instancie a classe PDF fora do foreach:
 $pdf = new \Eduardokum\LaravelBoleto\Boleto\Render\PdfSAF2();
2. Envie os dados: Faço o foreach com os dados do boleto  $boleto = new \Eduardokum\LaravelBoleto\Boleto\Banco\Bb(...)
crio esse array e vou armazenado ali:  $arrBoletos[] = $boleto;
4. Veja o erro:
![erroGerarBoletos](https://github.com/eduardokum/laravel-boleto/assets/22129530/ebbdcb33-eb33-4473-a1ef-5e6c0fbb00ab)
 "message": "Eduardokum\\LaravelBoleto\\Util::fillClass(): Argument #2 ($params) must be of type array, null given, called in /var/www/html/vendor/eduardokum/laravel-boleto/src/Pessoa.php on line 75",
    "exception": "TypeError",
    "file": "/var/www/html/vendor/eduardokum/laravel-boleto/src/Util.php",
    "line": 915,

**Comportamento esperado**
A geração do PDF dos boletos.

**Desktop (por favor, complete as seguintes informações):**
 - OS: Linux Ubuntu 20.04
 - Versão do PHP 8.1.20
 - Versão do Laravel 8.83

**Comment by eduardokum** [comment]
Não existe essa classe no projeto.

PdfSAF2
