### ISSUE TITLE
Arquivo de retorno UploadedFile

### ISSUE THREAD

**Issue by mprandot** [eduardokum/laravel-boleto#71]
Na aplicação que estou desenvolvendo o usuário pode importar um arquivo de retorno de seu computador (via input type="file").

Quando feito isso, no controller eu recebo o arquivo como UploadedFile. Nesse formato eu não consigo passar para o método make da Factory de retornos.

Existe uma maneira de transformar esse arquivo para o formato esperado? Ou há como implementar algo no package para aceitar os dois tipos?

Procurei bastante mas não estou encontrando...

**Comment by eduardokum** [comment]
Você pode fazer isso

```php
$retorno = RetornoFactory::make(file_get_contents($file->getPathname()));
```

**Comment by mprandot** [comment]
funcionou!
Só tem que ser sem o file_get_contents()!

Valeu @eduardokum, obrigado!

**Comment by eduardokum** [comment]
tem razão :)
