### ISSUE TITLE
Boleto Itaú com dados incompativeis

### ISSUE THREAD

**Issue by felipeaquinorwe** [eduardokum/laravel-boleto#710]
Útilizamos o Laravel-boleto mais de 2 anos em nosso sistema...

Aproximadamente 2 meses atrás aconteceu o primeiro caso em massa de sair diversos boletos com os dados correto no layout, porém quando os clientes foram pagar os dados saiam completamente diferente com valores e cobranças em outro nome.

Após entrar em contato com Itaú, solicitei o ultimo numero que foi utilizado no Nosso Numero e atualizei o script para começar a partir do seguinte numero.

Depois disso ficou praticamente tudo certo, porém, alguns casos ainda estão aparecendo de divergencia nos boletos.
Alguem já passou por isso ou sabe como posso resolver?

**Desktop (por favor, complete as seguintes informações):**
 - OS: Linux 20.04
 - Versão do PHP [7.4]
 - Versão do Laravel [7]

**Comment by eduardokum** [comment]
Esse é o único relato, caso possuir mais informaçoes reabra a issue.
