### ISSUE TITLE
Bug Remessa Santander (juros). Segue a solução

### ISSUE THREAD

**Issue by fabioonet** [eduardokum/laravel-boleto#711]
Em contato com o **Santander** na tentativa de validar o arquivo de **remessa**, me deparei com um problema nas casas dos juros/dia.

Ao verificar o arquivo Cnab/Remessa/Cnab240/Banco/Santander.php na linha 166, percebi que a contagem dos caracteres não estava batendo com o informado pelo banco.

Posição correta exigido pelo Santander  **127-141**
Como ficava no arquivo de remessa para R$ 0,03 -> 0000000000**3**000
Como o deve ficar -> 0000000000000**3**

Correção na linha 166:
De:
$this->add(127, 141, Util::formatCnab('9', $boleto->getJuros(), 15, **5**));
Para:
$this->add(127, 141, Util::formatCnab('9', $boleto->getJuros(), 15, **2**));

**Comment by eduardokum** [comment]
Essa alteração, ja foi feita em develop, logo saira uma versao master.
