### ISSUE TITLE
Controle Remessa\Cnab240\Banco\Santander

### ISSUE THREAD

**Issue by moyses-oliveira** [eduardokum/laravel-boleto#718]
Ola, sou CTO da properfy, quero relatar este bug, por favor entre em contato comigo, ja te mandei e-mail.
Vamos marcar um momento para conversar sobre meu projeto.
Sobre o bug esta no arquivo 
Eduardokum\LaravelBoleto\Cnab\Remessa\Cnab240\Banco\Santander
linha 170, numero de controle
[-] $this->add(196, 220, '');
[+] $this->add(196, 220, Util::formatCnab('X', $boleto->getNumeroControle(), 25));

**Comment by edigomes** [comment]
Boa tarde, envie detalhes do bug e alguém poderá te ajudar, isso aqui é uma comunidade open source, onde as pessoas se ajudam. 
vc deve fornecer mais informações para que isso fique registrado e ajude a comunidade, assim alguém poderá mandar um pull request ou até vc mesmo poderia enviar a correção.

**Comment by eduardokum** [comment]
Caso queira envie PR.
