### ISSUE TITLE
Envio de informações

### ISSUE THREAD

**Issue by Longinus-Ek** [eduardokum/laravel-boleto#722]
Como a biblioteca envia as informações para os bancos? 

Quando utilizo a biblioteca para emitir um boleto ela gera o pdf pra mim, entretanto preciso saber a resposta do envio e tratar essa resposta para controle de status de titulos no meu sistema.
Entretanto, inclui informações falsas na emissão do boleto e mesmo assim ele emite o pdf não dando nenhum erro. Gostaria de entender quando é enviado os arquivos, como é enviado e onde é recebido as respostas dos bancos.

**Comment by eduardokum** [comment]
a classe não envia, ela gera o arquivo cnab, e a pessoa tem que ir na conta do banco e enviar o arquivo.
