### ISSUE TITLE
Boleto no arquivo pdf.php e PdfCaixa.php com problema

### ISSUE THREAD

**Issue by romualdo-viana** [eduardokum/laravel-boleto#723]
**Descreva o bug**
subiu com a letra "x" na string nos dois arquivos
![image](https://github.com/eduardokum/laravel-boleto/assets/67743197/7b73e854-aaf1-4ce0-b3bc-05aa68176b5e)

Arquivo Pdf.php - linha 280
Arquivo PdfCaixa.php - linha 379

**Desktop (por favor, complete as seguintes informações):**
 - OS: Windows
 - Versão do PHP 7.3
 - Versão do Laravel 7

**Comment by eduardokum** [comment]
Corrigido em develop
