### ISSUE TITLE
[Dúvida] Dados boleto

### ISSUE THREAD

**Issue by brunoneve** [eduardokum/laravel-boleto#73]
Olá,

primeiramente gostaria de agradecer e parabenizar ao Eduardo e demais contribuintes que estão ativos nesse projeto. 

Minha dúvida é referente a composição de informações dos dados do cedente no boleto.

BANCO: CEF

conta : Qual informação deve ser preenchida aqui ? Numero da conta bancaria ou código do cedente.
codigoCliente: o que seria ? é o código do cedente?

OBS: Quando preencho o campo conta: com numero da conta bancaria , na impressão do boleto mostra agencia/Código beneficiário exemplo: 1131/1234 (1234=conta bancaria) e não o codigoCliente que seria o código do cedente.

Estou nessa dúvida, se alguém puder esclarecer agradecia.

**Comment by eduardokum** [comment]
é o codigo do cliente, pode colocar o codigo do cliente nos 2 na conta e no codigo do cliente, é que o boleto trata a conta como codigo do cliente e na remessa ele trata o codigo como codigo mesmo.

Na verdade o numero da conta não utiliza pra nada na caixa.

Estou fazendo uma alteração no develop pra não ter mais esse problema
