### ISSUE TITLE
Pix no boleto

### ISSUE THREAD

**Issue by SuportecTL** [eduardokum/laravel-boleto#733]
No campo "pix_qrcode" deve ser inserido os dados de uma transação gerada anteriormente pela api do banco? #675

**Comment by eduardokum** [comment]
Voce passa o pix copia e cola retornado pelo banco.

**Comment by BrunoPignatari** [comment]
mas cada boleto tem um pix copia e cola ? OU é 1 copia e cola para todos os boletos ? Eu imaginei que era a linha digitavel !
