### ISSUE TITLE
Proteger o PDF com senha durante a geração

### ISSUE THREAD

**Issue by vagnerfpaes** [eduardokum/laravel-boleto#734]
Existe alguma funcionalidade no pacote que permita proteger o PDF com senha durante a geração, garantindo que apenas usuários autorizados possam acessar o documento?

Recentemente tive uma situação que o cliente recebeu um pdf com dados diferentes do gerado. Mudou somente a linha digitável, código banco, código de barras e logo. O cliente tem dois e-mails cadastrados para receber o envio de boletos, em um e-mail recebeu corretamente e no outro recebeu com o pdf em anexo fraudado.

Primeira solução que pensei foi proteger com senha, se tiverem outras sugestões para adicionar mais segurança eu agradeço!

**Comment by eduardokum** [comment]
Sim, Subi uma versao em develop que possui essa opcao 

https://github.com/eduardokum/laravel-boleto/blob/develop/exemplos/boleto_protection.php

**Comment by vagnerfpaes** [comment]
Muito obrigado!!
