### ISSUE TITLE
Atributo Nosso Numero

### ISSUE THREAD

**Issue by dansfs9** [eduardokum/laravel-boleto#74]
Como fica a configuração no caso do banco (Itaú) só fornecer o Nosso Número?

**Comment by eduardokum** [comment]
Não entendi sua pergunta

**Comment by dansfs9** [comment]
no boleto tem o "numero" e o "numeroDocumento", mas o gerente da conta passou o "nossoNumero" já. Qual desses dois eu uso?

**Comment by dansfs9** [comment]
ele me passou: 109000000962

**Comment by eduardokum** [comment]
numero do documento é um número de identificação do boleto
numero é o numero sequencial do boleto
nosso numero o numero de identificação do boleto no banco cada boleto tem o seu, e ele é gerado a partir do numero

**Comment by dansfs9** [comment]
entao a partir desse numero 109000000962 eu tenho o numero=962 e numeroDocumento=109000000962 ? Porque já usava outro sistema para gerar os boletos.

**Comment by eduardokum** [comment]
não...

109 é o numero da carteira o numero do boleto é 00000096 e 2 é o dac

o numero do documento você pode usar qualquer coisa, pode ser o numero da nota o numero do parcela ate mesmo o numero do boleto

isso no branch develop, pois hoje no branch master ele usa o numeroDocumento pra gerar o nosso numero o que esta errado, mais esta agendado o merge do develop pro master no dia 01/02 para dar tempos das pessoas alterarem seus sistemas com a mudança.


Resumindo...
Hoje usa o numeroDocumento para gerar o nossoNumero
o correto no develop é o numeroDocumento usado pra qualquer coisa ate alfanumérico e utilizar o numero para gerar o nossoNumero

**Comment by dansfs9** [comment]
vou usar o develop entao. 
agora deixe-me ver se entendi, devo usar o 97 como 'numero' (uma vez que já disparei 96 boletos pelo outro sistema) e posso usar o pŕoprio 97 como 'numeroDocumento', daí no proximo uso o 98 e por aí vai?

**Comment by eduardokum** [comment]
isso mesmo

**Comment by dansfs9** [comment]
entendi, obrigado entao.
