### ISSUE TITLE
Homologação Banco Sicredi

### ISSUE THREAD

**Issue by renatoagomes** [eduardokum/laravel-boleto#75]
Olá Eduardo, 

Antes de tudo gostaria de agradecer, seu repositorio me ajudou muito, tanto na compreensão do processo quanto na implementaçao em sí.

Minha dúvida: Qual o estado atual do processo de homologação com o banco Sicredi? 

Estou fazendo uma implementaçao para emitir esses boletos e utilizei do seu repositório. Até agora a unica modificação que o banco me pediu foi o DV do prefixo do boleto (que identifica a moeda) Ex: 748-"DV".  Segue imagem:
 
![boleto-sicredi-homologacao](https://cloud.githubusercontent.com/assets/9811888/22077195/55ad5876-dd9a-11e6-908e-e03e8f54c4f2.png)

Implementei o método getCodigoBancoComDv() na classe Sicredi, para emitir esse 'X' e por enquanto estou esperando o retorno do banco. Se quiser posso fazer um pull request.

Obrigado

**Comment by eduardokum** [comment]
Tem razão, tem gente já com o boleto homologado, mais nunca apontaram isso... 

o codigo de barras você pode validar aqui: https://github.com/eduardokum/laravel-boleto/blob/master/manuais/SICREDI/analisa_boletos.xls 

Se puder mandar o PR só mande no branch develop, pois as novas atualizações estão sendo feitas la.


Obrigado

**Comment by renatoagomes** [comment]
Só pra ter certeza, vou esperar a resposta do banco antes de fazer PR. 

Uma outra sugestão que também me proponho a fazer uma PR, é uma documentação online usando o Github Pages a APIGen e o Travis-CI. O resultado é bem agradavel: ([https://renatoagomes.github.io/laravel-boleto](https://renatoagomes.github.io/laravel-boleto)).

Se quiser posso fazer uma PR com os arquivos necessários, mas para funcionar voce precisaria trocar a securekey e alguns outros detalhes: [https://github.com/ApiGen/ApiGen/wiki/Generate-API-to-Github-pages-via-Travis](https://github.com/ApiGen/ApiGen/wiki/Generate-API-to-Github-pages-via-Travis)

Se quiser posso fazer essa PR também.
Abraços

**Comment by eduardokum** [comment]
Pode fazer sim amigo será de grande ajuda. No projeto já está configurado o TravisCI e o scrutinizer

Abraços

**Comment by renatoagomes** [comment]
Enviei a PR da documentaçao. 

Sobre essa issue, se quiser pode fecha-la. Assim que o banco der retorno mando a PR com a modificação do digito da moeda.

**Comment by eduardokum** [comment]
Ok. Obrigado

**Comment by cristhianocastilho** [comment]
Senhores, Boa tarde. Estou utilizando o gerador de boleto para o Banco Sicredi e gostaria de saber se já encontra-se homologado o retorno 400 pois li os anteriores comentários e percebi que há algum tempo os Senhores já conversaram sobre... Muito obrigado por enquanto, agradeço o Senhor EduardoKum por proporcionar a utilização deste código de fácil utilização!
