### ISSUE TITLE
Duvida de um iniciante na parte de Geração de boleto por Remessa

### ISSUE THREAD

**Issue by thgcosta** [eduardokum/laravel-boleto#756]
A minha duvida é mais no fluxo de uso dessa lib, eu gero as remessas de boletos e depois do retorno positivo do banco eu imprimo os boletos?? ou eu posso gerar a remessa e os boletos e depois validar se o boleto foi aceito ou nao?
Minha situação de uso:
Venda de mercadorias por faturamento em 3x com boletos de 30 60 e 90 dias, eu faço a emissao de notas com sped-nfe e apos a autorização da nota eu preciso gerar esses Boletos para envio pro cliente, eu to em duvida de como seria o melhor (ou o uso correto) da lib.

**Comment by Rainzart** [comment]
Olá tudo bem?

Acho que isso depende das regras de negócio do seu sistema. Por exemplo, tenho clientes que emitem todos os boletos durante o dia e enviam a remessa só no final da tarde, porém durante a emissão já é impresso o boleto e entregue ao cliente final.
Alertei muito bem meu cliente que mesmo que ele preencha todos os dados corretos podem haver recusas e ele terá que encaminhar um novo boleto para o cliente final e foi uma escolha do meu cliente trabalhar desta forma.

Já em outra situação (que eu acho a forma mais correta), em um sistema que trabalhei o cliente primeiro emitia a NF e os boletos porém a impressão do boleto só era liberada após o retorno com a confirmação do banco.

Em resumo eu acredito que o fluxo vai de cada caso.

**Comment by thgcosta** [comment]
Muito obrigado pela ajuda.

Acredito que o melhor fluxo vai ser baseado no segundo exemplo que vc mandou, que eu tbm acredito que seja a forma mais correta.
