### ISSUE TITLE
Header Boleto Itau

### ISSUE THREAD

**Issue by dansfs9** [eduardokum/laravel-boleto#76]
Nas instruções do boleto do Itau, o valor e número estão trocados na versão de PDF.

**Comment by eduardokum** [comment]
Somente no Itaú? Você diz nas instruções? Está usando o master ou develop?

**Comment by dansfs9** [comment]
develop. 
Somente nas instruções de impressão

**Comment by eduardokum** [comment]
Já corrigi  5f06ada393c886309176b36d6006150061c87d9e

Abraço
