### ISSUE TITLE
Remessa Santander: Como mapeio o campo código de transmissão?

### ISSUE THREAD

**Issue by tperrelli** [eduardokum/laravel-boleto#78]
Boa tarde. Constei que pra gerar uma remessa santander para a empresa a qual estou trabalhando, preciso informar o código de transmissão. Fui procurar na documentação mas não encontrei. Qual seria o nome do campo? 

https://github.com/eduardokum/laravel-boleto/blob/master/exemplos/santander_remessa.php

**Comment by eduardokum** [comment]
Não precisa informar, o código de transmissão é um código composto por agencia **(4 dígitos)** + código do cliente **(8 dígitos)** + conta **(8 dígitos)** que da os **20 dígitos** do código de transmissão, a classe gera esse numero.

**Comment by irineujunior** [comment]
@tperrelli 
Vá em Cobrança e Recebimentos » Convênio » Consultar Convênio
Provavelmente faltou um **0** antes da conta

**Comment by tperrelli** [comment]
Quanto ao preenchimento dos valores, tranquilo. A bronca toda é que o sequencial do boleto não tá batendo. :(

**Comment by eduardokum** [comment]
utilize o branch develop, o branch master usa o numeroDocumento para gerar o nosso número o que esta errado no develop ele utiliza o campo numero para gerar, acho que talvez isso resolva, esta agendado o merge de develop para master em 01/02.

**Comment by tperrelli** [comment]
Dessa forma? "eduardokum/laravel-boleto": "develop"

**Comment by eduardokum** [comment]
dev-develop eu utilizo não sei dizer se só develop funciona

**Comment by tperrelli** [comment]
Utilizei dev-develop mas no momento de gerar o boleto em si dá algum erro de variável no template e a sequência dos códigos continua dando inválido :(

**Comment by eduardokum** [comment]
Tem como postar print do erro? aqui não da esse erro.

A ideia seria utilizar as mesma instancia que imprimiu o boleto para gerar a remessa.

**Comment by tperrelli** [comment]
Claro! Segue...
![eduardokum-santander-boleto](https://cloud.githubusercontent.com/assets/1470890/22204320/1ce1d04e-e150-11e6-88f2-1e4d13ba63e5.png)

**Comment by eduardokum** [comment]
aparentemente era aqui https://github.com/eduardokum/laravel-boleto/blob/develop/src/Boleto/Render/view/boleto.blade.php#L82

Não sei pq não tinha esse problema aqui..
