### ISSUE TITLE
Remessa Caixa: Protesto/Devolução

### ISSUE THREAD

**Issue by brunoneve** [eduardokum/laravel-boleto#80]
Olá, acredito que seja uma dúvida simples de se responder.

quando setamos diasBaixaAutomatica para geração da remessa, refere-se aos dias de protesto/devolução ?

Mas como o banco saberá se é pra protestar ou devolver -baixar o titulo ?

Obrigado

**Comment by eduardokum** [comment]
Man remessa ou passa dias de protesto ou dias baixa automática o campo pra informar os dias são o mesmo, o que muda somente é a instrução, ou passa uma ou passa outra, quando passa protesto normalmente ele baixa com protesto, se passar só baixa ele baixa sem o protesto
