### ISSUE TITLE
Remessa Bradesco

### ISSUE THREAD

**Issue by alissonlinneker** [eduardokum/laravel-boleto#81]
Em contato com o banco, foi verificado que o campo de remessa (posição 22 a 24) precisa ter os 3 dígitos preenchidos. Por padrão, informei no código o parâmetro 'carteira' => '09' e na remessa apareceu 090 ao invés de 009. Poderia verificar e realizar uma correção?
De qualquer forma, coloquei 009 em meu código.
Obrigado!

**Comment by eduardokum** [comment]
Isso ja esta corrigido no banch develop fb877b94ce2a466112764b8372c029de4f643d30

Aguardando dia 01/02 para o merge

**Comment by alissonlinneker** [comment]
Mesmo com a correção o problema continua. A posição 22 a 24 está saindo 090 ao invés de 009.
