### ISSUE TITLE
Renderiza a view em branco

### ISSUE THREAD

**Issue by guaracyalima** [eduardokum/laravel-boleto#82]
Fiz a configuração com a passagem de dados via post de uma view, só que ele gera uma pagina em branco nem da erro nenhum. há alguma configuração mais especifica alem da que consta na documentação para gerar boleto para banco do brasil?

**Comment by eduardokum** [comment]
Não somente isso, deve ser alguma configuração no seu php.ini ou no seu projeto laravel
