### ISSUE TITLE
Problema com DAC "Nosso Número" - Itaú

### ISSUE THREAD

**Issue by giovannicruz97** [eduardokum/laravel-boleto#83]
Estou tendo um problema quanto a homologação do boleto com o banco, a leitura do código de barras não apresentou nenhum problema, porém a composição numérica esta irregular. O que pode ser?

![image](https://cloud.githubusercontent.com/assets/13966008/22330197/2789e438-e3ac-11e6-871a-c6e661c201f9.png)

Obrigado!

**Comment by eduardokum** [comment]
você deve utilizar o branch develop esta corrigido la, o merge para o
master vai ocorrer no dia 01/02, merge programado pq tem alguma alterações
sensíveis com relação a geração do nosso numero que antes era gerado a
partir do numeroDocumento e passou a ser a partir do numero

EDUARDO GUSMÃO
Analista de Sistemas
E-mail: eduardo@intrasis.com.br
Telefone: 11 2208 2423 | 41 2626-1708 | 41 98479 6288 (Tim)
Endereço: Av. Engenheiro Caetano Álvares, 3536 | São Paulo
Site: www.intrasis.com.br

Em 26 de janeiro de 2017 09:45, Giovanni Cruz <notifications@github.com>
escreveu:

**Comment by giovannicruz97** [comment]
Como faço para mudar para o branch develop? To tentando desde ontem, pois imaginei que isso ja teria sido corrigido, mas não consegui ainda haha

**Comment by eduardokum** [comment]
"eduardokum/laravel-boleto": "dev-develop"

EDUARDO GUSMÃO
Analista de Sistemas
E-mail: eduardo@intrasis.com.br
Telefone: 11 2208 2423 | 41 2626-1708 | 41 98479 6288 (Tim)
Endereço: Av. Engenheiro Caetano Álvares, 3536 | São Paulo
Site: www.intrasis.com.br

Em 26 de janeiro de 2017 10:06, Giovanni Cruz <notifications@github.com>
escreveu:

**Comment by giovannicruz97** [comment]
Ok! Agora deve estar funcionando sem problemas. Porém, só os textos dos boletos que estão divergentes da homologação. Eu procurei no projeto para mudar a linha de "instrução" e "local de pagamento", porém quando salvo como PDF, as alterações não se mantêm. Como pode ser feito isso?

**Comment by eduardokum** [comment]
Ja atualizei o local de pagamento e as instruções.
