### ISSUE TITLE
Integração com Laravel

### ISSUE THREAD

**Issue by samwell1** [eduardokum/laravel-boleto#85]
Olá!
Gostaria de saber como eu faço a integração com o meu projeto em laravel. Existe algum arquivo para ser incluído ? Ou alguma linha de código para a inclusão ?
Como faço?
Att, Samuel.
Obrigado!

**Comment by alissonlinneker** [comment]
@samwell1 Basta instalar via composer, a essência do Laravel. Não tem mistério.

**Comment by eduardokum** [comment]
Não precisa incluir nada instalando via composer ja esta disponível para usar como nos [exemplos](https://github.com/eduardokum/laravel-boleto/tree/master/exemplos)

**Comment by samwell1** [comment]
Consegui! Muito Obrigado!
