### ISSUE TITLE
Erro ao pegar detalhes de retorno - Itaú

### ISSUE THREAD

**Issue by giovannicruz97** [eduardokum/laravel-boleto#86]
Estou recebendo um erro ao invocar o método getDetalhes().

![image](https://cloud.githubusercontent.com/assets/13966008/22341164/f0bcef42-e3d6-11e6-8d28-25d2a05ef81e.png)

	public function leRetorno()
	{
		$root = $_SERVER['DOCUMENT_ROOT'];
		$dir = $root . "/retorno/";
		$retorno = \Eduardokum\LaravelBoleto\Cnab\Retorno\Factory::make($dir.'itau.ret');
		$retorno->processar();

		echo $retorno->getBancoNome();
		foreach($retorno as $registro)
		{
		    dd($registro->getDetalhes());
		}
	}

**Comment by eduardokum** [comment]
getDetalhes é metodo da classe retorno nao da classe detalhe.

foreach($retorno as $registro){    dd($registro->getDados());}



ou

$retorno->getDetalhes();



EDUARDO GUSMÃO
Analista de Sistemas
E-mail: eduardo@intrasis.com.br
Telefone: 11 2208 2423 | 41 2626-1708 | 41 98479 6288 (Tim)
Endereço: Av. Engenheiro Caetano Álvares, 3536 | São Paulo
Site: www.intrasis.com.br

2017-01-26 14:55 GMT-02:00 Giovanni Cruz <notifications@github.com>:

**Comment by giovannicruz97** [comment]
Ah ok! Agora que percebi haha Vlw

**Comment by giovannicruz97** [comment]
Como faço para pegar o nosso número? Tem alguma função que faça isso?

**Comment by eduardokum** [comment]
$boleto->getNossoNumero()

**Comment by giovannicruz97** [comment]
> $boleto->getNossoNumero()

Isso é para pegar o Nosso Número do boleto, mas e pelo arquivo de retorno?

**Comment by eduardokum** [comment]
```php
foreach($retorno as $detalhe){    
    $detalhe->getNossoNumero();
    $detalhe->getNumeroDocumento();
    $detalhe->getNumeroControle();
}
```

ou qualquer outro método dessa interface [Detalhe](https://github.com/eduardokum/laravel-boleto/blob/develop/src/Contracts/Cnab/Retorno/Detalhe.php)

**Comment by giovannicruz97** [comment]
Ah ok, vlw :+1:
