### ISSUE TITLE
Duvida sobre remessa

### ISSUE THREAD

**Issue by brunoneve** [eduardokum/laravel-boleto#87]
Olá a todos,

gerei arquivo de remessa normalmente, com 2 boletos com valor de 1 real cada, usando mecanismo de protesto a x dias, enviei para CAIXA, eles receberam e processaram a remessa normalmente, Então fui fazer teste de baixarBoleto. Veja os passos que fiz:

1 Alterar status do boleto para  = 3 , usando $boleto->baixarBoleto()
2 Gerei remessa do objeto boleto
3 Foi gerado o arquivo, enviei para CAIXA, e eles estão me retornando o erro : 
01040 NUMERO DOCUMENTO INVALIDO

E o numero do documento creio que seja o alfanumero está idêntico ao da primeira remessa com instrução de registro, porém essa quando tento enviar com instrução de baixar o boleto, eles não aceitam a remessa.

Será que fiz algum processo errado? alguém já pegou esse error  ?

**Comment by brunoneve** [comment]
OBS: nessa segunda remessa enviei apenas 1 boleto com instrução de baixa

**Comment by giovannicruz97** [comment]
Cara, pelo o que eu entendi, acho que você deve primeiro enviar os arquivos de remessa, ai você recebe os números para colocar nos boletos pelo retorno e, por fim, gera os boletos. Espero ter ajudado!

**Comment by brunoneve** [comment]
Na verdade o numero quem impõe somos nós e não os bancos. So pra constar, hoje pela manha enviei o mesmo arquivo de remessa com instrução de baixarBoleto e foi processada normalmente. Parece que tem que esperar 24 horas, pelo menos com a CAIXA.

**Comment by eduardokum** [comment]
Isso sim, normalmente as remessas tem horários fixos para serem processados, depende do banco mais de 1 vez por dia.

Normalmente envia a remessa em um dia para o retorno no outro
