### ISSUE TITLE
BRADESCO - CNAB 400 - Status: Indícios de Rejeição (Remessa)

### ISSUE THREAD

**Issue by rodolphovfreire** [eduardokum/laravel-boleto#88]
Há necessidade de ajuste na função 

> addBoleto(BoletoContract $boleto)

 na classe Bradesco, que corresponde a "montagem" das posições (**021 a 037**). Nesse caso, devemos inserir um 0 (zero) antes do número da carteira, podendo preencher com um 0(zero) a mais. 

O banco rejeita pois não reconhece a carteira (**090**), ou seja, como faltou o 0 (zero) no início, ele entendeu que (**090**) era a carteira. Ao invés de, **0**(009).

```PHP
class Bradesco extends AbstractRemessa implements RemessaContract
{

....

 public function addBoleto(BoletoContract $boleto)
    {
        $this->iniciaDetalhe();

        $beneficiario_id = Util::formatCnab('9', $this->getCarteiraNumero(), **3**) .
            Util::formatCnab('9', $this->getAgencia(), 5) .
            Util::formatCnab('9', $this->getConta(), 7) .
            Util::formatCnab('9', $this->getContaDv(), 1);

....
```
Sustituir o 3 por 4, conforme abaixo:

```PHP
 public function addBoleto(BoletoContract $boleto)
    {
        $this->iniciaDetalhe();

        $beneficiario_id = Util::formatCnab('9', $this->getCarteiraNumero(), **4**) .
            Util::formatCnab('9', $this->getAgencia(), 5) .
            Util::formatCnab('9', $this->getConta(), 7) .
            Util::formatCnab('9', $this->getContaDv(), 1);

....
```

**Comment by eduardokum** [comment]
Isso já esta resolvido no branch develop, que ocorrera o merge quarta-feira, como anunciado no tópico atenção do [README ](https://github.com/eduardokum/laravel-boleto#atenÇÃo) pois tem algumas modificações um pouco sensíveis.

**Comment by fillipenorton** [comment]
Olá @eduardokum e @rodolphovfreire 

Comecei a usar o pacote nas últimas semanas. Ontem realizar o envio do arquivo de remessa para o bradesco e retornou com este mesmo problema de indícios de rejeição.

Eu encontrei a mesma situação do Rodolpho. Já foi resolvido na master? 

Obrigado

**Comment by rodolphovfreire** [comment]
Olá @fillipenorton 

Então, como tínhamos um _deadline_ na época de utilização do repositório, não esperamos pela atualização e, fizemos @_override_ na função que manipulava a criação do arquivo .REM

O problema na época consistia que a função estava criando o campo carteira com um "0" a mais.

Porém, acredito que o @eduardokum  já tenha feito esse fix.

**Comment by eduardokum** [comment]
Olá @fillipenorton ,
Acredito que isso ja estava arrumando, qual a versão que você esta usando?

**Comment by fillipenorton** [comment]
Oi @eduardokum, 

Versão 0.5

Fiz o indicado por Rodolpho e funcionou. Mandei remessa ontem e foi aceita.

**Comment by eduardokum** [comment]
Mais qual foi o override que você fez pra funcionar?

Foi nessa linha?

https://github.com/eduardokum/laravel-boleto/blob/master/src/Cnab/Remessa/Cnab400/Banco/Bradesco.php#L150

**Comment by fillipenorton** [comment]
Isso mesmo. Troquei o 3 por 4

**Comment by eduardokum** [comment]
Tem razão ali tem que ser 4 mesmo, 0 + 3 digitos da agencia. vou arrumar e fazer o PR e merge vlw.

**Comment by fillipenorton** [comment]
Legal. 

O pacote é muito bom! abrs
