### ISSUE TITLE
Gerar boleto com CNPJ no Pagador e no Beneficiario - Itaú

### ISSUE THREAD

**Issue by giovannicruz97** [eduardokum/laravel-boleto#89]
Os numeros de documento só saem com máscara de CPF, ou seja, a API corta o CNPJ e resulta um número errado. Como faço para mudar para sair com a máscara em CNPJ?

**Comment by eduardokum** [comment]
Onde que corta?


Na classe [Pessoa](https://github.com/eduardokum/laravel-boleto/blob/master/src/Pessoa.php) não tem lugar nenhum que limita o tamanho, somente valida tem tem 10 11 14 caracteres para definir o tipo do documento.

**Comment by giovannicruz97** [comment]
Os meus boletos serão gerado coms CNPJ em ambas as partes. A saída está cortando assim:
> CNPJ de Exemplo: 23.367.062/0001-31
> Saída no PDF: 670.620.001-31

**Comment by brunoneve** [comment]
Também aconteceu comigo isso, basta informar apenas numeros no CNPJ no momento que popular a Classe Pessoa para emitente.

**Comment by eduardokum** [comment]
Isso que ia dizer agora, fiz os testes e é exatamente isso, vou corrigir isso na classe, hoje vou fazer o merge do develop e criar uma nova tag la 

Abraço

**Comment by edigomes** [comment]
O cnpj ou cpf agora é informado somente os numeros sem a mascara! Antes ele
funcionava com a madcara.

Eduardo, o merge da develop será hj?

Em 1 de fev de 2017 08:31, "Eduardo Gusmão" <notifications@github.com>
escreveu:

**Comment by eduardokum** [comment]
Sim. 1/02 como marcado, só estou ajeitando o README aqui

**Comment by eduardokum** [comment]
já está lá, acredito que agora funcione normalmente

https://github.com/eduardokum/laravel-boleto/blob/master/tests/PessoaTest.php#L122

**Comment by giovannicruz97** [comment]
Ah ok! Mas o padrão será informar somente os números ou informar os números + máscara?

**Comment by eduardokum** [comment]
Agora tanto faz, as duas formas iram funcionar, se tiver com o pacote atualizado

**Comment by giovannicruz97** [comment]
No branch develop ou master?

**Comment by eduardokum** [comment]
no master

**Comment by edigomes** [comment]
@eduardokum Atualizei minha master e enviei 3 boletos itaú em produção para testar,

**Sugestão:**

 Criar um grupo no google groups para duvidas, as issues estão cheias de duvidas quando eram somente para ter coisas relacionadas a bugs.

**Comment by eduardokum** [comment]
@edigomes, Com certeza, vou criar isso. Obrigado

**Comment by giovannicruz97** [comment]
@edigomes @eduardokum Eu criei um grupo no [Telegram](https://t.me/laravelBoleto) para discussão sobre o projeto, dúvidas e afins. Acho lá um local bem legal para isso! Pretendo colocar no READ.ME ok?

**Comment by eduardokum** [comment]
@giovannicruz97  Pode adicionar sim. Obrigado
