### ISSUE TITLE
Extensão ext-intl

### ISSUE THREAD

**Issue by josericardomcastro** [eduardokum/laravel-boleto#9]
Eduardo,

Estou tentando instalar sua biblioteca mas ela pede essa extensão "ext-intl".

Tem horas que estou tentando instalar mas não consigo. 

Pra que você usa essa extensão? Ela é realmente necessária?

Não consigo instalar no MAC OS.

**Comment by ricardobarantini** [comment]
Tive problemas pra instalar ela também mas foi porque eu estava usando em um container do docker. Qual problema você tem pra instalar?

**Comment by eduardokum** [comment]
Precisa sim para as funções de formatação de número
