### ISSUE TITLE
Boleto CEF não homologado

### ISSUE THREAD

**Issue by mprandot** [eduardokum/laravel-boleto#95]
Geramos alguns boletos e enviamos para a CEF apenas para validação.

Eles retornaram que o layout do boleto não foi homologado, parece que está faltando algo : 

```
Parecer da análise dos bloquetos: Não Homologado

2-         Listamos abaixo os apontamentos que justificam o parecer:

II.        No Recibo do Pagador, faltou imprimir a expressão "Recibo do Pagador".
 
III.        O Recibo do Pagador deve possuir na parte inferior, à direita, a expressão "Autenticação Mecânica", com dimensão máxima de 2 mm de altura e traços com fio de 0,3 mm.
 
IV.        Faltou amostra de documento de dígito geral do código de barras número 4.

**Comment by AlissonSilvaCe** [comment]
Para ser homologado o boleto pela CEF também precisa que esse texto abaixo seja destacado em algum local no boleto.

**SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogíos)
Para pessoas com deficiência auditiva ou fala: 0800 726 2492 	
Ouvidoria: 0800 725 7474(reclamações não solucionadas e denúncias) 		
caixa.gov.br**

**Comment by eduardokum** [comment]
O item 2
![image](https://cloud.githubusercontent.com/assets/2566340/22662371/dff4cede-ec8f-11e6-84ed-979a137bf62e.png)

o item 3
![image](https://cloud.githubusercontent.com/assets/2566340/22662380/e794c608-ec8f-11e6-9408-9f46290384f7.png)

o item 4 não entendi

@AlissonSilvaCe  isso não poderia ser colocando manualmente no demonstrativo ??

```php
$boleto->addDescricaoDemonstrativo('SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogíos)');
$boleto->addDescricaoDemonstrativo('Para pessoas com deficiência auditiva ou fala: 0800 726 2492');
$boleto->addDescricaoDemonstrativo('Ouvidoria: 0800 725 7474(reclamações não solucionadas e denúncias)');
$boleto->addDescricaoDemonstrativo('caixa.gov.br');
```

**Comment by AlissonSilvaCe** [comment]
@eduardokum pode sim!

**Comment by mprandot** [comment]
@eduardokum, 
O item 2 não aparece pra mim. Não gerou como o seu.
O item 3 realmente está correto, não sei porque não foi validado.

**Comment by mprandot** [comment]
Atualizei o pacote, testei novamente com dados diferentes e atualizados, continua gerando da mesma maneira (errado).

**Comment by eduardokum** [comment]
não sei te dizer o pq, gera em html pra homologar e depois usa o pdf mesmo, essa classe de PDF pode ter comportamento diferente em cada ambiente eu acredito, mas não tem muito o que se fazer...

**Comment by AlissonSilvaCe** [comment]
Eu criei uma classe PdfCaixa um clone da Classe Pdf com as alterações que o
chato do gerente me pediu só para homologar depois vou usar a classe PDF
mesmo.

Em 07/02/2017 09:07, "Eduardo Gusmão" <notifications@github.com> escreveu:

**Comment by mprandot** [comment]
Bá, que estranho!

Estou gerando esses boletos em html mesmo (não uso a classe PDF), ai se o usuário querer o pdf ele gera pelo chrome mesmo.

**Comment by eduardokum** [comment]
Sim, tem gente que usa pdf por que quer enviar por email ou adicionar mais de 1 boleto, estou pensando em fazer em html a classe igual no pdf pra adicionar mais de 1 boleto, o que falta é tempo

**Comment by mprandot** [comment]
Eu tava olhando o código das views e encontrei o "recibo do pagador"

![data](https://cloud.githubusercontent.com/assets/14298396/22780769/09e31caa-eea7-11e6-9c30-7df494f517d5.png)

Acho que não é uma questão de pacotes usados. Deveria imprimir, não é?

**Comment by eduardokum** [comment]
Então os 2 tem, tanto no PDF quanto no HTML,
quando você manda renderizar não aparece em nenhum dos 2?

acabei de gerar (php exemplos\cef_boleto.php) ele coloca o item 2 e 3 normal
[cef.pdf](https://github.com/eduardokum/laravel-boleto/files/763458/cef.pdf)


e quanto item 4, "Faltou amostra de documento de dígito geral do código de barras número 4."

Acredito que a caixa quer um boleto com dv do nosso número de 0-10

tipo 1 boleto com número que gere do dv 0 outro 1 e assim por diante para testar todos, e faltou enviar um que gere o dv 4, seria isso?

**Comment by mprandot** [comment]
Vou testar de novo, com a classe PDF e com os dígitos.

Passo o resultado depois.

**Comment by mprandot** [comment]
@eduardokum 
não está imprimindo as instruções de impressão! Não sei como não vi antes...

As instruções de impressão são obrigatórias?

**Comment by eduardokum** [comment]
Não essas não são obrigatórias. Muito estranho no seu ambiente deixar de imprimir algumas coisas...

**Comment by mprandot** [comment]
Com o ctrl+p não imprime as instruções porque tem a classe `noprint!

Existe alguma configuração para não gerar essa informação? Já que não vou precisar dela...

**Comment by eduardokum** [comment]
hmm entendi, esta gerando html e imprimindo em pdf, não hoje não existe essa opção na classe.

**Comment by leosantoscunha** [comment]
Estou tentando colocar os campos:
 $boleto->addDescricaoDemonstrativo('SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogíos)');
$boleto->addDescricaoDemonstrativo('Para pessoas com deficiência auditiva ou fala: 0800 726 2492');
$boleto->addDescricaoDemonstrativo('Ouvidoria: 0800 725 7474');
$boleto->addDescricaoDemonstrativo('caixa.gov.br');

Porem no objeto que monta o pdf esta adicionado mais linhas vazias no array, olha só. 

 0 => string '' (length=0)
      1 => string '' (length=0)
      2 => string '' (length=0)
      3 => string 'SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogíos)' (length=78)
      4 => string 'Para pessoas com deficiência auditiva ou fala: 0800 726 2492' (length=61)
      5 => string 'Ouvidoria: 0800 725 7474' (length=24)
      6 => string 'caixa.gov.br' (length=12)
