### ISSUE TITLE
[ method Eduardokum\LaravelBoleto\Util::numberFormatValue() ]

### ISSUE THREAD

**Issue by alissonlinneker** [eduardokum/laravel-boleto#97]
Fatal error: Call to undefined method Eduardokum\LaravelBoleto\Util::numberFormatValue() in vendor/eduardokum/laravel-boleto/src/Boleto/AbstractBoleto.php on line 1187

**Comment by AlissonSilvaCe** [comment]
Joga o problema lá no grupo que a galera ajuda rapidinho!

[Laravel Boleto Groups](https://groups.google.com/forum/#!forum/laravel-boleto)
