### ISSUE TITLE
Grupo no Telegram

### ISSUE THREAD

**Issue by giovannicruz97** [eduardokum/laravel-boleto#98]
Olá a todos! Criei uma comunidade no telegram para podermos debater assuntos relacionados ao projeto seja dúvidas, commit, PR's e afins. Acho que pode ser uma saída para alguns casos mais rápidos, evitando a abertura de 'issues' aqui no GitHub. Para entrar no grupo [clique aqui](https://t.me/laravelBoleto).

**Comment by eduardokum** [comment]
Fiz o merge la vlw.
