### ISSUE TITLE
Contra-apresentação Caixa Economica

### ISSUE THREAD

**Issue by leoclaro** [eduardokum/laravel-boleto#99]
Boa tarde, 
gostaria de tirar uma dúvida referente a boletos da caixa de contra-apresentação. Onde a data de vencimento deve ficar vazio, e utilizar 999999 na ultima parte do código de barra do boleto, como devo proceder nesse caso?

Agradeço desde já pelo grande projeto feito.

**Comment by eduardokum** [comment]
Não sei, nunca utilizei esse tipo de cobrança, tem que ver no manual como deve ser enviado a remessa
